### ISSUE TITLE
Sample of working email configuration

### ISSUE THREAD

**Issue by DaneWeber** [huginn/huginn#108]
I didn't expect to spend so much time trying to get SMTP working. Would someone be so kind as to share their .env that works?

I'd love to see a GMail example and a local/ISP example. If you don't want to share your personal info, just replace the specific address and password as if it is for john.doe@gmail.com or john.doe@example.com with a password of "abc123".

I may just have a specific issue with my local setup, but I've made some telnet tests that seem to indicate that I can talk to the SMTP servers I'm specifying in my .env.

**Comment by anishvarghese** [comment]
I have problem while using outlook client to sent mails

**Comment by anishvarghese** [comment]
Unrecognized authentication type [BN6PR14CA0038.namprd14.prod.outlook.com]
