### ISSUE TITLE
Real RSS Agent

### ISSUE THREAD

**Issue by jdcc** [huginn/huginn#11]
I know the WebsiteAgent exists, but it'd be nice to have a real RSS agent as well.  RSS/Atom provide data with better fields, and people expect feeds to be crawled (not always the case with straight-up web content [does the WebsiteAgent obey robots.txt?]).  This would also remove the need for the CSS selector business (while it's powerful, it's not exactly convenient).

**Comment by cantino** [comment]
It'd be really helpful if anyone who uses the RSSAgent could test #1564 and make sure it still works for them. It's a major rewrite of the internals that we'll be switching to soon.
