### ISSUE TITLE
JavaScript Agent

### ISSUE THREAD

**Issue by cantino** [huginn/huginn#130]
Huginn's Agents are great, but sometimes you need the flexibility to just write code.  

We should create an agent that executes a block of JavaScript when either `#check` is called, or an event is received.  The JavaScript should have access to the contents of incoming events, as well as a lightweight API to access the Agent's `options`, `memory`, and to create new events with JSON payloads.  In addition, we should add a new field type to our JSON editor that allows input of escaped, formatted JavaScript with syntax highlighting.  Perhaps any field called `executable_javascript` (or similar) becomes an [Ace](http://ace.c9.io/) or [CodeMirror](http://codemirror.net/) editor.

**Comment by haniawni** [comment]
@cantino 

> "sense to add AgentAssets, which are files and source code attachable..."

If I want to use a javascript library (in a single .js file) within a javascript agent, is this AgentAssets idea what would be necessary? 

As in, for right now, i'd have to, like, paste the library code in with the actual agent code? :(

**Comment by cantino** [comment]
Hmm, maybe. I haven't thought about how to load in extra JS files for the JavaScriptAgent. It would probably be a new DB model, unless we re-used Credentials.

**Comment by christianechevarria** [comment]
Hey guys total newbie just dropping in here to see if there was anything else I could see about using JS with Huginn?

Full disclosure: I'm working on a JS machine learning library that I'm hoping will pair awesomely with Huginn to create quick models from web services

**Comment by dsander** [comment]
> I'm currently working on a JS machine learning library that I'm hoping will pair well with Huginn to create quick agents for any combination of services

The `JavaScriptAgent` is intended to be used to write small(ish) scripts in Javascript. If you have a bigger JS project it's better to expose it to Huginn via some sort of HTTP interface.

**Comment by brianpetro** [comment]
@christianechevarria write your javascript as an HTTP Cloud Function (Google Firebase). Then call that function using the website agent or post agent.

**Comment by christianechevarria** [comment]
By the way guys, never thanked you all for your help!

> @christianechevarria write your javascript as an HTTP Cloud Function (Google Firebase). Then call that function using the website agent or post agent.

This seems like a really solid idea and might turn this into a project in and of itself
