### ISSUE TITLE
Can't use # in FTP URLs

### ISSUE THREAD

**Issue by Quintasan** [huginn/huginn#1534]
Hi,

I have tried to set up Huginn to send me a notification when there's a new PDF file on my FTP server. The catch is that the password contains a # and Huginn complains about the URL not being valid.

**Comment by dsander** [comment]
Hi @Quintasan,

does it work when you replace `#` with the URL encoded version `%23`?

**Comment by Quintasan** [comment]
I will try it.

**Comment by Quintasan** [comment]
I'm getting `530 Login authentication failed` so I guess that's a no go.

**Comment by dsander** [comment]
I tested it with setting `ftp://bob:123%23123@localhost/` as the FTP url, my password is `123#123` and the login worked as expected.

**Comment by Quintasan** [comment]
Well, I just can't seem to get it working, I tried replacing `#` with `%23` but I'm still getting `530 Login authentication failed /usr/lib/ruby/2.2.0/net/ftp.rb:327:in `getresp'`

**Comment by Quintasan** [comment]
Scratch that. It turns out my login was looking like an email address so I had to escape `@` as well.

@dsander think that URL validation could be disabled for that field or should I update documentation to mention that case?

**Comment by dsander** [comment]
I see, sorry it was so annoying to debug. You are right we should work around the issue, I am thinking about automatically URL encoding the provided URL.

**Comment by knu** [comment]
You can use Liquid templating to escape your username and password for you:
```
  "url": "ftp://{{ 'user@name' | uri_escape }}:{{ 'pass#word' | uri_escape }}@host/dir/"
```
I recently updated the internal function `Utils.normalize_uri()` so it now uses even more lax URI parser and has an improved auto-escaper, but `#` is a leading character of the fragment component, so it can't be auto-escaped.
