### ISSUE TITLE
Reddit Agent

### ISSUE THREAD

**Issue by amacgregor** [huginn/huginn#16]
I have some code from a similar project that can be adapted to create a Reddit Agent

**Comment by McGriddle** [comment]
So I started to write some code around a reddit agent, but the more I dug into it the more opinionated I realized the agent would have to be. I prefer just to use the existing agents: Website -> Deduplication -> Trigger -> Formatter -> Pushbullet

**Comment by cantino** [comment]
You could put those in a Scenario and then export and share it.

**Comment by kholbekj** [comment]
Hey guys. I've started on this as my first agent, it's in a very rough, but functional state:
https://github.com/kholbekj/huginn/blob/reddit_agent/app/models/agents/reddit_agent.rb

It currently serves my intended purposes, but I'd love some feedback to refine it and create a PR <3

**Comment by cantino** [comment]
Hey @kholbekj, welcome! This might be a good candidate for pulling into a gem using https://github.com/cantino/huginn_agent. You're also welcome to make a preliminary PR to Huginn with this and we can give some feedback.

**Comment by kholbekj** [comment]
Okay, I'll start with the PR then, and look into extraction at some point!

**Comment by ZakharyH** [comment]
Any word on when this will be added?
