### ISSUE TITLE
TelegramAgent does not send messages greater then 4096 characters

### ISSUE THREAD

**Issue by alekseysotnikov** [huginn/huginn#1750]
Hi there!
The Telegram API has a limitation for a message size - 4096 UTF8 characters per message
https://core.telegram.org/method/messages.sendMessage 

So, currently, it just does not work for long messages (greater 4096 characters). Messages are disappearing. 
Is there any way to send long messages as two or more messages?

P.S: I use scenario DigestAgent -> TelegramAgent, so sometimes messages could be very long
P.P.S: Telegram desktop application just splits long messages and sends it as two or more messages. I think that it is a good idea.

Thanks

**Comment by dsander** [comment]
That sounds like a reasonable solution, I think we have to modify the Agent to send multiple messages as I don't think it is possible with Liquid or an other Agent.

For now you can use the [truncate](https://help.shopify.com/themes/liquid/filters/string-filters#truncate) liquid filter to ensure the first part of the message is send: `{{ message | truncate: 4096 }}`

**Comment by cantino** [comment]
You could definitely modify the Ruby TelegramAgent to split messages into 4096 character chunks and send them in batches.

**Comment by sumwatt** [comment]
I put in my first stab at this issue. Note - I'm still pretty green with ruby/rails myself and I have very limited knowledge of Telegram's APIs so I'm sure this will probably need a few re-writes before it is acceptable.
