### ISSUE TITLE
Implement  params in Telegram Agent

### ISSUE THREAD

**Issue by ali-sattari** [huginn/huginn#1781]
Hi,

Please consider implementing more snedMessage parameters into agent such as:
- disable_web_page_preview
- disable_notification

Thanks

**Comment by cantino** [comment]
This would likely be an easy change if you'd like to add it @ali-sattari.

**Comment by ali-sattari** [comment]
@cantino I have no Ruby experience, but I will give it a try.

**Comment by cantino** [comment]
Let us know if you need a hand!

**Comment by ali-sattari** [comment]
I did use a workaround for the time being and configured PostAgent with Telegram API params.

Here is the gist for any one looking for similar issue: [PostAgent Options](https://gist.github.com/ali-sattari/3dc28837ef59a864fbb4747f1c02a99c)

**Comment by cantino** [comment]
Nice solution :)

**Comment by aserpi** [comment]
Pull request merged, can be closed.

**Comment by knu** [comment]
Thanks for your contribution and the reminder!
