### ISSUE TITLE
Events not propagated

### ISSUE THREAD

**Issue by fabiogiglietto** [huginn/huginn#1951]
Hi to all,
following the upgrade to v39, the scheduled agents are not processed and events not propagated. When run manually, the agents works as expected creating the events but those events are not propagated. I've tried to flag propagate immediately (that is turned off by default in my scenario) but nothing changed.

My instance is running on Heroku with one web and one worker dynos and a Postgres db (PROCFILE_PATH = deployment/heroku/Procfile). Please also see the log attached: [log.txt](https://github.com/cantino/huginn/files/884703/log.txt).

I may also add that memory usage on the web dyno is often over the quota. I've tried to add the worker dyno in the attempt to resolve this issue.

Thank you in advance for your help.

Best regards, Fabio Giglietto

**Comment by cantino** [comment]
Hey @fabiogiglietto. Do you have a longer section of logs?  That's a bit short to see if anything interesting is happening.

**Comment by fabiogiglietto** [comment]
Here it is. Hope you can find something useful.

[log.txt](https://github.com/cantino/huginn/files/889132/log.txt)

**Comment by cantino** [comment]
The beginning of that log shows a bunch of restarts. Is it possible that it's running out of RAM or Heroku uptime and getting restarted?

Also, is it correct that you have two Dynos, one is running `web: bundle exec rails server -p ${PORT-3000} -b ${IP-0.0.0.0}` and the other is running `jobs: bundle exec rails runner bin/threaded.rb`?  If you're not running bin/threaded.rb, that would explain your issues.

**Comment by fabiogiglietto** [comment]
Yes you are right. I was running "worker: bundle exec rake jobs:work" but not "jobs: bundle exec rails runner bin/threaded.rb". I definitely need to get a better understanding of Heroku :) Shell I turn off "worker: bundle exec rake jobs:work" now?

**Comment by cantino** [comment]
We recommend running `web: bundle exec unicorn -c config/unicorn.rb` and `jobs: bundle exec rails runner bin/threaded.rb`. If you need extra capacity, you can also run additional workers.  See [the Procfile](https://github.com/cantino/huginn/blob/master/Procfile).
