### ISSUE TITLE
Feature request: access agent name of events

### ISSUE THREAD

**Issue by haxwithaxe** [huginn/huginn#2005]
# Preface
My immediate goal is to include the name of the original agent in the final output of an email digest to help me categorize the inputs for machine learning and quickly track down formatting problems after the fact.

# Suggested Spec
A liquid formatting token with the agent name similar to the existing agent id token.

**Comment by dsander** [comment]
Did you try using [`{{agent.name}}`](https://github.com/huginn/huginn/wiki/Formatting-Events-using-Liquid#objects-provided-by-huginn)? That should return the name of the previous agent.

**Comment by nogre** [comment]
You can also try to add a custom field to the agent submitting the event, and then access it via `{{agent.options.name}}`.

**Comment by haxwithaxe** [comment]
sorry, i was thinking of the JS agent when i wrote this. this is an invalid request.
