### ISSUE TITLE
How can I format the POST agent to consume data from Azure ml?

### ISSUE THREAD

**Issue by Toast707** [huginn/huginn#2020]
Hi, I'm trying to consume data from an Azure ml experiment and I'm having a bit of difficulty formatting the  post request agent (I've never had to format a request in this manner). I've tried using a few combinations using the [azure data consumption tutorial](https://docs.microsoft.com/en-us/azure/machine-learning/machine-learning-consume-web-services), but I'm not seeing any errors in the agent log. Any info would be greatly appreciated.

**Comment by Toast707** [comment]
![azureml](https://cloud.githubusercontent.com/assets/9059741/26599061/176dfc24-452c-11e7-99a1-e276502ecee0.PNG)
This is what I've got so far and now it's returning error 400 bad argument. [I found a gist](https://gist.github.com/nk773/febb753b87db00c628f1dbc0e86de6c6) for using the api with curl, I'm just not sure about how to format the post agent.

**Comment by dsander** [comment]
Hi @Toast707,

have you tried wrapping `input1` in `Inputs`?

```
{
  "Inputs": {
    "input1": {
      "ColumnNames": [
        "cog_speed"
      ],
      "Values": [
        [
          "0"
        ],
        [
          "1"
        ]
      ]
    }
  },
  "GlobalParameters": {}
}
```

**Comment by Toast707** [comment]
Hi @dsander,

Yes I have, I'm still getting a 400 request schema error =/

**Comment by dsander** [comment]
That is odd, you can use https://requestb.in/ to compare the request which is send via curl with the one that comes from Huginn.

**Comment by Toast707** [comment]
Thanks @dsander, I'll close this as it looks more like an azure ml issue.

**Comment by Toast707** [comment]
Alright, so I got it working. My experiment is a 2-column dataset "message" and "newscore": 
`{
  "post_url": "RRS_url",
  "expected_receive_period_in_days": "1",
  "content_type": "json",
  "method": "post",
  "payload": {
    "Inputs": {
      "input1": [
        {
          "message": "{{ title }} {{ subtitle }}",
          "newscore": "1"
        }
      ]
    }
  },
  "headers": {
    "Content-Type": "application/json",
    "Accept": "text/json",
    "Accept-Charset": "UTF-8",
    "Authorization": "Bearer api_key"
  },
  "emit_events": "true",
  "no_merge": "true",
  "GlobalParameters": {
  },
  "event_headers_style": "raw"
}`
