### ISSUE TITLE
Liquid formatting function divided_by in Event Formatting Agent not giving false divide by zero error

### ISSUE THREAD

**Issue by educatedwarrior** [huginn/huginn#2021]
Using an Event Formatting Agent with the payload below, and the liquid formatting function; I'm getting a divide by zero error when the denominator is not zero.   Any suggestions?

PAYLOAD
{
  "symbol": "HMY",
  "name": "Harmony Gold Mining Company Lim",
  "volume": "3634147",
  "volume_daily_avg": "5404530"
}

LIQUID FORMATTING
{{ volume | divided_by: volume_daily_avg }}

**Comment by dsander** [comment]
Hi @educatedwarrior,

I think this might be a bug in the liquid gem. It seems to work well with the `minus` filter:

```
[4] pry(main)> Liquid::Template.parse("{{ a | divided_by: b }}").render({a: 1, b: 1})
=> "Liquid error: divided by 0"
[5] pry(main)> Liquid::Template.parse("{{ a | minus: b }}").render({a: 1, b: 1})
=> "0"
```

**Comment by educatedwarrior** [comment]
Thanks for testing this out @dsander .    Any suggestions on how to get this resolved or a work around?

**Comment by dsander** [comment]
Actually I was wrong, liquid does not allow to pass variables to arguments of filters, I used a bad example:
```
[8] pry(main)> Liquid::Template.parse("{{ a | minus: b }}").render({a: 2, b: 1})
=> "0"
```

I can't think of any other option than the `JavascriptAgent`.

**Comment by knu** [comment]
You should be able to do that: https://shopify.github.io/liquid/filters/divided_by/#changing-variable-types

I guess render() takes a hash with string keys; `{a: 2, b: 1}` should be `{ 'a' => 2, 'b' => 1}`.

I have no idea yet as to why `divided_by` fails, though.

**Comment by knu** [comment]
Hmm, seems it should work:
```
[14] pry(main)> Agents::EventFormattingAgent.new.interpolate_string(
[14] pry(main)*   '{{ volume | times: 1.0 | divided_by: volume_daily_avg }}',
[14] pry(main)*   Event.new(payload: {
[14] pry(main)*       "symbol": "HMY",
[14] pry(main)*       "name": "Harmony Gold Mining Company Lim",
[14] pry(main)*       "volume": "3634147",
[14] pry(main)*       "volume_daily_avg": "5404530"
[14] pry(main)* }))
=> "0.6724260944059891"
```
(`| times: 1.0` is to get sub-integer precision which you may need)

**Comment by dsander** [comment]
Good catch, so it did not work because both arguments were strings and the `times` filter converts it to a float/integer?

**Comment by knu** [comment]
@dsander Well... no, it prints "0" if you omit `| times: 1.0` and does not seem to cause zero-division error.

@educatedwarrior Can you provide a minimum set of agent options with which we can reproduce the error?

**Comment by educatedwarrior** [comment]
The | times: 1.0 did the trick.   Thanks @knu and @dsander .

**Comment by knu** [comment]
Hmm, that was good for you but I still don't get it.  As I said above, `{{ volume | divided_by: volume_daily_avg }}` does not cause zero-division error, so I've no idea what this issue was all about.

```
>> Agents::EventFormattingAgent.new.interpolate_string(
?>     '{{ volume | divided_by: volume_daily_avg }}',
?>     Event.new(payload: {
?>         "symbol": "HMY",
?>         "name": "Harmony Gold Mining Company Lim",
?>         "volume": "3634147",
?>         "volume_daily_avg": "5404530"
>>       }))
=> "0"
```

Did you actually divided some other thing by the result of the division, assuming it should never be zero not knowing an integer divided by an integer would result in an integer?  I still need a repro.

**Comment by educatedwarrior** [comment]
This is the exact. Error I get when doing dry run.

1 error prohibited this Agent from being saved:
- Options has an error with Liquid templating: Liquid error: divided by 0.

I'm available and can do a screen share real-time with you if you like. I have a conference line. @knu
