### ISSUE TITLE
Rule in Trigger Agent Triggers when it evaluates to false for field>=value type comparison

### ISSUE THREAD

**Issue by educatedwarrior** [huginn/huginn#2022]
This trigger is firing when the condition is false.  Any suggestions?

PAYLOAD
{
  "symbol": "HMY",
  "name": "Harmony Gold Mining Company Lim",
  "open": "2.16",
  "low": "2.12",
  "high": "2.18",
  "previousClose": "2.10"
}

TRIGGER RULE
      "type": "field>=value",
      "value": "open",
      "path": "previousClose"

**Comment by knu** [comment]
Try putting `"value": "{{open}}"` in place of `"value": "open"`.

Liquid templating vs. JSONPath may be a bit confusing.  TriggerAgent should probably allow user to build an expression using Liquid only.

**Comment by knu** [comment]
It seems to me it'd be more intuitive if you could simply pass a Liquid template like the following code instead of having to compose a `rules` array of hashes, each with three keys:

```liquid
{% assign a = previousClose | plus: 0 -%}
{% assign b = open | plus: 0 -%}
{% if a >= b %}true{% endif -%}
```
(Suppose that the agent would trigger when the template evaluated to a string `true`)

What do you think about the idea, @dsander?

**Comment by dsander** [comment]
I can imagine liquid being easier to use in more complex scenarios, but for just checking if a value matches a string it feels like a bit more to write then to fill out one rule hash. Maybe it should be a `LquidTriggerAgent` to give the option of using a from configurable text field for the template?

**Comment by educatedwarrior** [comment]
Thanks Akinori, that did the trick.   For the possible LiquidTriggerAgent, that is definitely a cool idea.
