### ISSUE TITLE
Feature Request: Ability to set global static values

### ISSUE THREAD

**Issue by educatedwarrior** [huginn/huginn#2025]
Is there currently anyway to set static values that could be used in multiple agents?   

I considered the Manual Event agent, but I would like something that doesn't depend on creating an event or scheduling.

This would definitely come in handy to set parameters in which more than one agent could use.

**Comment by knu** [comment]
You could use "Credentials" for that.  The name much sounds like a special storage for keeping secret values, but it can store any value (string) that can be shared across your agents.

**Comment by educatedwarrior** [comment]
@knu , thanks for your reply.   I couldn't find any good reference speaking about setting up credentials and using them in agents.  Do you have a link?

**Comment by dsander** [comment]
@educatedwarrior The wiki has some information on [accessing credentials using liquid](https://github.com/huginn/huginn/wiki/Formatting-Events-using-Liquid#tags-added-by-huginn). `{% credential USER_CREDENTIAL_NAME %}` will insert the value of the credential named `USER_CREDENTIAL_NAME`.

**Comment by educatedwarrior** [comment]
Works well.  Haven't figured out how to use the java script embeding code in a message yet though.
