### ISSUE TITLE
Issue when trying to consume Post agent event with Website agent

### ISSUE THREAD

**Issue by Toast707** [huginn/huginn#2028]
Hi, I'm currently having an issue trying to consume an event using the website agent, made by a Post agent. The post agent is sending a request to the Azure ml api and returning an event that looks like this (trimmed to reduce space):
{
  "body": "{\"Results\":{\"output1\":[{\"newscore\":\"1\",\"message_HashingFeature_1\":\"0\",\"message_HashingFeature_2\":\"0\",\"Scored Labels\":\"27.5512530841685\"}]}}",
"headers": {
    "Content-Length": "562411",
    "Content-Type": "application/json; format=swagger; charset=utf-8",
    "ETag": "\"4757c602-2412-4ed6-9f43-a4d7d786c254\"",
    "Server": "Microsoft-HTTPAPI/2.0",
    "x-ms-request-duration": "00:00:00.2994713",
    "x-ms-request-id": "beee53e0-efa4-43f1-acb5-342d271a41f9",
    "Date": "Sat, 03 Jun 2017 22:04:18 GMT"
  },
  "status": 200
}

How do I format the Website agent to use data_from_event from the post agent if I didn't specify anything using liquid? {{ payload }}?

**Comment by Toast707** [comment]
Sorry for asking so many questions lately too.

**Comment by dsander** [comment]
I think the `JsonParseAgent` would be the better fit here. The `WebsiteAgent` can work with data from an event, but it does not parse or modify the data. `url_from_event: "{{ body }}"` would work on a string and not on the JSON data.

**Comment by Toast707** [comment]
Hey @dsander thanks for the response. The JsonParseAgent seems to be returning the entire event with data as {{ body }} and data key as [Scored Labels]. 

I've got a Website Agent correctly accepting data_from_event but I'm getting the error: "Error when handling event data: invalid value for Integer(): "Scored Labels". Is it possible to specify float instead of integer?

Just to clarify, I'm trying to return "Scored Labels" value, which looks like "27.5512530841685".

**Comment by dsander** [comment]
@Toast707 Yes the JsonParseAgent returns the parsed JSON data as a new event. `data_key` can be used to set the key in which the data is emitted.

How is the WebsiteAgent configured? I believe `Results.output1[0]["Scored Labels"]` is the JSON path that should return the data you are looking for.

**Comment by Toast707** [comment]
@dsander Looks like that cleared up my issue. I was using `$.*.[Scored Labels]` which kept giving me "invalid value for Integer()". The JsonPath you gave me works and returns what I need. Thanks for the help!

**Comment by dsander** [comment]
Nice! I guess yours would have worked as well if you escaped `Scored Labels`, without quotes JSONPath assumes you want to access an array and handles it as an integer to access the `n-th` entry of the array.

**Comment by Toast707** [comment]
Ah, that makes sense; I was wondering why it was treating it as an integer. Thanks for the help!
