### ISSUE TITLE
How can I access an upstream Agent's events?

### ISSUE THREAD

**Issue by Toast707** [huginn/huginn#2032]
Hi, I'm trying to merge events in similar effect to what was [described in this PR.](https://github.com/huginn/huginn/pull/1746)
I tried using {% previous_event 'my_agent', '{{my_key | as_object}}' %}, but received a Liquid formatting error. On the sidebar of EventFormattingAgent it states that events from upstream agents are accessible, but I'm not really sure on how to properly format it, and couldn't find any examples. 

My workflow looks like: WebsiteAgent => EventFormattingAgent => De-DuplificationAgent => PostAgent => WebsiteAgent2 => EventFormattingAgent2 => DataOutputAgent.

I'm trying to combine {{key}} from the De-DuplificationAgent and {{key2}} from WebsiteAgent2, into EventFormattingAgent2  and output it as one event. Any examples of accessing upstream events would be greatly appreciated.

**Comment by Toast707** [comment]
Here's an example scenario: https://www.pastiebin.com/593f002544327

Is it possible to just keep passing previous events within new events, or maybe specify multiple `data_from_event`s to a website agent?

**Comment by dsander** [comment]
Hi @Toast707,

I don't think that is possible at the moment. Your problem is that the `PostAgent` does not allow to merge the received Event with it's created payload, right?

It would be really great to have a universal way to either access previous Event data or allow all Agents to merge Events. Maybe you can try to revive the discussion in the PR.

**Comment by Toast707** [comment]
Hi @dsander yes, if the post agent allowed merging the received event with the results of the post request, my issue would be handled. I'll comment on the 'suggest an Agent' thread and see if that gets any attention.

**Comment by Toast707** [comment]
Switching to the docker container huginn:pr-1746 fixed my issue. Thanks for the help @dsander .
