### ISSUE TITLE
Login "Remember me" seems invalid under Firefox

### ISSUE THREAD

**Issue by waldens** [huginn/huginn#2033]
To verify this issue, I created a new blank Firefox profile with Firefox v53.0.2, no extension installed, complete default config, and then in Firefox and Chrome, both login to huginn with "remember me" option checked, and then close Firefox and Chrome both.

After 4 days ( I don't know whether or not it can be reproduced when only wait 1 day, anyway I waited 4 days ), reopen Firefox and Chrome, visit huginn again.

Test result:
Chrome remains the login state
Firefox is redirected to the sign_in, and need to input username and password.

Did anyone come across this same problem?

**Comment by dsander** [comment]
That is odd, I have not noticed it on my instance (but mostly use Chrome to access it). I will do the same test to verify my Firefox behaves the same as yours.

**Comment by iecompattest** [comment]
Testing 

> Test

**Comment by dsander** [comment]
My test ran for a very long time 😄 . For me Firefox kept me logged in to Huginn.

I am closing this issue. Please feel free to reopen if you need further assistance!
