### ISSUE TITLE
DATABASE_URL capacity limit on Heroku Free

### ISSUE THREAD

**Issue by Faberman** [huginn/huginn#2037]
Hello.
I have around 1300 events at any time on my Huginn on Heroku instance, but I've just received an email regarding 10000 row limit for DATABASE_URL database. The database contains 7,280 rows at the moment and it's only 18th day of the month. I didn't have this problem before with the same amount of events, what could go wrong? And is it possible to manually clean DATABASE_URL?

EVENT_EXPIRATION_CHECK is set to 3 hours.

**Comment by cantino** [comment]
Perhaps some Agent produced more events than expected? Huginn doesn't run well on the Heroku free plan.

**Comment by Faberman** [comment]
Do logs also use the database? Then 200 log entries per agent (default value) can be the problem.

**Comment by cantino** [comment]
Yes, that makes sense.
