### ISSUE TITLE
Agent event flow diagram has lost event counts on upgrade to Ubuntu 16.04

### ISSUE THREAD

**Issue by johnleeming** [huginn/huginn#2038]
I'm running huginn on Heroku and recently updated the stack to "heroku 16" which I understand to be based on Ubuntu 16.04 (see https://devcenter.heroku.com/articles/heroku-16-stack).  It all seems to work happily except that the agent event flow diagram has lost the little circles with the event flow counts and somehow looks a bit lower res.

Also it sometimes (not reproducibly) comes up with a message saying too many agents to display - max 80, even though I've only got about 45 (+9 disabled).

I did an empty commit to force a redeploy onto the new stack so nothing else changed.
![image](https://user-images.githubusercontent.com/13801070/27292905-be0d97c0-550c-11e7-89ae-efebb2c65e4b.png)

**Comment by dsander** [comment]
Hi @johnleeming,

it looks like graphviz is not working properly on heroku-16, can you try to replace [this line](https://github.com/huginn/huginn/blob/master/.buildpacks#L3) in `.buildpacks` with `https://github.com/weibeld/heroku-buildpack-graphviz`?

**Comment by johnleeming** [comment]
that fixes it, thanks very much.  John
