### ISSUE TITLE
How can i get the middle link in div?

### ISSUE THREAD

**Issue by Markryan-bear** [huginn/huginn#2039]
i transfer a website to RSS, but this website save the image link in the div and set the attr to style background like below:

div class="postimg" style="background:url('http://www.rosi365.com/wp-content/themes/wmpic1/timthumb.php?src=http://www.rosi365.com/tu/KZNO.315/d.jpg&amp;h=226&amp;w=340&amp;zc=1') no-repeat center center; width: 340px; height: 226px;"

Q: how i can get the src  "http://www.rosi365.com/tu/KZNO.315/d.jpg"?

Thank you first.

**Comment by nogre** [comment]
I've used regex in these situations (and if anyone has a better solution, please let me know): 

Set an Event Formatting Agent, or similar, to look for this regex match `(?<=php\?src=).+(?=&amp;h)`

What this says is to find everything after `php?src=` and before `&amp;h`. Since these tags are reasonably unique and auto-generated, this will grab the in-between image url.

**Comment by dsander** [comment]
Hi @Markryan-bear,

I think @nogre solution is the the way to go here. Neither `xpath` nor `css` selectors have a way to parse the contents of a tag attribute.

You could also try the `template` option of the `WebsiteAgent` and use the liquid [`regex_replace`](https://github.com/huginn/huginn/wiki/Formatting-Events-using-Liquid#filters-added-by-huginn) filter.

**Comment by Markryan-bear** [comment]
Thank you all
Finally, i refer to @dsander  method to use template, although I still don't know the regex_replace how to write.......but I use regex remove.......I know it's a stupid way but it's working...can you give me a regex_replace example for my case?
@nogre I also want to use your way to try....it should be helpful for my other RSS, but i haven't example for Event Formatting Agent.......so i don't know how to do....for my this case, can you give me a full example？
whatever thank you again.

**Comment by nogre** [comment]
Hi. See the Event Formatting Agent data below. Your Website Agent creates events and sends its data to this agent with the embedded URL data in a field called `div_style`. This agent will extract the data and populate the `jpg` field in the `instructions` with the URL. An event is then created from the `instructions`.

```
{
  "instructions": {
    "jpg": "{{ jpg_url.0 }}",
    "other_content": "{{ other_data_from_event }}"
  },
  "matchers": [
    {
      "path": "{{ div_style }}",
      "regexp": "(?<=php\\?src=).+(?=&amp;h)",
      "to": "jpg_url"
    }
  ],
  "mode": "clean"
}
```

**Comment by Markryan-bear** [comment]
@nogre thank you，i will use this to test other case.    ( • ̀ω•́ )✧
