### ISSUE TITLE
Retrieving Credentials in Liquid Output

### ISSUE THREAD

**Issue by nogre** [huginn/huginn#2042]
I'm having difficulty retrieving credential data using liquid output. From the [wiki](https://github.com/huginn/huginn/wiki/Formatting-Events-using-Liquid#tags-added-by-huginn):
```
{% credential USER_CREDENTIAL_NAME %}
```
However, when I do this, I get: `Liquid error: internal `.

I tried a few different credentials and used {{ }} instead of {% %}, but nothing worked. Please take a look and let me know what I can do.

Thanks

**Comment by dsander** [comment]
That's odd I can not reproduce the issue, in which Agent are you using the credential tag?

**Comment by nogre** [comment]
@dsander Good call: the problem appears in my Liquid Output Agent, but not when I tested it in an Event Formatting Agent.

**Comment by douniwan5788** [comment]
when use credential tag in  Liquid Output Agent
https://github.com/huginn/huginn/blob/af9193a2447b6fefaa468d90ad98ef14a231f8ee/app/concerns/liquid_interpolatable.rb#L334
context.registers[:agent] is nil
