### ISSUE TITLE
Exception reporting for Agents

### ISSUE THREAD

**Issue by joenas** [huginn/huginn#2043]
How about including something like this: https://github.com/ankane/errbase

Since `Agent#error` only takes a string as an argument I would suggest adding it [here](https://github.com/huginn/huginn/blob/master/app/jobs/agent_check_job.rb#L10) and [here](https://github.com/huginn/huginn/blob/master/app/jobs/agent_receive_job.rb#L11)!

**Comment by dsander** [comment]
Hi @joenas,

that looks like an interesting option. We already have an open issue about this topic (#1957) , would you mind adding it to the discussion there?

**Comment by joenas** [comment]
Done and done

**Comment by dsander** [comment]
Thanks!
