### ISSUE TITLE
Having problems with getting huginn up and running

### ISSUE THREAD

**Issue by Zatara7** [huginn/huginn#2050]
_# bundle exec rake production:start
Starting huginn ...
ok: run: huginn-web-1: (pid 5906) 0s
ok: run: huginn-jobs-1: (pid 5965) 0s
_# bundle exec rake production:status
down: huginn-web-1: 0s, normally up, want up; run: log: (pid 3302) 1126s
down: huginn-jobs-1: 0s, normally up, want up; run: log: (pid 3300) 1126s
_# bundle exec rake production:check
[  OK  ] Everything is fine

says everything is okay while the services are down.. also, log files are empty! So I'm really not sure how to approach this.

**Comment by dsander** [comment]
Hi,

have you tried to restart Huginn? Even if something goes wrong there should be something in `/home/huginn/huginn/log/web-1/current` and `/home/huginn/huginn/log/job-1/current`, are those files even present?

**Comment by Zatara7** [comment]
Yes, files are present but they are empty!

**Comment by dsander** [comment]
That is odd, which linux distribution and version are you using?

Can you also please paste the output of `ps aux`? It looks like the Huginn processes are not started even though runit claims it did.

**Comment by Zatara7** [comment]
It seems like the problem was happening because of root user not finding where bundle is located.. essentially an rvm issue.
I removed rvm and installed ruby from source.. now it works!

Thanks @dsander I wouldn't have known the issue without running `ps aux` like you mentioned.

**Comment by dsander** [comment]
Nice! Glad you were able to figure it out.
