### ISSUE TITLE
What's the different about "url" "url_from_event" and "url_from_event"?

### ISSUE THREAD

**Issue by se7cn** [huginn/huginn#2051]
e.g 
anget A get url list. 
anget B check the url page.

set  B 
`url : {{url}}`

it's looks worked.
B can get the url form A , just set `{{url}}`, 
              some times   A cant's get the page . only some "id"
              I can use B set ` url: http://some site / pageid={{id}}`
              it's still worked.

So I don't understand What's the different about "`url`" "`url_from_event`" and "`url_from_event`"

Thanks a lot

**Comment by dsander** [comment]
Hi,

to be honest I don't think there is a difference anymore, both `url` and `url_from_event` are Liquid interpolated with the received event.

Maybe @knu knows if I am missing something.

**Comment by se7cn** [comment]
Hi @dsander 
thanks you.
i found some answers like this

> ur: http...,
url_from_event:{{another_url_form_event}}

i think that's means i can set tow `url` values
one it's `url` . can be `{{value}}` , or `http...` write directly.
another it's `url_from_event` can be {{value}} from event
this 2 can work same time.

@knu  it's that right?
thanks guys

**Comment by knu** [comment]
I think there are a couple of reasons: one is as described in #1205, WebsiteAgent had once only had `url` defaulted to the value `url` from the payload of an incoming event, and one would easily get unexpected behavior when an event had a key named `url` when what one really wanted was `merge`.  Hence the migration to the new key named `url_from_event`.

As a bonus, you can see clearly that if a WebsiteAgent has only `url_from_event` set and no `url` it will run only when receiving an event and will not work alone.
