### ISSUE TITLE
what's the different about mod "all" and "merge"

### ISSUE THREAD

**Issue by se7cn** [huginn/huginn#2052]
question again.
another new guy question :(

`on_change` it's very useful
some times 
anget just check . no need to check is somting "on_change" . so  i guess i need set `mode: all or merge `

the question is 
what's main difference about `all` and `merge` mode?

if it is possible .pls give me some example. thanks a lot

writing by google translate

**Comment by dsander** [comment]
Hi @se7cn,

`all` means the Agent does not check if the extracted values changed, Events will be emitted every time the Agent ran.
When mode is set to `merge` the Event which is received by the `WebsiteAgent` will be merged into the the payload that is emitted. It allows to pass data through the Agent to process it later in the Agent chain (`merge` also implies `all`).

**Comment by se7cn** [comment]
@dsander thanks a lot

i got it!

merge it's very  usefull!
