### ISSUE TITLE
RSS Agent - include_feed_info - feed with no "description"

### ISSUE THREAD

**Issue by zoomequipd** [huginn/huginn#2054]
example feed: https://www.youtube.com/feeds/videos.xml?channel_id=UCoTLdfNePDQzvdEgIToLIUg

## Error from Dry Run
```
[00:00:00] INFO -- : Dry Run started
[00:00:00] ERROR -- : Failed to fetch https://www.youtube.com/feeds/videos.xml?channel_id=UCoTLdfNePDQzvdEgIToLIUg with message 'undefined method `description' for #<Feedjira::Parser::AtomYoutube:0x005611d3d0a620>': ["/home/huginn/huginn/app/models/agents/rss_agent.rb:233:in `feed_data'", [SNIP] 
```

## Agent Config
![image](https://user-images.githubusercontent.com/4827852/28049189-7cbdf14e-65aa-11e7-9eae-32a3743d7688.png)

```
{
  "expected_update_period_in_days": "5",
  "clean": "false",
  "url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCoTLdfNePDQzvdEgIToLIUg",
  "include_feed_info": "true"
}
```
## Troubleshooting
Looking at the RSS feed provided by youtube for a channel, it does not provide a "description" item in the feed data. I'm guessing this is causing issues on line 233 where it attempts to set a variable using that value if include_feed_info is true.

**Comment by dsander** [comment]
Thanks for the report @zoomequipd, I think you are right. We can probably fix it by wrapping the `description` call with `.try(:description)`, it could be worth doing the same for the more 'exotic' attributes that might not be present on all feeds.

**Comment by zoomequipd** [comment]
I'll see what I can do about this one as well. Feel free to assign it to me.
