### ISSUE TITLE
jobs stop

### ISSUE THREAD

**Issue by se7cn** [huginn/huginn#2055]
type: website agent

background Jobs stop and can't delete. 
only if `sudo bundle exec rake production:force_stop` and start again.

i search all about this issues " jobs stop / can't stop "
there's not less and looks it's same issue.

then I Try to set `DATABASE_POOL` 20 to `30`;

another way i find some answer is about "RUBY , Timeout " something .
forgive me I don't understand about how to fix "that problem"

so is any way can fix " background jobs stop" ?

thank you

**Comment by dsander** [comment]
Hi @se7cn,

do can you post the logs for the background processor (`/home/huginn/huginn/log/jobs-1/current`) before you restart it the next time?

It might also help to switch the separate background processes. Activate [those lines](https://github.com/huginn/huginn/blob/master/Procfile#L28-L31) by removing the `# ` commenting them out, deactivate [these](https://github.com/huginn/huginn/blob/master/Procfile#L24-L25) and re-export the configuration with `sudo bundle exec production:export`.

We got a few similar report in the past but sadly never were able to reproduce them in a reliable way which is required to find a fix for the problem.

**Comment by se7cn** [comment]
@dsander 
then i post this issue. it's stop again.
so i keep it "stop" and didn't "restart"

there's the log of

> /home/huginn/huginn/log/jobs-1/current

and  `/////` is my annotate.

> ///////// Correct results in front of  log. 
Agent#82: Fetching http://jandan.net/pic
//////// this url it's worked
Queuing schedule for every_1m
Queuing schedule for every_1m
Queuing schedule for every_2m
Agent#82: Error when fetching url: Failed: #<Faraday::Response:0x007f2002046068 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:get @body="" @url=#<URI::HTTP http://jandan.net/pic> @request=#<Faraday::RequestOptions (empty)> @request_headers={"Cookie"=>"////////my set cookie", "User-Agent"=>"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Mobile Safari/537.36", "Accept-Encoding"=>"gzip,deflate"} @ssl=#<Faraday::SSLOptions verify=true> @response=#<Faraday::Response:0x007f2002046068 ...> @response_headers={} @status=0>>
/home/huginn/huginn/app/models/agents/website_agent.rb:346:in `check_url'
/home/huginn/huginn/app/models/agents/website_agent.rb:333:in `block in check_urls'
/home/huginn/huginn/app/models/agents/website_agent.rb:332:in `each'
/home/huginn/huginn/app/models/agents/website_agent.rb:332:in `check_urls'
/home/huginn/huginn/app/models/agents/website_agent.rb:326:in `check'
/home/huginn/huginn/app/concerns/sortable_events.rb:92:in `check'
/home/huginn/huginn/app/jobs/agent_check_job.rb:7:in `perform'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.1.1/lib/active_job/execution.rb:37:in `block in perform_now'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/i18n-0.8.1/lib/i18n.rb:257:in `with_locale'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.1.1/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.1.1/lib/active_job/logging.rb:24:in `block (4 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `block in instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.1.1/lib/active_job/logging.rb:23:in `block (3 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.1.1/lib/active_job/logging.rb:44:in `block in tag_logger'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:69:in `tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.1.1/lib/active_job/logging.rb:44:in `tag_logger'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.1.1/lib/active_job/logging.rb:20:in `block (2 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.1.1/lib/active_job/execution.rb:33:in `perform_now'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.1.1/lib/active_job/execution.rb:22:in `block in execute'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.1.1/lib/active_job/railtie.rb:26:in `block (4 levels) in <class:Railtie>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/reloader.rb:68:in `block in wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/reloader.rb:67:in `wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.1.1/lib/active_job/railtie.rb:25:in `block (3 levels) in <class:Railtie>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.1.1/lib/active_job/execution.rb:20:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.1.1/lib/active_job/queue_adapters/delayed_job_adapter.rb:36:in `perform'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/backend/base.rb:78:in `invoke_job'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:230:in `block (2 levels) in run'
/usr/local/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/usr/local/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:230:in `block in run'
/usr/local/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:229:in `run'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:213:in `block in work_off'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:212:in `times'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:212:in `work_off'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:175:in `block (4 levels) in start'
/usr/local/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:174:in `block (3 levels) in start'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:173:in `block (2 levels) in start'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:172:in `loop'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:172:in `block in start'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:79:in `block in add'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:171:in `start'
/home/huginn/huginn/lib/delayed_job_worker.rb:6:in `run'
/home/huginn/huginn/app/concerns/long_runnable.rb:71:in `block in run!'
Agent#88: Fetching http://jandan.net/ooxx
/////////////this url it's stop jobs in "background jobs" list at first and "running".
////////////log of anget : last is "Fetching http://jandan.net/ooxx	~9h ago"
Queuing schedule for every_1m
Queuing schedule for every_1m
Queuing schedule for every_2m
Queuing schedule for every_1m
Queuing schedule for every_5m
/////////repeat Queuing schedule for every_ ?? m

**Comment by dsander** [comment]
That looks similar to the issues we got reported before, do you have enough memory (500mb-1gb more than currency used by Huginn) to switch to the separate background processes I described earlier?

**Comment by se7cn** [comment]
Hi @dsander  
Well.
I switch that as you described.
My memory is 1gb (only huginn) and everything looks fine.
i need keep watch some days.
if its not auto stop again.

so should i close this issues ?  or keep it , when is not work again . then need i post the log ?  There's no better way to fix that .  right? 




anyway thanks for your help.

**Comment by dsander** [comment]
Nice, it's good to know the separate background processes seem to fix the timeout issue.
