### ISSUE TITLE
How to create multiple events?

### ISSUE THREAD

**Issue by elvetemedve** [huginn/huginn#2060]
## The problem
Website Agent receives a JSON object in `data_from_event` mode like this:
```json
{
  "items": [
    {"name": "item1"},
    {"name": "item2"},
    {"name": "item3"}
  ]
}
```
I configure the `extract` mode like this:
```json
"extract": {
  "event": {
    "path": "items"
  }
}
```
### Actual output
1 event has been created:
```json
{
  "event": [
    {"name": "item1"},
    {"name": "item2"},
    {"name": "item3"},
  ]
}
```

### Expected output
3 events have been created:
```json
{
  "event": {"name": "item1"}
}
```
```json
{
  "event": {"name": "item2"}
}
```
```json
{
  "event": {"name": "item3"}
}
```

Is it possible to achieve that? So I would like to create multiple output events from a single incoming event.
I'm happy to switch to a different agent if needed, but I think this is the closest what I am trying to do.

**Comment by dsander** [comment]
Hi @elvetemedve,

yes that is possible with `.items[*]` it will retun everything inside the `items` array.

**Comment by elvetemedve** [comment]
Hi @dsander,

It worked well. Thank you. :)

I think it would be useful to point this out in the agent description.
