### ISSUE TITLE
Liquid Templating some code can not work

### ISSUE THREAD

**Issue by se7cn** [huginn/huginn#2067]
type : website agent
extract: num
template:
bigger:`{% if num > 100 %} {{num}} bigger than 100{% endif %}`

bug results is like this

> 101 bigger than 100
> 102  bigger than 100
> 10  bigger than 100
> 9 bigger than 100
> 150  bigger than 100

....Well .There is no law. some tome's right. some 's wrong results

I set template like this
bigger:`{% if **200** > 100 %} {{num}} bigger than 100{% endif %}`
and the results it's all right.

**Comment by se7cn** [comment]
i guess `{% if num > 100 %} {{num}} bigger than 100{% endif %}`
that `num` can not get a value. 
i try use `{% assign ` create a new value whit num and it's worked.
is that right?

**Comment by se7cn** [comment]
another  strange phenomenon
i set 
`{% assign num_new = num %}`
and log is

> [00:00:02] INFO -- : Values extracted: ["1028", "48", "1159", "2124", "3478", "1978", "1237", "1019", "67", "1000", "949", "0", "26", "140", "357", "6679", "400", "989", "1", "943", "4919", "0", "1495", "2408", "1115", "1766", "317", "7", "2441", "3", "7356", "6"]
[00:00:02] ERROR -- : Error when fetching url: Liquid error: comparison of String with 50 failed
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/condition.rb:117:in `rescue in interpret_condition'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/condition.rb:114:in `interpret_condition'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/condition.rb:44:in `evaluate'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/tags/if.rb:43:in `block (2 levels) in render'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/tags/if.rb:42:in `each'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/tags/if.rb:42:in `block in render'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/context.rb:123:in `stack'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/tags/if.rb:41:in `render'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:109:in `render_node'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:88:in `block in render'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `each'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `render'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:208:in `block in render'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:242:in `with_profiling'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:207:in `render'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:220:in `render!'
/home/huginn/huginn/app/concerns/liquid_interpolatable.rb:96:in `block (2 levels) in interpolate_string'
/home/huginn/huginn/app/concerns/liquid_interpolatable.rb:95:in `catch'
/home/huginn/huginn/app/concerns/liquid_interpolatable.rb:95:in `block in interpolate_string'
/home/huginn/huginn/app/concerns/liquid_interpolatable.rb:57:in `interpolate_with'
/home/huginn/huginn/app/concerns/liquid_interpolatable.rb:94:in `interpolate_string'
/home/huginn/huginn/app/concerns/liquid_interpolatable.rb:73:in `block in interpolate_options'
/home/huginn/huginn/app/concerns/liquid_interpolatable.rb:57:in `interpolate_with'
/home/huginn/huginn/app/concerns/liquid_interpolatable.rb:70:in `interpolate_options'
/home/huginn/huginn/app/concerns/liquid_interpolatable.rb:76:in `block (2 levels) in interpolate_options'
/home/huginn/huginn/app/concerns/liquid_interpolatable.rb:75:in `each'
/home/huginn/huginn/app/concerns/liquid_interpolatable.rb:75:in `each_with_object'
/home/huginn/huginn/app/concerns/liquid_interpolatable.rb:75:in `block in interpolate_options'
/home/huginn/huginn/app/concerns/liquid_interpolatable.rb:62:in `interpolate_with'
/home/huginn/huginn/app/concerns/liquid_interpolatable.rb:70:in `interpolate_options'
/home/huginn/huginn/app/models/agents/website_agent.rb:401:in `block in handle_data'
/home/huginn/huginn/app/models/agents/website_agent.rb:638:in `block in each'
/home/huginn/huginn/app/models/agents/website_agent.rb:637:in `times'
/home/huginn/huginn/app/models/agents/website_agent.rb:637:in `each'
/home/huginn/huginn/app/models/agents/website_agent.rb:637:in `zip'
/home/huginn/huginn/app/models/agents/website_agent.rb:637:in `each'
/home/huginn/huginn/app/models/agents/website_agent.rb:397:in `handle_data'
/home/huginn/huginn/app/models/agents/website_agent.rb:351:in `block in check_url'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/liquid-4.0.0/lib/liquid/context.rb:123:in `stack'
/home/huginn/huginn/app/models/agents/website_agent.rb:348:in `check_url'
/home/huginn/huginn/app/models/agents/website_agent.rb:333:in `block in check_urls'
/home/huginn/huginn/app/models/agents/website_agent.rb:332:in `each'
/home/huginn/huginn/app/models/agents/website_agent.rb:332:in `check_urls'
/home/huginn/huginn/app/models/agents/website_agent.rb:326:in `check'
/home/huginn/huginn/app/concerns/sortable_events.rb:92:in `check'
/home/huginn/huginn/app/concerns/dry_runnable.rb:31:in `dry_run!'
/home/huginn/huginn/app/controllers/agents/dry_runs_controller.rb:41:in `create'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/abstract_controller/base.rb:186:in `process_action'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:131:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/action_controller/metal/rescue.rb:20:in `process_action'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `block in instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.1/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/abstract_controller/base.rb:124:in `process'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionview-5.1.1/lib/action_view/rendering.rb:30:in `process'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/action_controller/metal.rb:189:in `dispatch'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/action_controller/metal.rb:253:in `dispatch'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/action_dispatch/routing/route_set.rb:31:in `serve'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/action_dispatch/journey/router.rb:46:in `block in serve'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/action_dispatch/journey/router.rb:33:in `each'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/action_dispatch/journey/router.rb:33:in `serve'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/action_dispatch/routing/route_set.rb:832:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.2/lib/rack/etag.rb:25:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.2/lib/rack/conditional_get.rb:38:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.2/lib/rack/head.rb:12:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.2/lib/rack/session/abstract/id.rb:232:in `context'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.2/lib/rack/session/abstract/id.rb:226:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/cookies.rb:613:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:97:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.1.1/lib/rails/rack/logger.rb:36:in `call_app'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.1.1/lib/rails/rack/logger.rb:24:in `block in call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:69:in `tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.1.1/lib/rails/rack/logger.rb:24:in `call'
/home/huginn/huginn/config/initializers/silence_worker_status_logger.rb:3:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/request_id.rb:25:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.2/lib/rack/method_override.rb:22:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.2/lib/rack/runtime.rb:22:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/executor.rb:12:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.2/lib/rack/sendfile.rb:111:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.1.1/lib/rails/engine.rb:522:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.1.1/lib/rails/railtie.rb:185:in `public_send'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/railties-5.1.1/lib/rails/railtie.rb:185:in `method_missing'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.2/lib/rack/tempfile_reaper.rb:15:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.2/lib/rack/lint.rb:49:in `_call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.2/lib/rack/lint.rb:37:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.2/lib/rack/show_exceptions.rb:23:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.2/lib/rack/common_logger.rb:33:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.2/lib/rack/chunked.rb:54:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/rack-2.0.2/lib/rack/content_length.rb:15:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:562:in `process_client'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:658:in `worker_loop'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:132:in `start'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/bin/unicorn:126:in `<top (required)>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bin/unicorn:22:in `load'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bin/unicorn:22:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/cli.rb:360:in `exec'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/cli.rb:20:in `dispatch'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/cli.rb:10:in `start'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/exe/bundle:35:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.1/exe/bundle:27:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
[00:00:02] INFO -- : Dry Run finished


but 
`{% assign num_new = num | minus: 0 %}`
everything it's fine....

**Comment by dsander** [comment]
Because `num` are extracted as strings strings you need to convert them to an integer first, what I have read ` {% assign num_new = num | minus: 0 %}` is the 'official' way of doing string to integer conversions in Liquid.

What was the liquid code you used when you got the exception? ` {% assign num_new = num %}` should not compare anything.

**Comment by se7cn** [comment]
@dsander 
yes . i got it.
`num` it's strings not a number.

i find  answers . it's funny

> To convert a string to a number just add 0 to the variable:
{% assign variablename = variablename | plus:0 %}
Not super elegant but it works!

via. https://stackoverflow.com/questions/27198710/convert-string-to-integer-in-shopify-liquid
