### ISSUE TITLE
Manual Install: problem installing gems

### ISSUE THREAD

**Issue by IAMEVANHE** [huginn/huginn#2080]
I was following the official manual installation guide and trying to install huginn on my Ubuntu (Ubuntu 16.04 x86_64) OVM. I could not proceed at "[5. Huginn > Install Gem](https://github.com/huginn/huginn/blob/master/doc/manual/installation.md)".

Below are the info from console:
```
root@localhost:/home/huginn/huginn# sudo -u huginn -H bundle install --deployment --without development  test                                                                                                     
Fetching gem metadata from https://rubygems.org/........                                                 
Fetching version metadata from https://rubygems.org/...                                                  
Fetching dependency metadata from https://rubygems.org/..                                                
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/dsl.rb:551:in `parse_line_number_from_description': invalid byte sequence in US-ASCII (ArgumentError)                                              
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/dsl.rb:517:in `to_s'         
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/friendly_errors.rb:16:in `to_
s'                                                                                                       
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/friendly_errors.rb:16:in `mes
sage'                                                                                                    
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/friendly_errors.rb:16:in `log
_error'                                                                                                  
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/friendly_errors.rb:123:in `re
scue in with_friendly_errors'                                                                            
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/friendly_errors.rb:121:in `wi
th_friendly_errors'                                                                                      
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/exe/bundle:22:in `<top (required)>'      
        from /usr/local/bin/bundle:22:in `load'                                                          
        from /usr/local/bin/bundle:22:in `<main>'     
```                                                   
Any advice?

**Comment by dsander** [comment]
Hi,

I think the problem is caused by missing unicode locale settings. Please check the output of `locale`, it should contain something like `LANG="en_US.UTF-8"`. If that is not the case add that to `/etc/default/locale` and run `sudo locale-gen`.
After opening a new shell the bundle installation should work.

**Comment by IAMEVANHE** [comment]
@dsander 
Thanks, but I am still having issues. 
I edited the file "/etc/default/locale" as below:
"
#  File generated by update-locale
LANG="en_US.UTF-8"
"
And after that, I ran:
$ sudo locale-gen"
And here are the result:
"
root@localhost:/home/huginn/huginn# sudo -u huginn -H bundle install --deployment --without development test
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/dsl.rb:551:in `parse_line_number_from_description': invalid byte sequence in US-ASCII (ArgumentError)
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/dsl.rb:517:in `to_s'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/friendly_errors.rb:16:in `to_s'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/friendly_errors.rb:16:in `message'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/friendly_errors.rb:16:in `log_error'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/friendly_errors.rb:123:in `rescue in with_friendly_errors'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/exe/bundle:22:in `<top (required)>'
        from /usr/local/bin/bundle:22:in `load'
        from /usr/local/bin/bundle:22:in `<main>'
"
Any more advice? Thank you.

**Comment by dsander** [comment]
Did you also open a new shell? Maybe you also need to set `LC_ALL`:
```
LANG=en_GB.UTF-8
LC_ALL=en_GB.UTF-8
```
If it still does not work try prepending the environment variables to the bundle install command:
```
LANG=en_GB.UTF-8 LC_ALL=en_GB.UTF-8 sudo -u huginn -H bundle install --deployment --without development test
```

**Comment by IAMEVANHE** [comment]
@dsander 
Sorry, still no resolved.
The file "/etc/default/locale" is configured as:
"
LANG="en_GB.UTF-8"
LC_ALL="en_GB.UTF-8"
"
And then:
"
root@localhost:~# sudo locale-gen
**/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_GB.UTF-8)**
Generating locales (this might take a while)...
Generation complete.
"
And then:
"
root@localhost:~# LANG=en_GB.UTF-8 LC_ALL=en_GB.UTF-8 sudo -u huginn -H bundle install --deployment --wi thout development test
**-bash: warning: setlocale: LC_ALL: cannot change locale (en_GB.UTF-8)
Could not locate Gemfile**
"
I am with an OVM. Would this be the issue?

**Comment by dsander** [comment]
I think the problem is not necessarily caused by OVM, but the Ubuntu base image. Are you using a public could provider or is there an other way for me to test the installation with the same base image?

Can you try this?
```
sudo locale-gen en_GB.UTF-8
sudo update-locale LANG=en_GB.UTF-8
```

**Comment by zikeji** [comment]
I'm gravedigging, and I'm not sure if this is your issue - but I had the same issue, and it had to do with being connected remotely. See: https://askubuntu.com/a/530829

I just logged in from within my session (su -u user) and it fixed it.

**Comment by IAMEVANHE** [comment]
I don't have that VPS now, and I am not having this issue. So let's close it.
