### ISSUE TITLE
The Attribute Difference Agent 

### ISSUE THREAD

**Issue by se7cn** [huginn/huginn#2082]
last1 = 10 ，diff -1
last2 = 11， diff -4
last3 = 15...

so when i set value form other agent. it's multiple sets of data

> url A num = 1，  url A num = 10， 
 url B num = 5，  url B num = 3，

can not works every url ？ ... it's always last event‘s value...’ 

> 1 diff = -9
10 diff = +5
5 diff = -2
3

how to check every event‘s diff？

**Comment by dsander** [comment]
I don't think that is possible with one `AttributeDifferenceAgent`, you could use a `TriggerAgent` to send values from `url A` to one Agent, `url B` to a second `AttributeDifferenceAgent` and so forth.

**Comment by se7cn** [comment]
thanks a lot . i will try it
