### ISSUE TITLE
Problems after upgrading Docker image

### ISSUE THREAD

**Issue by r0cknfire** [huginn/huginn#2087]
Hello. 
So I've been using Huginn for about three weeks now, but I've ran into some problems a couple hours back, after I updated the Docker image to the latest version. Here's what I did.
```
docker stop huginn
docker rm huginn
docker pull huginn/huginn:latest
docker run --detach \
    --publish 3000:3000 \
    --name huginn \
    --restart always \
    --env-file .env \
    -e DO_NOT_SEED=1 \
    -e DO_NOT_CREATE_DATABASE=1 \
    huginn/huginn
```

Everything was going well, it migrated the schema correctly judging by the last migration (`20170731191002`), though, after I log back into huginn and do anything related to agents or running a job, I'm getting the ***We're sorry, but something went wrong.*** page. 

And after checking the logs, I do indeed have an error with a backtrace. 
```
18:58:59 jobs.1 | /app/lib/huginn_scheduler.rb:141:in `+': no implicit conversion of nil into String (TypeError)
18:58:59 jobs.1 |       from /app/lib/huginn_scheduler.rb:141:in `block in setup'
18:58:59 jobs.1 |       from /app/lib/huginn_scheduler.rb:140:in `times'
18:58:59 jobs.1 |       from /app/lib/huginn_scheduler.rb:140:in `setup'
18:58:59 jobs.1 |       from /app/app/concerns/long_runnable.rb:86:in `setup!'
18:58:59 jobs.1 |       from /app/lib/agent_runner.rb:82:in `block in run_workers'
18:58:59 jobs.1 |       from /app/lib/agent_runner.rb:79:in `each'
18:58:59 jobs.1 |       from /app/lib/agent_runner.rb:79:in `run_workers'
18:58:59 jobs.1 |       from /app/lib/agent_runner.rb:39:in `run'
18:58:59 jobs.1 |       from bin/threaded.rb:13:in `<top (required)>'
18:58:59 jobs.1 |       from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/commands/runner/runner_command.rb:34:in `load'
18:58:59 jobs.1 |       from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/commands/runner/runner_command.rb:34:in `perform'
18:58:59 jobs.1 |       from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
18:58:59 jobs.1 |       from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
18:58:59 jobs.1 |       from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
18:58:59 jobs.1 |       from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/command/base.rb:63:in `perform'
18:58:59 jobs.1 |       from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/command.rb:44:in `invoke'
18:58:59 jobs.1 |       from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/commands.rb:16:in `<top (required)>'
18:58:59 jobs.1 |       from bin/rails:9:in `require'
18:58:59 jobs.1 |       from bin/rails:9:in `<main>'
18:58:59 jobs.1 | Starting HuginnScheduler
18:58:59 jobs.1 | exited with code 1
```
It seems to be coming from data contained in the database (which is running on the host system), as it works fine with a database that Huginn created and seeded by itself.

Any idea as for where it may come from ? I'll try rolling back to an older version in the meantime. 
Thanks in advance.

**Comment by r0cknfire** [comment]
After testing, I found various things:
* Rolling back to an old image doesn't work, same error
* Launching the docker container with `DO_NOT_RUN_JOBS` makes it work, though it doesn't run any job, obviously.
* Removing the container and the image, giving huginn an empty database and letting it create the structure and giving it the same .env file that I would normally use doesn't work either, same error.

I don't know what's wrong, but it seems to be coming from my .env file. I'll check it and try I can find something wrong with it.

**Comment by r0cknfire** [comment]
Soo... I found the issue and fixed it. Turns out it's the `TIMEZONE` setting that I set wrong. 
I set at `Europe/Paris` instead of `Paris`, and it caused the error above. So a wrong timezone seems to be the issue.
I'm closing the issue, since it's fixed.

**Comment by dsander** [comment]
Hi @r0cknfire,

did you modify your `.env` file before updating? The exception looks like the `TIMEZONE` setting does not contain a valid timezone.

**Comment by dsander** [comment]
Ah! I should have refreshed the page before answering, glad you figured it out 😄
