### ISSUE TITLE
How to get the original url in Data Output Agent after Phantom Js Cloud Agent 

### ISSUE THREAD

**Issue by tortoo** [huginn/huginn#2088]
In Data Output Agent the url option can only receive the last Phantom Js Cloud Agent‘s url which is converted, and how can I get the original url in Data Output Agent? Thanks for helping!😊

**Comment by tortoo** [comment]
Solved this perfectly. Only need to change the name of original url to url2. 😹

**Comment by kevinrench** [comment]
excuse me, How can you do that? I use phantomJS, also get this url which is not the real url

https://phantomjscloud.com/api/browser/v2/ak-bwpwz-jt6j6-6pjhm-3hcsz-82fdq/?request=%7B%22url%22%3A%22http%3A%2F%2Fwww.szse.cn%2Faboutus%2Ftrends%2Fnews%2F%22%2C%22renderType%22%3A%22html%22%2C%22requestSettings%22%3A%7B%22userAgent%22%3A%22Mozilla%2F5.0%20%28Windows%20NT%2010.0%3B%20Win64%3B%20x64%29%20AppleWebKit%2F537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome%2F60.0.3100.0%20Safari%2F537.36%22%7D%7D
