### ISSUE TITLE
Is there an agent to store a data in memory?

### ISSUE THREAD

**Issue by homlett** [huginn/huginn#2089]
I'm looking to compare the same data (from the same source) over the time.

Is there a way to keep a value produced by an agent (typically the Website agent) in memory to use it later? To use it either by the same agent the next time is running, or by any other agent anytime. Or is there a way to access to the payload history of an agent?

If not, I think a good solution would be to have an agent able to create/update/delete a credential value. Moreover, if credentials could be an array or a hash of values, it would be easier to keep a history of a value (with an *add* function in addition to *create*, *update* and *delete*).

Thank you!

**Comment by dsander** [comment]
Hi @homlett,

the only Agent that can freely modify it's memory is the `JavaScriptAgent`. There are a few others that can keep track of the change of a value (`ChangeDetectorAgent` or `PeakDetectorAgent` might be helpful depending on your use case).

I don't think it is possible to access historic events easily. You could use a `DataOutputAgent` to create a JSON or XML feed of events it received and consume that feed with a `WebsiteAgent`.

That is your use case to modify credentials? We have the `CommanderAgent` which can modify the options of a different Agent.

**Comment by nogre** [comment]
@homlett I use credentials to store persistent data. The Javascript agent can read, modify and update them. As @dsander said, it can also do this with its local memory.

You might also consider using a Digest Agent, which can look back at X recent events assuming that those events haven't expired.

**Comment by homlett** [comment]
Sorry guys, I can't remember what I tried to do so I probably found a way to do it! Thanks for Huginn, it's awesome.

**Comment by dsander** [comment]
Nice, glad you like it 😄
