### ISSUE TITLE
resolve remote gem dependencies during docker image build

### ISSUE THREAD

**Issue by m0** [huginn/huginn#2090]
As far as I understand [docker/multi-process/scripts/init#L59](https://github.com/huginn/huginn/blob/master/docker/multi-process/scripts/init#L59) it updates remote gem dependencies on container start.

Shouldn't container images ship software of defined version (including dependencies) offering reproducable behaviour in development and production environment?

I suggest moving the installation of dependencies from container startup (init-script) to image build phase (Dockerfile).

**Comment by dsander** [comment]
Hi @m0,

we are doing that. The versions are locked in `Gemfile.lock`, we have to re-run `bundle install` when the container starts because some of the dependencies are optional (the database adapters) and we support adding [agent gems](https://github.com/huginn/huginn/blob/master/.env.example#L165-L181) to extend Huginn.

**Comment by m0** [comment]
Thank you for the response @dsander! I stumbled over this, when the container did not start because `bundle install` was unable to connect to the remote gem repos. I would prefer running `bundle install` only when required due to added custom agents but AFAIU that would mean the database adapters would have to become "non optional". As I currently can't offer any idea how to properly improve this, I'll close the issue.

**Comment by dsander** [comment]
I see, it would be nice if we could skip `bundle install` if it is not required. I think we would need to duplicate some of the logic of the `Gemfile` in bash to check if we need to run `bundle install`, not impossible but certainly some work 😄
