### ISSUE TITLE
How to control angent work flow ?

### ISSUE THREAD

**Issue by se7cn** [huginn/huginn#2092]
> webtsite angent： 
> extract value = 1 // cookie is worked.
> extract value = 0 // cookie is expired. need post anget login and get new cookies.

So.

How to control and chose the next agent ..

some times . whit the different value. need different angent flow next.

**Comment by dsander** [comment]
I think the `TriggerAgent` is what you are looking for.

**Comment by se7cn** [comment]
thanks...：）
