### ISSUE TITLE
website angent can't extract the url form huginn..

### ISSUE THREAD

**Issue by se7cn** [huginn/huginn#2093]
Liquid Output Agent or any angent output a url

> url = http://.../huginn/users/1/web_requests/...

website angent: 

> set  url =  http://.../huginn/users/1/web_requests/...

and it's timeout and can't work anymore.

I need Liquid Output Agent make a data list . list private  article list. and use website angent to check that. sometimes i neet Liquid Output Agent update form other angent.

so . how to work it? thanks

**Comment by dsander** [comment]
Hi @se7cn,

I need more information to be able to help you. In general the setup does work, how are your Agents configured and can you access the feed of the output Agent without Huginn?

**Comment by se7cn** [comment]
configured nothing
use other url whitout huginn  everthing it's work.

with url like this.  Dry RUN it's time out and “ Error: ”  or“Error: Bad Gateway”
> {
  "expected_update_period_in_days": "2",
  "url": "http://....huginn's url..../users/1/web_requests/98/XY******7.xml",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "title": {
      "xpath": "/html",
      "value": "string(.)"
    }
  }
}


The last test .. I try save that
And RUN.  It's worked
So i don‘t’ understand that `Dry RUN` it's always time out. 
I never try to save it,
My fault...
