### ISSUE TITLE
Huginn website

### ISSUE THREAD

**Issue by metboris90** [huginn/huginn#2095]
After configuring the website agent (which works well), I would like to know how to download the entire web page and keep it on my local server?

**Comment by dsander** [comment]
Hi @metboris90,

you can use a `LocalFileAgent` to write the contents of an Event to a file (`ENABLE_INSECURE_AGENTS` needs to be set to `true` in `.env`). We also have the `LiquidOutputAgent`,  which can output HTML.

**Comment by metboris90** [comment]
The Liquid Output Agent interests me a lot, I'll try as soon as possible to see what it's going to give and then I'll get back to you. Thanks for your help but is that you would not have an example of configuration of the Liquid Output Agent?

If others have ideas please help me

**Comment by dsander** [comment]
I don't understand, the Agent does come with an example configuration when you create it.

**Comment by metboris90** [comment]
Please @dsander Can you explain to me the content field of the agent "LiquidOutputAgent"?
I do not know how to fill in the parameters for the money to get me the data on the url.

The field "content" contains by default

[When you use the "Last event in" or "Merge events" option, you can use variables from the last event received, like this:

Name: {{name}}
Url:  {{url}}

If you use the "Last X Events" mode, a set of events will be passed to your Liquid template.  You can use them like this:

<table class="table">
  {% for event in events %}
    <tr>
      <td>{{ event.title }}</td>
      <td><a href="{{ event.url }}">Click here to see</a></td>
    </tr>
  {% endfor %}
</table>
]

If others have ideas please help me

**Comment by dsander** [comment]
You first need to send the data you want to display with an Event to the `LiquidOutputAgent`, for example use a `WebsiteAgent` to extract the whole html of a page:
```json
{
  "expected_update_period_in_days": "2",
  "url": "https://xkcd.com",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "body": {
      "css": "html",
      "value": "."
    }
  }
}
```

Send that to a `LiquidOutputAgent` with `mode` set to `last event in` and `content`: `{{body}}` of you open the link displayed on the Agents show page you should see the content of the page you fetched.

**Comment by nogre** [comment]
@metboris90 The content of the Liquid Output Agent is the final step for your data. It takes whatever content it has received from events, formats it, and then makes it publicly available. 

So, in Last X Events mode, the agent gets an array of the last X events. You can then iterate over those events. For example, if the events passed to your Liquid Output Agent are a series of forum post titles with links to them, then 

```
{% for event in events %} 
<p><a href ="{{ event.url }}">{{ event.title }}</a></p>
{% endfor %} 

```
will print a list of the forum titles linked to their respective posts. The output will be like:

> [Post Title 1](link1)
> [Post Title 2](link2)
> [Post Title 3](link3)
> ...

This data is then accessible from the URL linked in the Agent's summary.

**Comment by metboris90** [comment]
Thanks @dsander it works fine, I am very happy. You saved me

**Comment by dsander** [comment]
Great! Can we close the issue?

**Comment by metboris90** [comment]
yes

**Comment by metboris90** [comment]
hello I open again this subject because I need clarification on the Last X Events mode of the agent Liquid output agent.

If I choose the last x events mode, I would like to know where the variables come from
"event.title" and "event.url".

In my opinion it must come from the extraction of the website agent. but for the moment no extraction is made by these parameters

Here is my website agent
{
  "expected_update_period_in_days": "2",
  "url": "https://beninwebtv.com/",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "body": {
      "css": "html",
      "value": "."
    }

    "url": {
      "css": "html",
      "value": "@src"
    }

    "title": {
      "css": "html",
      "value": "@title"
    }
  }
}

and here is the content of my agent liquid output agent in last x events mode
<table class = "table">
  {% for event in events%}
    <Tr>
      <td> {{event.title}} </ td>
      <td> <a href="{{ event.url }}"> Click here to see </a> </ td>
    </ Tr>
  {% endfor%}
</ Table>

**Comment by dsander** [comment]
The `LiquidOutputAgent` operates on on the last X events it received. Inside the `for` loop every `event` object corresponds to the Event payload of the received events. You can check the events of your `WebsiteAgent` on the "Agent show" -> "Events" page.

**Comment by dsander** [comment]
Closing because the same question was asked in #2117
