### ISSUE TITLE
Postagent and set-cookie

### ISSUE THREAD

**Issue by 7x11** [huginn/huginn#2097]
PostAgen Run Results

> "Set-Cookie": "token=ced50********aa46;expires=Fri, 25-Aug-17 10:12:25 GMT;path=/, random=7550;path=/, userid=487527; expires=Sun, 24-Sep-2017 10:07:25 GMT; Max-Age=2592000; path=/, user_email=*********; expires=Sun, 24-Sep-2017 10:07:25 GMT; Max-Age=2592000; path=/, any_web=nleh2j2u5******nbb0; path=/",

and this cookies can't work whit any anget.
i removed  code   `expires=Fri, 25-Aug-17 10:12:25 GMT;path=/,`   like this.
and everything it's worked.

I check network 
Then Post success and Response Headers get cookies

> Set-Cookie:GINFO=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; domain=.zimuzu.tv
Set-Cookie:GKEY=a8fe2f*****a4a6fc; expires=Mon, 23-Aug-2027 09:41:30 GMT; Max-Age=315360000; path=/; domain=.zimuzu.tv; httponly
Set-Cookie:GKEY=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; domain=.zimuzu.tv

so. if Post agent use cookies form this
it's can't work. if remove the code whit `expires=` `Max-Age` .....

I'm not sure . so What is the right way? thanks

**Comment by dsander** [comment]
You are trying to use the `Set-Cookie` header you are getting from a `PostAgent` Event in another Post/WebsiteAgent? As far as I know the the website sending the cookie like this should also accept it when you send it back.
Did you check in the Chrome or Firefox developer tools how the browser is accepting and sending the cookie back to that website?
