### ISSUE TITLE
PostAgent \n being escaped as \\n in payload

### ISSUE THREAD

**Issue by si1en7** [huginn/huginn#2098]
This is my first day using huginn and I am definitely loving getting to know the project better. I am experimenting with the different agents and seemed to have stumbled over a roadblock with creating a new line '\n' in the PostAgent. I take json data collected from another agent and send it to PostAgent to push to a Mattermost channel.

The problem I am running into is that when trying to output a new line, huginn converts \n to` \\n` when you save the PostAgent settings. Thus making \n become literal. Is there any workaround to this or something I'm missing to make a new line? Any help appreciated.

**Comment by dsander** [comment]
Hi @si1en7,

I suppose you are using liquid to format the body you are sending to Mattermost? We have a [custom tag](https://github.com/huginn/huginn/wiki/Formatting-Events-using-Liquid) to insert line breaks: `{% line_break %}`

**Comment by si1en7** [comment]
Sorry for taking so long to get back to you! Thanks for the reply and I appreciate the response. :)
