### ISSUE TITLE
[Fluff] My Agent Flow Diagram, 400+ agents

### ISSUE THREAD

**Issue by nogre** [huginn/huginn#2099]
I made a Google-News-like site that monitors philosophy blogs and media. Here is the Agent Flow for all agents.

https://i.imgur.com/vAkpc8i.png

**Comment by dsander** [comment]
That looks very cool, I suppose most of the input Agents are Website and RssAgents?

**Comment by nogre** [comment]
Yep. The 'top layer', if you will, are the hundreds of RSS and Website Agents. They then go through a series of formatters, classifiers, and filters before being reformatted for output.

**Comment by dsander** [comment]
Nice, it is always nice to hear from bigger Huginn setups. How did the setup scale for you?

**Comment by knu** [comment]
Cool.  You can share your story in #308, or maybe write a blog article and put the link on our Wiki!

**Comment by cantino** [comment]
Thanks for sharing this!

**Comment by nogre** [comment]
Thanks to you all, @cantino @dsander @knu .

@dsander I had it running on a 512mb ram setup on Digital Ocean at first, 1 worker. Eventually the Website Agents caused issues. They use more ram to begin with and, for reasons I am unsure about and don't have time to investigate, eventually caused all the ram to get used up.

Switched to a 2g ram box on OVH, and it runs great. There is still some odd issue that causes ram to get used up with the Website Agents. I have the thing periodically reboot itself, and haven't had to worry about it since.

**Comment by dsander** [comment]
Yeah, memory is always an issue, especially WebsiteAgents and RSSAgents that fetch multiple feeds/sites can require a lot of it.
