### ISSUE TITLE
How to add the "Unix timestamp" in http requests?

### ISSUE THREAD

**Issue by ttestdock** [huginn/huginn#2102]
Some website will require the "Unix timestamp" as a parameter to view content. 
How to add the "Unix timestamp", accurated to milliseconds like `1504066333999`, in website agent?

**Comment by dsander** [comment]
Hi @ttestdock,

Liquid has [date filters](https://shopify.github.io/liquid/filters/date/) which allow to format a date the same as strftime does: `{{"now" | date: "%s%L"}}`

**Comment by ttestdock** [comment]
it works. Thank you!
