### ISSUE TITLE
when clicking diagram report We're sorry, but something went wrong.

### ISSUE THREAD

**Issue by manyang901** [huginn/huginn#2109]
these are logs
I, [2017-09-02T22:19:33.593717 #2469]  INFO -- : 2017-09-02T22:19:33-0700: [Worker(host:localhost.localdomain pid:2469)] 1 jobs processed at 9.5306 j/s, 0 failed
I, [2017-09-02T22:19:38.842009 #2513]  INFO -- : [22396c95-0625-4c51-b3ef-1df3952a777f]   Rendered diagrams/show.html.erb within layouts/application (60006.6ms)
I, [2017-09-02T22:19:38.842394 #2513]  INFO -- : [22396c95-0625-4c51-b3ef-1df3952a777f] Completed 500 Internal Server Error in 60013ms (ActiveRecord: 1.6ms)
F, [2017-09-02T22:19:38.843629 #2513] FATAL -- : [22396c95-0625-4c51-b3ef-1df3952a777f]
F, [2017-09-02T22:19:38.843696 #2513] FATAL -- : [22396c95-0625-4c51-b3ef-1df3952a777f] ActionView::Template::Error (execution expired):
F, [2017-09-02T22:19:38.843876 #2513] FATAL -- : [22396c95-0625-4c51-b3ef-1df3952a777f]     22:       </div>
[22396c95-0625-4c51-b3ef-1df3952a777f]     23:
[22396c95-0625-4c51-b3ef-1df3952a777f]     24:       <div class='digraph'>
[22396c95-0625-4c51-b3ef-1df3952a777f]     25:         <%= render_agents_diagram(@agents, layout: params[:layout]) %>
[22396c95-0625-4c51-b3ef-1df3952a777f]     26:       </div>
[22396c95-0625-4c51-b3ef-1df3952a777f]     27:     </div>
[22396c95-0625-4c51-b3ef-1df3952a777f]     28:   </div>
F, [2017-09-02T22:19:38.843932 #2513] FATAL -- : [22396c95-0625-4c51-b3ef-1df3952a777f]
F, [2017-09-02T22:19:38.844001 #2513] FATAL -- : [22396c95-0625-4c51-b3ef-1df3952a777f] app/helpers/dot_helper.rb:16:in `render_agents_diagram'
[22396c95-0625-4c51-b3ef-1df3952a777f] app/views/diagrams/show.html.erb:25:in `_app_views_diagrams_show_html_erb__904839570449105690_391227651600'
[22396c95-0625-4c51-b3ef-1df3952a777f] config/initializers/silence_worker_status_logger.rb:3:in `call'
Both nginx logs and unicorn logs displays no error

I don't understand what happened 
New to Ruby

**Comment by dsander** [comment]
Hi @manyang901,

the error log looks a bit cut up, can you upload a bigger part of the logfile?

It seems the error is coming from a call that is made to the google charts API to render the diagram. Can your huginn server reach `https://chart.googleapis.com/chart`?

If you followed the manual installation guide you already should have graphviz installed, check  that is the case by running `which dot` in a console.
If the command returned a path you can enable `USE_GRAPHVIZ_DOT=dot` in `.env` and re-export the Huginn configuration with `sudo bundle exec rake production:export`. Huginn will then not rely on the Google API to render the chart but use graphviz locally.

**Comment by manyang901** [comment]
Thank you for analyzing me issue 
I know what is the problem 
It's China great firewall's fault
My server do not have access to Google API
Thank you

**Comment by dsander** [comment]
I see, if you have installed or can install [graphviz](http://www.graphviz.org/) you can avoid the need for the API call to google servers.
