### ISSUE TITLE
Issues storing recipient list for email agent in a credential

### ISSUE THREAD

**Issue by educatedwarrior** [huginn/huginn#2121]
When I attempt to use a recipient list from credentials, I get the error below.

Error sending digest mail to "207798XXXX@txt.att.net","205401XXXX@tmomail.net","404788XXXX@txt.att.net","704524XXXX@messaging.sprintpcs.com": 501 <"207798XXXX@txt.att.net">: recipient address must contain a domain

**Comment by dsander** [comment]
That is because the recipients must be an array. You can do the following:

```
{% capture emails %}{% credential emails  %}{% endcapture %}{{ emails | split: ',' | as_object }}
```

@knu Do you think it would make sense to liquid interpolate the credential string? That would allow to put the `split`, `as_object` filter chain inside the credential itself.

**Comment by educatedwarrior** [comment]
Thanks, that worked.
