### ISSUE TITLE
New installation SQL / MariaDB issues

### ISSUE THREAD

**Issue by xdirty** [huginn/huginn#2131]
so im new to linux, i have installed huginn in the past with minor issues.
Im trying to install a local installation of huginn but this whole conversion from mysql to mariaDB is driving me crazy.

In the past as soon as i installed mysql it would prompt a dialog to set a password. i would leave it blank and also leave it blank in my .env file. i tried creating a root password and works for a short while then stops working.

In the huginn folder i try to run `bundle exec rake db:create ` but i get:

> pi@raspberrypi:~/huginn $ bundle exec rake db:create
#<Mysql2::Error: Access denied for user 'root'@'localhost'>
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "reconnect"=>true, "database"=>"huginn_development", "pool"=>20, "username"=>"root", "password"=>"kostas9", "host"=>nil, "port"=>nil, "socket"=>"/var/run/mysqld/mysqld.sock", "strict"=>false}, {:charset=>"utf8"}
(If you set the charset manually, make sure you have a matching collation)
Created database 'huginn_development'
#<Mysql2::Error: Access denied for user 'root'@'localhost'>
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "reconnect"=>true, "database"=>"huginn_test", "pool"=>20, "username"=>"root", "password"=>"kostas9", "socket"=>"/var/run/mysqld/mysqld.sock", "host"=>nil, "port"=>nil, "strict"=>false}, {:charset=>"utf8"}
(If you set the charset manually, make sure you have a matching collation)
Created database 'huginn_test'

im so confused can anyone help me out ?

I even tried to do a docker installation but i was told the docker image doesn support arm processor as i have a raspberry pie

**Comment by xdirty** [comment]
I figured out my database problems! MariaDB by default authenticates by plugin not password so you have to change the settings, heres the commands

> sudo mysql -u root

[mysql] use mysql;
[mysql] update user set plugin='' where User='root';
[mysql] flush privileges;
[mysql] \q

source:https://stackoverflow.com/questions/30815971/mariadb-installed-without-password-prompt

I hate mariadb!
please dont close this thread yet i have 1 more minor issue that i will post soon

**Comment by xdirty** [comment]
I get these errors, are they a problem ?

> pi@raspberrypi:~/huginn $ bundle exec foreman start
01:39:50 web.1  | started with pid 6712
01:39:50 jobs.1 | started with pid 6713
01:40:20 jobs.1 | /home/pi/huginn/lib/utils.rb:175: warning: already initialized constant Utils::HTMLTransformer::SINGLE
01:40:20 jobs.1 | /home/pi/huginn/lib/utils.rb:175: warning: previous definition of SINGLE was here
01:40:20 jobs.1 | /home/pi/huginn/lib/utils.rb:176: warning: already initialized constant Utils::HTMLTransformer::MULTIPLE
01:40:20 jobs.1 | /home/pi/huginn/lib/utils.rb:176: warning: previous definition of MULTIPLE was here
01:40:20 jobs.1 | /home/pi/huginn/lib/utils.rb:177: warning: already initialized constant Utils::HTMLTransformer::COMMA_SEPARATED
01:40:20 jobs.1 | /home/pi/huginn/lib/utils.rb:177: warning: previous definition of COMMA_SEPARATED was here
01:40:20 jobs.1 | /home/pi/huginn/lib/utils.rb:178: warning: already initialized constant Utils::HTMLTransformer::SRCSET
01:40:20 jobs.1 | /home/pi/huginn/lib/utils.rb:178: warning: previous definition of SRCSET was here
01:40:20 jobs.1 | /home/pi/huginn/lib/utils.rb:180: warning: already initialized constant Utils::HTMLTransformer::URI_ATTRIBUTES
01:40:20 jobs.1 | /home/pi/huginn/lib/utils.rb:180: warning: previous definition of URI_ATTRIBUTES was here
01:40:20 jobs.1 | /home/pi/huginn/lib/utils.rb:208: warning: already initialized constant Utils::HTMLTransformer::URI_ELEMENTS_XPATH
01:40:20 jobs.1 | /home/pi/huginn/lib/utils.rb:208: warning: previous definition of URI_ELEMENTS_XPATH was here
01:40:20 jobs.1 | Starting HuginnScheduler
01:40:20 jobs.1 | /usr/local/lib/ruby/gems/2.4.0/gems/rufus-scheduler-3.3.2/lib/rufus/scheduler/cronline.rb:89: warning: constant ::Fixnum is deprecated
01:40:20 web.1  | [2017-09-20 18:40:20] INFO  WEBrick 1.3.1
01:40:20 web.1  | [2017-09-20 18:40:20] INFO  ruby 2.4.1 (2017-03-22) [armv7l-linux-eabihf]
01:40:20 web.1  | [2017-09-20 18:40:20] INFO  WEBrick::HTTPServer#start: pid=6714 port=3000
01:40:22 jobs.1 | Starting DelayedJobWorker

**Comment by dsander** [comment]
Hi @xdirty,

glad you figured out the issue with MariaDB. Those warnings are totally fine in development mode.

**Comment by xdirty** [comment]
Thank you. I think all my issues are solved now

**Comment by dsander** [comment]
Great!
