### ISSUE TITLE
网页代理工作会卡住

### ISSUE THREAD

**Issue by 7x11** [huginn/huginn#2133]
@waldens @WangQiru 
大家好， 我遇到了问题， 在你们的 issues 找到了同样的错误，
website angent 总是会卡住。 频率不明确，最多坚持一周肯定会卡住。

总之我尝试了很多配置，更换了服务器，ram从1G到4G都试过， 使用最低的能耗 1 worker  进行工作。唯一没有尝试过的就是 使用 debian 以外的OS， 因为我只会配置 debian 8 x64 ，其他OS 都无法完成安装 

我一度怀疑是不是中文的原因？所以才找到两位
> I am worried that the error comes from the Chinese characters -__-!

`
不知道你们有没有找到解决的办法？谢了

**Comment by WangQiru** [comment]
Postgres没出过问题，貌似是由于mysql。

**Comment by se7cn** [comment]
@WangQiru 谢谢 终于看到希望了
这就去尝试一下

**Comment by tortoo** [comment]
居然看到中文提问😹。感觉是你频率设置的问题，量大，频率密集，一个没执行完另一个又来了，叠加多了就卡了。一个建议调整运行时间间隔，另一个建议手机装个能方便重启你自己服务器的app，卡了就随手重启。通常重启能恢复

**Comment by se7cn** [comment]
@tortoo 

看到中文回复才6啊 

这问题按照比例来看， 也不算是小众问题了。
作者每次的回复都差不多， 关键是作者无法重现故障，而这个神奇的日志里没有任何可靠的问题记录。  
只能自己摸黑尝试了 我觉得跟性能和频率无关

**Comment by se7cn** [comment]
我想到另外一个方式， 用huginn 自己监控自己。
当卡住了自己重启一下。
不过我发现，卡住以后无法自救...
所以我想我不如开两个huginn互相监控
是个办法?

**Comment by tortoo** [comment]
我用的heroku，是重启heroku。原来找过自动重启的办法，无果。监控卡住然后推送提醒也不知道怎么实现，感觉能做到这步然后手机端手工重启就已经相当满足，自动的办法估计很难实现

**Comment by waldens** [comment]
我的是Ubuntu14，后来卡住的Agent自己变正常了，前后唯一变量就是pull了新版本，但有可能是巧合，并没找到其它排查线索，帮不上忙…

**Comment by WangQiru** [comment]
@se7cn @tortoo 试试cron定时自动重启？我现在改用docker+postgres没出过问题

**Comment by tortoo** [comment]
heroku用的就是Postgres。不知道怎么用cron重启……

**Comment by WangQiru** [comment]
@tortoo 我觉得是ram问题，但是不太确定。之前2G的VPS用MySQL就有这个问题，后来换成Postgres莫名其妙就好了。huginn其实超级吃ram，job多的时候web界面都会卡死。

**Comment by se7cn** [comment]
我看这个问题 大概有五六个具体实例的帖子， 其中有三个都是中文用户
我深深的怀疑是中文编码什么的问题

如果按照这个尿崩的频率， 其他用户早就炸窝了吧 ？ 
反正我最高记录是半个月，一般 1-5天肯定要挂一次

**Comment by WangQiru** [comment]
@se7cn取决于目标网站的编码吧，我有部分涉及到中文的website agent，加了：
```js
"force_encoding": "gbk"
```

**Comment by se7cn** [comment]
心累 感觉只有走自动重启这条路了

**Comment by se7cn** [comment]
@waldens 谢谢，

> 后来卡住的Agent自己变正常了
意思是没有重启 就自己恢复了？ 如果这样的话 那还真是明显升级了  可以自己干掉卡住的任务

还是。。恢复以后就再也没出过问题

**Comment by tortoo** [comment]
@WangQiru 应该是内存的问题，我查了heroku，会内存泄漏，网上有定时重启的办法，我还在试。感觉和编码关系不大，gbk的网站貌似不加这句解析不出来，非gbk的估计加了也没用

**Comment by tortoo** [comment]
@se7cn vps应该更容易定时重启，而且定时重启应该更健康，管它到底是哪的问题，定时重启最好上上

**Comment by se7cn** [comment]
@tortoo 研究下

> Shell Command Agent

定时执行 1 清除重启计划  2 新增重启计划

如果jobs 挂了， 那么 就没人去清除重启计划了。。。自动重启就好
如果没挂， 那么就是一直去循环创建计划，但并不会重启。

行得通么？

**Comment by tortoo** [comment]
@se7cn 我不是很懂，都是直接找代码和教程，你搜下，应该有不少，直接拿来用

**Comment by se7cn** [comment]
定时重启确实可以解决这个问题

我使用 shell common agent  设置了一个定时任务
当卡住的时候就自杀一次

**Comment by tortoo** [comment]
@se7cn 又搜了下，把.env里的database pool改成30能解决，试试看

**Comment by se7cn** [comment]
@tortoo 没用的。所有能找到的方法，除了更换数据库， 都试过了。
我看了下自动重启日志， 24小时内挂了两次， 按照计划任务自己重启了，也算解决问题了。

**Comment by tortoo** [comment]
@se7cn 没搞过，这个怎么设置？

**Comment by se7cn** [comment]
跑了一段时间， 1G内存机器， 按照最低配运行
发现最近每天都要抽风，以前好歹能坚持三四天的

- 配置里打开 shell 权限， 也就是 shell common agent 的权限
- 设置一个 shell agent， 每小时创建一个 定时任务，并删除上一个定时任务。
- 意味着， 永远有一个定时任务。
- 定时任务的内容就是，60分钟后，重启。
- 所以，如果卡住了，就不会继续创建新任务，也不会删除这个60分钟的“自杀”任务

观察了下agent event 日志
`exit_status":1,"` 就是   删除任务时，任务已经不再了，也就是 已经“自杀”了。。

另外， 有时候发现自杀也没用
查了半天。。发现是错误是 “ 内存无法分配 ”，导致重启任务都无法执行。

`还是加内存把。。。`



> 1d ago	{"command":"atrm 631","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
1d ago	{"command":"atrm 630","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
1d ago	{"command":"atrm 629","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
1d ago	{"command":"atrm 628","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
1d ago	{"command":"atrm 627","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
1d ago	{"command":"atrm 626","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
1d ago	{"command":"atrm 625","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
1d ago	{"command":"atrm 624","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
1d ago	{"command":"atrm 623","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
1d ago	{"command":"atrm 622","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
1d ago	{"command":"atrm 621","path":"/","exit_status":1,"errors":"Cannot find jobid 621","output"	ShowRe-emitDelete
1d ago	{"command":"atrm 620","path":"/","exit_status":0,"errors":"","output":""}
1d ago	{"command":"atrm 619","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
1d ago	{"command":"atrm 618","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
1d ago	{"command":"atrm 617","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
1d ago	{"command":"atrm 616","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
1d ago	{"command":"atrm 615","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
1d ago	{"command":"atrm 614","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
1d ago	{"command":"atrm 613","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
1d ago	{"command":"atrm 612","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
1d ago	{"command":"atrm 611","path":"/","exit_status":1,"errors":"Cannot find jobid 611","output"	ShowRe-emitDelete
1d ago	{"command":"atrm 610","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
1d ago	{"command":"atrm 609","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 608","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 607","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 606","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 605","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 604","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 603","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 602","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 601","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 600","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 599","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 598","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 597","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 596","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 595","path":"/","exit_status":0,"errors":"","output":""}
2d ago	{"command":"atrm 594","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 593","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 592","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 591","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 590","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 589","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 588","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 587","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 586","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 585","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 584","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 583","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 582","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 581","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 580","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 579","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 578","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 577","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 576","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 575","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 574","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
2d ago	{"command":"atrm 573","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
3d ago	{"command":"atrm 572","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
3d ago	{"command":"atrm 571","path":"/","exit_status":0,"errors":"","output":""}	ShowRe-emitDelete
3d ago	{"command":"atrm 570","path":"/","exit_status":1,"errors":"Cannot find jobid 570","output"

**Comment by tortoo** [comment]
@se7cn 我heroku的512内存，用十分钟定时自动重启完美解决。建议你找找docker的定时自动重启办法，网上应该不难搜到，一小时间隔感觉有点长，比如半小时可能会好。看heroku的log，问题就是内存溢出，这种针对环境的外部重启才有用，你给huginn增加一个agent，只会增加内存消耗，而且如果小于一小时，频率越高消耗和排队越严重

**Comment by se7cn** [comment]
@tortoo 学习了   这个问题就到这里吧 ：）

**Comment by sherppard** [comment]
> @tortoo
> 
> 看到中文回复才6啊
> 
> 这问题按照比例来看， 也不算是小众问题了。 作者每次的回复都差不多， 关键是作者无法重现故障，而这个神奇的日志里没有任何可靠的问题记录。 只能自己摸黑尝试了 我觉得跟性能和频率无关

哈哈哈哈哈，是的，这日志可神奇了，我没看到任何有用的信息，甚至两个报错也没有。

**Comment by sherppard** [comment]
huginn 可以改进的几个地方：
  1. website agent 添加 proxy 设置，原因是很多网站需要跨国家获取，如果不通过 proxy ，就经常导致进程卡住
  	 虽然可以全局设置 proxy，但是这不能满足我们的需求，我们需要为每个不同的网站分配一个 proxy
  2. 每次获取 website content，可以添加一个 timeout 时间，这不会让 http 请求等待时间过久，导致任务堆积
  3. 日志可以输出更多的细节内容，好让我们进一步排错
  4. 数据提取的效率过慢，导致进程卡住，进而堆积任务
  5. 对于堆积任务，需要有自我恢复的能力，而不是放任任务堆积下去。
