### ISSUE TITLE
Using powertrack rules with TwitterStreamAgent

### ISSUE THREAD

**Issue by fabiogiglietto** [huginn/huginn#2136]
Hi :)
Is there is a way to use rules such as "cat has:links" or other combination of rules as documented in http://support.gnip.com/apis/powertrack2.0/rules.html in TwitterStreamAgent?

Right now I'm filtering events including tweets with links with a trigger agent but I'm looking for a way to optimize the number of agents in the scenario and events created.

Thank you in advance for your help. Best, Fabio

**Comment by dsander** [comment]
Hi Fabio!

it might work with a few adjustments, but the Twitter API docs mention that you need a enterprise account to use the PowerTrack API: https://developer.twitter.com/en/docs/tweets/filter-realtime/overview/powertrack-api

> This is an enterprise API available within our managed access levels only. To use this API, you must first set up an account with our enterprise sales team. Learn more

**Comment by fabiogiglietto** [comment]
Hi Dominik, 
you are totally right! I'll stick with my suboptimal solution.

Thanks for the prompt reply. Best, Fabio
