### ISSUE TITLE
How can I deploy this app on the google cloud platform?

### ISSUE THREAD

**Issue by qytang326** [huginn/huginn#2137]
How can I deploy this app on the google cloud platform? Are there any docs about this?
怎么样把huginn在gcp上部署？有没有详细的教程？之前部署在openshift上只工作了一个多小时就出问题了

**Comment by dsander** [comment]
Hi!

We don't have any documentation about how to deploy to GCP, if you are deploying a Compute Engine VM you should be able to use either the [manual installation guide](https://github.com/huginn/huginn/blob/master/doc/manual/installation.md) or deploy one of our [Docker images](https://github.com/huginn/huginn/tree/master/docker/single-process).

**Comment by qytang326** [comment]
Thank you!

Must I deploy it to a Compute Engine VM？ If I choose  deploy one of Docker images to GCP, can I just use an app engine or a docker engine?

**Comment by dsander** [comment]
It might work, but I don't know of anyone who tried to deploy the docker images to GCP or AWS. If you succeed a blog post or wiki page would be greatly appreciated. 😄

**Comment by qytang326** [comment]
Thanks, I will try and if I succeed, I will be back or post a blog.

**Comment by seeARMS** [comment]
If anyone's interested, I got Huginn working on GCP and recently documented my efforts: https://blog.colinarms.com/posts/huginn-slack-gcp-automation/

**Comment by virtadpt** [comment]
Nice work!
