### ISSUE TITLE
configure email when SMTPS is self signed

### ISSUE THREAD

**Issue by kornflex** [huginn/huginn#2141]
Hi, 
I send a lots of mail for my website. I'm a blocked from gmail every hour.
So I want to use my own SMTP server.

It is well configured : SMTP, 465, STARTTLS and I can send email for thunderbird.

But, It's a self signed certificate. I had to trust it in thunderbird.
I think I'm blocked in Huginn because of this.

How can I tell to huginn to not check ssl certificate ?

thank you

**Comment by kornflex** [comment]
This is my mail.log error :
Oct 11 16:02:52 postfix/smtps/smtpd[11719]: connect from localhost[127.0.0.1]
Oct 11 16:03:52 postfix/smtps/smtpd[11719]: SSL_accept error from localhost[127.0.0.1]: lost connection
Oct 11 16:03:52 postfix/smtps/smtpd[11719]: lost connection after CONNECT from localhost[127.0.0.1]
Oct 11 16:03:52 postfix/smtps/smtpd[11719]: disconnect from localhost[127.0.0.1]

**Comment by kornflex** [comment]
I have found another way : uss port 25 and block all from the outside with iptable

**Comment by dsander** [comment]
Glad you figured it out, an other option would have been to set `SMTP_OPENSSL_VERIFY_MODE=none`
