### ISSUE TITLE
Invitation code?

### ISSUE THREAD

**Issue by BasharAG** [huginn/huginn#2142]
I deployed the Heroku version, but I  am being asked for an invitation code. How do I get one?

**Comment by putiyeb** [comment]
Do you run the `bin/setup_heroku` in a terminal？ If not, you can login Heroku website, go to your huginn app "setting", click "reveal config vars" and see the "INVITATION_CODE".

**Comment by DerekTso** [comment]
@putiyeb deploying to Heroku, any possibility that when I run that command, and it provides a admin account for me? e.g. admin/password? 

Then no need to signup a new account again?

**Comment by dsander** [comment]
@DerekTso It will ask you if you want to set up an admin account when it is running the first time. If you missed it you can get your invitation code from the environment config with `heroku config:get INVITATION_CODE`

**Comment by DerekTso** [comment]
@dsander Problem solved. Thanks a lot

**Comment by JoshFialkoff** [comment]
I am not using Heroku (I am using Docker). How can I get an invitation code?

**Comment by dsander** [comment]
@JoshFialkoff You can set the `INVITATION_CODE` environment variable when creating the docker container(s).

**Comment by Assazm** [comment]
> Do you run the `bin/setup_heroku` in a terminal？ If not, you can login Heroku website, go to your huginn app "setting", click "reveal config vars" and see the "INVITATION_CODE".

ths,it's very useful

**Comment by Heartnett** [comment]
Got to say - its not great running into this "feature". A heads-up in the form of documentation would be great. Or even better - a feature to disable it (by default).

**Comment by ll3N1GmAll** [comment]
> @JoshFialkoff You can set the `INVITATION_CODE` environment variable when creating the docker container(s).

How is this done in the launching command? I tried to add it; but the syntax is incorrect. Is this documented somewhere that I am failing to locate? Thanks to any who respond!

**Comment by ll3N1GmAll** [comment]
To any with my same level if docker ignorance, here is the solution - 
docker run -it -e INVITATION_CODE=welcome -p 3000:3000 ghcr.io/huginn/huginn
