### ISSUE TITLE
Issue with Json Parse Agent

### ISSUE THREAD

**Issue by putiyeb** [huginn/huginn#2143]
is "Json Parse Agent" support the `merge` mode?
The original events from post agent:
```
{
.
  "title"
  "body": "{\n  \"resultStatus\" : {\n    \"message\" : \"ok\"
.
}
```
I use to parse the "body". But "title" will be miss in next event.
The post agent have setting the mode to `merge`.

**Comment by dsander** [comment]
No the Agent does not support a merge mode, as a work around you should be able to send your Event to a `WebsiteAgent` and, use `data_from_event`:
```json
{
  "expected_update_period_in_days": "2",
  "data_from_event": "{{body}}",
  "type": "json",
  "mode": "merge",
  "extract": {
    "json": {
      "path": "."
    }
  }
}

```

**Comment by putiyeb** [comment]
Thanks a lot!
