### ISSUE TITLE
How to use fulldom-server?

### ISSUE THREAD

**Issue by putiyeb** [huginn/huginn#2144]
I have deployed the fulldom-server.
http://x1.containerum.io:39801/
I try to GET `http://x1.containerum.io:39801/https:%2F%2Fshui.azurewebsites.net?selector=body`, but nothing return.

**Comment by dsander** [comment]
The request looks correct to me, maybe the image you use to deploy is missing phantomjs?

**Comment by putiyeb** [comment]
Sorry for forgetting to install phantomjs.
I create a docker image which can be easy to deploy in heroku and docker hosting.
Detail:https://shui.azurewebsites.net/2017/10/13/browser-emulation-using-fulldom-server/

**Comment by dsander** [comment]
Very cool, thanks for documenting the process!
