### ISSUE TITLE
Using npm with js agent?

### ISSUE THREAD

**Issue by OmgImAlexis** [huginn/huginn#2147]
I've looked through the wiki and can't find anything that mentions how to include other libraries when using the Javascript agent.

Is there anyway to use npm/yarn and can someone point me to some docs about it.

**Comment by OmgImAlexis** [comment]
Looks like this is a dupe of https://github.com/huginn/huginn/issues/1064

**Comment by dsander** [comment]
Kind of, yes 😄 . What you can do to get around it is to include the minified version of the library in your `JavaScriptAgent`s code.

**Comment by OmgImAlexis** [comment]
I was hoping huginn used execjs so I could have just enabled the node option. Without being able to use npm libs it kinda makes the js agent pointless when you can just have the shell agent start node with your actual script.

**Comment by dsander** [comment]
The main benefit of the JavaScriptAgent is the option to interoperate with Huginn/ruby like setting the Agent's memory, emitting multiple events, etc, while still having the freedom to define the logic. This is only possible by using an embedded JavaScript runtime but comes with limitations like not being able to use npm modules. I think both Agents have their use case depending on what one wants to achieve.
