### ISSUE TITLE
Email Digest Agent not working

### ISSUE THREAD

**Issue by DrJosepon** [huginn/huginn#2148]
Hello, I'm having problems with the Email Digest Agent after deploying Huginn in Heroku, when I try to run the Email Digest Agent, it doesn't change it's working status even after refreshing the page. I'm using Sendgrid from the initial config.

![huginn](https://user-images.githubusercontent.com/10107118/31614913-76c3a79e-b24d-11e7-9787-917fa0af7cf8.png)

**Comment by dsander** [comment]
Hi!

Did you check the `Log` tab on the DigestAgents show page? For the working status to change the Agent needs to have receive an Event without emitting an error.

**Comment by DrJosepon** [comment]
It's empty even though I already tried to start it before.

![log](https://user-images.githubusercontent.com/10107118/31628619-ddbb50c2-b276-11e7-9c92-b77013b29b8a.png)

**Comment by dsander** [comment]
Did the Agent receive any Events that can be send out? There is a `Show` memory link on the "Details" page which should not be empty. Without any queued Events the Agent will simply do nothing.

**Comment by DrJosepon** [comment]
Thanks, that one fixed it.
