### ISSUE TITLE
Post Agent stuck running and holding up queue.

### ISSUE THREAD

**Issue by TheChrisK** [huginn/huginn#2159]
Greetings!

I have several Twitter search agents pushing to webhooks for Discord. It checks every 5 minutes. I have noticed that if a Twitter account posts a tweet but deletes it shortly after, the search agent picks it up and pushes it to the post agent but then hangs because the tweet doesn't actually exist anymore. Sometimes this is only fixed by restarting Huginn.

Is there a way to prevent posting deleted tweets? Is it something as simple as increasing the check interval or perhaps a setting that I am missing. Would it also be possible to have more than one agent running at a time so the queue would not get backed up?

I am running Huginn on Ubuntu 16.04 in Azure from source.

Thank you for your time.

**Comment by TheChrisK** [comment]
Here is the error:

Exception during receive. execution expired (Delayed::Worker.max_run_time is only 120 seconds): /home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/ffi-1.9.18/lib/ffi/pointer.rb:51:in `read_string'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/ethon-0.7.1/lib/ethon/easy/callbacks.rb:57:in `block in header_write_callback'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/ethon-0.7.1/lib/ethon/easy/operations.rb:23:in `easy_perform'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/ethon-0.7.1/lib/ethon/easy/operations.rb:23:in `perform'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/typhoeus-0.6.9/lib/typhoeus/request/operations.rb:16:in `run'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/typhoeus-0.6.9/lib/typhoeus/request/cacheable.rb:18:in `run'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/typhoeus-0.6.9/lib/typhoeus/request/block_connection.rb:31:in `run'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/typhoeus-0.6.9/lib/typhoeus/request/stubbable.rb:23:in `run'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/typhoeus-0.6.9/lib/typhoeus/request/before.rb:26:in `run'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/typhoeus-0.6.9/lib/typhoeus/adapters/faraday.rb:68:in `perform_request'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/typhoeus-0.6.9/lib/typhoeus/adapters/faraday.rb:58:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/bundler/gems/faraday_middleware-59088da02940/lib/faraday_middleware/gzip.rb:24:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.1/lib/faraday/request/url_encoded.rb:15:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.1/lib/faraday/request/multipart.rb:15:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/bundler/gems/faraday_middleware-59088da02940/lib/faraday_middleware/response/follow_redirects.rb:78:in `perform_with_redirection'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/bundler/gems/faraday_middleware-59088da02940/lib/faraday_middleware/response/follow_redirects.rb:66:in `call'
/home/huginn/huginn/app/concerns/web_request_concern.rb:26:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.1/lib/faraday/rack_builder.rb:139:in `build_response'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.1/lib/faraday/connection.rb:386:in `run_request'
/home/huginn/huginn/app/models/agents/post_agent.rb:218:in `handle'
/home/huginn/huginn/app/models/agents/post_agent.rb:147:in `block (2 levels) in receive'
/home/huginn/huginn/app/concerns/liquid_interpolatable.rb:62:in `interpolate_with'
/home/huginn/huginn/app/models/agents/post_agent.rb:144:in `block in receive'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.1/lib/active_record/relation/delegation.rb:41:in `each'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.1/lib/active_record/relation/delegation.rb:41:in `each'
/home/huginn/huginn/app/models/agents/post_agent.rb:143:in `receive'
/home/huginn/huginn/app/jobs/agent_receive_job.rb:8:in `perform'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/execution.rb:37:in `block in perform_now'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/i18n-0.8.1/lib/i18n.rb:257:in `with_locale'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/logging.rb:24:in `block (4 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `block in instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/logging.rb:23:in `block (3 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/logging.rb:44:in `block in tag_logger'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:69:in `tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/logging.rb:44:in `tag_logger'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/logging.rb:20:in `block (2 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/execution.rb:33:in `perform_now'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/execution.rb:22:in `block in execute'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/railtie.rb:26:in `block (4 levels) in <class:Railtie>'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/reloader.rb:68:in `block in wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/reloader.rb:67:in `wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/railtie.rb:25:in `block (3 levels) in <class:Railtie>'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/execution.rb:20:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/queue_adapters/delayed_job_adapter.rb:36:in `perform'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/backend/base.rb:78:in `invoke_job'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:230:in `block (2 levels) in run'
/usr/local/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
/usr/local/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:230:in `block in run'
/usr/local/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:229:in `run'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:213:in `block in work_off'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:212:in `times'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:212:in `work_off'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:175:in `block (4 levels) in start'
/usr/local/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:174:in `block (3 levels) in start'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec

**Comment by TheChrisK** [comment]
Now I've noticed it does it randomly, not just on a deleted twitter post. The job hangs for 20 minutes then fails. After a retry, it works fine.

**Comment by dsander** [comment]
Hi @TheChrisK,

I assume you are running the [threaded background processes](https://github.com/huginn/huginn/blob/master/Procfile#L25)? If that is the case I think you are hitting a long standing issue (see the references in #1892). Unfortunately the only way to work around the problem is to run delayed_job in a separate process like it is done [here](https://github.com/huginn/huginn/blob/master/Procfile#L28-L31).
To be a little bit more memory efficent you could also try this:
```
web: bundle exec unicorn -c config/unicorn.rb
agent_runner: bundle exec rails runner bin/agent_runner.rb
dj: bundle exec script/delayed_job run
```
Keep in mind you need to re-export the configuration with `sudo bundle exec rake production:export` after changing the `Procfile`.

**Comment by TheChrisK** [comment]
I am running threaded. I will give this a try. I currently have two servers running Huginn, one in Azure and one on-prem. I will apply to both and see how things go. Thank you!

**Comment by TheChrisK** [comment]
After making the changes, the issue persists. It is not just affecting Twitter feeds but also my RSS feed agents.

**Comment by dsander** [comment]
Help me understand the issue a little better. Sometimes the PostAgent takes a long time to run and fails with `execution expired`, but after that the Agents continue to run?
If you are getting the same timeout locally and on Azure the problem is probably the slowness of the server you are POSTing to. You can reduce the maximum runtime of Agents to one minute in `.env` with `DELAYED_JOB_MAX_RUNTIME=1`.
If the slow PostAgents hold up your other Agents from being processed you can [add additional `delayed_job` processes to your Procfile](https://github.com/huginn/huginn/blob/master/Procfile#L42).

**Comment by TheChrisK** [comment]
Yeah it's usually 15 minutes of `running` then it clears with the error, the other agents process in the queue and the failed agent is then successful on the first retry. `DELAYED_JOB_MAX_RUNTIME` has been set to `1` and the issue continues to occur. 

I have just recently added 3 more `delayed_job` processes to the Procfile as RAM is not a concern. I will monitor this change and see what comes of it. I'm fine if one webhook takes a few minutes longer as long as other agents are processing behind it.

It is quite possible that Discord webhooks are the culprit. We switched from IFTTT to Huginn after our webhooks would seemingly get skipped or just fail with little or no information to troubleshoot.

Thank you for all your support on Huginn. I'm using this for the Waze map editing community. This is a great tool that helps us monitor road closures via Twitter for announcing in Discord. We are able to get so much more information piped into our feeds in almost real-time.

I'll post my findings regarding the `delayed_job` process change.

**Comment by dsander** [comment]
> Yeah it's usually 15 minutes of running then it clears with the error, the other agents process in the queue and the failed agent is then successful on the first retry. DELAYED_JOB_MAX_RUNTIME has been set to 1 and the issue continues to occur.

That is odd, `delayed_job` should kill those jobs much sooner. We normally get bug reports about DJ 'killing' jobs which then results in the threaded background process being stuck, that's why I suggested to switch to separate processes.

You could try [this change](https://github.com/huginn/huginn/pull/1892/commits/5c26e58cfb2b8f4d6028383e4227569315c9b401) and see if that fixes the issue of jobs running too long.

**Comment by TheChrisK** [comment]
I will try that. Things seems to be running smoother now but still having delayed jobs pop up which is now causing duplicate POSTs to webhooks when the delay does happen. I'll keep you posted on the change to faraday.

**Comment by TheChrisK** [comment]
@dsander After several days of testing, it seems my issue is resolved. Feeds are still getting hung up but with the recent change, they come out of the queue in 30 seconds and usually completed after the 2nd or 3rd retry without posting any duplicates. Even with that, the feeds appear on the front end smoothly and timely. Thank you kindly for your help on this.

**Comment by dsander** [comment]
Nice! I am glad it is working well now.
