### ISSUE TITLE
Emit event with added fields from list

### ISSUE THREAD

**Issue by signallhill** [huginn/huginn#2166]
I have several agent which basically have 1 username field that is different from each other. Every time I need to add another username to the field I have to clone the agent and change that one field. 

Is it possible to have the list of username in 1 agent and just combine the incoming event with 1 username and emit it?

If there is another way to do this can I have an example on how this can be done?

**Comment by aserpi** [comment]
If you plan to add and remove usernames often, I think the best solution is concatenating the agent with a JavaScript one like this:
```
usernames = ['user1', 'user2', 'user3'];

Agent.receive = function() {
  var events = this.incomingEvents();
  for(var i = 0; i < events.length; i++) {
    for (var u = 0; u < usernames.length; u++) {
      events[i].payload.username = usernames[u];
      this.createEvent(events[i].payload);
    }
  }
}
```
Liquid is nice, but it is a pain to use with static arrays.

**Comment by signallhill** [comment]
This is great, worked perfectly. Thanks
