### ISSUE TITLE
HTTP Basic Auth with Huggins?

### ISSUE THREAD

**Issue by MCOfficer** [huginn/huginn#2167]
Since #1783 seems to have come to a halt, i'm trying to manually POST the reddit API. However, i am stuck in the authentication process - i can't figure out how to send a HTTP Basic Auth using Huggins. Is this already a thing, and if it is, can someone help me with it?

**Comment by dsander** [comment]
The `PostAgent` takes an optional `basic_auth` key in it's options. It can be either set to a string `username:password` or an array `["username", "password"]`.

**Comment by MCOfficer** [comment]
that's what i was looking for, thanks a lot!
