### ISSUE TITLE
Query - API fetch

### ISSUE THREAD

**Issue by hobojoe720** [huginn/huginn#2169]
Hey Guys,

Just installed Huginn as I needed to start looking at Zapier like features and didnt want to pay the costs. 
I have a few things I am going to be trying to do with it but the first is to monitor if something is running.

I have an API that I can call to run my checks. Basically there are 2 options, 

The first one that gives me a result if it is running: 
{"lts":123456789,"identifer":"cast4","**hash":"5121**","totalHash":"123456789","validShares":123456,"invalidShares":null}

If it is not running
{"lts":null,"identifer":"cast5","validShares":null,"invalidShares":null}

The important one is "hash", if hash exists I am happy, if it doesn't I have an issue.

Alternatively, there is another API URL that doesn't return JSON per say but does give me:
["cast1","cast2","cast3","cast4","OtherDevice"]

The problem with the second one is I only care about values starting with "cast", any others will come and go, but named castN it should be there all the time. If one disappears, I have an issue.

I have created a WebsiteAgent that returns the value of "hash" (so going option 1, as it seams easier but I have more agents). But confused at this point, as I guess I have created the opposite of what I want?

The idea is to check to see if this doesnt exist and if it doesnt exist (so my service stopped working) send a message to a Telegram group, or an email, or WhatsApp (if at all possible) to notify some people that we need to do something.

Any advice is appreciated, Im going to keep going through the Wiki and info I can find online.

Chris

**Comment by dsander** [comment]
Hi Chris,

I think the first check is easier to to than the second one. You can send the result of your `WebsiteAgent` to a `TriggerAgent` and check if the value is non empty. Putting `{{never_existing}}` inside the value is a hack to make the Agent accept an empty string 😄 :

```json
{
  "expected_receive_period_in_days": "2",
  "keep_event": "false",
  "rules": [
    {
      "type": "field==value",
      "value": "{{never_existing}}",
      "path": "hash"
    }
  ],
  "message": "We have a problem!"
}
```

**Comment by hobojoe720** [comment]
Thanks it does look like the first one is easier, it just means creating an event for each one of these I look after, but wouldnt there be no event from the WebsiteAgent if the value is not found?

My understanding (and I could be very wrong) is that the event is only generated by the WebsiteAgent if a value is found?

**Comment by dsander** [comment]
The options I posted were for a `TriggerAgent` that received the events emitted by the `WebsiteAgent`. 

I was assuming the `WebsiteAgent` is fetching a JSON API, if you don't to any specific extraction it will always emit Events if the data changed.

**Comment by hobojoe720** [comment]
Correct, its fetching JSON. The value of hash is ever changing so it will trigger an event every time its run.

**Comment by dsander** [comment]
That should be fine, the `TriggerAgent` will consume all those events and only fire an Event itself if the value is empty. Am I missing something?

**Comment by hobojoe720** [comment]
Sorry been out of the office so havnt had a chance to test. So the issue is as follows:
When the service is running "hash" exists. As such an event is generated by the websiteagent.

When the service isnt running, "hash" doesnt exist, an error is generated and no event.

ERROR -- : Error when fetching url: Got an uneven number of matches for : {"hash"=>{"path"=>"hash"}, "identifer"=>{"path"=>"identifer"}}

**Comment by dsander** [comment]
I see, that is a feature/limitation of the `WebsiteAgent`, I suggest you either extract the JSON root or just the deepest element that is always present.
When extracting multiple fields the `WebsiteAgent` requires the amount of matches to be even, because it is normally used to extract table rows or similar repeating elements from a HTML page. If you would extract 3 elements from row 1, 2 from row 2 and 3 from row 3 the Agent would not know which element belongs to which row.

**Comment by hobojoe720** [comment]
Ahh I see, that makes sense. I will give that a go.

Thanks for the help
