### ISSUE TITLE
How to change the namespace of the Huginn Docker image?

### ISSUE THREAD

**Issue by ChenWeird** [huginn/huginn#2177]
NAS: Synology DS 918+ 
Docker Image: cantino/huginn  https://hub.docker.com/r/cantino/huginn/

Warning! You need to change the namespace of the Huginn Docker image you are using.

How?

**Comment by dsander** [comment]
You need to recreate you docker container using the new image namespace and pass the same environment/volume/port configuration you used before.

**Comment by ChenWeird** [comment]
Done. Just use new huginn docker image:
from "cantino/huginn"  https://hub.docker.com/r/cantino/huginn/ 
to "huginn/huginn"  https://hub.docker.com/r/huginn/huginn/
