### ISSUE TITLE
Huginn Agent to support iteration check

### ISSUE THREAD

**Issue by neethkrish** [huginn/huginn#2178]
Hi,
I am in need of an agent to check for  URLs  in the payload body and then pass it to the post agent . Is there any way I could make use of iteration concept to check for the URLs  .

Currently I implemented a trigger agent to check for the URLs in the payload body and passed it to the post agent, it works fine for the first match but  I need to implement iteration concept so that all the URLs in payload are passed to the post agent separately. 

Any help on this would be appreciated..Thanks in advance..

**Comment by dsander** [comment]
Hi @neethkrish,

can you give an example how your payload looks? Depending on the format of the HTML or JSON the `WebsiteAgent` uses to extract the URLs, it might be possible to send them as different Events to the `PostAgent`. If that does not work the only solution I can think if is the `JavascriptAgent`.

**Comment by neethkrish** [comment]
Hi @dsander

**Comment by neethkrish** [comment]
Hi @dsander, 

Thanks for the reply.

The payload is from an IMAP folder agent . I need to check for URL content in the mail body. With JavaScript agent I was able to implement this. Is there a way I could make use of website agent in this scenario (just for info).
 
For example my payload looks something like this:

{
  "folder": "INBOX",
  "subject": "Sample",
  "from": "noreply@test.com",
  "to": [
    "test.sample@gmail.com"
  ],
  "cc": [

  ],
  "date": "2017-12-27T02:51:34+00:00",
  "mime_type": "text/plain",
  "body": "sample test mail, refer: http://test.com",
  "matches": {
  },
  "has_attachment": false
}

For each URL  in the body I need to pass it to post agent .  

Thanks..

**Comment by dsander** [comment]
No I think the `JavascriptAgent` is the easiest solution here. It might be possible to extract the urls from the body by using the [`regex_replace`](https://github.com/huginn/huginn/wiki/Formatting-Events-using-Liquid#tags-added-by-huginn) filter in combination with some string splitting and `as_object` but that would be a lot trickier.

A Liquid `scan` filter that behaves like rubies [String#scan](https://ruby-doc.org/core-2.2.0/String.html#method-i-scan) would be helpful here I think.

**Comment by neethkrish** [comment]
Thanks @dsander .. I was able to achieve this using Javascript Agent and I think that is the easiest solution here. 

Thanks for the suggestions.
