### ISSUE TITLE
[Suggestion] The Weather Agent(Wunderground)'s language option is not all in ISO 639-1 format

### ISSUE THREAD

**Issue by malagebidi** [huginn/huginn#2181]
Hi,

I just set up my weather agent and found the language option is different from the prompt on the right, like simplified Chinese, it's 'CN', not the ISO 639-1 format 'ZH'.

[wunderground language support page](https://espanol.wunderground.com/weather/api/d/docs?d=language-support&MR=1)

**Comment by dsander** [comment]
Thanks for reporting the issue, we should add a note [here](https://github.com/huginn/huginn/blob/master/app/models/agents/weather_agent.rb#L30) stating that darksky uses ISO country codes, but wunderlist has different codes.
