### ISSUE TITLE
Add the article source when Filter multiple RSS and output one RSS

### ISSUE THREAD

**Issue by poonjh** [huginn/huginn#2184]
It's very cool and useful agent to filter multiple RSS resources and generate one combined RSS based on keywords mentioned.  I love it... :)

So now I read the article via my combined RSS feed.  Is it possible to add a field to indicate which Source the article extracted from?   This is really important since I can roughly evaluate the article quality based on the Media source before I read it. 

Currently, they're only title, description, URL fields extracted, I cannot see the URL on my mobile RSS reader.  It will be great if there's a way to expose the article source.

Thanks and happy New year to all Huginner here... ... 💯

**Comment by dsander** [comment]
Hi @poonjh,

if the `RSSAgent` is not extracting any useful information from the source feed you can use a `EventFormattingAgent` to insert a name for the feed before outputting it with the `DataOutputAgent`. Assuming the name is in the `name` key of the event you could modify the `title` attribute to also show the name `{{name}} - {{title}}`.

**Comment by poonjh** [comment]
Thank you very much. @dsander   

This is great,  I didn't realize we have EventFormattingAgent.       Now It fixed, display the source and title beautifully.
