### ISSUE TITLE
A error '502 bad gateway'. 

### ISSUE THREAD

**Issue by Ji4Ji4n** [huginn/huginn#2185]
Hello!
When I accessing huginn via my browser, I get a error '502 bad gateway'. 
Then I run sudo rake production:status to check the status, it print out:

> root@VM-111-211-ubuntu:/home/huginn/huginn# sudo rake production:status
rake aborted!
Gem::LoadError: You have already activated rake 12.3.0, but your Gemfile requires rake 12.0.0. Prepending `bundle exec` to your command may solve this.
/home/huginn/huginn/config/boot.rb:6:in `<top (required)>'
/home/huginn/huginn/config/application.rb:1:in `require_relative'
/home/huginn/huginn/config/application.rb:1:in `<top (required)>'
/home/huginn/huginn/Rakefile:5:in `require_relative'
/home/huginn/huginn/Rakefile:5:in `<top (required)>'

> Caused by:
LoadError: cannot load such file -- bundler/setup
/home/huginn/huginn/config/boot.rb:6:in `<top (required)>'
/home/huginn/huginn/config/application.rb:1:in `require_relative'
/home/huginn/huginn/config/application.rb:1:in `<top (required)>'
/home/huginn/huginn/Rakefile:5:in `require_relative'
/home/huginn/huginn/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)

How to fix it?
Look forward to reply!

**Comment by dsander** [comment]
Hi,

try prepending `bundle exec`: `sudo bundle exec rake production:status`. If you are still getting 502 errors can you append the contents of the log files  specified [here](https://github.com/huginn/huginn/blob/master/doc/manual/installation.md#troubleshooting)?

**Comment by Ji4Ji4n** [comment]
@dsander, thank  you!
I reinstalled huginn again, the error '502 bad gateway' has been fixed.
I thought it would be I skipped the steps '**sudo apt-get install -y runit-systemd libssl1.0-dev**'.
Thank you anyway! XD
