### ISSUE TITLE
How to add 'receiver_cell' from payload in Twilio Agent ?

### ISSUE THREAD

**Issue by njmathews** [huginn/huginn#2186]
Hi,
    I wish to obtain receiver mobile number from payload but its not working. Can anybody help me to figure out.

{
[{account_sid: ACxxxxxxxxxxxxxxxxxxxxxxxxxxxx...
[{auth_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx...
[{sender_cell: xxxxxxxxxx
[{receiver_cell: {{to}}                     <====================== Read from payload not working ?
[{server_url: http://somename.com:3000
[{receive_text: true
[{receive_call: false
[{expected_receive_period_in_day...: 1
}

Thanks in Advance

Matt

**Comment by dsander** [comment]
Hi Matt,

I think that should work as long as the event has the `to` key in it.

**Comment by njmathews** [comment]
Hi dsander, 
                Thank you for your response. Yes, we have 'to' key in it. 
This is the code for reference:
![image](https://user-images.githubusercontent.com/30118662/34551399-80de0d92-f13f-11e7-8ff3-86cbac560c22.png)

And we call like this:
 {
"message":"Test Message",
"toNumber":"+91123456789"
}
And we are getting the following exception.
Exception during receive. A 'To' phone number is required.: /home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/twilio-ruby-3.11.6/lib/twilio-ruby/rest/client.rb:233:in `connect_and_send'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/twilio-ruby-3.11.6/lib/twilio-ruby/rest/client.rb:172:in `block (2 levels) in <class:Client>'

**Comment by dsander** [comment]
You are right, I overlooked an issue and send a PR which fixes it.

**Comment by njmathews** [comment]
Thank you very much, Sander. I will check it.
