### ISSUE TITLE
Unable to use "divided_by" in Event Formatting Agent

### ISSUE THREAD

**Issue by stesie** [huginn/huginn#2188]
This relates to #2021, yet wasn't really tracked down back then, hence once more with more details:

Event Formatting Agent options:

```json
{
  "instructions": {
    "message": "{{ 23 | divided_by: content.some_value }}"
  },
  "matchers": [],
  "mode": "clean"
}
```

... give it whatever name and click "dry run". ("save" also fails for same reasons, see below)

Sample event:

```json
{
  "content": {
    "some_value": "23"
  }
}
```

Obviously the result should be 1 (23 divided by 23), yet it never is evaluated at all.

Problem is that `LiquidInterpolatable#validate_interpolation` tries to interpolate the template (probably to check for syntax errors in liquid template). Yet since there is no event data during validation it tries to divide by zero, which fails for obvious reasons. That way validation however fails, so the agent is neither saved nor is dry-run performed.

I'm not sure what a good resolution might look like, since template validation makes sense. Probably to just catch the error in the current `vaildate_interpolation` function and ignore it, like so:

```diff
--- app/concerns/liquid_interpolatable.rb       2018-01-04 19:25:04.373951061 +0100
+++ /home/stesie/liquid_interpolatable.rb       2018-01-04 19:16:49.000000000 +0100
@@ -15,6 +15,8 @@
 
   def validate_interpolation
     interpolated
+  rescue Liquid::ZeroDivisionError => e
+    # ignore error (due to possibly missing variables)
   rescue Liquid::Error => e
     errors.add(:options, "has an error with Liquid templating: #{e.message}")
   rescue
```

**Comment by dsander** [comment]
Thanks for the detailed explanation. Rescueing the `ZeroDvisionError` sounds like a good solution to me, do you mind opening a pull request?
