### ISSUE TITLE
working state

### ISSUE THREAD

**Issue by cjywoo** [huginn/huginn#2193]
why  are  working states of my agents all no? isn't shoud be yes? And I run the agents, it's working state is also no after a while? Can anyone tell me why it happens? Thanks a lot

**Comment by dsander** [comment]
That depends on the Agent, every Agent defines it's own [working?](https://github.com/huginn/huginn/blob/master/app/models/agents/website_agent.rb#L216) method. Most Agents assume to have received an Event in a certain time frame as well as having processed the Event without errors.
