### ISSUE TITLE
Why must expected_receive_period_in_days be set for PostAgent?

### ISSUE THREAD

**Issue by sfischer13** [huginn/huginn#2194]
My `PostAgent` does not receive events but `expected_receive_period_in_days` is required. If I understand correctly, my agent will never be shown as working. Is this a bug?

**Comment by dsander** [comment]
`expected_receive_period_in_days` will only be used if the Agent has received at least one Event. If the Agent never received an Event it will be shown as not working if an error log was created after the last emitted Event.

**Comment by sfischer13** [comment]
Thanks for the explanation! Still, my agent is shown as not working even though there are no entries in the "Log". What could be the problem?

**Comment by dsander** [comment]
Can you paste the JSON representation of your Agent here? You can access it via the browser: `https://<your domain>/agents/<agent_id>.json`

**Comment by sfischer13** [comment]
In the JSON representation, I found `"last_receive_at":null`. Is that what makes the `working?` method fail?

**Comment by dsander** [comment]
I don't know that is the working logic:
```ruby
last_receive_at && 
  last_receive_at > interpolated['expected_receive_period_in_days'].to_i.days.ago && 
  !(last_event_at && 
    last_error_log_at && 
    last_error_log_at > (last_event_at - 2.minutes)
  )
```

**Comment by sfischer13** [comment]
Huh, that is not the same code as in [post_agent.rb](https://github.com/huginn/huginn/blob/master/app/models/agents/post_agent.rb#L87) ... Now I'm confused.
Does `null` in the JSON representation go back to `nil` in the internal representation? In that case, the boolean expression should fail at the first operand `last_receive_at`.

**Comment by dsander** [comment]
Oh sorry you are right I was on the wrong track from the beginning. We should change that to only check `last_recieve_at` if it is not `nil`.

**Comment by sfischer13** [comment]
There is now also a PR: #2329.
