### ISSUE TITLE
Input agent for a WebsiteAgent

### ISSUE THREAD

**Issue by hunhejj** [huginn/huginn#2201]
Hey,
I have a WebsiteAgent, that scrapes different websites with the same structure on a scheduled basis. Normally I would use an array for "url" for this scenario. 
However this time I want to set other event properties based on the url. For example I have two group of urls and I want to fill the event property "target_email_address" with two different values depending on the url groups. I am looking for an agent that could create this input event for the WebsiteAgent. Any ideas (besides the JavaScript agent)?

**Comment by dsander** [comment]
Hi,

it might be possible by using liquid templates to generate a JSON string which is then parsed by a `JsonParseAgent` to convert it back into an array. In the WebsiteAgent you can then use `{{ urls | as_object }}` access the `urls` array.

**Comment by hunhejj** [comment]
Hi @dsander, 
thank you for your suggestion! The most intuitive way to solve my issue would be if scheduling of manual events was possible. 
I will close this issue because it is a duplicate of #1936.
