### ISSUE TITLE
Revolut Agent

### ISSUE THREAD

**Issue by marbetschar** [huginn/huginn#2202]
It'll be greate to have a Revolut Agent in Huggin which supports their OpenAPI:
https://www.revolut.com/business/openapi?lang=en

**Comment by smithjoelt** [comment]
It doesn't seem that this idea got much traction. Are we going to close this issue?

**Comment by marbetschar** [comment]
😆 sure, feel free to do so!

**Comment by smithjoelt** [comment]
Only the person who opened the issue or people with write access can do that. I'm just doing some triage. 🙂
