### ISSUE TITLE
Limit number of events pushed per scan?

### ISSUE THREAD

**Issue by TheChrisK** [huginn/huginn#2206]
Often we hit rate limits when using Post Agents to push out webhooks. I believe the magic number is five. Is there a way to limit the number of events that Huginn pushes out per cycle and queue the rest for the next scan?

I know this is a stretch but I thought I would ask.

**Comment by dsander** [comment]
I think a `DelayAgent` with `max_emitted_events` configured to your limit should work.

**Comment by TheChrisK** [comment]
How did I not see that option before...? :joy: 

Thank you again, I will give this a go. :+1:
