### ISSUE TITLE
How to check other agents status and emit?

### ISSUE THREAD

**Issue by putiyeb** [huginn/huginn#2212]
For some reason, e.g. the format of response or the theme of website changed, the agent would extract nothing and doesn't generate events to the next agent. Until the content haven't been updated for a long time, I may the agents have broken.

So is there a agent could select the agents which need to monitor, check the status of them on time, and emit the status?

**Comment by dsander** [comment]
We don't have a Agent to check the status of another Agent, but if you are expecting every X days you can use a `GapDetectorAgent` to detect when you Agent stopped creating Events.

**Comment by putiyeb** [comment]
It seems good. I will try it later. Thank you!
