### ISSUE TITLE
Basic Auth for LiquidOutputAgent?

### ISSUE THREAD

**Issue by darrencauthon** [huginn/huginn#2213]
I was thinking about adding some simple basic auth for the LiquidOutputAgent.  Even though the agent has a secret, it's still open.  The agent can create HTML pages, with links, and clicking on those links will include the secret as a referrer.

It's not a big deal, but I was thinking that having the option of adding a simple user/pass might be nice.  I know I'd use it.

Thoughts or concerns before I code it up?  (I'll probably code it up anyway for my own instance :smile: )

**Comment by dsander** [comment]
Good idea to prevent leaking the secret in the referrer. What do think about adding a [Referrer-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy) header to the output? That would secure all Huginn without additional configuration steps.

**Comment by knu** [comment]
Adding `rel="noreferrer"` to every link may be a better bet, as it is getting wide support by major browsers: https://caniuse.com/#feat=rel-noreferrer

**Comment by knu** [comment]
Of course, it does not solve the problem but only mitigates the issue.  I guess adding Basic Auth wouldn't be that hard.

**Comment by dsander** [comment]
@knu The support for basic options (never/origin) of `Referrer-Policy` looks similar: https://caniuse.com/#feat=referrer-policy

Adding `rel` to links is fine with me as well, but probably require more work as we would need to parse the generated HTML and modify the links, or did you have something different in your mind?

Assuming we fix leaking the referrer, would adding Basic Auth add additional security? As far as I know both solutions are equally save or unsafe when using HTTPS.

**Comment by knu** [comment]
Ah, I just thought rel="noreferrer" should be enough as a user-side workaround because you could insert the attribute to your templates without waiting for us to work on enhancing Huginn, but I just overlooked the `response_headers` option, so it should be fine either way.

**Comment by darrencauthon** [comment]
One other story...

Let's say that I'm using Huginn to monitor an application.  The application has an API that allows Huginn to gather all sorts of statistics on specific events.  Huginn monitors the application to look for things that stop happening, or if the numbers suddenly jump or drop.  If there is something of note, Huginn will send texts and emails to various people to warn about a potential problem.

So this Huginn instance has a lot of stats, and let's say that I wanted to use something like vis.js to produce charts.  I can do this with the Huginn agent, but since it would expose some sort of wide-open company data, having *some* sort of authentication on it might be nice.

**Comment by darrencauthon** [comment]
Oh, wait, maybe that's it?  

We could have a trigger that requires the user to authenticate through Huginn before viewing the page?

**Comment by darrencauthon** [comment]
When I wrote this agent, I was planning on using it mostly to create some JSON blocks and a simple RSS reader (which is why I was thinking about the referrer, as I'm giving out my secret RSS news page).

But I've been using tools for visualizing data, and I think many are a perfect match for Huginn.  I can use Huginn not just for the data aggregation, but to host the simple charts so I can look at the results in a snappy, styled way.

**Comment by knu** [comment]
@dsander With regard to the second question, basic auth credentials can be better than a secret token embedded in the URL when you have multiple third parties to give access to.  You can add, change or revoke credentials for each user.  We could extend the agent to accept multiple secret tokens, but an option to separate auth info from a URL would be nice when your users wouldn't want to change their bookmark every time you update the secret key/password.

**Comment by dsander** [comment]
> having some sort of authentication on it might be nice.

I think from a authentication standpoint a secret or `username/password` combination are similar.



> We could have a trigger that requires the user to authenticate through Huginn before viewing the page?

That could be an option too, but it would only allow the owner of the Agent, right?

How about combining that idea with @knu's use case of having multiple basic auth users? We could authenticate the basic auth user against the Huginn user database. So the output Agent could either use a secret or require basic auth with a allowlist of a subset of the Huginn users (or all of them).

> With regard to the second question, basic auth credentials can be better than a secret token embedded in the URL when you have multiple third parties to give access to. You can add, change or revoke credentials for each user.

That is a good point, I always just thought of one secret and one valid username/password combination.

**Comment by darrencauthon** [comment]
I think multiple authentication "schemes" sound good.  By default, we have "None," but the user could select something like "Huginn Owner" to use Huginn's auth, and check that the person who logs in is the owners.  Then we could have a strategy for "All Huginn owners" which would allow for any Huginn users, and a strategy for "Some Huginn owners" with an allowlist.  And we can include a strategy for "Basic Auth" with a single credential, or a list of credentials.

I'm putting no thought into the strategy names above.... that'd come later.  And they don't have to happen all at once.

I'd recommend starting with the Huginn auth strategies, as Huginn already has authentication and I don't like touching passwords.

**Comment by darrencauthon** [comment]
> So the output Agent could either use a secret or require basic auth with a allowlist of a subset of the Huginn users (or all of them).

Just to be precise... a secret is always required because it is used to form the URL.  For example, if my secret is "news" then the URL I use to access the page would be news.html, news.json, etc.

**Comment by dsander** [comment]
> Just to be precise... a secret is always required because it is used to form the URL. For example, if my secret is "news" then the URL I use to access the page would be news.html, news.json, etc.

Good point, I guess we could change the url to be `https://DOMAIN/web_requests/:id.:scheme` when using basic auth but that's not really necessary.



> and a strategy for "Some Huginn owners" with an allowlist.

I did not remember the Agent was `FormConfigurable`, at the moment we don't have a way to select multiple values so you either need to add that feature or fall back to the JSON editor.

**Comment by darrencauthon** [comment]
I love huginn, it's an awesome tool that I've used for years.

I don't know why I had this issue still open... I'm going to close it.
