### ISSUE TITLE
DataOutputAgent doesn't respect DOMAIN env in docker

### ISSUE THREAD

**Issue by WangQiru** [huginn/huginn#2215]
Despite setting `-e DOMAIN=huginn.domain.com ` when launching huginn container

`Data Output Agent` still outputs XML with **localhost**:

```XML
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/">
<channel>
 <atom:link href="https://localhost:3000/users/345/web_requests/213/somename.xml" rel="self" type="application/rss+xml" />
 <atom:icon>https://localhost:3000/favicon.ico</atom:icon>
 

 <title>title</title>
 <description>description</description>
 <link>https://localhost:3000</link>
 <lastBuildDate>Fri, 09 Feb 2018 08:10:05 -0800</lastBuildDate>
 <pubDate>Fri, 09 Feb 2018 08:10:05 -0800</pubDate>
 <ttl>60</ttl>
<items/>

</channel>
</rss>
```

**Comment by dsander** [comment]
Looking at the code the Agent either uses the option `template self` falls back to `template link` and if that is empty as well uses `https://#{ENV['DOMAIN']}`. How does you Agent configuration look?

**Comment by WangQiru** [comment]
Yeah it’s still localhost:3000 in .env. Docker env is not taken for DOMIAN, I just tried launching another container with `-e DOMAIN=huginn.example.com`

**Comment by WangQiru** [comment]
It turns out my huginn image was too old, updating to the latest has fixed the problem! But https://github.com/huginn/huginn/issues/2208 is still not fixed.
