### ISSUE TITLE
Error with Post Agent

### ISSUE THREAD

**Issue by yulahuyed** [huginn/huginn#2219]
I try to send a HTTP post request to the API of https://pan.baidu.com for getting the download link by Post Agent. But the response is incorrect, comparing with the response from `curl` command by using the same parameters.

The curl command:
`curl "https://pan.baidu.com/api/sharedownload?timestamp=1518423085&sign=a06070a50d3bc57cd2966e536d9c6d98ea3efb78&bdstoken=null&app_id=250528&channel=chunlei&clienttype=0&web=1" -H "Host: pan.baidu.com" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0" -H "Accept: */*" -H "Accept-Language: en-US,en;q=0.8,zh-CN;q=0.5,zh;q=0.3" --compressed -H "Referer: https://pan.baidu.com/s/1o9VqGMe" -H "Content-Type: application/x-www-form-urlencoded; charset=UTF-8" -H "X-Requested-With: XMLHttpRequest" -H "Cookie: PANWEB=1; BAIDUID=01B35F6AAD143D7731A26B0CC31409AA:FG=1" -H "DNT: 1" -H "Connection: keep-alive" -H "Cache-Control: max-age=0" --data "encrypt=0&product=share&uk=1822488384&primaryid=2560513910&fid_list=%5B%22117680932205672%22%5D"`

The response of curl command:
<img width="1052" alt="capture20" src="https://user-images.githubusercontent.com/27191666/36088448-5180b2b0-1012-11e8-97f1-89408299324c.PNG">

Post Agent:
```
{
  "post_url": "https://pan.baidu.com/api/sharedownload?timestamp=1518423085&sign=a06070a50d3bc57cd2966e536d9c6d98ea3efb78&bdstoken=null&app_id=250528&channel=chunlei&clienttype=0&web=1",
  "expected_receive_period_in_days": "1",
  "content_type": "form",
  "method": "post",
  "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0",
  "payload": {
    "encrypt": "0",
    "product": "share",
    "uk": "1822488384",
    "primaryid": "2560513910",
    "fid_list": "%5B%22117680932205672%22%5D"
  },
  "headers": {
    "Host": "pan.baidu.com",
    "Accept": "*/*",
    "Accept-Language": "en-US,en;q=0.8,zh-CN;q=0.5,zh;q=0.3",
    "Accept-Encoding": "gzip, deflate, br",
    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
    "Connection": "keep-alive",
    "Cookie": "PANWEB=1; BAIDUID=01B35F6AAD143D7731A26B0CC31409AA:FG=1",
    "origin": "null"
  },
  "emit_events": "true",
  "no_merge": "false",
  "output_mode": "merge"
}
```

The response of Post Agent:
<img width="602" alt="capture21" src="https://user-images.githubusercontent.com/27191666/36088482-734dfd76-1012-11e8-9cb7-17081efab7ec.PNG">

**Comment by dsander** [comment]
I am getting `{"errno":112,"request_id":991485881735216821,"server_time":1518429572}%` as response with your curl command.

https://requestb.in/ Is a useful site to compare the requests made by different tools.

**Comment by yulahuyed** [comment]
`"errno":112` means the request has expired. Some parameters have time limit on the request. It need to generate a new request to test.
e.g.
https://pan.baidu.com/s/1mkoXBjq

the curl command
`curl "https://pan.baidu.com/api/sharedownload?timestamp={{ timestamp }}&sign={{ sign }}&bdstoken=null&app_id=250528&channel=chunlei&clienttype=0&web=1" -H "Host: pan.baidu.com" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0" -H "Accept: */*" -H "Accept-Language: en-US,en;q=0.8,zh-CN;q=0.5,zh;q=0.3" --compressed -H "Referer: https://pan.baidu.com/s/1mkoXBjq" -H "Content-Type: application/x-www-form-urlencoded; charset=UTF-8" -H "X-Requested-With: XMLHttpRequest" -H "Cookie: PANWEB=1; BAIDUID={{ BAIDUID }}:FG=1" -H "DNT: 1" -H "Connection: keep-alive" -H "Cache-Control: max-age=0" --data "encrypt=0&product=share&uk=1822488384&primaryid=3574473842&fid_list=%5B%22505222519162181%22%5D"`

On the command, the `{{ sign }}` , `{{ timestamp }}` and `{{ BAIDUID }}` need to change. 
The `{{ timestamp }}` and `{{ sign }}` can be found on the source code of webpage. 
The `{{ BAIDUID }}`  can be found on any request on opening https://pan.baidu.com/s/1mkoXBjq

<img width="820" alt="capture21" src="https://user-images.githubusercontent.com/27191666/36093861-edd2f042-1026-11e8-8fa2-860d8f218e65.PNG">
  
<img width="614" alt="capture22" src="https://user-images.githubusercontent.com/27191666/36093355-5b6e1afc-1025-11e8-9f3d-5db01b797c09.PNG">

**Comment by dsander** [comment]
Did you compare the two requests? There seem to be a few headers in your curl request that you did not include in the agent configuration (`Referer`, `X-Requested-With`, `content-type` vs `X-Requested-With`). You probably also need to input the value `"fid_list": "%5B%22117680932205672%22%5D"` url decoded: `"fid_list": "[\"117680932205672\"]"`.

I'd recommend finding the smallest working curl command (remove one header/option at a time and then move all required options to the Huginn Agent.

**Comment by yulahuyed** [comment]
@dsander Sorry for the late reply.

I find the smallest working curl command:
`curl "https://pan.baidu.com/api/sharedownload?timestamp=1519103490&sign=c731c0c62727f34e680e22f2c5027fbd79dce5a9&bdstoken=null&app_id=250528&channel=chunlei&clienttype=0&web=1" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0" -H "Cookie: PANWEB=1; BAIDUID=16C58D4491809AEFD8075AFAD0E5E9B8:FG=1" --data "encrypt=0&product=share&uk=1822488384&primaryid=3574473842&fid_list=%5B%22505222519162181%22%5D"`


After converting to post agent, and decoding the `fid_list`, I get the download link successfully.
```
{
  "post_url": "https://pan.baidu.com/api/sharedownload?timestamp=1519104500&sign=4e6347d6cdfcd551a2a88a7737a8c8654704799f&bdstoken=null&app_id=250528&channel=chunlei&clienttype=0&web=1",
  "expected_receive_period_in_days": "1",
  "content_type": "form",
  "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0",
  "method": "post",
  "payload": {
    "encrypt": "0",
    "product": "share",
    "uk": "1822488384",
    "primaryid": "3574473842",
    "fid_list": "[\"505222519162181\"]"
  },
  "headers": {
    "Cookie": "PANWEB=1; BAIDUID=16C58D4491809AEFD8075AFAD0E5E9B8:FG=1"
  },
  "emit_events": "true",
  "no_merge": "false",
  "output_mode": "merge"
}
```

Thank you for your help! :)

**Comment by dsander** [comment]
Nice! Glad you figured it out.
