### ISSUE TITLE
[Suggestion] Editing raw options. (raw data, w/o editor)

### ISSUE THREAD

**Issue by jack1142** [huginn/huginn#2224]
Hi,
I think there should be possibility to edit option in raw, w/o tree editor. Sometimes it would be a lot easier to just edit raw data instead of using that editor. Also, it shouldn't escape any character and should leave data exactly as they were put into text box.

**Comment by dsander** [comment]
Hi, 

there is a "Toggle view" link on the top right of the JSON editor. It will change the editor to a textarea field with the raw JSON.

**Comment by jack1142** [comment]
I have no idea why I haven't closed it yet.
