### ISSUE TITLE
how to: create a telegram agent

### ISSUE THREAD

**Issue by nileio** [huginn/huginn#2225]
Hi all,
I would like to know if I can create an agent that recieves events for each new chat message that i recieve in my telegram for a specific channel or from a bot ?
can someone give me the guidelines for creating such an agent - i am going through the docs and I think it is possible. any clues or ideas would be greatly appreciated.
Thank YOu!

**Comment by dsander** [comment]
Hi,

I think the simplest solution would be to use the `WebhookAgent`. This guide explains how to register a the Webhhok with Telegram: https://core.telegram.org/bots/webhooks

You will get the required token after you created your bot: https://core.telegram.org/bots/api#authorizing-your-bot

**Comment by nileio** [comment]
hi dsander, 
thanks for reply.. i wanted to use the telegram api, instead of the bot api because i needed to capture other bots messages, public channels that i participate in, etc. I believe bot api cannot do that.
i am not looking to create a bot so .. would be looking for a wrapper telegram api and use it as a huginn agent.. looking to find ways to achieve that

**Comment by dsander** [comment]
I see, have a look at the existing [`TelegramAgent`](https://github.com/huginn/huginn/blob/master/app/models/agents/telegram_agent.rb#L65) it uses the `GetUpdates` API call to get a list if recent conversations, I think you can use that call as a base for your Agent.

To help create new Agent (gems) we have [huginn_agent](https://github.com/huginn/huginn_agent) which will create a Agent gem skeleton. You need to have a working ruby on rails development environment to run the test though.

**Comment by standin000** [comment]
> 

have you finish this agent before you close this issue? I also have this demand.
