### ISSUE TITLE
Request: Nextcloud Integration for huginn

### ISSUE THREAD

**Issue by sunjam** [huginn/huginn#2226]
Please consider adding support for [Nextcloud integration,](https://github.com/nextcloud) an open source platform that provides a [large community alternative to the proprietary Google suite and Dropbox.](https://nextcloud.com/)

**Comment by dsander** [comment]
Hi, 

can you please add it to the [Agent suggestions thread](https://github.com/huginn/huginn/issues/353)?

**Comment by sunjam** [comment]
Added to the agent suggestion thread; see link above.
