### ISSUE TITLE
A question of multitask with Credentials 

### ISSUE THREAD

**Issue by yulahuyed** [huginn/huginn#2227]
I try to run a task which consists of "send request" and "check status". 

The flow chart:
<img width="697" alt="capture20" src="https://user-images.githubusercontent.com/27191666/36458771-756c6fcc-16eb-11e8-8dae-ffab0be77085.PNG">

However, I cannot start a new request until the old one has ended. Because when I send a new request, the Java Script Agent will update the credential `{% credential TASK_ID %}` to the new one, and the old `TASK_ID` will be overwritten.

So how could I update the credentials when sending many requests with the same Agent?

**Comment by yulahuyed** [comment]
Keep `TASK_ID`s via Events on loop agents would cost more resource and cannot be controlled  by schedule.

Requirements:
- keep `TASK_ID`s for a long time for running the check process
- control the schedule of the check process
- once the status of a `TASK_ID` meets the requirements, it can be removed from the list.

I try to use three Javascript agents, two control credentials, a series of ID credentials to achieve it, but have some problems.

The flow chart:
<img width="799" alt="capture31" src="https://user-images.githubusercontent.com/27191666/36630053-cbab401e-199a-11e8-9af8-22bac0bf6ffe.PNG">

Maybe add a new data structure "Queue" to credential  will be helpful.
One line is one event on a credential.
the operators:
`this.credential(name)`: read value to event line by line
`this.credential.update(value)`: add new value to the tail
`this.credential.remove(value)`: compare the given value with the value of credential line by line. If match, remove the line.
`this.credential.delete(name)`: delete the credential

**Comment by dsander** [comment]
I see, would it work to keep the `TASK_ID`s that need to be checked in the JavaScriptAgents memory? Depending on the incoming event it would either add the id to it's memory or remove it. On schedule the JavascriptAgent could emit events with the task ids that need to be checked.

**Comment by yulahuyed** [comment]
`this.memory()` maybe works. But there are some issues too.
- spend more memory. Normally, the huginn instance use about `750M` memory, and the postgresql use about `70M` memory. If use the memory to deal with hundreds of requests, the required memory of huginn will be increased. 
- Unstable. If the machine shuts down suddenly, would the `TASK_ID`s disappear? Sometimes, the address of memory may be mixed up, and return the different results.
- Complicated. If need to keep more than two parameters for checking, and need to be used with other groups of agents, maybe cost more time to figure out the relation.

**Comment by dsander** [comment]
Sorry the name might be misleading, it's memory in the sense of "brain memory" of the Agent. The data is actually stored in the database and thus as safe as the credentials.

**Comment by yulahuyed** [comment]
Thanks for your explanation.

I have achieved one goal with one JavaScript Agent and one Command agent.

<img width="423" alt="capture31" src="https://user-images.githubusercontent.com/27191666/36660067-af1efc42-1b11-11e8-98c6-f632f01e89a1.PNG">

Like "cache", the JavaScript Agent saves all requests to the memory. Create a new event for checking when the previous one finish or running first.

It would be easy to rewrite for other situations of multitask.

```
Agent.receive = function() {
  var events = this.incomingEvents();
  for(var i = 0; i < events.length; i++) {
    var TASKS_NO = this.memory('TASKS_NO') || 0;
    this.memory('TASKS_NO', TASKS_NO + 1);
    this.memory('TASKS_NO'+this.memory('TASKS_NO'), events[i].payload.text.toString());
    if(this.memory('TASKS_NO') == 1){
    this.createEvent({ 'Running': this.memory('TASKS_NO'), 'text': this.memory('TASKS_NO'+this.memory('TASKS_NO')) });
    this.deleteKey('TASKS_NO'+this.memory('TASKS_NO'));
    }
  }
};

Agent.check = function() {
  var RUN_NO = this.memory('RUN_NO') || 1;
  if(RUN_NO < this.memory('TASKS_NO')){
    this.memory('RUN_NO', RUN_NO + 1);
    this.createEvent({ 'Running': this.memory('RUN_NO'), 'text': this.memory('TASKS_NO'+this.memory('RUN_NO')) });
    this.deleteKey('TASKS_NO'+this.memory('RUN_NO'));
    if(this.memory('RUN_NO') == this.memory('TASKS_NO')){
      this.deleteKey('TASKS_NO');
      this.deleteKey('RUN_NO');
    }
  }
}
```

Thank you again.
