### ISSUE TITLE
Custom fields in RSS feed

### ISSUE THREAD

**Issue by jack1142** [huginn/huginn#2231]
Hi,
is there a way to get data from custom fields in RSS feed - like <media:thumbnail> from there: https://www.youtube.com/feeds/videos.xml?channel_id=UCBjQwd62OJgixzW49TKGERg

**Comment by dsander** [comment]
Not with the `RssAgent`, but you can use the `WebsiteAgent` with `type` set to `xml`:
```json
{
  "url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCBjQwd62OJgixzW49TKGERg",
  "mode": "on_change",
  "use_namespaces": "false",
  "type": "xml",
  "expected_update_period_in_days": "10",
  "extract": {
    "title": {
      "css": "thumbnail",
      "value": "@url"
    }
  }
}
```

**Comment by jack1142** [comment]
Thanks for help (even though I used this help few months ago)
