### ISSUE TITLE
Suggestion: Agent List vertical navigation bar

### ISSUE THREAD

**Issue by nileio** [huginn/huginn#2233]
Hi All,
I like the user interface of Huginn, however, I find that when creating a new agent, I have to scroll down on the long list of Agents, and click each one by itself to read the description. I then move to the next in the list, and so on. I suggest using a vertical navigation bar instead of a drop-down list. 
This way we can see the whole list at once. If it is too long for a navigation bar, then other suggestions ?

Thanks,

**Comment by dsander** [comment]
We have a list of all Agents here: https://huginnio.herokuapp.com/agents. The site is not completely done, but the Agent and Agent gem database should be quite useful.
