### ISSUE TITLE
Website Agent: Get old value when 'on_change' emits events

### ISSUE THREAD

**Issue by ali-sattari** [huginn/huginn#2234]
I am using website agent to get textual data from an API and then emit events on change.
I would like to retrieve previous value for data that is changed, so that I can mark the difference and alert recipients with more context.

I tried using `agent.memory` in the `template` section, hoping it might include previous value and get passed to the next agent (in this case setting mode to all and using de-duplicate agent) But `agent.memory` value is an empty object.

Do you know any configuration or agent that could detect change and return both old and new values?

**Comment by dsander** [comment]
Hi,

the `WebsiteAgent` does not use the memory but checks it's previously emitted Events. I did not try it build this might work:

* Set the `WebsiteAgent` to `on_change`
* Send the Events to a `DelayAgent`, configure this to "propagate immediately" and `max_events: 2, max_emitted_events: 2`
* Also send the Event to a `CommanderAgent` with "propagate immediately" disabled and have the commander run the `DelayAgent`.

**Comment by ali-sattari** [comment]
That's neat! 

I solved it using `WebsiteAgent` in `on_change` mode and then passing events to a `JavascriptAgent`, using its memory, added some logic to return the diff.

**Comment by arvalaan** [comment]
Would you be able to paste that logic here and explain how you've done this @ali-sattari - Google brought me here

**Comment by ali-sattari** [comment]
@arvalaan this is the whole Huginn scenario for my case: [json export](https://github.com/ali-sattari/domain-whois-history/blob/master/huginn-scenario/domain-history.json). You can see the JS code [embedded there](https://github.com/ali-sattari/domain-whois-history/blob/master/huginn-scenario/domain-history.json#L101).
