### ISSUE TITLE
WebSite Agent and Slack Webhook

### ISSUE THREAD

**Issue by keremcankabadayi** [huginn/huginn#2235]
Hi there! I'm newbie at this great app. I read wiki and tried some examples but i got really confused. I'm basically trying to get notified when the css field changes. It says no working. And i don't understand how to add matching words and how to attach with Slack Webhook. Can somebody help me to understand this beauty?

![](https://image.prntscr.com/image/JjQgdIvhQumcdSmVlOcBGQ.png)

**Comment by dsander** [comment]
Hi,

does the extraction work at all? Clicking on `dry run` should show you a modal that will list the Event(s) that the Agent would emit.

Can you please copy & paste the Options JSON into the issue? (Click on toggle view to get a textarea).

**Comment by keremcankabadayi** [comment]
```
{
  "expected_update_period_in_days": "2",
  "url": "http://ceng.anadolu.edu.tr/Duyurular.aspx",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "url": {
      "css": "#tickertable",
      "value": "@src"
    },
    "title": {
      "css": "#ContentPlaceHolder1_GridView1 a",
      "value": "@alt"
    },
    "hovertext": {
      "css": ".default-content",
      "value": "@title"
    }
  }
}
```

when i click `dry run` events get nothing. 

![](https://image.prntscr.com/image/vyx9NpjjQ_WP-wNp87GrxA.png)

**Comment by dsander** [comment]
There is nothing in the Log tab either? I was getting an exception about uneven amount of matches.

This should extract all links for the side navigation:

```json
{
  "expected_update_period_in_days": "2",
  "url": "http://ceng.anadolu.edu.tr/Duyurular.aspx",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "url": {
      "css": "#tickertable tr:not(:last-child) a",
      "value": "@href"
    },
    "title": {
      "css": "#tickertable tr:not(:last-child) a",
      "value": "normalize-space(.)"
    }
  }
}
```

**Comment by keremcankabadayi** [comment]
That's what i exactly wanted! I'm getting used to Huginn thanks to you.
