### ISSUE TITLE
help wanted: using Website Agent to scrape a url which directs everyday to a date-related url

### ISSUE THREAD

**Issue by PeterHouCN** [huginn/huginn#2236]
Hi, I'm trying to use Website Agent to scrape a digital daily news webiste. The original url is "http://paper.people.com.cn/rmrb/paperindex.htm", it redirects to a date-related url like"http://paper.people.com.cn/rmrb/html/2018-03/03/nbs.D110000renmrb_01.htm" everyday.

I've tried to using Liquid, but I really don't understand it.  Can you help to find a way to generate the daily url for Website Agent to use?

Thanks a lot !

Useful webpages:
1. http://huginnio.herokuapp.com/agents#WebsiteAgent
2. https://github.com/huginn/huginn/wiki/Formatting-Events-using-Liquid
3. https://shopify.github.io/liquid/basics/introduction/

**Comment by dsander** [comment]
Hi,

I would use two WebsiteAgents, first fetch the "base" URL and extract the redirection url, send that url to a second Agent with appends the extracted URL to its confiured url to fetch `http://paper.people.com.cn/rmrb/{{url}}`.

This should extract the redirection url:

```json
{
  "expected_update_period_in_days": "2",
  "url": "http://paper.people.com.cn/rmrb/paperindex.htm",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "url": {
      "css": "meta[http-equiv=REFRESH]",
      "value": "@content"
    }
  },
  "template": {
    "url": "{{url | split: \"=\" | last}}"
  }
}
```

**Comment by PeterHouCN** [comment]
@dsander Thanks a lot. Problem solved.
