### ISSUE TITLE
Agent event flow diagram is static

### ISSUE THREAD

**Issue by jimsug** [huginn/huginn#2241]
This looks similar to #2038, it's a manual install on Ubuntu 16.04.3 (xenial).

The event flow chart is static and doesn't display event badges.

![image](https://user-images.githubusercontent.com/2616308/37466540-1b05abf6-28b2-11e8-9579-c8fb6db3865f.png)

All dependencies are installed, I'm pretty sure. The logs aren't displaying any errors, not sure what's wrong with my install.

**Comment by dsander** [comment]
Did you install the `graphviz` package? You also need to enabled [`USE_GRAPHVIZ_DOT`](https://github.com/huginn/huginn/blob/master/.env.example#L224) in you `.env` file. After changing this the services need to be reexported.

**Comment by jimsug** [comment]
I am embarassed that I didn't enable `USE_GRAPHVIZ_DOT` and will exile myself to the depths of the internets.

Thanks very much for the quick fix :+1:
