### ISSUE TITLE
How to adopt Liquid String filter MD5

### ISSUE THREAD

**Issue by tingod** [huginn/huginn#2244]
I'd like to give MD5 encrypt to strings in my events, how ever seems no effect when trying below codes.
`{{str_to_md5 | md5}}`
I found there is the filter in Shopify help web as below:
https://help.shopify.com/themes/liquid/filters/string-filters#md5
Seems that Huginn doesn't adopt the most update version of Liquid?
How can I convert a string to MD5 in the easiest way?

**Comment by dsander** [comment]
For some reason the md5 filter seems to be only on Shopify and not in the open source liquid release: https://github.com/Shopify/liquid/pull/703#issuecomment-187328761

At the moment the only option is the use a JavascriptAgent and embed a md5 function like [this one](https://github.com/blueimp/JavaScript-MD5/blob/master/js/md5.min.js).

**Comment by tingod** [comment]
@dsander Great thanks for your comment and fix my pain quite well. Working on optimization now. Thank you!

**Comment by lessrand** [comment]
Hello,

could you please specify in more detail on how to embed a javscript function in the javaScript Agent?
I am having the same issue, trying to login to a server with a token challenge and MD% function ...

kind regards

Randolph

**Comment by dsander** [comment]
@lessrand You copy the source code of the `md5.min.js` file into your JavascriptAgent and call it with `md5("something")`.

**Comment by lessrand** [comment]
Super, I took another - non-minified - javascript, but it works.

I would suggest the following improvements:

* resizing for the editor form - maybe code formating
* uploading js libraries in huginn, and the possibility to include them

kind regards 

Randy
