### ISSUE TITLE
Truncate Description of RSS feed

### ISSUE THREAD

**Issue by DreamFlasher** [huginn/huginn#2245]
How do I limit the description of an rss feed to a limited number of characters? (And if that's not possible: How do I remove the description?)

**Comment by dsander** [comment]
You should be able to use the Liquid [truncate fileter](https://shopify.github.io/liquid/filters/truncate/) either in the output Agent directly or in a EventFormattingAgent.

**Comment by DreamFlasher** [comment]
Thank you very much!
For future reference, if you have an RSS feed as an input and want to limit the description here's the code for the EventFormattingAgent:

 ```
{
  "instructions": {
    "title": "<a href=\"{{url}}\">{{title}}<\/a>",
    "description": "{{description | truncate: 500 }}"
  },
  "matchers": [

  ],
  "mode": "clean"
}
```

**Comment by virtadpt** [comment]
It might be worth adding this to the wiki for future reference.

**Comment by DreamFlasher** [comment]
added to the wiki
