### ISSUE TITLE
Website Agent Question

### ISSUE THREAD

**Issue by gogoing1092** [huginn/huginn#2250]
I want to make a rss from "https://www.jinse.com/lives", but it seems not work.

This is agent Options:

> {
>   "expected_update_period_in_days": "2",
>   "url": "https://www.jinse.com",
>   "type": "html",
>   "mode": "on_change",
>   "extract": {
>     "description": {
>       "css": "div.time",
>       "value": "string(.)"
>     },
>     "title": {
>       "css": "div.content",
>       "value": "string(.)"
>     }
>   }
> }

Can anyone help me to improve this, thank you very much

**Comment by kornflex** [comment]
hello,

Want do you want to do : rss from jinse.com or /lives ???? Use the correct URL.

I try to find div.time nothing. Are you sure of the css path ???

**Comment by gogoing1092** [comment]
I want to rss this website:"https://www.jinse.com/lives" and monitor this 2 things(below image)
https://imgur.com/a/k5Boa
https://imgur.com/a/to7sX

Thank you kornflex 

> {
> "expected_update_period_in_days": "2",
> "url": "https://www.jinse.com/lives",
> "type": "html",
> "mode": "on_change",
> "extract": {
> "description": {
> "css": "div.time",
> "value": "string(.)"
> },
> "title": {
> "css": "div.content",
> "value": "string(.)"
> }
> }
> }

**Comment by kornflex** [comment]
hi,

I think there is a problem with javascript..
Huginn tries to get source code when javascript is running.
If I try this : 
{
  "expected_update_period_in_days": "2",
  "url": "https://www.jinse.com/lives",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "time": {
      "css": "div.js-main",
      "value": "./node()"
    }
  }
}

you will have the javascript loading image, not the content

you should try to have the content with a sleep or disabling JS but I don't know how :/

**Comment by dsander** [comment]
@gogoing1092 Huginn itself is not able to scrape pages build via Javascript, you can use [fulldom-server](https://github.com/strugee/fulldom-server) or https://phantomjscloud.com/ to do extraction based on the final page that has been generated by the javascript.

**Comment by gogoing1092** [comment]
Thank you @dsander & @kornflex, This can solve my question

**Comment by txj347** [comment]
> Thank you @dsander & @kornflex, This can solve my question
@gogoing1092,我也遇到同样的问题，你是如何解决这个问题的，请教。

**Comment by txj347** [comment]
@gogoing1092，你好，我也遇到同样的问题，你是如何解决这个问题的，求教。最好附上可运行的代码。

**Comment by erebor** [comment]
@gogoing1092 Could this issue be closed?
