### ISSUE TITLE
Can I monitor page for any change?

### ISSUE THREAD

**Issue by jack1142** [huginn/huginn#2251]
Like in title, I want to get email, when there will be any change on the page. Something like what visualping.io offers.

**Comment by kornflex** [comment]
Hello,

Do you try "mode": "on_change" in your website agent ?

**Comment by dsander** [comment]
> Do you try "mode": "on_change" in your website agent ?

Exactly that, you can use `body` or `html` as the css selector and `.`  (which will use the html) or `normalize-space(.)` (to use all text on the page for the change detection) as value.

**Comment by jack1142** [comment]
Thanks, both of you, I just didn't know which agent has such possibility. I even used it before and forgot about it :D
