### ISSUE TITLE
how to send event minute by minute ?

### ISSUE THREAD

**Issue by kornflex** [huginn/huginn#2252]
Hello,

I get a lot of events in a small time. My server is slowing down. 

Is it possible to have an agent ( buffer agent ?? ) which sends events one by one, minute by minute ( or in a specific time range we can specify ? )
I see delay agent but he keeps events and sent all in the same time, not one by one.

Thank you

**Comment by dsander** [comment]
Hi!

You can use the `DelayAgent` and set `max_emitted_events` to 1 which will then just create one event every time it is running.

**Comment by kornflex** [comment]
Great ! Thank you !
I was using this, but without this parameter :/ I thuoght it was a limit. After x events, everything else will be ignored :/

thank you
