### ISSUE TITLE
Cannot start latest docker image 

### ISSUE THREAD

**Issue by johnnyzen** [huginn/huginn#2254]
Getting a permission issue?? when starting docker with 

`sudo docker run -it -p 3000:3000 -v /home/test/mysql-data:/var/lib/mysql --restart always huginn/huginn`

Results in: 

```
bootstrap stderr | mv:  bootstrap stderr | cannot create directory ‘/var/lib/mysql/mysql’ bootstrap stderr | : Permission denied bootstrap stderr |
bootstrap stderr | mv:  bootstrap stderr | cannot create directory ‘/var/lib/mysql/performance_schema’ bootstrap stderr | : Permission denied bootstrap stderr |
```

Any ideas?

**Comment by johnnyzen** [comment]
Tried some of the older dcoker images and found it stopped working for me at this tag:

80549455938ef32a043e986529c50b6245154b81

**Comment by johnnyzen** [comment]
looking into further, that tag date kinda matches this merge and looks like it could be related:
https://github.com/huginn/huginn/pull/2112

**Comment by johnnyzen** [comment]
I managed to get it working by changing `/home/test/mysql-data` to permission `777` ???

Any ideas why?

**Comment by dsander** [comment]
Hi @johnnyzen,

I was afraid that the change you mention could cause problems upgrading, but I guess the permission issue does not happen on macOS. 

To improve security, newer versions of the docker image do not run the processes as root that is why mysql could not be started.

An alternative solution would be to chown the mysql-data directory to `1001:1001`.

I will try to find some time to document the upgrade process in the next days.

**Comment by johnnyzen** [comment]
many thanks @dsander

**Comment by vtoomas** [comment]
Got around the issue using docker volume. Maybe helpful for some. 
`docker volume create huginn-data`
`docker run -it -p 3000:3000 -v huginn-data:/var/lib/mysql huginn/huginn
`

**Comment by samching** [comment]
Thank you @vtoomas 🙏 Saved me many more hours of googling around for this issue.

**Comment by johnnyzen** [comment]
Nice one :)
