### ISSUE TITLE
Please help me get the post agent for Discord webhooks to work with twitter agent ; _;

### ISSUE THREAD

**Issue by Baniita** [huginn/huginn#2258]
I... I have no idea what I'm doing. 😂

What am I doing wrong? When I ran this through Zapier, the tweets came in... but I don't quite know how to do this haha. T vT

Source -- Twitter Search Agent: 
```
{
  "search": "list:Yullenator/d-gray-man filter:media -filter:retweets",
  "expected_update_period_in_days": "1"
}
```

Post Agent (receiver of that):
Type: Post Agent
Schedule: Never
Last checked: never
Keep events: 14 days
Last event created: never
Last received event: 2m ago
Events created: 0
Event sources: DGM Twitter Art
Propagate immediately: No
Event receivers: None
Working: Yes

```
{
  "post_url": "https://discordapp.com/api/webhooks/423997652653309964/SqT288KxwppjJnhAv2qRkaeeLZpCdEh8LfetLf9dFdlEkY-K3xVqVl2Dixe4U1SOjGm9",
  "expected_receive_period_in_days": "1",
  "content_type": "json",
  "method": "post",
  "payload": {
    "username": "{{user}}",
    "content": "{{expanded_url}} {{user}}-{{id_str}}",
    "avatar_url": "{{profile_image_url}}"
  },
  "headers": {
    "Content-Type": "application/json"
  },
  "emit_events": "false",
  "no_merge": "false",
  "output_mode": "clean"
}
```

**Comment by jimsug** [comment]
Is there any logging data?

**Comment by Baniita** [comment]
Not for the post agent, but there is for the twitter search agent:
`Exception during check. Rate limit exceeded: /home/huginn/huginn/vendor/bundle/ruby/2.4.0/bundler/gems/twitter-d11707edf4ab/lib/twitter/rest/request.rb:81:in `fail_or_return_response_body' /home/hu...`

.....well, it didn't use to be "rate limit exceeded" but it didn't work before that either o7

**Comment by dsander** [comment]
The `Rate limit exceeded` exception means your Twitter Agent(s)s are running too ofter and/or requesting too much data. Not sure why the search is not working, looking at the [docs](https://developer.twitter.com/en/docs/tweets/rules-and-filtering/overview/standard-operators) your query looks correct.

**Comment by dsander** [comment]
Found it the agent expects the `starting_at` option to be set:

```json
{
  "search": "list:Yullenator/d-gray-man filter:media -filter:retweets",
  "expected_update_period_in_days": "2",
  "starting_at": "Mon Jun 02 00:38:12 +0000 2014"
}
```

**Comment by Baniita** [comment]
The search is working, but the post agent isn't. It can grab the links from search, but they won't post to Discord.

**Comment by dsander** [comment]
What is the response you are getting from Discourse when you are dry running the PostAgent with one of the Tweet Events? Setting `create_events` to `true` can help debug problems.

I think the payload should look more like this:
```
    "username": "{{user.screen_name}}",
    "content": "{{entities.media | map: 'expanded_url'}} {{user.screen_name | join: ' '}}-{{user.id_str}}",
    "avatar_url": "{{user.profile_image_url}}"
```

**Comment by Baniita** [comment]
Sorry... discourse? T _T I.... I don't know, but when I dry run it, this is all that happens: 
`[00:00:00] INFO -- : Dry Run started
[00:00:00] INFO -- : Dry Run finished`

and... the elements I put in are from the twitter dev documentation but I can't find the "entities.media" or... nor do I understand the rest of that line aha...haha...... map? join? e-eeehh....

something weird happened, too. 
![image](https://user-images.githubusercontent.com/4813941/38711346-f0da2da6-3e79-11e8-8d24-65f35c6864af.png) last night, this appeared in #art-feed, the channel I wanted to put fetched tweets to.... but it only ever happened once and then never happened again, and I don't really know why. I'll try playing around with the "check every ~ minutes" though.... but I don't understand why I would be exceeding a rate--
https://developer.twitter.com/en/docs/ads/general/guides/rate-limiting
according to this, I shouldn't be hitting any of these rates...? hmm..

**Comment by Baniita** [comment]
Bless you, thank you!
