### ISSUE TITLE
How do you filter out terms? Possibility of filtering twitter users? 

### ISSUE THREAD

**Issue by Baniita** [huginn/huginn#2259]
Is this possible with twitter user agent (or stream agent)? 🤔 I looked into previous issues but I couldn't find anything about how to _exclude_ terms. For instance, I want to follow a twitter that releases information on books, but I don't want the tweets that go "here are all the releases for today"?

As well, is it possible to use Twitter Stream Agent but only for certain users? i.e. I want to follow merchandise releases from several merchandise manufacturing companies, but if I use the filter terms on the entire twitter stream I follow, it'll pick up a lot stuff that's not merch.

**Comment by dsander** [comment]
I think for that either the `TwitterUserAgent` or `TwitterSearchAgent` are the best options we have. The search API has [some advanced query options](https://developer.twitter.com/en/docs/tweets/search/guides/standard-operators) but you are not guaranteed to get all matching tweets.

The filtering out of Tweets would need to be done downstream by other Agents (a `TriggerAgent` for example). You can have multiple `TwitterUserAgent`s feeding into one `TriggerAgent`.

**Comment by Baniita** [comment]
Can TriggerAgent work with excluding terms? o:

**Comment by Baniita** [comment]
Like... this?

`{
  "expected_receive_period_in_days": "1",
  "keep_event": "true",
  "rules": [
    {
      "type": "field!=value",
      "value": "yulit_",
      "path": "$.retweeted_status.user.screen_name"
    },
    {
      "type": "field!=value",
      "value": "nieniekoto",
      "path": "$.retweeted_status.user.screen_name"
    },
    {
      "type": "field!=value",
      "value": "ラビアレ",
      "path": "$.full_text"
    },
    {
      "type": "field!=value",
      "value": "ラビユ",
      "path": "$.full_text"
    },
    {
      "type": "field!=value",
      "value": "ティキアレ",
      "path": "$.full_text"
    }
  ],
  "message": "",
  "must_match": "1"
}`

**Comment by virtadpt** [comment]
That looks like it should work.  I don't know if the i18n characters are messing it up or not.  Anybody know?

**Comment by Baniita** [comment]
Messed with it again, waiting to see if the previous filter (filter A) works, but
In the meantime, let's call this filter B; I'm trying to recreate this zapier filter, but I don't know how to put in "does not exist" o ~o

> 
> {
>   "expected_receive_period_in_days": "1",
>   "keep_event": "true",
>   "rules": [
>     {
>       "type": "field==value",
>       "value": "null",
>       "path": "$.retweeted_status"
>     }
>   ],
>   "message": ""
> }
> 

Is it possible to create a filter to prevent retweeted posts from coming through? "-filter:retweets" in the twitter search agent doesn't seem to work here as they still go through, as a result I'm getting like 10 duplicate entries oftentimes. 

That's what I put in, but seems like no posts are going through at all.

**Comment by dsander** [comment]
For the `full_text` matches it might be help to use the `!regex` `type`,  that way it will filter out the event if the text occurs somewhere in `full_text`.

I think that should work for filter B:

```
    {
      "type": "field!=value",
      "value": "{{retweeted_status | default: 'thiswillneveractuallybeintheevent' }}",
      "path": "retweeted_status"
    }
```

**Comment by Baniita** [comment]
Switched to regex! Filter A seems to be working so far?

Changed to that for filter B, thank you! (No $. in front of retweeted status?) Testing to see if it works!

**Comment by dsander** [comment]
> (No $. in front of retweeted status?)

The leading `$.` is optional, you can use it but you don't have to.

**Comment by Baniita** [comment]
wheeeee everything seems to be working thank uuuu \o/
