### ISSUE TITLE
RSS to PostAgent on Discord, can't figure out how to make it work

### ISSUE THREAD

**Issue by Baniita** [huginn/huginn#2260]
I'm so sorry for posting _again_ T _T I really have no idea what I'm doing and I can't make heads or tails of the Liquid Interpolation article.

feed: https://rss.simplecast.com/podcasts/52/rss

current setup:
> {
>   "post_url": "https://discordapp.com/api/webhooks/424037023133990912/buhkFmHuZ[redacted]TS3eN2qBO33m_u3jpn3W-7ppDTH_hSfCrxdD",
>   "expected_receive_period_in_days": "10",
>   "content_type": "json",
>   "method": "post",
>   "payload": {
>     "content": "**{{item.title}}**{% line_break %}{% line_break %} {{item.description}}{% line_break %} <{{item.link}}>"
>   },
>   "headers": {
>     "Content-Type": "application/json"
>   },
>   "emit_events": "true",
>   "no_merge": "false",
>   "output_mode": "clean"
> }

Or is it `**{{title}}**{% line_break %}{% line_break %}
{{description}}{% line_break %}
<{{link}}>`
or is it `**{{channel.item | map: 'title'}}**{% line_break %}{% line_break %}
{{channel.item | map: 'description'}}{% line_break %}
<{{channel.item | map: 'link'}}>`?
God I'm beyond noob I am so sorry. I tried and I failed.

**Comment by Baniita** [comment]
Thank you! I'm waiting to see if it works aha;

This is the filter for my tumblr RSS:

> {
>   "expected_receive_period_in_days": "1",
>   "keep_event": "true",
>   "rules": [
>     {
>       "type": "field!=value",
>       "value": "klance",
>       "path": "$.category"
>     },
>   ],
>   "message": ""
> }

It should filter out anything tagged klance, however is it possible to make an exception rule for when tags are tagged with "general"?
i.e. blacklist klance, whitelist general which takes priority over the blacklisted term

**Comment by dsander** [comment]
> ?? I'm not sure why it's in html, I only wanted it to post the permalink of the post

Sorry me neither, the RSS Agent should only put the plain url as text in the `url` of it's Events. Did you check how the Events look that come from the RSS Agent?

> i.e. blacklist klance, whitelist general which takes priority over the blacklisted term
> And if so, how would I do that?

At the moment you are doing a string comparison, so if the category is not equal to `klance` it will never equal `general`. You could switch the `type` to `!regex` for the blacklist and add another rule with `regex` for `general` and set `must_match` to `1`. That should allow events with `general` in `category` or events that do not have `klance` in it.

**Comment by Baniita** [comment]
> Sorry me neither, the RSS Agent should only put the plain url as text in the url of it's Events. Did you check how the Events look that come from the RSS Agent?

Description's coming out as

>  "description": "<img src=\"https://78.media.tumblr.com/4cc317bb948c5ccde90ed1a6fbd7ad3f/tumblr_p523lwJGXx1wrb3z2o4_r1_500.gif\"><br> <br><img src=\"https://78.media.tumblr.com/c557d02e5c548a4fd49779ddc27843b8/tumblr_p523lwJGXx1wrb3z2o3_r1_500.gif\"><br> <br><img 
src=\"https://78.media.tumblr.com/9eb671b5c7b96f5b452eb92f967834a2/tumblr_p523lwJGXx1wrb3z2o2_r1_500.gif\"><br> <br><img src=\"https://78.media.tumblr.com/f17124f2609e0eb37741e240f0eece5a/tumblr_p523lwJGXx1wrb3z2o1_r1_500.gif\"><br> <br>",

@ _@

Oh, thank you!

**Comment by dsander** [comment]
> Description's coming out as

That looks correct, above you mentioned that you used `{{url}}` in you PostAgent.

Events from the RssAgent look like this:

```
  {
    "id": "https://vld-news.tumblr.com/post/172907231732",
    "url": "https://vld-news.tumblr.com/post/172907231732",
    "urls": [
      "https://vld-news.tumblr.com/post/172907231732"
    ],
    "links": [
      {
        "href": "https://vld-news.tumblr.com/post/172907231732"
      }
    ],
    "title": "voltron:When you get hit in the feels",
    "description": "<img src=\"https://78.media.tumblr.com/02e9eba37c06ce9fbe575e2c39fbe921/tumblr_p75c59T4Ej1u9w1bwo1_500.gif\"/><br/><br/><p><a href=\"https://voltron.tumblr.com/post/172907175611/when-you-get-hit-in-the-feels\" class=\"tumblr_blog\" target=\"_blank\">voltron</a>:</p><blockquote><p>When you get hit in the feels</p></blockquote>",
    "content": "<img src=\"https://78.media.tumblr.com/02e9eba37c06ce9fbe575e2c39fbe921/tumblr_p75c59T4Ej1u9w1bwo1_500.gif\"/><br/><br/><p><a href=\"https://voltron.tumblr.com/post/172907175611/when-you-get-hit-in-the-feels\" class=\"tumblr_blog\" target=\"_blank\">voltron</a>:</p><blockquote><p>When you get hit in the feels</p></blockquote>",
    "image": null,
    "enclosure": null,
    "authors": [

    ],
    "categories": [
      "keith",
      "vld social",
      "s5",
      "5.04",
      "gifs"
    ],
    "date_published": "2018-04-13T18:07:49-05:00",
    "last_updated": "2018-04-13T18:07:49-05:00"
  }
```

So `{{url}}` will only post the url, but the description includes a bunch of HTML.

**Comment by Baniita** [comment]
Yeah, I put {{url}}, but for some reason it seemed to be spewing the description. Anyway, changing "no merge" to true seemed to have fixed it. o7 thank youuu

**Comment by dsander** [comment]
Nice, glad it's working now!
