### ISSUE TITLE
domain missing from url 

### ISSUE THREAD

**Issue by xdirty** [huginn/huginn#2261]
So im using a website agent to extract a url from a website. the problem is that this particular website only has part of the url in their source code. For example instead of www.website.com/website/section i only get /website/section/.

```
{
  "title": "website title",
  "url": "/website/section/"
}
```
**Is there anyway to add the domain in the webagent to show a full url ?**

heres what my website agent looks like

```
{
  "url": "www.website.com",
  "mode": "on_change",
  "type": "html",
  "expected_update_period_in_days": "10",
  "extract": {
    "title": {
      "css": ".postlist li a",
      "value": ".//text()"
    },
    "url": {
      "css": ".postlist li a",
      "value": "@href"
    }
  }
}

```

**Comment by dsander** [comment]
Yes that is possible with the `to_uri` Liquid filter and the template option:

```
{
  "url": "www.website.com",
  "mode": "on_change",
  "type": "html",
  "expected_update_period_in_days": "10",
  "extract": {
    "title": {
      "css": ".postlist li a",
      "value": ".//text()"
    },
    "url": {
      "css": ".postlist li a",
      "value": "@href"
    }
  },
  "template": {
    "url": "{{ url | to_uri: _response_.url }}"
  }
}
```

**Comment by xdirty** [comment]
That's amazing. Thank you so much Dominik. I cant thank you enough

**Comment by ericsupreme** [comment]
hey guys shouldn't this issue be closed?

**Comment by dsander** [comment]
Sure
