### ISSUE TITLE
Rancher-cattle template deploys, but delayed-job continually restarts

### ISSUE THREAD

**Issue by yamlCase** [huginn/huginn#2269]
I was able to successfully deploy the Huginn cattle template and add an agent which was able to pull test data just fine.  After rebooting the docker-machine this stack is running on I continually see the 'huginn-delayed-job' container restarting every few seconds and jobs just pile up in the queue.  Attached are logs, and composer yamls.

I'm inviting @Zicklag to the party as I believe he is the author of the template.

Template URL: https://github.com/rancher/community-catalog/tree/master/templates/huginn

[huginn-delayed-job.log](https://github.com/huginn/huginn/files/1945119/huginn-delayed-job.log)
[docker-compose.yml.txt](https://github.com/huginn/huginn/files/1945189/docker-compose.yml.txt)
[rancher-compose.yml.txt](https://github.com/huginn/huginn/files/1945190/rancher-compose.yml.txt)

**Comment by dsander** [comment]
I don't know much about rancher, but I am using a similar docker-compose configuration and restarting the delayed job container works without issues. Did you hard reset the machine? It is possible that the DJ process was not properly shut down and is hanging on a old PID file.

**Comment by yamlCase** [comment]
Give me some time to get back around to docker again.  I'm new with Docker also trying to be new at Huginn and my priority is to evaluate Huginn.  I say if @zicklag can't reproduce just close the issue.

**Comment by zicklag** [comment]
I'll have to check my instance. I think it may have been happening to me, I just didn't notice it. I've been busy so I'm not sure when I'll be able to check it out, though.
