### ISSUE TITLE
 Why is the website agent fetching values ​​that are always empty?

### ISSUE THREAD

**Issue by sevenrad** [huginn/huginn#2272]
![image](https://user-images.githubusercontent.com/18319298/39352207-9b48d6f8-4a36-11e8-8460-a1efe0a2477b.png)
as the picture shows，thanks!

**Comment by dsander** [comment]
Hmm not sure that I understand, the Agent is fetching the Website and trying to extract data from the fields you configured. If the selectors aren't matching anything the Agent also can not extract anything.

**Comment by dsander** [comment]
It is possible that the Website is using Javascript to render, if that is the case you can use [fulldom-server](https://github.com/strugee/fulldom-server) or https://phantomjscloud.com/ to do extraction based on the final page that has been generated by the javascript.

**Comment by sevenrad** [comment]
thank you very much. I have slove the problem!

**Comment by lingllting** [comment]
@sevenrad how did you make it work?

**Comment by lingllting** [comment]
@sevenrad  留个联系方式交流一下...
