### ISSUE TITLE
Need help with custom format for HTTP POST

### ISSUE THREAD

**Issue by yamlCase** [huginn/huginn#2273]
InfluxDB accepts HTTP POST to write new datapoints in the database.  It uses its own "[Line Protocol](https://docs.influxdata.com/influxdb/v1.5/write_protocols/line_protocol_reference/)" format for the payload that differs so far as I can tell:
- spaces instead of ampersand for delimiter,
- (optional) last field is a timestamp, no key value pair
- (required)first field is a comma delimited string
- (required)first field of the first field is a value for measurement.  This is similar to a table name in a database
- (optional) first field's other parameters are key=value pairs called "tags" (comma delimited)
- (required) middle field is a key=value pair.
Example:

```
curl -i -XPOST "http://localhost:8086/write?db=mydatabase&precision=s" --data-binary 'mymeasurement,mytag=1 myfield=9000 1463683075'
                                            {db name}      {options}                  {measurement}  {tag}  {key,value}  {timestamp}
                                             req'd           opt'l                         req'd      opt      req'd         opt
```

I spend a couple of hours today trying to use the POST agent to no avail.  Part of this is me not really understanding all the options that can go into it I'm sure, but I also might be using the wrong agent.

Issues I'm unable to overcome with this agent:
- delimiters are ampersands instead of spaces
- see no way to have a non-key=value pair bit in the body (the 'measurement' bit)
- measurement field must be first
- optional timestamp field must be last
- datapoint key=value pair must be in the middle (the 'myfield' bit)

I'm hopeful if I can find a way to overcome these issues it'll work, but don't know if there'll be anything else blocking.

References:
- InfluxDB write API docu: https://docs.influxdata.com/influxdb/v1.5/tools/api/#write
- Line Protocol reference: https://docs.influxdata.com/influxdb/v1.5/write_protocols/line_protocol_reference/

**Comment by dsander** [comment]
Hi,

you can use the `PostAgent` to send a "raw" string in the body by specifying a different `content_type`. When doing that the query string parameter have to be put into the url itself:

```json
{
  "post_url": "https://hugrequestbin.herokuapp.com/1gn5zbe1?db=mydb&precision=s",
  "expected_receive_period_in_days": "1",
  "content_type": "text/plain",
  "method": "post",
  "payload": "mymeas,mytag=1 myfield=90 1463683075",
  "headers": {},
  "emit_events": "true",
  "no_merge": "true",
  "output_mode": "clean"
}
```

**Comment by yamlCase** [comment]
that did the trick!  thank you very much.
