### ISSUE TITLE
Custom agent hanging forever but not showing anything in the UI logs

### ISSUE THREAD

**Issue by hilts-vaughan** [huginn/huginn#2275]
```
[ActiveJob] [AgentCheckJob] [fd070321-1363-4e56-80c8-3f6269ddca0d] Error performing AgentCheckJob (Job ID: fd070321-1363-4e56-80c8-3f6269ddca0d) from DelayedJob(default) in 35.09ms: NoMethodError (undefined method `join' for nil:NilClass):
```

I'm getting something like this over and over. However, the logs never show a problem. Furthermore, it back logs the rest of my jobs and never completes. 

The code is here: https://github.com/hilts-vaughan/plex-huginn-ruby and I'm sure I have a bug somewhere -- but it would be nice if Huginn would be more specific about what is going.

Can I find more info elsewhere other than `development.log` or a longer stack trace to figure out what is going on?

**Comment by hilts-vaughan** [comment]
Looks like Arch Linux is Ruby 2.5, yes: https://www.archlinux.org/packages/extra/x86_64/ruby/

I'll give it a try tonight -- thanks!

**Comment by hilts-vaughan** [comment]
That seemed to have worked!

Thanks.

**Comment by dsander** [comment]
Nice, thanks for testing it!
