### ISSUE TITLE
Replying to Tweet - possible with existing agent?

### ISSUE THREAD

**Issue by spdustin** [huginn/huginn#2277]
If supplied with a tweet event payload, is there a way to reply to that tweet?

**Comment by dsander** [comment]
Not at the moment. It would be a nice addition to the `TwitterPublishAgent`, the [update](https://github.com/huginn/huginn/blob/master/app/models/agents/twitter_publish_agent.rb#L63) method from the twitter gem accepts optional arguments. `client.update("I'm tweeting with @gem!", in_reply_to_status_id: 402712877960019968)` would create a reply to that tweet id.

**Comment by spdustin** [comment]
I'll look into updating that agent. I'm teaching a class this week, so it may be a while before I get to it, but I'm happy to contribute that change.

I've been meaning to update the agent chooser (via Select2) I originally contributed to, also. Hey, @knu, is #1802 still a WIP for you, or can I take that on?
