### ISSUE TITLE
Agent Gems and Dokku

### ISSUE THREAD

**Issue by spdustin** [huginn/huginn#2278]
Are there specific steps required to use Huginn Agent **gems** under Dokku?

**Comment by dsander** [comment]
Hi @spdustin,

the way the dokku (the same as Heroku) works it requires the `Gemfile.lock` to include the Agent gem you want to use. That means you have to run `bundle install` locally with the same `ADDITIONAL_GEMS` configuration you have set on your dokku host. After that is done commit the changes to `Gemfile.lock` and push it to dokku.

If you do not have a local ruby development environment you can also use the test docker image to modify the Gemfile.lock. This command will override your local `.env`, create a backup before running the command.

```
ocker run -e ADDITIONAL_GEMS="yourconfiguration" -v `pwd`:/app huginn/huginn-test
```

The container will fail at one point but it should have written the changes to the `Gemfile.lock`.

**Comment by spdustin** [comment]
So it needs to be in *both* the `Gemfile`/`Gemfile.lock` **and** the `ADDITIONAL_GEMS` config setting?

**Comment by dsander** [comment]
Yes, exactly. The ruby buildpack we are using for Heroku and Dokku is using the bundler `--deployment` flag which requires the `Gemfile.lock` to match the `Gemfile`. Because we dynamically change the `Gemfile` when `ADDITIONAL_GEMS` is set it needs to be updated locally.

**Comment by spdustin** [comment]
Gotcha, thanks @dsander.
