### ISSUE TITLE
Refresh agent

### ISSUE THREAD

**Issue by ghost** [huginn/huginn#2282]

**Comment by dsander** [comment]
Hi,

we do not have an Agent that can create other Agents, but you can use `CommanderAgent` to change the options of another Agent.

**Comment by Jacob09** [comment]
Hi,

how can i change the default options? I wrote an agent, which parse a json file in "default options -> title". If the json file changes, default options remains constant.

**Comment by dsander** [comment]
The default options are only used when creating new Agents and your function should be called every time a user selects the Agent from the Type dropdown.

Do you want the Agent to read your JSON file every time it is running?

**Comment by Jacob09** [comment]
Yes, i want that the Agent read the JSON file every time. 
How can I address the title of rss feed outside of the default option?

I would like change any words from RSS feed title and use the "Data Output Agent" for the output.

**Comment by dsander** [comment]
I am not sure that I completely understand what you are trying to do. You can change the title of DataOutputAgent by changing the `title` option in the Agents options. You could use a `ReadFileAgent` to read the JSON file, pass the data to a `JsonParseAgent`, and then feed the data to an `CommandAgent` which changes the options of the `DataOutputAgent`.

**Comment by spdustin** [comment]
Are you saying you want to use a JSON file as a text replacement configuration file, basically? Where you describe the search/replace transformations you intend to make in another agent being used to transform the RSS feed?

**Comment by Jacob09** [comment]
I have a JSON file with word A and word B. I just want word A to be swapped with word B in the RSS feed title.

**Comment by Jacob09** [comment]
So, I have a LocalFileAgent and JsonParseAgent. 
Json Parse Agent gives me: 

```
{
  "data": {
    "replace": [
      {
        "meta": {
          "WordA": [
            "Google"
          ]
        },
        "WordB": "Facebook"
      },
      {
        "WordB": "Huginn",
        "meta": {
          "WordA": [
            "Windows"
          ]
        }
      }
    ]
  }
}
```
How do I replace WordA with WordB in the RSS feed title?

**Comment by dsander** [comment]
@Jacob09 It's hard to do directly, I would run the `ReadFileAgent` on interval (every X minutes) and pass the result of the `JsonParseAgent` to a `JavascriptAgent` which transforms your JSON data into a Liquid replace-filter-chain which is passed to a  `CommanderAgent` who then configures the options of a `EventFormattingAgent`.

I spend some time trying to do the transformation in Liquid but did not succeed. Your `EventFormattingAgent` should in the end look something like this to receive Events from the RSSAgent and replace the words you configured:
```
{
  "instructions": {
    "title2": "{{  title |  replace: \"Google\", \"Facebook\" |  replace: \"Windows\", \"Huginn\" }}"
  },
  "matchers": [],
  "mode": "merge"
}
```

**Comment by dsander** [comment]
That does not work because the `LocalFileAgent` can not pass events it receives to the next Agent. You need two Agent chains:

```
ReadFileAgent -> JsonParseAgent -> JavascriptAgent (transform the JSON into the options for the EventFormattingAgent) -> CommanderAgent -- <configures options> -> EventFormattingAgent

and

RssAgent -> EventFormattingAgent -> DataOutputAgent
```

**Comment by Jacob09** [comment]
Can you give me a example for `JavascriptAgent (transform the JSON into the options for the EventFormattingAgent) -> CommanderAgent -- <configures options>` ? I don't know, how they work. 
How must the agents be defined?

**Comment by Jacob09** [comment]
Can I solve the problem without the `JavascriptAgent`?

**Comment by dsander** [comment]
Mhm i guess we can close the issue 😕

**Comment by Jacob09** [comment]
I'm sorry, but can you help me? How can i transform the JSON into the options for the EventFormattingAgent?

**Comment by Jacob09** [comment]
I'm sorry, but can you help me? How can i transform the JSON into the options for the EventFormattingAgent?
