### ISSUE TITLE
scrape urls produced by liquid template 

### ISSUE THREAD

**Issue by AngelPone** [huginn/huginn#2283]
I'm sorry but I am new to Huginn. I want to fetch a url list produced by liquid template below.

```
{%assign a = http://www.topit.cc/weimei/278_3.html %}
{%for i in (2..48)%}
{{a | replace: '3',i}
{%endfor%}
```

I put this template into 

```
"url": "{%assign a = "http://luolitu.com/photo/1794_2.html" %}{%for i in (1..47)%}{{a | replace: '2', i}}{%endfor%}",
```
The template produced 47 urls , but Website Agent only scrapes the first web page , so which parameters do you recommend to scrape web page lists ? 

Thanks!

**Comment by dsander** [comment]
Hi,

we have the `as_object` Liquid filter which can be used to return the result of a liquid filter chain as array or Hash/object, but I don't think there is a way to use it in your use case. The only solution I can think of is to use Liquid to generate JSON and pass that to the `JsonParseAgent` to get an array which can then be passed to your WebsiteAgent.

**Comment by AngelPone** [comment]
Ok, thanks
