### ISSUE TITLE
Have extracted values but have no out event

### ISSUE THREAD

**Issue by lingllting** [huginn/huginn#2286]
![image](https://user-images.githubusercontent.com/12082650/39855530-d927ad50-545e-11e8-9524-f626150c22a2.png)

The agent can extract values, but its last event out is severval days ago. It worked well before, I don't know what's wrong with it now.

**Comment by dsander** [comment]
Did you configure `mode` to `on_change`? If that is the case the Agent will only emit events if the extracted values changed.

**Comment by lingllting** [comment]
@dsander Yes, I've configured the mode to on_change.
![image](https://user-images.githubusercontent.com/12082650/39974794-86e7cd20-575d-11e8-9800-e727b799606c.png)
It worked well before, but I have no idea what's wrong with it now.

**Comment by lingllting** [comment]
I get some errors as follows:
![image](https://user-images.githubusercontent.com/12082650/39974877-ed2d3192-575d-11e8-99a3-a6c5f63a9353.png)
Does it matter?

**Comment by dsander** [comment]
> It worked well before, but I have no idea what's wrong with it now.

You can try to copy the configuration to a new Agent, that way you can rule out problems with the duplicate detection.  


> Does it matter?

Yes, the EmailAgent can not connect to the SMTP server because the username or password are wrong.

**Comment by se7cn** [comment]
看下出错agent的Logs，就左边那一列菜单

没event 就是 采集为空 或者 出错了
