### ISSUE TITLE
No Output

### ISSUE THREAD

**Issue by p1956** [huginn/huginn#2289]
```
{
  "expected_update_period_in_days": "2",
  "url": "https://www.youtube.com/feed/subscriptions",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "title": {
      "xpath": "//*[@id=\"video-title\"]"
    },
    "description": {
      "xpath": "//*[@id=\"description-text\"]"
    },
    "url": {
      "xpath": "//*[@id=\"video-title\"]",
      "value": "@href"
    }
  },
  "headers": {
    "Cookie": "VISITOR_INFO1_LIVE=8njYBykFxsY; YSC=GqjzPac_Eno; LOGIN_INFO=AFmmF2swRQIhAPp2qikjJDOzSUvl*************************************************************************************************************************************************************************************sr67ecMYown1ynAsIw_vxLJqUi-8lNKQ.; HSID=An**aTsQ3_AbcnVdk; SSID=AaG0pwNyRNv**xkI; APISID=ylLxrSt9dI_j3cST/A**Mtb-sCxIXMAU49; SAPISID=Whfp**alN2EgOWlK/Ac4Gek3nYBmWXzJzR; PREF=al=zh-CN&f6=1&fms1=10000&fms2=10000&f1=50000000&f5=30&f4=4000000"
  }
}
```

**Comment by dsander** [comment]
That website is using a lot of Javascript to render you can use fulldom-server or https://phantomjscloud.com/ to do extraction based on the final page that has been generated by the javascript. Another option would the the Youtube API.

**Comment by p1956** [comment]
@dsander 
thanks！i tried iphone mobile page, but faild. Please help me

`{
  "expected_update_period_in_days": "2",
  "url": "https://www.youtube.com/feed/subscriptions",
  "type": "xml",
  "mode": "on_change",
  "extract": {
    "title": {
      "xpath": "//*[@id=\"koya_child_21\"]/div/div/div[1]/a"
    }
  },
  "headers": {
    "Cookie": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "host": "m.youtube.com",
    "user-agent": "Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_3_2 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8H7 Safari/6533.18.5"
  }
}`

ERROR：
```
Error when fetching url: too many redirects; last one to: https://www.youtube.com/feed/subscriptions?app=desktop
/app/vendor/bundle/ruby/2.5.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/follow_redirects.rb:82:in `block in perform_with_redirection
```

**Comment by dsander** [comment]
> Error when fetching url: too many redirects; last one to: https://www.youtube.com/feed/subscriptions?app=desktop

Google is redirecting your request to the normal version of the website. You might need to send more headers, Google chrome has a mobile simulator, maybe you can get those headers from the requests it is sending when the mobile emulation is enabled.

**Comment by p1956** [comment]
The problem is solved. thanks
