### ISSUE TITLE
How to extract the posted article？

### ISSUE THREAD

**Issue by sevenrad** [huginn/huginn#2292]
I want to save the pushed articles for screening classification and machine learning. What should I do? Thank you!

**Comment by lingllting** [comment]
哥们，你是想订阅指定公众号的推送文章吧。。

**Comment by sevenrad** [comment]
不是，我想把推送的文章保存下来作分类和机器学习，请问有什么方法吗？

**Comment by se7cn** [comment]
这个需求 听得一头雾水
