### ISSUE TITLE
Docker Image - How to configure SMTP?

### ISSUE THREAD

**Issue by RayPS** [huginn/huginn#2294]
I have the exactly same error with this issue #1767. No related information found for this case in Wiki. 
I am new to Huginn and Docker or even Linux, using the Docker image is much simpler installation to me. Where can i found and edit the .env file?

**Comment by dsander** [comment]
How are you starting the docker container, are you using the command line or docker-compose?

Either way every configuration option listed in [.env.example](https://github.com/huginn/huginn/blob/master/.env.example) can be passed to the docker container via environment variables.

We have some examples for the database configuration [here](https://github.com/huginn/huginn/blob/master/docker/single-process/README.md#usage) and [there](https://github.com/huginn/huginn/tree/master/docker/single-process#usage), the SMTP configuration variables can be passed the same way.

**Comment by RayPS** [comment]
Now i am using `--env-file` to pass those variables, then it brings another problem, the e-mail was not sent and there is empty logs in the logs page. P.S: I am using GunMail SMTP.

**Comment by RayPS** [comment]
Tried many times without any reconfiguration and finally got 1 of them sent!

I think that was MailGun's problem.
