### ISSUE TITLE
Baseurl support

### ISSUE THREAD

**Issue by McGriddle** [huginn/huginn#2301]
I haven't been able to find (and maybe it isn't a thing) any information about using huginn behind a reverse proxy like nginx configured with a baseurl/subfolder.

So starting huginn which listens on http://localhost:3000/huginn and nginx would proxy something like
 `https://www.example.com/huginn` to huginn . I know with nginx you can use rewrite and sub_filter to set this up, but that's not an ideal solution.

**Comment by dsander** [comment]
Sorry we don't have support to that. We tried it [here](https://github.com/huginn/huginn/issues/2040) but it turned out having baseurl support would require a lot of changes.
