### ISSUE TITLE
Pushbullet Agent

### ISSUE THREAD

**Issue by sfischer13** [huginn/huginn#2302]
In the Pushbullet agent, validation of options will fail if one uses a credential:

https://github.com/huginn/huginn/blob/af9193a2447b6fefaa468d90ad98ef14a231f8ee/app/models/agents/pushbullet_agent.rb#L61

**Comment by dsander** [comment]
When using a credential you would still need to put a liquid tag into the `api_key` options, right? That should not make the validation fail.

**Comment by sfischer13** [comment]
Thanks, now I understand! It's the first time I use credentials and I thought the agent simply expects a credential with the exact name `pushbullet_api_key`.
