### ISSUE TITLE
MqttAgent status

### ISSUE THREAD

**Issue by sfischer13** [huginn/huginn#2304]
The _working_ flag of my MQTT agent does not work properly.

The agent receives a message from another agent and then forwards/publishes the message to a MQTT server. I can confirm that the messages are received by the MQTT server.

Yet, no events are shown in the MQTT agent's event list. As a consequence, the `working?` method returns `false`.

https://github.com/huginn/huginn/blob/fba26e951a3e87902924b3f61aba1eabc364e599/app/models/agents/mqtt_agent.rb#L79-L81

If I understand correctly, an event should be created here:

https://github.com/huginn/huginn/blob/fba26e951a3e87902924b3f61aba1eabc364e599/app/models/agents/mqtt_agent.rb#L109-L115

How can I fix this? I'd send a pull request, but I am not familiar with Huginn's API.

**Comment by dsander** [comment]
> Yet, no events are shown in the MQTT agent's event list.

That is correct, the Agents Event list only contain the Events the Agent created itself.

, not the ones it received

> As a consequence, the working? method returns false.

Right, at the moment the working method is not checking if the Agent successfully received Events. This should fix it:

```ruby
    def working?
      (event_created_within?(interpolated['expected_update_period_in_days']) && !recent_error_logs?) || received_event_without_error?
    end
```

**Comment by sfischer13** [comment]
Thanks for the fast fix. Here is the pull request #2307 using your solution.
