### ISSUE TITLE
can not scrap url(website agent)

### ISSUE THREAD

**Issue by pes2017** [huginn/huginn#2306]
Any help would be appreciated.

{
  "expected_update_period_in_days": "2",
  "url": "http://pesdb.net/pes2018/",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "url": {
      "xpath": "//*[@id=\"content\"]/div[2]/table/tbody/tr[*]/td[2]/a",
      "value": "@href"
    }
  }
}

**Comment by dsander** [comment]
Are you trying to get the link to the player detail page? I find using css selectors easier than xpath:

```
{
  "expected_update_period_in_days": "2",
  "url": "http://pesdb.net/pes2018/",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "url": {
      "css": "table td:nth-child(2) a",
      "value": "@href"
    }
  }
}
```

**Comment by pes2017** [comment]
that's awesome.
@dsander ,thank you very much.
