### ISSUE TITLE
<pubDate> zone change?

### ISSUE THREAD

**Issue by xiaoweb** [huginn/huginn#2308]
Hey:
How does my data output <pubDate> time zone change? It is always -0700;
Does not match the time of the crawled site.

**Comment by dsander** [comment]
I believe the timezone used in the DataOutputAgent is always the one configured in `TIMEZONE` via the `.env` file or the environment variables when using docker container. Why do you need to timezone to match the crawled site?

**Comment by xiaoweb** [comment]
I changed the system time zone in the docker container to +0800 and restarted the docker container, but it's strange that the huginn still outputs the pubDate time zone to be -0700, which is very puzzling.

**Comment by xiaoweb** [comment]
Since the websites I searched and the websites I analyze are in China, due to errors in the time zone, resulting in a future pubDate time

**Comment by xiaoweb** [comment]
When I run docker

-e HUGINN_TIMEZONE=Beijing

Time zone is normal, thank you very much!
