### ISSUE TITLE
how to use random credential 

### ISSUE THREAD

**Issue by Howard-guo** [huginn/huginn#2311]
i have 3 token and save them as credentials,names "c1","c2" and "c3", i wanna use them random.
like this:
http://somesite/withtoken/{% credential c? %}.....

thanks for help

**Comment by knu** [comment]
There's room for improvement of Huginn/Liquid here; Liquid does not have a random number generator and Huginn's credential tag only takes a bare key name.

For the first matter, I think you could use a millisecond value to get a pseudo random number.  For the second matter, I'm afraid there's no way to obtain a credential value with a dynamically composed key name; you'll have to write a lengthy conditional:
```
{% assign n = "now" | date: "%L" | modulo: 3 | plus: 1 -%}
http://somesite/withtoken/
{%- case n -%}
{%- when 1 -%}
{%- credential c1 -%}
{%- when 2 -%}
{%- credential c2 -%}
{%- when 3 -%}
{%- credential c3 -%}
{%- endcase -%}
......
```

**Comment by Howard-guo** [comment]
@knu thanks a lot for your help.
what's the meaning about symbol '-' near '%' ?

i'm sorry for that i can't write english so well.
