### ISSUE TITLE
How to use “expected update period in days” and check the Working status

### ISSUE THREAD

**Issue by 7x11** [huginn/huginn#2312]
when i set  

> agent_1 
> `expected update period in days  = 2 `
> that mean is 
>  if  did't creat any event in 48hours（2d）.
> agent_1  will change Working  `yes` to `no`

is that right？

btw. i have too many agents. 
is there any agent types  can check  other agents‘s `Working status`?

e.g.
if anget_1.anget_2.anget_3.anget_N  `Working` is  change to `No` or `yes`.
creat one event .  
i will check that and fix is

**Comment by dsander** [comment]
> is that right？

Yes that is correct, some Agents have other conditions in their working check as well.



> is there any agent types can check other agents‘s Working status?

No we don't have a Agent that can do that at the moment.
