### ISSUE TITLE
How to run Huginn behind a proxy

### ISSUE THREAD

**Issue by IAMEVANHE** [huginn/huginn#2314]
I could configure my local server with Ubuntu 16.04 to run behind a system-wide proxy. In other words, if I run "curl ipinfo.io/ip", it returns my proxy server's public IP, not my public IP from my ISP. 

But, when I run a Website Agent from Huginn, it could somehow bypass my system-wide proxy. I could confirm this by using a Website Agent to fetch, for example, "http://ipinfo.io/ip".

Any way that I can run Huginn behind a proxy?

**Comment by dsander** [comment]
Setting the `HTTP_PROXY` variable in your `.env` file should enforce all connection are going through that proxy.

**Comment by IAMEVANHE** [comment]
Many thanks! This works!

**Comment by LeonLuchs** [comment]
Is there a way to make it easier? For example instead of re-exporting the .env just to put a http_proxy to the website-agent (similar to user_agent)? Thanks.

**Comment by SwarShah** [comment]
Add `http_proxy` instead of `HTTP_PROXY`. The `HTTP_PROXY` seems to be ignored by `typhoeus` which is the default `FARADAY_HTTP_BACKEND` in huginn.

**Comment by gingerbeardman** [comment]
Can we set proxy at an agent level? I'd like to only use the proxy with certain agents. (Yahoo Japan, who today blocked access to UK & Europe)

**Comment by virtadpt** [comment]
I don't know, I've never tried.  The only thing that comes to mind I'm afraid is using a Shell Agent calling wget or curl with the appropriate command line switches.

**Comment by gingerbeardman** [comment]
I read in another issue that you can simply use "proxy" key on the WebAgent, it works.
