### ISSUE TITLE
Website agent works only in edit mode

### ISSUE THREAD

**Issue by somepaulo** [huginn/huginn#2316]
Hello!
I have a Website Agent (on a Heroku (free account) deploy of Huginn) that has been running just fine for almost two years now. It's parsing a regular FeedBurner XML feed. A couple of weeks ago the agent stopped working. When I do a dry run from the Agents tab of Huginn, I get a log output with no errors, the correct amount of instances for each data point, but not events. No error messages appear at all in the dry run log. Curiously, when I do a dry run from within the Edit screen of this particular Website Agent, I get a perfect set of 15 events in the output. But that's only in the Dry Run and only in the Edit screen. A regular run, as well as a dry run from the Agents tab produces no events. And the Agent is marked as not working. Other Website Agents on this deploy work just fine. I have 12 of them, and some parse much more data than this particular one.
What could be wrong?

**Comment by dsander** [comment]
Hi @somepaulo,

probably the background workers crashed. Did you try to restart the application on Heroku?

**Comment by somepaulo** [comment]
Hi @dsander,
Yes, I've updated Huginn to the latest version and restarted my app (both from the Heroku dashboard and from console). No luck. Out of 14 Website Agents this is the only one that fails. Dry runs work fine in the Edit Agent screen, but fail elsewhere, as well as live runs.
Since all data points are captured correctly, the only thing that fails is combining 15 sets of 4 correctly fetched data points into 15 events.

**Comment by somepaulo** [comment]
It gets weirder.
I cloned the agent, saved it with no changes, and the clone works just fine.

So for the immediate purpose of my grief, this issue can be closed, but for the sake of anybody else experiencing the same problem, is there a way of pinpointing its source?
Could this be a DB glitch? I did save and re-save the Agent several times in the process though. The problem appeared out of the blue. I updated Huginn after that, hoping to fix it. It's still there and only affects one Agent while its clone works fine.

**Comment by dsander** [comment]
Are you using the `on_change` mode for the Agent? If that is the case it will not emit any events if the extracted values did not change since it was last run, that would also explain why it works when you clone the Agent.

**Comment by somepaulo** [comment]
Yes, I'm using `on_change`. I did check existing events in the faulty Agent, and only 10 of 15 matched. So there were 5 new events in the current RSS feed being fetched.
After your reply I deleted all events from the Agent and now it works again.
Will keep in mind deleting all events from faulty Agents in the future before opening a new issue.
Thank you for your help!
