### ISSUE TITLE
agent can't extract  any information, and I ensure that the xpath syntax is correct.

### ISSUE THREAD

**Issue by nageshuizeii** [huginn/huginn#2318]
![image](https://user-images.githubusercontent.com/16527235/41654596-82c376c8-74bc-11e8-9ea5-9dad542767cb.png)
the url is :http://law.scu.edu.cn/speedcmsol/

**Comment by dsander** [comment]
Can you share the JSON representation of the Agent options? The screenshot is cutting some of them off. Click on "toggle view" and copy & paste the text here.

**Comment by nageshuizeii** [comment]
{
  "expected_update_period_in_days": "2",
  "url": "http://law.scu.edu.cn/speedcmsol/",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "url": {
      "xpath": "//*[@class='leftbox']//li/a/@href",
      "value": "."
    },
    "title": {
      "xpath": "//*[@class='leftbox']//li/a",
      "value": "normalize-space(.)"
    },
    "date": {
      "xpath": "//*[@class='leftbox']//li/span",
      "value": "normalize-space(.)"
    }
  }
}

**Comment by dsander** [comment]
The Website is using JavaScript to generate the content. Huginn itself is not able to scrape pages build via Javascript, but you can use [fulldom-server](https://github.com/strugee/fulldom-server) or https://phantomjscloud.com/ to do extraction based on the final page that has been generated by the JavaScript.

**Comment by irfancharania** [comment]
Both ways are provided in the wiki: 
https://github.com/huginn/huginn/wiki/Browser-Emulation-Using-PhantomJs-Cloud
https://github.com/huginn/huginn/wiki/Browser-Emulation-using-fulldom-server

**Comment by nageshuizeii** [comment]
How do I pass http://gs.scu.edu.cn/ to the second agent, the rss agent can't pass the change link, only the link like .atom/.feed can be passed.

**Comment by dsander** [comment]
Do you mean the `PhantomJsCloudAgent`? If the url is static you can put it in the `url` option directly.

**Comment by nageshuizeii** [comment]
{
  "schema_version": 1,
  "name": "PhantomJs Cloud Demo",
  "description": "Example usage with PhantomJs Cloud (https://phantomjscloud.com/).\r\nYou'll need to sign up and get an API key for this to work.",
  "source_url": false,
  "guid": "32329783da28399392645cff5a14ab9f",
  "tag_fg_color": "#ffffff",
  "tag_bg_color": "#5bc0de",
  "icon": null,
  "exported_at": "2018-07-31T16:39:13Z",
  "agents": [
    {
      "type": "Agents::DataOutputAgent",
      "name": "PhantomJS Cloud - Out - RSS",
      "disabled": false,
      "guid": "37094003a5077e78ec3114a475d2382c",
      "options": {
        "secrets": [
          "phantom"
        ],
        "expected_receive_period_in_days": 2,
        "template": {
          "title": "scu info",
          "description": "This is a feed of recent XKCD comics, generated by Huginn",
          "item": {
            "title": "{{title}}",
            "url": "{{url}}"
          }
        }
      },
      "propagate_immediately": false
    },
    {
      "type": "Agents::WebsiteAgent",
      "name": "PhantomJS Cloud - Process - Fetch Page",
      "disabled": false,
      "guid": "3bc94a9d728abd43439c797518089513",
      "options": {
        "expected_update_period_in_days": "2",
        "url_from_event": "https://PhantomJsCloud.com/api/browser/v2/{%credential phantomjs_cloud%}/?request={{url}}",
        "type": "html",
        "mode": "on_change",
        "extract": {
          "title": {
            "xpath": "//*[@id=\"form1\"]/div[6]/div[2]/div[1]/div[2]/div/div[1]/a",
            "value": "normalize-space(.)"
          },
          "url": {
            "xpath": "//*[@id=\"form1\"]/div[6]/div[2]/div[1]/div[2]/div/div[1]/a/@href",
            "value": "."
          }
        }
      },
      "schedule": "every_1d",
      "keep_events_for": 3600,
      "propagate_immediately": true
    },
    {
      "type": "Agents::EventFormattingAgent",
      "name": "PhantomJS Cloud - Process - Format",
      "disabled": false,
      "guid": "3d0bed6bac1892bea2f8e440e44c58b8",
      "options": {
        "instructions": {
          "message": {
            "url": "http://gs.scu.edu.cn/",
            "renderType": "html",
            "requestSettings": {
              "userAgent": "Mozilla/5.0 (BlackBerry; U; BlackBerry 9900; en) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.1.0.346 Mobile Safari/534.11+"
            }
          }
        },
        "mode": "clean"
      },
      "keep_events_for": 3600,
      "propagate_immediately": true
    },
    {
      "type": "Agents::JavaScriptAgent",
      "name": "PhantomJS Cloud - Process - JS Escape",
      "disabled": false,
      "guid": "e22d083a6fa306ac83692095a11221ce",
      "options": {
        "language": "JavaScript",
        "code": "Agent.receive = function() {\r\n  var events = this.incomingEvents();\r\n  for(var i = 0; i < events.length; i++) {\r\n    var js = JSON.stringify(events[i].payload.message);\r\n    this.log('Message to escape: ' + js);\r\n    this.createEvent({ 'url': encodeURIComponent(js) });\r\n    var callCount = this.memory('callCount') || 0;\r\n    this.memory('callCount', callCount + 1);\r\n  }\r\n}",
        "expected_receive_period_in_days": "2",
        "expected_update_period_in_days": "2"
      },
      "schedule": "never",
      "keep_events_for": 3600,
      "propagate_immediately": true
    }
  ],
  "links": [
    {
      "source": 1,
      "receiver": 0
    },
    {
      "source": 2,
      "receiver": 3
    },
    {
      "source": 3,
      "receiver": 1
    }
  ],
  "control_links": [

  ]
}

**Comment by nageshuizeii** [comment]
can't work

**Comment by dsander** [comment]
What does not work? I don't have a PhantomJS Clound account.

**Comment by irfancharania** [comment]
http://gs.scu.edu.cn/ brings up an authentication page where you have to click the link...?

**Comment by nageshuizeii** [comment]
yes! So can I solve this situation with the Scenarios?
