### ISSUE TITLE
Apache configuration problems

### ISSUE THREAD

**Issue by NJBirth** [huginn/huginn#2322]
I recently tried to install huginn on my Ubuntu 16.04 server. I followed the [installation guide](https://github.com/huginn/huginn/blob/master/doc/manual/installation.md) up to chapter 6. Huginn itself is working correctly. However, when I want to use the suggested [Apache configuration](https://github.com/huginn/huginn/wiki/Apache-Huginn-configuration), I get the error `Job for apache2.service failed because the control process exited with error code. See "systemctl status apache2.service" and "journalctl -xe" for details.` when I try to restart Apache. I use Apache/2.4.18 (Ubuntu), I followed all instructions on the Apache wiki page including the change in config/unicorn.rb and the adaptions for Apache 2.4.

This is the output of `systemctl status apache2.service`:

```
* apache2.service - LSB: Apache2 web server
   Loaded: loaded (/etc/init.d/apache2; bad; vendor preset: enabled)
  Drop-In: /lib/systemd/system/apache2.service.d
           `-apache2-systemd.conf
   Active: failed (Result: exit-code) since Fri 2018-06-22 14:50:17 CEST; 3min 40s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 15282 ExecStop=/etc/init.d/apache2 stop (code=exited, status=0/SUCCESS)
  Process: 12018 ExecReload=/etc/init.d/apache2 reload (code=exited, status=0/SUCCESS)
  Process: 15305 ExecStart=/etc/init.d/apache2 start (code=exited, status=1/FAILURE)
```

  
I also tried to build my own configuration. This was my attempt:

```
<VirtualHost *:80>
   ServerName huginn.<domain>
   RedirectPermanent / https://huginn<.domain>/
</VirtualHost>

<VirtualHost *:443>
   ProxyPreserveHost On
   ProxyRequests Off
   ServerName huginn.<domain>
   ProxyPass / http://localhost:3000/
   ProxyPassReverse / http://localhost:3000/
   DocumentRoot </path/to/huginn/public>

   SSLEngine On
   SSLCertificateFile <path>
   SSLCertificateKeyFile <path>
</VirtualHost>
```

This is working partially. I can access huginn, but it looks like this:

![81f80cb9-ae21-42f3-820e-f11b9d6af2b4](https://user-images.githubusercontent.com/26522961/41777928-495e8d10-762d-11e8-9d47-bd47eda4d881.jpg)

I compiled the assets with `sudo -u huginn -H bundle exec rake assets:precompile RAILS_ENV=production` before, so this is probably not the problem.
These are the errors that are shown in the console:

![a1e404ec-80bf-4daf-a60b-4baad0bac446](https://user-images.githubusercontent.com/26522961/41777980-73fb7448-762d-11e8-8c70-e58816ca93a0.jpg)

Do you have any suggestions how I can solve these problems?

**Comment by dsander** [comment]
I don't know anything about configuring Apache, but the problem you are seeing is caused by the static files not being served properly.
The configuration example in the wiki has a `Directory` directive for the directory, maybe that is needed as well?

**Comment by NJBirth** [comment]
Thank you for your answer. I'm also not an Apache expert myself, but after a lot of websearching and trial and error I finally got it to work.

I also tried to figure out why the configuration from the wiki isn't working. It seems that the problem lies somewhere in this loadbalancer thing, but I couldn't find out where exactly.

This is my configuration (I'm not sure, what the line `RequestHeader set X_FORWARDED_PROTO https` does, but without it I get an error when I try to login):

```
<VirtualHost *:80>
  ServerName huginn.example.com
  RedirectPermanent / https://huginn.example.com/
</VirtualHost>

<VirtualHost *:443>
  ServerName huginn.example.com
  DocumentRoot /path/to/huginn/public

  RequestHeader set X_FORWARDED_PROTO https

  ProxyPreserveHost On
  ProxyRequests Off
  ProxyPass /assets !
  ProxyPassMatch "^/(.*\.(png|ico))$" !
  ProxyPass / http://localhost:3000/
  ProxyPassReverse / http://localhost:3000/

  <Directory "/path/to/huginn/public">
    Require all granted
  </Directory>

  SSLEngine On
  SSLCertificateFile /path/to/cert
  SSLCertificateKeyFile /path/to/private_key
</VirtualHost>
```

Do you think it could be useful to link this issue on the [Apache wiki page](https://github.com/huginn/huginn/wiki/Apache-Huginn-configuration), just in case someone else gets this problem (I'm still not sure if the suggested configuration just doesn't work for me or if it is broken in general)?

**Comment by dsander** [comment]
Nice! We have the same header in the [nginx configuration](https://github.com/huginn/huginn/blob/master/deployment/nginx/huginn-ssl#L100) it is used to tell the rails application that the client connected via HTTPS to the load balancer, otherwise all internal links would redirect to HTTP.

> Do you think it could be useful to link this issue on the Apache wiki page, just in case someone else gets this problem (I'm still not sure if the suggested configuration just doesn't work for me or if it is broken in general)?

That would be great, if you are certain the current configuration in the Wiki does not work anymore feel free to replace it with your version.

**Comment by NJBirth** [comment]
> That would be great, if you are certain the current configuration in the Wiki does not work anymore feel free to replace it with your version.  

As I said, I'm not completely sure about it, so I just added a note and a link to this issue below the wiki configuration and let the rest of the page unchanged. I hope this is okay this way.

**Comment by dsander** [comment]
Sounds good to me, thank you!

**Comment by NJBirth** [comment]
Great. Then all my questions regarding this topic are answered for the moment. Thank you for your help.

**Comment by infominer33** [comment]
I've been fighting with the apache config for a few days and finally got it working. so I want to leave a note here for anyone else who may be trying to follow along.. 

ultimately my problem had something to do with using certbot (`sudo certbot --apache -d huginn.bitcoinfo.xyz -d www.huginn.bitcoinfo.xyz`) which makes its own separate config file for ssl.. it worked perfectly for the last site I was setting up... but after feeding above configurations it made a conflicting config with endless re-directs.

Basically I just copied over relevant rules for accessing from the outside into the ssl config

so now I've got one confg file  (`/etc/apache2/sites-available/huginn.bitcoinfo.xyz.conf`) looking like so: 
``` 
<VirtualHost *:80>
   ServerName huginn.bitcoinfo.xyz
   ServerAlias www.huginn.bitcoinfo.xyz
   RedirectPermanent / https://huginn.bitcoinfo.xyz/
</VirtualHost>

RewriteEngine on
RewriteCond %{SERVER_NAME} =www.huginn.bitcoinfo.xyz [OR]
RewriteCond %{SERVER_NAME} =huginn.bitcoinfo.xyz [OR]
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
```

And another for ssl (`/etc/apache2/sites-available/reader.bitcoinfo.xyz-le-ssl.conf`), looking like so:
```
<IfModule mod_ssl.c>
<VirtualHost *:443>
  ServerName huginn.bitcoinfo.xyz
  ServerAlias www.huginn.bitcoinfo.xyz
  DocumentRoot /var/www/huginn.bitcoinfo.xyz/public

  RequestHeader set X_FORWARDED_PROTO https

  ProxyPreserveHost On
  ProxyRequests Off
  ProxyPass /assets !
  ProxyPassMatch "^/(.*\.(png|ico))$" !
  ProxyPass / http://localhost:3000/
  ProxyPassReverse / http://localhost:3000/

  <Directory /var/www/huginn.bitcoinfo.xyz/public>
    Require all granted
  </Directory>

  SSLEngine On
  Include /etc/letsencrypt/options-ssl-apache.conf
  SSLCertificateFile /etc/letsencrypt/live/huginn.bitcoinfo.xyz/fullchain.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/huginn.bitcoinfo.xyz/privkey.pem

</VirtualHost>
</IfModule>
```

Thanks!

**Comment by NJBirth** [comment]
>ultimately my problem had something to do with using certbot (sudo certbot --apache -d huginn.bitcoinfo.xyz -d www.huginn.bitcoinfo.xyz) which makes its own separate config file for ssl.. it worked perfectly for the last site I was setting up... but after feeding above configurations it made a conflicting config with endless re-directs.

I think you can also use the certonly-Option of certbot to get a certificate without changing the configuration of the webserver. Then you don't have the problem with the conflicting config file.
