### ISSUE TITLE
got a install gems problem 

### ISSUE THREAD

**Issue by F1sh-Yu** [huginn/huginn#2330]
i try to install gems and type 

> sudo -u huginn -H bundle install --deployment --without development test

and it turns out 

> There was an error while trying to write to '/home/huginn/huginn/.bundle/config'. It is likely that you need to grant permissions for that path.

why does it say i have no permissions cause i was using the root

**Comment by dsander** [comment]
Hi,

the command is executing `bundle install` as the `huginn` user, you probably ran one of the command above as root. Try `sudo chown -R huginn:huginn /home/huginn` and then run `sudo -u huginn -H bundle install --deployment --without development test` again.

**Comment by F1sh-Yu** [comment]
thanks,
@dsander 
I've worked this problem out, and installed huginn .
but ultimately when I visit my IP it shows "502 Bad Gateway"
so I tried 

> sudo bundle exec rake production:check
and it shows 

> [  OK  ] Everything is fine
the i want to check the log 

> /var/log/nginx/huginn_error.log
it told me 

> -bash: /var/log/nginx/huginn_error.log: Permission denied
By the way, how can I find the FQDN ? I don't fully understand it so I just typed huginn.example.com like the comment . Am I wrong ?
Really sorry to bother you.

**Comment by dsander** [comment]
> -bash: /var/log/nginx/huginn_error.log: Permission denied

You can use either `cat` or `tail` to get the contents of the logs, some of them need to be accessed as root: `sudo cat /var/log/nginx/huginn_error.log`.

Did you modify the [`Procfile`](https://github.com/huginn/huginn/blob/master/doc/manual/installation.md#install-init-script)?

FQDN stand for "full qualified domain name", it is the domain/url your server is using. If you don't have one you can also use the IP if the server.

**Comment by F1sh-Yu** [comment]
OK I checked my huginn_error.log and it told me there is no such file.
then `sudo ls -al /home/huginn/huginn/tmp/sockets/unicorn.socket`and it shows 

> ls: cannot access /home/huginn/huginn/tmp/sockets/unicorn.socket: No such file or directory

so it seems the unicorn configuration is not set up correctly. But the only thing I did is to change the worker_process from 2 to 1,what else should I do?

**Comment by F1sh-Yu** [comment]
Good news ,
I've installed huginn with docker ! It's way easier!
Still, so thankful for your nice answers.

**Comment by dsander** [comment]
Great! And yes the docker setup is a lot easier 😄

**Comment by sfischer13** [comment]
Sorry for jumping in ...
How does  the docker setup deal with updates?

**Comment by dsander** [comment]
@sfischer13 You pull the updated image from docker hub, stop and delete the old container and recreate it based on the new image.

**Comment by sfischer13** [comment]
Thanks, so data should not be stored in the container.
One more question (the [Environment Variables](https://hub.docker.com/r/huginn/huginn/) section is really hard to read). Can I pass all variables from `.env` to the docker container by prefixing them with `HUGINN_`?

**Comment by dsander** [comment]
> Thanks, so data should not be stored in the container.

Exactly, for a setup on a server I would recommend linking the Huginn container to a mysql or postgres conatiner and store their data in a docker volume.

> One more question (the Environment Variables section is really hard to read).

You are right that documentation is a bit dated. In fact you can use every `.env` variable without prefixing them. The `huginn/huginn` started with prefixes but we allowed using the `.env` without prefixes some time ago.
