### ISSUE TITLE
Whether some value should only be extracted by cookie？And how to get the cookie by PostAgent?

### ISSUE THREAD

**Issue by tortoo** [huginn/huginn#2331]
I got a strange thing when parsing this [site](https://buluo.qq.com/p/detail.html?bid=10247&pid=1112558-1528855165_10247_). Before log-inning I couldn't get the value `enc_uin ` on the comment part but it could be got on the article part and other values on the comment part were also well caught. After log-inning I got another new value `uin` by using cookie.

comment part:
```{
  "expected_update_period_in_days": "2",
  "url": "https://buluo.qq.com/cgi-bin/bar/post/get_comment_by_page_v2?bid=10247&pid=1112558-1528855165_10247_&num=10&start=0",
  "type": "json",
  "mode": "on_change",
  "extract": {
    "user": {
      "path": "$.result.comments[*].user.nick_name"
    },
    "gender": {
      "path": "$.result.comments[*].user.gender"
    },
    "enc_uin": {
      "path": "$.result.comments[*].user.enc_uin"
    }
  },
  "headers": {
    "referer": "https://buluo.qq.com/p/detail.html?bid=10247&pid=1112558-1528855165_10247_"
  }
}
```
result:
```[00:00:00] INFO -- : Dry Run started
[00:00:00] INFO -- : Fetching https://buluo.qq.com/cgi-bin/bar/post/get_comment_by_page_v2?bid=10247&pid=1112558-1528855165_10247_&num=10&start=0
[00:00:01] INFO -- : Extracting json at $.result.comments[*].user.nick_name
[00:00:01] INFO -- : Values extracted: ["还有谁！！！", "还有谁！！！", "千寻", "垃圾", "垃圾", "垃圾", "千寻", "如初🌸", "如初🌸", "夜雨声烦"]
[00:00:01] INFO -- : Extracting json at $.result.comments[*].user.gender
[00:00:01] INFO -- : Values extracted: [1, 1, 255, 2, 2, 2, 255, 2, 2, 2]
[00:00:01] INFO -- : Extracting json at $.result.comments[*].user.enc_uin
[00:00:01] INFO -- : Values extracted: []
[00:00:01] ERROR -- : Error when fetching url: Got an uneven number of matches for : {"user"=>{"path"=>"$.result.comments[*].user.nick_name"}, "gender"=>{"path"=>"$.result.comments[*].user.gender"}, "enc_uin"=>{"path"=>"$.result.comments[*].user.enc_uin"}}
```
article part:

```{
  "expected_update_period_in_days": "2",
  "url": "https://buluo.qq.com/cgi-bin/bar/post/content?bid=10247&pid=1112558-1528855165_10247_",
  "type": "json",
  "mode": "on_change",
  "extract": {
    "enc_uin": {
      "path": "$.result.user_info.enc_uin"
    }
  },
  "headers": {
    "referer": "https://buluo.qq.com/p/detail.html?bid=10247&pid=1112558-1528855165_10247_"
  }
}
```
result:

```
[
  {
    "enc_uin": "8FT2Rpo3ZKZk6ZwoEqtbSA"
  }
]
```

By using cookie:
```
{
  "expected_update_period_in_days": "2",
  "url": "https://buluo.qq.com/cgi-bin/bar/post/get_comment_by_page_v2?bid=10247&pid=1112558-1528855165_10247_&num=10&start=0",
  "type": "json",
  "mode": "on_change",
  "extract": {
    "uin": {
      "path": "$.result.comments[*].user.uin"
    },
    "enc_uin": {
      "path": "$.result.comments[*].enc_uin"
    }
  },
  "headers": {
    "referer": "https://buluo.qq.com/p/detail.html?bid=144106&pid=5794662-1516500479",
    "cookie": "{% credential Q-login cookie %}"
  }
}
```

result:
```
[00:00:00] INFO -- : Dry Run started
[00:00:00] INFO -- : Fetching https://buluo.qq.com/cgi-bin/bar/post/get_comment_by_page_v2?bid=10247&pid=1112558-1528855165_10247_&num=10&start=0
[00:00:01] INFO -- : Extracting json at $.result.comments[*].user.uin
[00:00:01] INFO -- : Values extracted: [2102980263, 2102980263, 1581112400, 3205752411, 3205752411, 3205752411, 1581112400, 3354429359, 3354429359, 1960106343]
[00:00:01] INFO -- : Extracting json at $.result.comments[*].enc_uin
[00:00:01] INFO -- : Values extracted: []
[00:00:01] ERROR -- : Error when fetching url: Got an uneven number of matches for : {"uin"=>{"path"=>"$.result.comments[*].user.uin"}, "enc_uin"=>{"path"=>"$.result.comments[*].enc_uin"}}
```

But the cookie was copied from the page of chrome develop tool after I loginned in😹. I can't get the cookie by PostAgent. 

```
{
  "post_url": "https://ui.ptlogin2.qq.com/cgi-bin/login?style=9&appid=1006102&daid=371&s_url=https%3A%2F%2Fbuluo.qq.com%2Fmobile%2Fbarindex.html%3F_wv%3D1027%26_bid%3D128%26from%3Dpc%26bid%3D10247&low_login=0&hln_css=https%3A%2F%2Fpub.idqqimg.com%2Fqqun%2Fxiaoqu%2Fmobile%2Fimg%2Flogin-logo.png",
  "expected_receive_period_in_days": "1",
  "content_type": "form",
  "method": "post",
  "payload": {
    "username": "{% credential Q-user %}",
    "password": "{% credential Q-pass %}"
  },
  "headers": {
    "Cookie": "{{cookie}}"
  },
  "emit_events": "true",
  "no_merge": "false",
  "output_mode": "clean",
  "disable_redirect_follow": "true",
  "user_agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1"
}
```

result:
```
  {
    "body": "",
    "headers": {
      "Date": "Tue, 10 Jul 2018 14:12:07 GMT",
      "Content-Type": "text/html",
      "Content-Length": "0",
      "Connection": "keep-alive",
      "Server": "QZHTTP-2.38.41",
      "Strict-Transport-Security": "max-age=0"
    },
    "status": 501
  }
```

 If I change the method to `get` it outputs the following, but it's different from the one I copied after log-inning and is useless to get the `uin`.

```
 "headers": {
      "Date": "Tue, 10 Jul 2018 14:12:36 GMT",
      "Content-Type": "text/html",
      "Content-Length": 17751,
      "Connection": "keep-alive",
      "Server": "QZHTTP-2.38.41",
      "P3p": "CP=\"CAO PSA OUR\"",
      "Cache-Control": "max-age=86400",
      "Set-Cookie": "pt_user_id=1795827860676532641; EXPIRES=Fri, 07-Jul-2028 14:12:37 GMT; PATH=/; DOMAIN=ui.ptlogin2.qq.com;, pt_login_sig=wUlgTn3fxJGbOYUb69Rar7IvZ0TkFBjiuLPivsPiYiJUG84LlHVNBB9wE3vhU7JD; PATH=/; DOMAIN=ptlogin2.qq.com;, pt_clientip=f65a3692e0997d30; PATH=/; DOMAIN=ptlogin2.qq.com;, pt_serverip=3fe10af17164f9b9; PATH=/; DOMAIN=ptlogin2.qq.com;, login_param=appid%3D1006102%26daid%3D371%26hln_css%3Dhttps%253A%252F%252Fpub.idqqimg.com%252Fqqun%252Fxiaoqu%252Fmobile%252Fimg%252Flogin-logo.png%26low_login%3D0%26password%3D7259070tuqq%26s_url%3Dhttps%253A%252F%252Fbuluo.qq.com%252Fmobile%252Fbarindex.html%253F_wv%253D1027%2526_bid%253D128%2526from%253Dpc%2526bid%253D10247%26style%3D9%26username%3D3339857065; PATH=/; DOMAIN=ui.ptlogin2.qq.com;, uikey=eaf42e2d594c8d54b357af3a4833dfbf7f07e42791b40f6b37c016054f4e37f5; PATH=/; DOMAIN=ptlogin2.qq.com;, ptui_identifier=000DF39348B3DBA5DCAB47B46F95FA0C8418C7FB656010BD5823BE3D; PATH=/; DOMAIN=ui.ptlogin2.qq.com;",
      "Last-Modified": "Thu, 08 Mar 2012 02:04:00 GMT",
      "Strict-Transport-Security": "max-age=0"
    },
    "status": 200
```

In fact what I want is to get the unique ID such as `enc_uin` or `uin`. Currently I can't get either of them.

My first question is how can I extract the `enc_uin` if there is no cookie. If it's impossible the only way is to get the cookie by PostAgent to extract the `uin` . But I failed😔. By the way, I find someone solved this by PhantomJs on [the site](https://www.cnblogs.com/imxiu/p/6023930.html) but how to achieve this by huginn?

**Comment by dsander** [comment]
> comment part:
> 
>   "expected_update_period_in_days": "2",
>   "url": "https://buluo.qq.com/cgi-bin/bar/post/get_comment_by_page_v2?bid=10247&pid=1112558-1528855165_10247_&num=10&start=0",
> ....
> 
> result:

The JSON the server is responding with is not including the value you are looking for try using `$.result.comments` as the path (and the only extraction option to avoid the "uneven amount of matches error") to get everything in that JSON array.

> "status": 501

HTTP status 501 most likely means something went wrong with your request.



> If I change the method to get it outputs the following, but it's different from the one I copied after log-inning and is useless to get the uin.

The cookie you get on different systems will never be the same, so that is normal 😄 



> By the way, I find someone solved this by PhantomJs on the site but how to achieve this by huginn?

Maybe https://phantomjscloud.com/ will work. If the site is requiring JavaScript to log in.

**Comment by tortoo** [comment]
@dsander Ha，so nice to see u again!😸

> The JSON the server is responding with is not including the value you are looking for try using $.result.comments as the path (and the only extraction option to avoid the "uneven amount of matches error") to get everything in that JSON array.

I tried `$.result.comments`but the output value of `uin` was always `0` and had no `enc_uin` key even I could see it on the page of chrome develop tool. Only after log-inning in and using cookie the key `uin` had the right output. I just applied another [QQ account](1041428077.pass.is.test_test) for you and please help me to have a look at that👻. If login needs verification code I'll send you here.
```
{
        "replay": 0,
        "index": 1,
        "op": 0,
        "liketotal": 0,
        "ispostor": 0,
        "uin": 0,
        "pid": "1112558-1528855165_10247_",
        "tlist_index": 1,
        "like": 0,
        "cid": "2980473-1528884829",
        "time": 1528884829,
        "isdel": 0,
        "postsrc": 1,
        "is_black": 0
}
```
![image](https://user-images.githubusercontent.com/28673736/42565789-064f852e-8537-11e8-9b1a-0dffe4ce5301.png)

> Maybe https://phantomjscloud.com/ will work. If the site is requiring JavaScript to log in.

From now on what I konw about phantomjscloud is to make the page static state to get the content but how to get cookie by that? [This site](https://www.cnblogs.com/imxiu/p/6023930.html) has the code which have got the cookie by phantomjs. If phantomjscloud can't get the cookie how to get it by huginn with those codes?

**Comment by dsander** [comment]
I am not sure if the login can be automated with Huginn, it seems to be doing a couple of requests, which seem to be trigged from Javascript.

After I got the cookie requesting the JSON worked.

```
{
  "expected_update_period_in_days": "2",
  "url": "https://buluo.qq.com/cgi-bin/bar/post/get_comment_by_page_v3?bid=10247&pid=1759938-1530848707_10247_&num=20&start=0&barlevel=1&r=0.29110315122991737&bkn=589647426",
  "type": "json",
  "mode": "on_change",
  "extract": {
    "user": {
      "path": "$.result.comments[*].user.nick_name"
    },
    "gender": {
      "path": "$.result.comments[*].user.gender"
    },
    "enc_uin": {
      "path": "$.result.comments[*].user.enc_uin"
    }
  },
  "headers": {
    "referer": "https://buluo.qq.com/p/detail.html?bid=10247&pid=1759938-1530848707_10247_",
    "cookie": "pgv_pvi=4567318528; pgv_si=s4156928000; ptisp=os; pt2gguin=o1041428077; RK=dJJdIq1kbS; ptcz=598c663c909548010cc97a085b19a4983802208d25d72411724fb30288b78d99; enc_uin=9qUrVQdjUiIgl3NM4uBaNg; uin=o1041428077; skey=@792PRBo2v; p_uin=o1041428077; pt4_token=froTGuFqfzDxnFBYF9a4yRdhVMZ8PC1-nKZ35jTGTO8_; p_skey=R*rBtZKgBHSfcIhpbiw50qqNmt3r980GJuMUCVOd1YA_"
  }
}
```

I copied the "cookie" header from the chrome development tools.

**Comment by tortoo** [comment]
Copying and pasting the cookie is a feasible way to fetch the `uin` value but the cookie has a time limit. Almost one or two days later when the cookie becomes invalid all of the `uin` value will return to `0`. You can test and verify it  tomorrow or later😹. So getting the fresh cookie with huginn maybe slove the problem but I don't know how.

**Comment by dsander** [comment]
> So getting the fresh cookie with huginn maybe slove the problem but I don't know how.

The problem with that is that they are using JavaScript to somehow sign/encrypt the password. I think you best bet is to use the phantomjs code you linked on your local computer and update the cookie on Huginn using a WebhookAgent.

**Comment by tortoo** [comment]
Dose that mean I must open my computer one or two days one time to update the cookie? But when the cookie becomes invalid is hard to know exactly. Is there anyway to fetch the `enc_uin` which needn't to login and depend on the cookie. I think `enc_uin` should be fetched because it's there on the page of chrome develop tool. Maybe getting cookie is too much of trouble.

**Comment by dsander** [comment]
> think enc_uin should be fetched because it's there on the page of chrome develop tool.

Fetched from where? The JSON data is not including `enc_uin` when the request is made without a cookie.

**Comment by tortoo** [comment]
Maybe that is my always misunderstanding about JSON that the key seen on the chrome develop tool page should all be included in the data and could be fetched🙈. It's hard to implement that one or two days a time to open computert to get the cookie. Sigh!

**Comment by tortoo** [comment]
@dsander I think I may have solved this problem after changing v2 to v3 in the url and then I fetched the `enc_uin` smoothly. Let's forget about the cookie😹. Thank u very much and enjoy the weekend~

**Comment by dsander** [comment]
Nice!That is way easier 😄
