### ISSUE TITLE
Please support merge event in JsonParseAgent

### ISSUE THREAD

**Issue by whtsky** [huginn/huginn#2334]
Right now JsonParseAgent always create a new event.

**Comment by a10kiloham** [comment]
I would find this useful too. I assume it's just a matter of adding a one line merge into the agent. I don't have a Dev environment to try this on but should be easy to extend

**Comment by whtsky** [comment]
I tried to [implement this](https://github.com/whtsky/huginn/commit/190ee7c4b10f0a36150f087c018c0fc7bff20155) but then give up 'cause I don't know Ruby well.

**Comment by a10kiloham** [comment]
@whtsky this looks good up to line 50 since it doesn't seem to perform a merge. Probab needs something like events . payload = this.memory('agent1', events[i].payload) to actually do the merge right?
