### ISSUE TITLE
 I use the docker deployment of huginn, how to run multiple DelayedJob?

### ISSUE THREAD

**Issue by nageshuizeii** [huginn/huginn#2335]
How docker reconfigures Procfile files？Because the Procfile cannot be annotated properly。

**Comment by dsander** [comment]
You can not change the Procfile that is used in the docker container. If you want to run more delayed job processes use the [single-process](https://github.com/huginn/huginn/tree/master/docker/single-process) image which runs every process in a separate container. In theory you can mix `huginn/huginn` with one or more additional `huginn/single-process` containers running only DJ if you ensure both are up to date.

**Comment by nageshuizeii** [comment]
thank you sir！
