### ISSUE TITLE
Data output agent needs a function to remove repeat events

### ISSUE THREAD

**Issue by sqliuchang** [huginn/huginn#2340]
Events from different  source agents may repeat, and it's very useful to add a function to remove duplicates.
To deal with the repeat events, a flag to identify events is needed. For example,  "guid" , "url" and "title"  are all available for that.
Besides, if two events repeat, it's a problem which one should be removed. For example, one website agent generates a simple description and another one is full-text. I want the full-text one to cover the simple one. But only simple description is available for all websites and full-text is just available for parts of them. I don't know how to deal with this situation. Maybe the order of events generated will help and the later one will cover the former one if they have the same flag.
I'm so sorry  my English is very poor.

**Comment by dsander** [comment]
I don't think that functionality should be in the `DataOutputAgent`, we already have the `DeduplicationAgent` which prevent duplicate Events.

> Besides, if two events repeat, it's a problem which one should be removed. For example, one website agent generates a simple description and another one is full-text.

This could be done with a custom Agent but would require some work, it would require modifying the `DataOutputAgent`s memory to replace the previous Event with the  one containing more information.

**Comment by sqliuchang** [comment]
Thank you!
I have known how to deal with duplicate events from your answer.
