### ISSUE TITLE
The problem of Liquid's for loop.

### ISSUE THREAD

**Issue by tortoo** [huginn/huginn#2343]
When I use Liquid's `for` loop in the Event Formatting Agents, it outputs nothing. I don't know where's the fault.

```
  "instructions": {
    "team-a": [
      "abcd",
      "fgggggffghuuhhh"
    ],
    "enc_uin": "abcd",
    "team": "{% assign a = team-a %}{% assign b = enc_uin %}{% for b in a %}{{ b }}{% endfor %}"
  },
  "matchers": [],
  "mode": "clean"
```
Output:
```
[
  {
    "team-a": [
      "abcd",
      "fgggggffghuuhhh"
    ],
    "enc_uin": "abcd",
    "team": ""
  }
]
```
What I want to output is `team:"abcd"`.

**Comment by tortoo** [comment]
The field `enc_uin` is from the Website Agent which scraps  [the page for example](https://buluo.qq.com/p/detail.html?bid=144106&pid=5794662-1516500479) as you saw in the past😹, and field `team-a` is from another Website Agent which scraps the [txt file](https://www.dropbox.com/home?preview=%E8%BF%90%E5%8A%A8%E6%89%93%E5%8D%A1%E6%88%90%E5%91%98%E5%90%8D%E5%8D%95.txt) from my dropbox. My thought is after I typing a list of `enc_uin` in the txt file the content will be fetched by another Website Agent and formatted by Liquid as an object and then inserted into  the Event Formatting Agent by a Commander Agent. It is the field `team-a`  and the data is updated by live. How can I merge the two events or search `enc_uin` in `team-a` which are from two different events?

**Comment by dsander** [comment]
We don't have a good way to merge Events.



> My thought is after I typing a list of enc_uin in the txt file the content will be fetched by another Website Agent and formatted by Liquid as an object and then inserted into the Event Formatting Agent by a Commander Agent

That should work by using a second Formatting Agent.
```
CommanderAgent -> sets options of FormattingAgent1
WebsiteAgent -> sends Events to FormattingAgent1 which includes the data in it's Event
FormattingAgent1 -> FormattingAgent2 here you can work on the combined data
```

**Comment by tortoo** [comment]
@dsander Sorry I'm late to confirm that after setting another FormattingAgent the `for` loop works! But the result is that more than 10 agents should be set for me and it's soooo long. 😟
