### ISSUE TITLE
[FYI For Novice guide] Default mysql install conflicts with bundle

### ISSUE THREAD

**Issue by chrisvanklutter** [huginn/huginn#2347]
**Issue:**
For some months homebrew installs mysql 8.0.12 by default. This leads to bundle being unable to install mysql 0.4.8.
**Solution:**
This can be resolved by installing the older binary 5.7.23 from Oracle directly.

**Comment by dsander** [comment]
Thanks for the heads up, I think we can fix that problem by upgrading the `mysql2` gem.
