### ISSUE TITLE
JsonPostAgent - how to send Json as non-string

### ISSUE THREAD

**Issue by a10kiloham** [huginn/huginn#2352]
I've a result such that I need to post it back to an API that requires it to be submitted as int. I.e., Json formed as {"key": "123"} errors but {"key":123} is perfectly fine. The editor requires manually removing the quotes, but works great once removed.

I'm extracting the key however from prior Json. Therefore, I need to return this without the quotes or format it as such. No matter what I do, Liquid formatting seems to add the quotes - is there an option in liquid to output as an integer specifically?

I.e., I need to use {"key": {{company_id}} } without company_id being returned with surrounding quotes but as a plain int.

**Comment by a10kiloham** [comment]
As_xpath seems like it could be the answer but still doesn't work for me :(

**Comment by a10kiloham** [comment]
Also I can do this in javascript agent but I don't belive I can send and receive json from that agent can I? I can't see examples that issue http requests.
Cheers for any help!

**Comment by dsander** [comment]
I have never tried it with "non objects" but in theory it should work: `{"key": "{{company_id | as_object}}"}`  should pass the id as an integer, assuming it is stored like that in the received Event.

**Comment by a10kiloham** [comment]
Yeah I tried that and it seems to insert the quotations regardless. I've been pulling my hair out but I can't think of any other way to do a post of json data this way - no matter what the json post agent seems to always presume string and recast the int as string

**Comment by a10kiloham** [comment]
I'll post sample code later today to demonstrate

**Comment by a10kiloham** [comment]
crap ok, i'm wrong again :) that worked. Thank you!

**Comment by a10kiloham** [comment]
For thickos like me in the future I've updated the wiki :)

**Comment by dsander** [comment]
Nice, thank you 😄
