### ISSUE TITLE
Dynamically change PostAgent payload - accept as input from earlier event

### ISSUE THREAD

**Issue by a10kiloham** [huginn/huginn#2355]
I've got a tricky API that fails whenever a POST has keys that are unused. For example, if I'm filling in 3 fields like name, address, phone, if phone is NULL then the entire post breaks as NULL isn't an accepted response. But I can't build this payload as there's no way to make a key optional through conditionals. I'd like to preprocess in Javascript and build a payload where a key only appears if a value is present so in this case it would only post name and address. But payload will not accept input of other JSON objects. I can see the codebase where it allows array or hash, but using {{ payload | as_object }} is not considered valid. Is there a way to check/allow this? Happy to submit the PR but am not sure how to parse whether a liquid variable is outputting a hash or not.

Example:
```
    "party": {
          "name": "{{tag1}}",
          "phone":  "{{tag2}}",
    }
```
Post successful if tag1 and tag2 exist. POST fails if tag2 is NULL, but that's not consistently present. And there are too many tags to reasonably do this with a Trigger agent to check whether a key is present.

**Comment by a10kiloham** [comment]
oh awesome. i was confused as the text on the right hand side just says "json" as a content type. So both are valid but only the MIME type functions like this? I'll clarify the text but i'm a bit confused the difference in handling.

**Comment by a10kiloham** [comment]
For others that discover via Google, this seems to work best when payload uses {{payload | json}} as the liquid formatting agent.

**Comment by dsander** [comment]
> So both are valid but only the MIME type functions like this?

`json` is kind of a shortcut and requires the payload to be an object or array. Specifying a "real" content type in form of a MIME type allows to send anything as the payload. I think it was initially added to send data as `text/plain`.

> payload uses {{payload | json}} as the liquid formatting agent.

Neat! I did not know about the `json` filter. 😄
