### ISSUE TITLE
After correctly extracting the information, it is reported in the last step.

### ISSUE THREAD

**Issue by nageshuizeii** [huginn/huginn#2356]
{
  "expected_update_period_in_days": "2",
  "url": "http://book.zongheng.com/book/342974.html",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "url": {
      "xpath": "//*[@class='chap']/@href",
      "value": "."
    },
    "title": {
      "xpath": "//*[@class='chap']/text()",
      "value": "normalize-space(.)"
    }
  }
}

![image](https://user-images.githubusercontent.com/16527235/44595183-df9bea80-a7fa-11e8-9b80-052a9d5b1b51.png)

**Comment by dsander** [comment]
I am no expert when it comes to xpath, I think using CSS selectors gives you the response to expect:
```json
{
  "expected_update_period_in_days": "2",
  "url": "http://book.zongheng.com/book/342974.html",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "url": {
      "css": ".chap",
      "value": "@href"
    },
    "title": {
      "css": ".chap",
      "value": "normalize-space(.)"
    }
  }
}
```

**Comment by nageshuizeii** [comment]
It's hard to believe that this is true. I tried it and it worked successfully. Because xpath is easier for me than css, because there is a plugin for xpath helper. Thank you! This may be a bug.

**Comment by nageshuizeii** [comment]
It is my negligence, you are correct, thank you very much, I will pay attention next time.
