### ISSUE TITLE
Got a problem about updating huginn and how to combine extraction into one event.

### ISSUE THREAD

**Issue by tortoo** [huginn/huginn#2364]
The following is my operating to update my huginn.

```
$ git fetch origin
remote: Counting objects: 644, done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 644 (delta 356), reused 374 (delta 346), pack-reused 252
Receiving objects: 100% (644/644), 156.85 KiB | 98.00 KiB/s, done.
Resolving deltas: 100% (467/467), completed with 97 local objects.
From https://github.com/huginn/huginn
   6a1509d9..e81ae4a6  master        -> origin/master
 * [new branch]        huginn-master -> origin/huginn-master
$ git merge origin/master
error: Your local changes to the following files would be overwritten by merge:
	Gemfile.lock
Please commit your changes or stash them before you merge.
Aborting
$ git checkout Gemfile.lock
$ git merge origin/master
Removing spec/models/agents/google_flights_spec.rb
Removing docker/single-process/environment.yml
Removing docker/scripts/setup
Removing docker/multi-process/docker-compose.yml
Removing app/models/agents/google_flights_agent.rb
error: There was a problem with the editor 'vi'.
Not committing merge; use 'git commit' to complete the merge.
$ git merge origin/master
fatal: You have not concluded your merge (MERGE_HEAD exists).
Please, commit your changes before you merge.
$ git commit -m "commit"
[master 3cc883fc] commit
$ git fetch origin      # --> It outputs nothing.
$ git merge origin/master
Already up-to-date.
$ git push -f heroku master
Counting objects: 646, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (264/264), done.
Writing objects: 100% (646/646), 139.07 KiB | 0 bytes/s, done.
Total 646 (delta 473), reused 537 (delta 379)
remote: Compressing source files... done.
remote: Building source:
remote: 
...

$ heroku run rake db:migrate
Running rake db:migrate on xxx... up, run.4197 (Free)
fatal: Not a git repository (or any parent up to mount point /app)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /app)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /app)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /app)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

I think the updating is failed and don't know how to do next. In fact I just want to update [this commit a04faa8](https://github.com/huginn/huginn/commit/a04faa82450c20227c63c46e3f104e4ac14209d1)  but don't know how to update this one only.  

And I have another question about this commit.
Before my updating the WebsiteAgent outputs the following:

```
[
  {
    "content": "ab"
  },
 {
   "content": "cd"
  },
 {
   "content": "ef"
  }
]
```

The quantity of `content` is uncertain and I want to combine them into one event . And what's the output looks like after updating?

The last question is whether this is just for HTML/XML mode? I strongly recommend adding the `TEXT` mode. 😸

**Comment by tortoo** [comment]
Do you mean my updating is successful?  When I execute `$ git fetch origin` it outputs nothing. Dose it mean there's nothing to fetch and everything is up to date? Maybe it should say something like `you are up to date`? 😹

I tested `"array": "true"` just now and it works well. But I'm not certain if it's updated by the operating above in the earlier today. 

> That should be doable, because I rarely use the text extraction I only added it for HTML/XML.

I need TEXT mode because it's more convenient to use Regular expression to get the content which has some special symbol set by myself. In fact `JSON` mode is also needed which can solve the uneven amount problem.

**Comment by tortoo** [comment]
I'm glad to hear that! 😹 The feature `"array": "true"` is very useful and my appreciate! @dsander

**Comment by tortoo** [comment]
@dsander Recently I found that I really need the function `"array": "true"` to be used in JSON mode because some operation in different comment can't get through. How can I modify my code in huginn to achieve this function? Thanks for your great help!😸

**Comment by dsander** [comment]
@tortoo I am not sure how `array: true` could work with JSON, can you give an example of the JSON and the extractors you are trying to use?

**Comment by malagebidi** [comment]
Need `"array": "true"` work with text type.

**Comment by oltdaniel** [comment]
@dsander For JSON you can have a list full of e.g. temperature recordings which represent objects with different fields. Example:

```{
  "expected_update_period_in_days": "2",
  "url": "https://api.openweathermap.org/data/2.5/forecast?q=Berlin,de&appid={% credential weather_api_key %}&lang=de&cnt=5&units=metric",
  "type": "json",
  "mode": "all",
  "extract": {
    "description": {
      "path": "list[*].weather[0].description"
    },
    "temp": {
      "path": "list[*].main.temp"
    },
    "time": {
      "path": "list[*].dt_txt"
    }
  }
}```

If the array option would work, I could combine the hourly reports into a single message instead of sending e.g. 5 events.

**Comment by dsander** [comment]
I think I understand the use case, the combination could also be done downstream using the liquid `as_object` filter or when generating the report via Liquid, right?

**Comment by oltdaniel** [comment]
@dsander You mean in e.g. the Formatting Agent? My Understanding is, that the WebsiteAgent outputs each (here list item) as a single event. I cannot see where `as_object` could be used here amd even if Liquid as is, would be usable in the Website Agent Selector part at all?

**Comment by dsander** [comment]
@oltdaniel Yes either in a Formatting Agent or in the Agent that generates the notification/report. For that approach you would need to extract "more" from the original JSON so that it includes all data in one extracted field (a bit hard to explain without an actual JSON structure). You could then filter/combine the data in the downstream Agent.

**Comment by oltdaniel** [comment]
@dsander I see. But this would make the Website Agent with its selector part now completely useless and the liquid template for the report generation in the end way to complicated. Here the JSON I need to parse and why the `array` option is easier:

The json [here](https://pastebin.com/raw/vduvdKYB). So I have a list of objects, each containing the weather forecast for an hour. If I need to use `as_object` in my Formatting Agent, I would need to parse it, iterate over each list item, and have a long selection to extract the value. If the API would change, I need to completely rework this. If the `array` option would be available for JSON too (as it is for HTML now) I can parse the weather part in the Website Agent to my custom uniform format, to be able to add different APIs in the future.

This would just require an if-statement in https://github.com/huginn/huginn/blob/410617109719bc8645679d88e5121cab3318a760/app/models/agents/website_agent.rb#L589 as done in https://github.com/huginn/huginn/blob/410617109719bc8645679d88e5121cab3318a760/app/models/agents/website_agent.rb#L632 for the HTML/XML part.

**Comment by dsander** [comment]
I am not saying it is hard to add or something that we would not accept as a change, I was only pointing out that there are ways to process the data. Especially when working with JSON the `JqAgent` is very powerful and can do stuff the `WebsiteAgent` will never be able to do. I always like the Agents to be as specialized and simple as possible (that ship clearly has sailed for the WebsiteAgent 😄 ). If there is already an Agent that is better suited for a job, I am more hesitant in adding/accepting a change to another Agent that enables it to do a bit more.
