### ISSUE TITLE
A website is available in Simplified Chinese, Traditional Chinese and English. I use the website agent to grab the default and return to English. How can I set it back to Simplified Chinese?

### ISSUE THREAD

**Issue by nageshuizeii** [huginn/huginn#2366]
{
  "expected_update_period_in_days": "2",
  "url": "http://91porn.com/uvideos.php?UID=bccdY4LbJ9Pz4LJ0oDwp40t0Q96ni2Gbty7HMiaBlop2IjBR&type=public",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "url": {
      "xpath": "//*[@id=\"myvideo-content\"]//p//a/@href",
      "value": "."
    },
    "title": {
      "xpath": "//*[@id=\"myvideo-content\"]//p//a/text()",
      "value": "normalize-space(.)"
    },
    "date": {
      "xpath": "//*[@id=\"myvideo-content\"]/div/div[2]/p/text()[3]",
      "value": "normalize-space(.)"
    }
  }
}

**Comment by dsander** [comment]
The website probably uses a header or cookie to determine the language, you will have to inspect the requests the browser makes and send the header/cookie with the WebsiteAgent. Please also mention that links are NSFW.
