### ISSUE TITLE
Why is my EventFormattingAgent not working?

### ISSUE THREAD

**Issue by nageshuizeii** [huginn/huginn#2368]
first step use rss agent (https://rsshub.app/instagram/user/diygod)
```
{
  "instructions": {
    "message": "{{photo}}"
  },
  "matchers": [
    {
      "path": "{{description}}",
      "regexp": "/(http)?s?:?(\\/\\/[^\"']*\\.(?:png|jpg|jpeg|gif|png|svg))/g",
      "to": "{{photo}}"
    }
  ],
  "mode": "clean"
}
```
But can't work. The purpose of my doing this is to pass the event to the third step of the telegram agent.

**Comment by dsander** [comment]
Hi,

`to` has to be just a string and the regular expression must not be enclosed with `/`;
```
{
  "instructions": {
    "message": "{{photo.0}}"
  },
  "matchers": [
    {
      "path": "{{description}}",
      "regexp": "(http)?s?:?(\\/\\/[^\"']*\\.(?:png|jpg|jpeg|gif|png|svg))",
      "to": "photo"
    }
  ],
  "mode": "clean"
}
```

If you expect a description to contain multiple photos it might be better to send the whole `description` to a `WebsiteAgent` in text extraction mode because it can handle multiple matches for the same regular expression.

**Comment by nageshuizeii** [comment]
First of all, thank you for your busy schedule to answer my questions! The photo.url can be extracted correctly after adopting your comments, but the telegram is not working properly.
![jietu20180908-224241](https://user-images.githubusercontent.com/16527235/45255414-c5e0d280-b3b8-11e8-80d6-7dc100c4a93f.jpg)
![image](https://user-images.githubusercontent.com/16527235/45255422-d85b0c00-b3b8-11e8-835b-5601d2a07323.png)

**Comment by dsander** [comment]
> It is assumed that events have either a `text`, `photo`, `audio`, `document` or `video` key. You can use the EventFormattingAgent if your event does not provide these keys.

Check the documentation of the TelegramAgent, try changing `message` to `photo` or `text` in your WebsiteAgent, `Long message` should either be `truncate` or `split`

**Comment by dsander** [comment]
I am not totally sure, but I think someone mentioned `photo` can be an url and does not have to be an actual image. Try it with:

```
{
  "instructions": {
    "photo": "{{photo.0}}"
  },
  "matchers": [
    {
      "path": "{{description}}",
      "regexp": "(http)?s?:?(\\/\\/[^\"']*\\.(?:png|jpg|jpeg|gif|png|svg))",
      "to": "photo"
    }
  ],
  "mode": "clean"
}

```

The TelegramAgent expects the incoming Event to have a `photo` or `text` key. You can expect the Events an Agent emitted on the Agent detail page on in the global Events section.
