### ISSUE TITLE
how does “on_change” work?

### ISSUE THREAD

**Issue by 7x11** [huginn/huginn#2369]
website agent for stock.

if the events like this.   

> --
> 20m ago
> title: item name
> stock: no
> --
> --
> 30m ago
> title: item name
> stock: yes
> ---

is that means : it's never create new event. because the event already "yes" or "no" ?
i think is can be just on_change/ different with last event

> like this
> ---
> 1m ago
> title: item name
> stock: yes 
> ---
> --
> 20m ago
> title: item name
> stock: no
> --
> --
> 30m ago
> title: item name
> stock: yes
> ---

I have tested but im not sure. pls confirm.
：）

**Comment by dsander** [comment]
> i think is can be just on_change/ different with last event

That is correct, on_change compare the extracted values with the previous Event, in your case it will create new events every time `stock` flips from `yes` to `no` and visa-versa .
