### ISSUE TITLE
Post Agent : Post XMLwithout xml version

### ISSUE THREAD

**Issue by signallhill** [huginn/huginn#2376]
I have post agent as follows

{
  "post_url": "https://api.api/api",
  "expected_receive_period_in_days": "1",
  "content_type": "xml",
  "method": "post",
  "xml_root": "root",
  "payload": {
    "sub-root": {
      "Title": "Title",
      "Date": "09/09/2009",
      "Description": "Description"
    }
  },
  "emit_events": "true",
  "no_merge": "true",
  "output_mode": "clean"
}

Response is

`<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<response uri=\"/api"><error><code>null</code><message>null</message></error></response>\n"`

The issue seems to be `"<?xml version=\"1.0\" encoding=\"UTF-8\" ?>"` which is sent as a first line of the XML Post. 

Is it possible to send the post request without sending the version and encoding?

`<root>
   <sub-root>
      <Title>Title</Title>
      <Date>09/09/2009</Date>
     <Description>Description</Description>
   </sub-root>
</root>`

**Comment by dsander** [comment]
That is a funny API, they don't accept the xml header but send it as part of their own response? 😄 

The only way to to it is to set `content_type: "application/xml"` and the `payload` to a manually constructed XML string.

**Comment by signallhill** [comment]
I don't know. Some kind of half baked API.

I tested the `content_type: "application/xml"` in beeceptor.com

Looks like maybe Json instead of xml

{"root"=>{ "sub-root"=>{ "Title"=>"Title", "Date"=>"09/09/2009", "Description"=>"Description"}}}

When I do `content_type: "xml"` the format is correct except for the xml version being included.

**Comment by signallhill** [comment]
Yep that did it.

I looked at an older issue to figure our the string part. https://github.com/huginn/huginn/issues/2248
