### ISSUE TITLE
Not support Heroku new stack-18

### ISSUE THREAD

**Issue by Edison-Hsu** [huginn/huginn#2377]
The building log shows `https://github.com/weibeld/heroku-buildpack-graphviz.git not support stack-18`

**Comment by dsander** [comment]
Thanks for the head up, we are now using the older `heroku-16` stack. You should be able to deploy the application again.

**Comment by Edison-Hsu** [comment]
Thanks for your reply. It's a nice way to use `heroku-16` stack by indicating it in app.json.
In addition we can create app manually by using `heroku create --stack=heroku-16`
My Huginn works perfect on Heroku right now.
