### ISSUE TITLE
XML post not received.

### ISSUE THREAD

**Issue by signallhill** [huginn/huginn#2381]
In the post agent there is a note - By default, non-GETs will be sent with form encoding (application/x-www-form-urlencoded).

Is the below post also form encoded? How do I send it non form encoded if possible?

    post_url: url
    expected_receive_period_in_day...: 1
    content_type: text/xml
    method: post
    payload: string
    emit_events: true
    no_merge: true
    output_mode: clean

I have the string exactly how the receiver wants it but they say the are not receiving any payload when I post.

**Comment by dsander** [comment]
It should not be, you can test requests with sites like these and check that we actual request looks like: https://beeceptor.com/
