### ISSUE TITLE
Depricate the Weather Underground API

### ISSUE THREAD

**Issue by tantalum** [huginn/huginn#2391]
The Weather Underground API will be deactivated on 31/12/2018. As such support for the weather underground API should be de-activated. 

For the Weather Underground announcement see: https://apicommunity.wunderground.com/weatherapi/topics/end-of-service-for-the-weather-underground-api

**Comment by dsander** [comment]
Not sure if we need to deprecate it first, but we can remove the code once they shut down the API.

**Comment by e-alfred** [comment]
The API is shut down by now. Please remove the code and maybe add a better alternative like openweathermap.org or something like it.

**Comment by tantalum** [comment]
Hi. I have a pull request open that should resolve this issue. If there is any cleanup that is needed before it can be merged please let me know.

**Comment by dsander** [comment]
@tantalum I made a few comments on the pull request

**Comment by tantalum** [comment]
I have updated the PR
