### ISSUE TITLE
can huginn send http request ? i want to trigger some service ...

### ISSUE THREAD

**Issue by ACERY1** [huginn/huginn#2392]
i know that huginn can config webhooks，but can huginn send http request ?

**Comment by ACERY1** [comment]
<img width="1034" alt="20181017222023" src="https://user-images.githubusercontent.com/19555547/47093038-dd826500-d25a-11e8-9833-b60007f4e984.png">

I found this.

**Comment by virtadpt** [comment]
Yes - you can either use a Website Agent or the Post Agent for that.

**Comment by ACERY1** [comment]
thx !
