### ISSUE TITLE
got a utf-8 error,help

### ISSUE THREAD

**Issue by Howard-guo** [huginn/huginn#2395]
i create a post agent like this:

```json
{
  "disable_redirect_follow": "true",
  "post_url": "https://**********/v2/Handler/UCenter?action=Login&username=********&password=********c228ab8aae6bc&rememberPwd=true&user_domain=hj&business_domain=&hpuid=uRcr4C5jUxczoXuaIt630&callback=reqwest_15*********01093",
  "expected_receive_period_in_days": "1",
  "content_type": "form",
  "method": "get",
  "emit_events": "true",
  "no_merge": "false",
  "output_mode": "clean",
  "event_headers_style": "raw"
}
```
it can request and response correct,but after i set emit_events to true and dry run,it responsed this:
>[00:00:00] INFO -- : Dry Run started
[00:00:03] INFO -- : Dry Run failed
[00:00:03] ERROR -- : Exception during dry-run. "\xE7" from ASCII-8BIT to UTF-8: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/core_ext/object/json.rb:36:in `encode'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/core_ext/object/json.rb:36:in `to_json'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/core_ext/object/json.rb:36:in `to_json'
/app/vendor/bundle/ruby/2.5.0/gems/json-1.8.6/lib/json/common.rb:223:in `generate'
/app/vendor/bundle/ruby/2.5.0/gems/json-1.8.6/lib/json/common.rb:223:in `generate'
/app/vendor/bundle/ruby/2.5.0/gems/json-1.8.6/lib/json/common.rb:394:in `dump'
/app/lib/json_with_indifferent_access.rb:10:in `dump'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.1/lib/active_record/type/serialized.rb:27:in `serialize'
/app/vendor/bundle/ruby/2.5.0/gems/activemodel-5.1.1/lib/active_model/type/helpers/mutable.rb:6:in `cast'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.1/lib/active_record/attribute.rb:173:in `type_cast'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.1/lib/active_record/attribute.rb:38:in `value'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.1/lib/active_record/attribute.rb:154:in `changed_from_assignment?'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.1/lib/active_record/attribute.rb:55:in `changed?'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.1/lib/active_record/attribute_mutation_tracker.rb:41:in `changed?'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.1/lib/active_record/attribute_mutation_tracker.rb:29:in `change_to_attribute'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.1/lib/active_record/attribute_mutation_tracker.rb:21:in `block in changes'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.1/lib/active_record/attribute_mutation_tracker.rb:20:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.1/lib/active_record/attribute_mutation_tracker.rb:20:in `each_with_object'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.1/lib/active_record/attribute_mutation_tracker.rb:20:in `changes'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.1/lib/active_record/attribute_methods/dirty.rb:201:in `changes_to_save'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.1/lib/active_record/attribute_methods/dirty.rb:206:in `changed_attribute_names_to_save'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.1/lib/active_record/associations/association.rb:178:in `initialize_attributes'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.1/lib/active_record/associations/association.rb:272:in `block in build_record'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.1/lib/active_record/core.rb:339:in `initialize'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.1/lib/active_record/inheritance.rb:66:in `new'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.1/lib/active_record/inheritance.rb:66:in `new'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.1/lib/active_record/reflection.rb:154:in `build_association'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.1/lib/active_record/associations/association.rb:271:in `build_record'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.1/lib/active_record/associations/collection_association.rb:98:in `build'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.1/lib/active_record/associations/collection_proxy.rb:313:in `build'
/app/app/models/agent.rb:112:in `build_event'
/app/app/concerns/dry_runnable.rb:90:in `create_event'
/app/app/models/agents/post_agent.rb:229:in `handle'
/app/app/models/agents/post_agent.rb:161:in `check'
/app/app/concerns/dry_runnable.rb:31:in `dry_run!'
/app/app/controllers/agents/dry_runs_controller.rb:41:in `create'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.1/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.1/lib/abstract_controller/base.rb:186:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:131:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.1/lib/action_controller/metal/rescue.rb:20:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `block in instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `instrument'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.1/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.1/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.1/lib/abstract_controller/base.rb:124:in `process'
/app/vendor/bundle/ruby/2.5.0/gems/actionview-5.1.1/lib/action_view/rendering.rb:30:in `process'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.1/lib/action_controller/metal.rb:189:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.1/lib/action_controller/metal.rb:253:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.1/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.1/lib/action_dispatch/routing/route_set.rb:31:in `serve'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.1/lib/action_dispatch/journey/router.rb:46:in `block in serve'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.1/lib/action_dispatch/journey/router.rb:33:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.1/lib/action_dispatch/journey/router.rb:33:in `serve'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.1/lib/action_dispatch/routing/route_set.rb:832:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
/app/vendor/bundle/ruby/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
/app/vendor/bundle/ruby/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.3/lib/rack/conditional_get.rb:38:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/cookies.rb:613:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:97:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/railties-5.1.1/lib/rails/rack/logger.rb:36:in `call_app'
/app/vendor/bundle/ruby/2.5.0/gems/railties-5.1.1/lib/rails/rack/logger.rb:24:in `block in call'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:69:in `tagged'
/app/vendor/bundle/ruby/2.5.0/gems/railties-5.1.1/lib/rails/rack/logger.rb:24:in `call'
/app/config/initializers/silence_worker_status_logger.rb:3:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/request_id.rb:25:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/executor.rb:12:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/static.rb:125:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/ssl.rb:66:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/railties-5.1.1/lib/rails/engine.rb:522:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/railties-5.1.1/lib/rails/railtie.rb:185:in `public_send'
/app/vendor/bundle/ruby/2.5.0/gems/railties-5.1.1/lib/rails/railtie.rb:185:in `method_missing'
/app/vendor/bundle/ruby/2.5.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:562:in `process_client'
/app/vendor/bundle/ruby/2.5.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:658:in `worker_loop'
/app/vendor/bundle/ruby/2.5.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
/app/vendor/bundle/ruby/2.5.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:132:in `start'
/app/vendor/bundle/ruby/2.5.0/gems/unicorn-5.1.0/bin/unicorn:126:in `<top (required)>'
/app/vendor/bundle/ruby/2.5.0/bin/unicorn:23:in `load'
/app/vendor/bundle/ruby/2.5.0/bin/unicorn:23:in `<top (required)>'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:27:in `run'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli.rb:360:in `exec'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli.rb:20:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli.rb:10:in `start'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/exe/bundle:30:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/exe/bundle:22:in `<top (required)>'
/app/bin/bundle:3:in `load'
/app/bin/bundle:3:in `<main>'

**Comment by dsander** [comment]
Does it help if you set `"force_encoding": "utf-8"`?

**Comment by Howard-guo** [comment]
> Does it help if you set `"force_encoding": "utf-8"`?

thx anyway
i don't know how to set it
can you describe the detail please.
