### ISSUE TITLE
Huginn - No start during server boot

### ISSUE THREAD

**Issue by JtheBAB** [huginn/huginn#2400]
Hi

I followed the installation steps in the wiki and everything is working as expected.

Just one problem: When i restart the server, huginn is not starting automatically. How can i solve this?

OS: Debian Stretch

Best regards

JtheBAB

**Comment by dsander** [comment]
Hi,

I think `sudo systemctl enable upstart` should work. If that complains about the service not existing you can use `sudo systemctl` to get a list of all services, maybe the upstart service has a slightly different name.

**Comment by JtheBAB** [comment]
Hi

Thanks for the hint. 
I did the following command and it worked:

`systemctl disable runit && systemctl enable runit`

**Comment by dsander** [comment]
Right, it's runit not upstart 🤦‍♂️  😄
