### ISSUE TITLE
I exported the huginn data from the mysql database. After reinstalling huginn, I imported my backup mysql data table and found that the agents are all there, but the sources and Receiver relationships between events, Scenarios and agents are lost.

### ISSUE THREAD

**Issue by nageshuizeii** [huginn/huginn#2408]
I exported the huginn data from the mysql database. After reinstalling huginn, I imported my backup mysql data table and found that the agents are all there, but the sources and Receiver relationships between events, Scenarios and agents are lost.

**Comment by nageshuizeii** [comment]
[db.sql.zip](https://github.com/huginn/huginn/files/2545914/db.sql.zip)

Database with my problem

**Comment by dsander** [comment]
The information seems to be in the database backup. Did you restore the backup into a empty database?

**Comment by nageshuizeii** [comment]
Yes, my imported mysql is a new empty database

**Comment by dsander** [comment]
I loaded your backup with `cat db.sql | mysql -u root huginn` into a new database and the connections look good to me. Did you get any errors or warnings while importing the data?

**Comment by nageshuizeii** [comment]
There was an error message, but I forgot the screenshot at the time. The agent is running normally. The problem is that the event of the website agent cannot be passed to the data output agent. I delete the original output agent and regenerate the new output agent before outputting the rss or passing it to the slack agent.

**Comment by nageshuizeii** [comment]
do you see the Scenarios? When I restored the database, Scenarios also disappeared.

**Comment by nageshuizeii** [comment]
The problem is that after mysql recovery, the website agent can work normally, the data output agent can not work normally, you need to delete the data output agent and then reset it to generate rss.
![image](https://user-images.githubusercontent.com/16527235/48071566-9a8e2e80-e215-11e8-9603-d4e7c3171193.png)

**Comment by dsander** [comment]
> There was an error message, but I forgot the screenshot at the time.

That will most likely be the root of  your problems.



> do you see the Scenarios? When I restored the database, Scenarios also disappeared.

The backup does not contain any scenarios. I see the Agents and their connections, events are created and propagated normally.

**Comment by nageshuizeii** [comment]
That should be my mistake here, not the huginn or database error, the next time I encounter I will take screenshot feedback, thank you for your answer. If huginn has a better backup agent and recovery agent, that's great!
