### ISSUE TITLE
rake export hangs

### ISSUE THREAD

**Issue by Taffer** [huginn/huginn#2410]
I ran this about 18 hours ago when I was leaving the office:

```
$ sudo bundle exec rake production:export
Stopping huginn ...
Exporting new services ...
```

I don't actually know anything about Ruby, so I have no idea what to do next.

**Comment by Taffer** [comment]
I've following the install directions at https://github.com/huginn/huginn/blob/master/doc/manual/installation.md and have completed everything up until this final step in the **Install Init Script** section.

System is Ubuntu 18, database is PostgreSQL running on `localhost`. I'm also running Mattermost on this VM, proxy'd through nginx.

**Comment by dsander** [comment]
Can you post the contents of the logs mentioned in the [troubleshooting section](https://github.com/huginn/huginn/blob/master/doc/manual/installation.md#troubleshooting)?

**Comment by Taffer** [comment]
Following the troubleshooting instructions...

`sudo bundle exec rake production:check` produces:

`[  OK  ] Everything is fine`

No nginx log yet as I haven't gotten to the step of configuring that.

The only thing in the `log` directory is `production.log`, which doesn't have any errors in it:

```
I, [2018-11-05T12:43:37.302749 #23377]  INFO -- : Migrating to DeviseCreateUsers (20120728210244)
I, [2018-11-05T12:43:37.345974 #23377]  INFO -- : Migrating to AddAdminToUsers (20120728215449)
I, [2018-11-05T12:43:37.385458 #23377]  INFO -- : Migrating to EnableLockableStrategyForDevise (20120919061122)
I, [2018-11-05T12:43:37.434047 #23377]  INFO -- : Migrating to AddUsernameToUsers (20120919063304)
I, [2018-11-05T12:43:37.456720 #23377]  INFO -- : Migrating to CreateEvents (20121216025930)
I, [2018-11-05T12:43:37.495722 #23377]  INFO -- : Migrating to CreateAgents (20121220053905)
I, [2018-11-05T12:43:37.548016 #23377]  INFO -- : Migrating to CreateLinks (20121222074732)
I, [2018-11-05T12:43:37.576240 #23377]  INFO -- : Migrating to CreateDelayedJobs (20121223203701)
I, [2018-11-05T12:43:37.617837 #23377]  INFO -- : Migrating to AddMemoryToAgents (20121231170705)
I, [2018-11-05T12:43:37.620532 #23377]  INFO -- : Migrating to AddInvitationCodeToUsers (20130107050049)
I, [2018-11-05T12:43:37.623391 #23377]  INFO -- : Migrating to AddIndexes (20130124050117)
I, [2018-11-05T12:43:37.635623 #23377]  INFO -- : Migrating to ChangeMemoryToLongText (20130126080736)
I, [2018-11-05T12:43:37.637683 #23377]  INFO -- : Migrating to AddLastWebhookAtToAgents (20130509053743)
I, [2018-11-05T12:43:37.639936 #23377]  INFO -- : Migrating to CreateAgentLogs (20130819160603)
I, [2018-11-05T12:43:37.661578 #23377]  INFO -- : Migrating to AddExpiresAtToEvents (20131105063248)
I, [2018-11-05T12:43:37.674507 #23377]  INFO -- : Migrating to AddKeepEventsForToAgents (20131222211558)
I, [2018-11-05T12:43:37.724196 #23377]  INFO -- : Migrating to SwitchToJsonSerialization (20131223032112)
I, [2018-11-05T12:43:37.729832 #23377]  INFO -- : Migrating to AddCachedDatesToAgent (20131227000021)
I, [2018-11-05T12:43:37.733928 #23377]  INFO -- : Migrating to CreateUserCredentials (20140121075418)
I, [2018-11-05T12:43:37.765190 #23377]  INFO -- : Migrating to ChangeHandlerToMediumText (20140127164931)
I, [2018-11-05T12:43:37.767564 #23377]  INFO -- : Migrating to AddModeToUserCredentials (20140210062747)
I, [2018-11-05T12:43:37.797673 #23377]  INFO -- : Migrating to AddEventIdAtCreationToLinks (20140213053001)
I, [2018-11-05T12:43:37.828606 #23377]  INFO -- : Migrating to AddPropagateImmediatelyToAgent (20140216201250)
I, [2018-11-05T12:43:37.876840 #23377]  INFO -- : Migrating to AddDisabledToAgent (20140403043556)
I, [2018-11-05T12:43:37.925603 #23377]  INFO -- : Migrating to RenameWebhookToWebRequest (20140408150825)
I, [2018-11-05T12:43:37.931379 #23377]  INFO -- : Migrating to MigrateAgentsToLiquidTemplating (20140505201716)
I, [2018-11-05T12:43:37.955650 #23377]  INFO -- : Migrating to CreateScenarios (20140509170420)
I, [2018-11-05T12:43:38.033770 #23377]  INFO -- : Migrating to CreateScenarioMemberships (20140509170443)
I, [2018-11-05T12:43:38.046709 #23377]  INFO -- : Migrating to CreateServices (20140515211100)
I, [2018-11-05T12:43:38.089576 #23377]  INFO -- : Migrating to AddServiceIdToAgents (20140525150040)
I, [2018-11-05T12:43:38.092385 #23377]  INFO -- : Migrating to MigrateAgentsToServiceAuthentication (20140525150140)
I, [2018-11-05T12:43:38.144438 #23377]  INFO -- : Migrating to AddFieldsToScenarios (20140531232016)
I, [2018-11-05T12:43:38.167965 #23377]  INFO -- : Migrating to AddIndicesToScenarios (20140602014917)
I, [2018-11-05T12:43:38.197857 #23377]  INFO -- : Migrating to RenameDigestEmailToEmailDigest (20140603104211)
I, [2018-11-05T12:43:38.202502 #23377]  INFO -- : Migrating to AddGuidToAgents (20140605032822)
I, [2018-11-05T12:43:38.221774 #23377]  INFO -- : Migrating to ConvertEfaSkipAgent (20140722131220)
I, [2018-11-05T12:43:38.225699 #23377]  INFO -- : Migrating to AdoptXpathInWebsiteAgent (20140723110551)
I, [2018-11-05T12:43:38.231613 #23377]  INFO -- : Migrating to ConvertEfaSkipCreatedAt (20140730005210)
I, [2018-11-05T12:43:38.234337 #23377]  INFO -- : Migrating to RemoveServiceIndexOnUserId (20140809211540)
I, [2018-11-05T12:43:38.239485 #23377]  INFO -- : Migrating to AddUidColumnToServices (20140811200922)
I, [2018-11-05T12:43:38.269929 #23377]  INFO -- : Migrating to SetCharsetForMysql (20140813110107)
I, [2018-11-05T12:43:38.273273 #23377]  INFO -- : Migrating to AddTagColorToScenarios (20140820003139)
I, [2018-11-05T12:43:38.276657 #23377]  INFO -- : Migrating to AddControlLinks (20140901143732)
I, [2018-11-05T12:43:38.316711 #23377]  INFO -- : Migrating to SetEventsCountDefault (20140906030139)
I, [2018-11-05T12:43:38.323360 #23377]  INFO -- : Migrating to AddTypeOptionAttributeToPushbulletAgents (20150219213604)
I, [2018-11-05T12:43:38.327019 #23377]  INFO -- : Migrating to UpdateKeepEventsForToBeInSeconds (20150507153436)
I, [2018-11-05T12:43:38.329707 #23377]  INFO -- : Migrating to RemoveRequirementFromUsersInvitationCode (20150808115436)
I, [2018-11-05T12:43:38.331591 #23377]  INFO -- : Migrating to WebsiteAgentDoesNotUseEventUrl (20160108221620)
I, [2018-11-05T12:43:38.340202 #23377]  INFO -- : Migrating to AddModeOptionToFtpsiteAgents (20160224120316)
I, [2018-11-05T12:43:38.346192 #23377]  INFO -- : Migrating to AddConfirmableAttributesToUsers (20160301113717)
I, [2018-11-05T12:43:38.360229 #23377]  INFO -- : Migrating to AddDeactivatedAtToUsers (20160302095413)
I, [2018-11-05T12:43:38.373447 #23377]  INFO -- : Migrating to AddDeactivatedToAgents (20160307084729)
I, [2018-11-05T12:43:38.440371 #23377]  INFO -- : Migrating to WarnAboutDuplicateUsernames (20160307085545)
I, [2018-11-05T12:43:38.445059 #23377]  INFO -- : Migrating to PostAgentSetEventHeaderStyle (20160405072512)
I, [2018-11-05T12:43:38.448431 #23377]  INFO -- : Migrating to AddIconToScenarios (20160419150930)
I, [2018-11-05T12:43:38.451122 #23377]  INFO -- : Migrating to AddXmlNamespaceOptionToDataOutputAgents (20160423163416)
I, [2018-11-05T12:43:38.455601 #23377]  INFO -- : Migrating to ChangeEventsOrderToEventsListOrder (20160607055850)
I, [2018-11-05T12:43:38.458420 #23377]  INFO -- : Migrating to RemoveQueueFromEmailDigestAgentMemory (20160807000122)
I, [2018-11-05T12:43:38.463737 #23377]  INFO -- : Migrating to SetEmitErrorEventForTwitterActionAgents (20160823151303)
I, [2018-11-05T12:43:38.469686 #23377]  INFO -- : Migrating to UpdatePushoverAgentOptions (20161004120214)
I, [2018-11-05T12:43:38.474190 #23377]  INFO -- : Migrating to ResetDataOutputAgents (20161007030910)
I, [2018-11-05T12:43:38.476621 #23377]  INFO -- : Migrating to ConvertWebsiteAgentTemplateForMerge (20161124061256)
I, [2018-11-05T12:43:38.479261 #23377]  INFO -- : Migrating to AddTemplatesToResolveUrl (20161124065838)
I, [2018-11-05T12:43:38.481700 #23377]  INFO -- : Migrating to AddMinEventsOptionToPeakDetectorAgents (20170307190555)
I, [2018-11-05T12:43:38.484820 #23377]  INFO -- : Migrating to SetRssContentType (20170419073748)
I, [2018-11-05T12:43:38.487250 #23377]  INFO -- : Migrating to MigrateGrowlAgentToLiquid (20170731191002)
I, [2018-11-05T12:45:48.058634 #23409]  INFO -- :   Rendering devise/mailer/confirmation_instructions.html.erb
I, [2018-11-05T12:45:48.060494 #23409]  INFO -- :   Rendered devise/mailer/confirmation_instructions.html.erb (1.7ms)
I, [2018-11-05T12:45:49.132128 #23409]  INFO -- : Sent mail to admin@example.com (20.9ms)
```

**Comment by dsander** [comment]
Do you get any output when running this?
```
foreman export runit -a huginn -l /home/huginn/huginn/log /etc/service
```

If that ran successfully check if there is a directory in `/etc/service/` for every service you configured in the `Procfile` and run `chown -R huginn:huginn /etc/service/huginn*`.

When that worked you should be able to proceed with the installation instructions.

**Comment by Taffer** [comment]
I'm thinking the installation only made it part-way through before hanging. At the **Ensure Your Huginn Instance Is Running** step:

```
$ sudo bundle exec rake production:status
rake aborted!
'sv status huginn-jobs-1' exited with a non-zero return value: warning: huginn-jobs-1: unable to open supervise/ok: file does not exist
/home/huginn/huginn/lib/tasks/production.rake:85:in `run'
/home/huginn/huginn/lib/tasks/production.rake:77:in `block (2 levels) in run_sv'
/home/huginn/huginn/lib/tasks/production.rake:93:in `with_retries'
/home/huginn/huginn/lib/tasks/production.rake:76:in `block in run_sv'
/home/huginn/huginn/lib/tasks/production.rake:75:in `each'
/home/huginn/huginn/lib/tasks/production.rake:75:in `run_sv'
/home/huginn/huginn/lib/tasks/production.rake:47:in `block (2 levels) in <top (required)>'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => production:status
(See full trace by running task with --trace)
```

Running with `--trace` just gives a longer stack trace into rake's code.

**Comment by dsander** [comment]
I over read that you are using Ubuntu 18, installing `runit-systemd` might fix the issue.

**Comment by Taffer** [comment]
@dsander Looks like you've provided an excellent hint!

```shell
$ sudo bundle exec rake production:status
run: huginn-jobs-1: (pid 10676) 58s; run: log: (pid 10675) 58s
run: huginn-web-1: (pid 10678) 58s; run: log: (pid 10677) 58s
```

**Comment by Taffer** [comment]
Ok, I've got it installed, it's running, and I've got my `nginx` config going, I've been able to see Huginn's 404 page at least.

Thanks for your help!

**Comment by Azimoth** [comment]
Hi,
trying to install this on Gentoo I ran into a very similar looking problem. I don't know how to narrow the problem down further.

The information I have so far:
`sudo bundle exec rake production:check` warns about
`WARNING: Nokogiri was built against LibXML version 2.9.10, but has dynamically loaded 2.9.9`, but still produces:

`[ OK ] Everything is fine`

Running `foreman export runit -a huginn -l /home/huginn/huginn/log /etc/service` leads to the output underneath.
The logs are all empty as far as I can see...

sudo bundle exec rake production:status also returns:
```
WARNING: Nokogiri was built against LibXML version 2.9.10, but has dynamically loaded 2.9.9
rake aborted!
'sv status huginn-web-1' exited with a non-zero return value: fail: huginn-web-1: unable to change to service directory: file does not exist
/home/huginn/huginn/lib/tasks/production.rake:85:in `run'
/home/huginn/huginn/lib/tasks/production.rake:77:in `block (2 levels) in run_sv'
/home/huginn/huginn/lib/tasks/production.rake:93:in `with_retries'
/home/huginn/huginn/lib/tasks/production.rake:76:in `block in run_sv'
/home/huginn/huginn/lib/tasks/production.rake:75:in `each'
/home/huginn/huginn/lib/tasks/production.rake:75:in `run_sv'
/home/huginn/huginn/lib/tasks/production.rake:47:in `block (2 levels) in <top (required)>'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => production:status
(See full trace by running task with --trace)
```
_____________________
> [foreman export] creating: huginn-web-1
> [foreman export] creating: huginn-web-1/env
> [foreman export] creating: huginn-web-1/log
> [foreman export] writing: huginn-web-1/run
> [foreman export] setting huginn-web-1/run to mode 493
> [foreman export] writing: huginn-web-1/env/APP_SECRET_TOKEN
> [foreman export] writing: huginn-web-1/env/DOMAIN
> [foreman export] writing: huginn-web-1/env/PORT
> [foreman export] writing: huginn-web-1/env/DATABASE_ADAPTER
> [foreman export] writing: huginn-web-1/env/DATABASE_RECONNECT
> [foreman export] writing: huginn-web-1/env/DATABASE_NAME
> [foreman export] writing: huginn-web-1/env/DATABASE_POOL
> [foreman export] writing: huginn-web-1/env/DATABASE_USERNAME
> [foreman export] writing: huginn-web-1/env/DATABASE_PASSWORD
> [foreman export] writing: huginn-web-1/env/DATABASE_ENCODING
> [foreman export] writing: huginn-web-1/env/RAILS_ENV
> [foreman export] writing: huginn-web-1/env/FORCE_SSL
> [foreman export] writing: huginn-web-1/env/INVITATION_CODE
> [foreman export] writing: huginn-web-1/env/SKIP_INVITATION_CODE
> [foreman export] writing: huginn-web-1/env/REQUIRE_CONFIRMED_EMAIL
> [foreman export] writing: huginn-web-1/env/ALLOW_UNCONFIRMED_ACCESS_FOR
> [foreman export] writing: huginn-web-1/env/CONFIRM_WITHIN
> [foreman export] writing: huginn-web-1/env/MIN_PASSWORD_LENGTH
> [foreman export] writing: huginn-web-1/env/RESET_PASSWORD_WITHIN
> [foreman export] writing: huginn-web-1/env/LOCK_STRATEGY
> [foreman export] writing: huginn-web-1/env/MAX_FAILED_LOGIN_ATTEMPTS
> [foreman export] writing: huginn-web-1/env/UNLOCK_STRATEGY
> [foreman export] writing: huginn-web-1/env/UNLOCK_AFTER
> [foreman export] writing: huginn-web-1/env/REMEMBER_FOR
> [foreman export] writing: huginn-web-1/env/IMPORT_DEFAULT_SCENARIO_FOR_ALL_USERS
> [foreman export] writing: huginn-web-1/env/SMTP_DOMAIN
> [foreman export] writing: huginn-web-1/env/SMTP_USER_NAME
> [foreman export] writing: huginn-web-1/env/SMTP_PASSWORD
> [foreman export] writing: huginn-web-1/env/SMTP_SERVER
> [foreman export] writing: huginn-web-1/env/SMTP_PORT
> [foreman export] writing: huginn-web-1/env/SMTP_AUTHENTICATION
> [foreman export] writing: huginn-web-1/env/SMTP_ENABLE_STARTTLS_AUTO
> [foreman export] writing: huginn-web-1/env/SEND_EMAIL_IN_DEVELOPMENT
> [foreman export] writing: huginn-web-1/env/EMAIL_FROM_ADDRESS
> [foreman export] writing: huginn-web-1/env/AGENT_LOG_LENGTH
> [foreman export] writing: huginn-web-1/env/TWITTER_OAUTH_KEY
> [foreman export] writing: huginn-web-1/env/TWITTER_OAUTH_SECRET
> [foreman export] writing: huginn-web-1/env/THIRTY_SEVEN_SIGNALS_OAUTH_KEY
> [foreman export] writing: huginn-web-1/env/THIRTY_SEVEN_SIGNALS_OAUTH_SECRET
> [foreman export] writing: huginn-web-1/env/GITHUB_OAUTH_KEY
> [foreman export] writing: huginn-web-1/env/GITHUB_OAUTH_SECRET
> [foreman export] writing: huginn-web-1/env/TUMBLR_OAUTH_KEY
> [foreman export] writing: huginn-web-1/env/TUMBLR_OAUTH_SECRET
> [foreman export] writing: huginn-web-1/env/DROPBOX_OAUTH_KEY
> [foreman export] writing: huginn-web-1/env/DROPBOX_OAUTH_SECRET
> [foreman export] writing: huginn-web-1/env/WUNDERLIST_OAUTH_KEY
> [foreman export] writing: huginn-web-1/env/WUNDERLIST_OAUTH_SECRET
> [foreman export] writing: huginn-web-1/env/EVERNOTE_OAUTH_KEY
> [foreman export] writing: huginn-web-1/env/EVERNOTE_OAUTH_SECRET
> [foreman export] writing: huginn-web-1/env/USE_EVERNOTE_SANDBOX
> [foreman export] writing: huginn-web-1/env/AWS_ACCESS_KEY_ID
> [foreman export] writing: huginn-web-1/env/AWS_ACCESS_KEY
> [foreman export] writing: huginn-web-1/env/AWS_SANDBOX
> [foreman export] writing: huginn-web-1/env/FARADAY_HTTP_BACKEND
> [foreman export] writing: huginn-web-1/env/DEFAULT_HTTP_USER_AGENT
> [foreman export] writing: huginn-web-1/env/ENABLE_INSECURE_AGENTS
> [foreman export] writing: huginn-web-1/env/ENABLE_SECOND_PRECISION_SCHEDULE
> [foreman export] writing: huginn-web-1/env/SCHEDULER_FREQUENCY
> [foreman export] writing: huginn-web-1/env/EVENT_EXPIRATION_CHECK
> [foreman export] writing: huginn-web-1/env/TIMEZONE
> [foreman export] writing: huginn-web-1/env/FAILED_JOBS_TO_KEEP
> [foreman export] writing: huginn-web-1/env/DELAYED_JOB_MAX_RUNTIME
> [foreman export] writing: huginn-web-1/env/DELAYED_JOB_SLEEP_DELAY
> [foreman export] writing: huginn-web-1/log/run
> [foreman export] setting huginn-web-1/log/run to mode 493
> [foreman export] creating: huginn-jobs-1
> [foreman export] creating: huginn-jobs-1/env
> [foreman export] creating: huginn-jobs-1/log
> [foreman export] writing: huginn-jobs-1/run
> [foreman export] setting huginn-jobs-1/run to mode 493
> [foreman export] writing: huginn-jobs-1/env/APP_SECRET_TOKEN
> [foreman export] writing: huginn-jobs-1/env/DOMAIN
> [foreman export] writing: huginn-jobs-1/env/PORT
> [foreman export] writing: huginn-jobs-1/env/DATABASE_ADAPTER
> [foreman export] writing: huginn-jobs-1/env/DATABASE_RECONNECT
> [foreman export] writing: huginn-jobs-1/env/DATABASE_NAME
> [foreman export] writing: huginn-jobs-1/env/DATABASE_POOL
> [foreman export] writing: huginn-jobs-1/env/DATABASE_USERNAME
> [foreman export] writing: huginn-jobs-1/env/DATABASE_PASSWORD
> [foreman export] writing: huginn-jobs-1/env/DATABASE_ENCODING
> [foreman export] writing: huginn-jobs-1/env/RAILS_ENV
> [foreman export] writing: huginn-jobs-1/env/FORCE_SSL
> [foreman export] writing: huginn-jobs-1/env/INVITATION_CODE
> [foreman export] writing: huginn-jobs-1/env/SKIP_INVITATION_CODE
> [foreman export] writing: huginn-jobs-1/env/REQUIRE_CONFIRMED_EMAIL
> [foreman export] writing: huginn-jobs-1/env/ALLOW_UNCONFIRMED_ACCESS_FOR
> [foreman export] writing: huginn-jobs-1/env/CONFIRM_WITHIN
> [foreman export] writing: huginn-jobs-1/env/MIN_PASSWORD_LENGTH
> [foreman export] writing: huginn-jobs-1/env/RESET_PASSWORD_WITHIN
> [foreman export] writing: huginn-jobs-1/env/LOCK_STRATEGY
> [foreman export] writing: huginn-jobs-1/env/MAX_FAILED_LOGIN_ATTEMPTS
> [foreman export] writing: huginn-jobs-1/env/UNLOCK_STRATEGY
> [foreman export] writing: huginn-jobs-1/env/UNLOCK_AFTER
> [foreman export] writing: huginn-jobs-1/env/REMEMBER_FOR
> [foreman export] writing: huginn-jobs-1/env/IMPORT_DEFAULT_SCENARIO_FOR_ALL_USERS
> [foreman export] writing: huginn-jobs-1/env/SMTP_DOMAIN
> [foreman export] writing: huginn-jobs-1/env/SMTP_USER_NAME
> [foreman export] writing: huginn-jobs-1/env/SMTP_PASSWORD
> [foreman export] writing: huginn-jobs-1/env/SMTP_SERVER
> [foreman export] writing: huginn-jobs-1/env/SMTP_PORT
> [foreman export] writing: huginn-jobs-1/env/SMTP_AUTHENTICATION
> [foreman export] writing: huginn-jobs-1/env/SMTP_ENABLE_STARTTLS_AUTO
> [foreman export] writing: huginn-jobs-1/env/SEND_EMAIL_IN_DEVELOPMENT
> [foreman export] writing: huginn-jobs-1/env/EMAIL_FROM_ADDRESS
> [foreman export] writing: huginn-jobs-1/env/AGENT_LOG_LENGTH
> [foreman export] writing: huginn-jobs-1/env/TWITTER_OAUTH_KEY
> [foreman export] writing: huginn-jobs-1/env/TWITTER_OAUTH_SECRET
> [foreman export] writing: huginn-jobs-1/env/THIRTY_SEVEN_SIGNALS_OAUTH_KEY
> [foreman export] writing: huginn-jobs-1/env/THIRTY_SEVEN_SIGNALS_OAUTH_SECRET
> [foreman export] writing: huginn-jobs-1/env/GITHUB_OAUTH_KEY
> [foreman export] writing: huginn-jobs-1/env/GITHUB_OAUTH_SECRET
> [foreman export] writing: huginn-jobs-1/env/TUMBLR_OAUTH_KEY
> [foreman export] writing: huginn-jobs-1/env/TUMBLR_OAUTH_SECRET
> [foreman export] writing: huginn-jobs-1/env/DROPBOX_OAUTH_KEY
> [foreman export] writing: huginn-jobs-1/env/DROPBOX_OAUTH_SECRET
> [foreman export] writing: huginn-jobs-1/env/WUNDERLIST_OAUTH_KEY
> [foreman export] writing: huginn-jobs-1/env/WUNDERLIST_OAUTH_SECRET
> [foreman export] writing: huginn-jobs-1/env/EVERNOTE_OAUTH_KEY
> [foreman export] writing: huginn-jobs-1/env/EVERNOTE_OAUTH_SECRET
> [foreman export] writing: huginn-jobs-1/env/USE_EVERNOTE_SANDBOX
> [foreman export] writing: huginn-jobs-1/env/AWS_ACCESS_KEY_ID
> [foreman export] writing: huginn-jobs-1/env/AWS_ACCESS_KEY
> [foreman export] writing: huginn-jobs-1/env/AWS_SANDBOX
> [foreman export] writing: huginn-jobs-1/env/FARADAY_HTTP_BACKEND
> [foreman export] writing: huginn-jobs-1/env/DEFAULT_HTTP_USER_AGENT
> [foreman export] writing: huginn-jobs-1/env/ENABLE_INSECURE_AGENTS
> [foreman export] writing: huginn-jobs-1/env/ENABLE_SECOND_PRECISION_SCHEDULE
> [foreman export] writing: huginn-jobs-1/env/SCHEDULER_FREQUENCY
> [foreman export] writing: huginn-jobs-1/env/EVENT_EXPIRATION_CHECK
> [foreman export] writing: huginn-jobs-1/env/TIMEZONE
> [foreman export] writing: huginn-jobs-1/env/FAILED_JOBS_TO_KEEP
> [foreman export] writing: huginn-jobs-1/env/DELAYED_JOB_MAX_RUNTIME
> [foreman export] writing: huginn-jobs-1/env/DELAYED_JOB_SLEEP_DELAY
> [foreman export] writing: huginn-jobs-1/log/run
> [foreman export] setting huginn-jobs-1/log/run to mode 493
> [foreman export] creating: huginn-dj2-1
> [foreman export] creating: huginn-dj2-1/env
> [foreman export] creating: huginn-dj2-1/log
> [foreman export] writing: huginn-dj2-1/run
> [foreman export] setting huginn-dj2-1/run to mode 493
> [foreman export] writing: huginn-dj2-1/env/APP_SECRET_TOKEN
> [foreman export] writing: huginn-dj2-1/env/DOMAIN
> [foreman export] writing: huginn-dj2-1/env/PORT
> [foreman export] writing: huginn-dj2-1/env/DATABASE_ADAPTER
> [foreman export] writing: huginn-dj2-1/env/DATABASE_RECONNECT
> [foreman export] writing: huginn-dj2-1/env/DATABASE_NAME
> [foreman export] writing: huginn-dj2-1/env/DATABASE_POOL
> [foreman export] writing: huginn-dj2-1/env/DATABASE_USERNAME
> [foreman export] writing: huginn-dj2-1/env/DATABASE_PASSWORD
> [foreman export] writing: huginn-dj2-1/env/DATABASE_ENCODING
> [foreman export] writing: huginn-dj2-1/env/RAILS_ENV
> [foreman export] writing: huginn-dj2-1/env/FORCE_SSL
> [foreman export] writing: huginn-dj2-1/env/INVITATION_CODE
> [foreman export] writing: huginn-dj2-1/env/SKIP_INVITATION_CODE
> [foreman export] writing: huginn-dj2-1/env/REQUIRE_CONFIRMED_EMAIL
> [foreman export] writing: huginn-dj2-1/env/ALLOW_UNCONFIRMED_ACCESS_FOR
> [foreman export] writing: huginn-dj2-1/env/CONFIRM_WITHIN
> [foreman export] writing: huginn-dj2-1/env/MIN_PASSWORD_LENGTH
> [foreman export] writing: huginn-dj2-1/env/RESET_PASSWORD_WITHIN
> [foreman export] writing: huginn-dj2-1/env/LOCK_STRATEGY
> [foreman export] writing: huginn-dj2-1/env/MAX_FAILED_LOGIN_ATTEMPTS
> [foreman export] writing: huginn-dj2-1/env/UNLOCK_STRATEGY
> [foreman export] writing: huginn-dj2-1/env/UNLOCK_AFTER
> [foreman export] writing: huginn-dj2-1/env/REMEMBER_FOR
> [foreman export] writing: huginn-dj2-1/env/IMPORT_DEFAULT_SCENARIO_FOR_ALL_USERS
> [foreman export] writing: huginn-dj2-1/env/SMTP_DOMAIN
> [foreman export] writing: huginn-dj2-1/env/SMTP_USER_NAME
> [foreman export] writing: huginn-dj2-1/env/SMTP_PASSWORD
> [foreman export] writing: huginn-dj2-1/env/SMTP_SERVER
> [foreman export] writing: huginn-dj2-1/env/SMTP_PORT
> [foreman export] writing: huginn-dj2-1/env/SMTP_AUTHENTICATION
> [foreman export] writing: huginn-dj2-1/env/SMTP_ENABLE_STARTTLS_AUTO
> [foreman export] writing: huginn-dj2-1/env/SEND_EMAIL_IN_DEVELOPMENT
> [foreman export] writing: huginn-dj2-1/env/EMAIL_FROM_ADDRESS
> [foreman export] writing: huginn-dj2-1/env/AGENT_LOG_LENGTH
> [foreman export] writing: huginn-dj2-1/env/TWITTER_OAUTH_KEY
> [foreman export] writing: huginn-dj2-1/env/TWITTER_OAUTH_SECRET
> [foreman export] writing: huginn-dj2-1/env/THIRTY_SEVEN_SIGNALS_OAUTH_KEY
> [foreman export] writing: huginn-dj2-1/env/THIRTY_SEVEN_SIGNALS_OAUTH_SECRET
> [foreman export] writing: huginn-dj2-1/env/GITHUB_OAUTH_KEY
> [foreman export] writing: huginn-dj2-1/env/GITHUB_OAUTH_SECRET
> [foreman export] writing: huginn-dj2-1/env/TUMBLR_OAUTH_KEY
> [foreman export] writing: huginn-dj2-1/env/TUMBLR_OAUTH_SECRET
> [foreman export] writing: huginn-dj2-1/env/DROPBOX_OAUTH_KEY
> [foreman export] writing: huginn-dj2-1/env/DROPBOX_OAUTH_SECRET
> [foreman export] writing: huginn-dj2-1/env/WUNDERLIST_OAUTH_KEY
> [foreman export] writing: huginn-dj2-1/env/WUNDERLIST_OAUTH_SECRET
> [foreman export] writing: huginn-dj2-1/env/EVERNOTE_OAUTH_KEY
> [foreman export] writing: huginn-dj2-1/env/EVERNOTE_OAUTH_SECRET
> [foreman export] writing: huginn-dj2-1/env/USE_EVERNOTE_SANDBOX
> [foreman export] writing: huginn-dj2-1/env/AWS_ACCESS_KEY_ID
> [foreman export] writing: huginn-dj2-1/env/AWS_ACCESS_KEY
> [foreman export] writing: huginn-dj2-1/env/AWS_SANDBOX
> [foreman export] writing: huginn-dj2-1/env/FARADAY_HTTP_BACKEND
> [foreman export] writing: huginn-dj2-1/env/DEFAULT_HTTP_USER_AGENT
> [foreman export] writing: huginn-dj2-1/env/ENABLE_INSECURE_AGENTS
> [foreman export] writing: huginn-dj2-1/env/ENABLE_SECOND_PRECISION_SCHEDULE
> [foreman export] writing: huginn-dj2-1/env/SCHEDULER_FREQUENCY
> [foreman export] writing: huginn-dj2-1/env/EVENT_EXPIRATION_CHECK
> [foreman export] writing: huginn-dj2-1/env/TIMEZONE
> [foreman export] writing: huginn-dj2-1/env/FAILED_JOBS_TO_KEEP
> [foreman export] writing: huginn-dj2-1/env/DELAYED_JOB_MAX_RUNTIME
> [foreman export] writing: huginn-dj2-1/env/DELAYED_JOB_SLEEP_DELAY
> [foreman export] writing: huginn-dj2-1/log/run
> [foreman export] setting huginn-dj2-1/log/run to mode 493
>

**Comment by dsander** [comment]
That looks like an issue with the `runit` installation, check if both `/etc/service` and `/service` exist. We don't support Gentoo in the manual installation guide, it's probably easier to install Huginn using Docker.

**Comment by Azimoth** [comment]
`/etc/service` does exist, `/service` does not. How can I check the runit installation? And how is it supposed to be configured?

I must admit, I'm not very familiar with Docker. Using Docker would mean to use the web server and database included in the container, rather than my systems install, right?
I'd prefer to be able to update especially nginx and mariaDB independent from some container maintainer...

**Comment by dsander** [comment]
You can try to create `/service` and run the export again.

**Comment by Azimoth** [comment]
I got it working!

Step 1: take the `runit.service` file from the .deb file and put it in `/etc/systemd/system/` after installing runit --> runit-systemd on Gentoo

Step 2: Create the `/service` folder as a SYMLINK to to `/etc/service`
`ln -s /etc/service/ /service`
(I guess this could be done more elegantly by changing the appropriate part of some config)

(Step 3: create a symlink from the webroot to `/home/huginn/huginn/public`, but I assume this depends on the webserver config, which I simply copied over from my old machine, so I just put that there again)

Thx for the hint with `/etc/service` and `/service`, @dsander!
