### ISSUE TITLE
In order to get right <pubDate>, I added `TIMEZONE=Shanghai` to `mysql.env`, But it doesn't work. I using docker-compose install it.

### ISSUE THREAD

**Issue by Derekmini** [huginn/huginn#2423]
In order to get right <pubDate>, I added `TIMEZONE=Shanghai` to `mysql.env`, But it doesn't work.

I use 
`git clone https://github.com/huginn/huginn`, 
to get the [docker single-process source file](https://github.com/huginn/huginn/blob/master/docker/single-process),
then 
`cd huginn/docker` and `nano mysql.env`, 
to add `TIMEZONE=Shanghai` at the end of the file,
finally 
`cd huginn/docker/single-process`, and `docker-compose up` to start to install.

But it didn't work, and there is an infinite restarting of the docker container.

SO I want to know how to set a `TIMEZONE` by using docker-compose?

Thank you!

**Comment by Derekmini** [comment]
<pubDate> zone change? [#2308](https://github.com/huginn/huginn/issues/2308)
By using the setting in the #2308 , it works well ! So, if someone wants set your own TIMEZONE using docker-compose install method, you could add `HUGINN_TIMEZONE=Beijing` or somewhere else to the end of `mysql.env` if you use mysql as your outer database.

**Comment by dsander** [comment]
Please don't use the legacy `HUGINN_` prefix. `TIMEZONE` will work as well. It would be cleaner to add that to the `secrets.env` file so it only affects the Huginn containers, alternatively you can add a third `.env` file [here](https://github.com/huginn/huginn/blob/master/docker/single-process/docker-compose.yml#L23) and [there](https://github.com/huginn/huginn/blob/master/docker/single-process/docker-compose.yml#L33).

**Comment by Derekmini** [comment]
yea! It does work! And modifing `secrets.env` could avoid affecting other container whitch use mysql as their database. Thanks very much, I have get this method! ^o^
