### ISSUE TITLE
WebAgent - Read events from html calendar

### ISSUE THREAD

**Issue by 8bitgentleman** [huginn/huginn#2429]
I am trying to scrape events from an html calendar [Like this](https://thebrooklynstrategist.com/schedule/) and I'm not sure how to output each event with the date that it occurs on.  

Since each day has multiple entries how would I output an event that has the title, time, and date of the entry? I imagine each event output would look something like this

```
{ 
"date": "...", 
"time": "..", 
"title": "...", 
"url": "..." 
}
```
Thanks!

**Comment by dsander** [comment]
That one is a bit tricky. I think you need to chain two WebsiteAgents. First extract the dates and the HTML content containing all events for that date. Send that data, which should look something like `{"date": "Monday, December 03, 2018", "html": "a bunch of html"}`, to a second WebsiteAgent with `data_from_event` set to `{{ html }}` and extract the individual events. You can either use `mode` `merge` on the second Agent or use the `template` option to add the date to the individual event Events.

**Comment by 8bitgentleman** [comment]
This worked for me, thanks!
