### ISSUE TITLE
Extract data from gzip xml file

### ISSUE THREAD

**Issue by kornflex** [huginn/huginn#2430]
Hello,

With the website agent, I'm trying to extract data from XML file but the URL used return a GZIP xml file.
So before trying to extract with Huginn, I have manually download and extract the xml file and try to get a data.
It works.

So now, I'm trying to give the right URL but the file is gzipped.
I have add this command : "unzip" : "gzip"
Nothing return.

But if I put :  "unzip" : "zip" I have an error : wrong compression format.

So Huginn seems to understand, and tell me if I'm wrong but it doesn't return my data.

Could you help me please ?

**Comment by dsander** [comment]
Can you share the URL of the XML file? When `unzip` is used Huginn will try do decompress the returned body using gzip.

**Comment by dsander** [comment]
Can you share the URL of the XML file? When `unzip` is used Huginn will try do decompress the returned body using gzip.

**Comment by kornflex** [comment]
Hello,
Thank you. I have tried with an other xml file, smaller and it's works.
