### ISSUE TITLE
Can huginn do the same thing Website Watcher does?

### ISSUE THREAD

**Issue by majestique** [huginn/huginn#2432]
Basically I can bulk import thousands of links into website watcher and it will detect and alert me if the link has any changes (without considering HTML tags -- just content)

Can Huginn do the same thing? I need to be able to bulk import links and alert me if there's a content change in the website. I don't want to manually set each link.

Also, what if the page has Ajax/Javascript content, can it process those?

Website Watcher -https://www.aignes.com/features.htm

**Comment by dsander** [comment]
The `WebsiteAgent` can monitor a site for changes. An extractor like
```
    "text": {
      "css": "body",
      "value": "normalize-space(.)"
    },
```
will emit events as soon as any of the test changed. To automate the creation of Agents you can use the (undocumented) JSON API or create the Agents in the database directly.

 Huginn itself is not able to scrape pages build via Javascript, but you can use [fulldom-server](https://github.com/strugee/fulldom-server) or https://phantomjscloud.com/ to do extraction based on the final page that has been generated by the JavaScript.

**Comment by majestique** [comment]
Thanks for the clarity!
