### ISSUE TITLE

Liquid - Key within Key

### ISSUE THREAD

**Issue by 8bitgentleman** [huginn/huginn#2436]
I have a merged event coming in that looks similar to this.

```
{
  "selected_option":"key2",
  "all_options":{
    "key1":"value1",
    "key2":"value2",
    "key3":"value3"
  }
}

```

The "selected_option" regularly changes but "all_options" is always the same.

How would I use liquid formating to get the value with the "selected_option" key? I've tried something like this
 
```
{{ all_options.{{ selected_option }} }}
```

 but it returns everything from "all_options" and not the specific key:value that I need.

**Comment by dsander** [comment]
I think `{{ all_options[selected_option] }}` should work.

**Comment by 8bitgentleman** [comment]
C'est parfait! Thanks!
