### ISSUE TITLE
WebsiteAgent :Error when fetching url: "\x8C" on EUC-KR

### ISSUE THREAD

**Issue by lilytumblr** [huginn/huginn#2444]
Hello,
One of my website agents used to work very well and fetch articles but it now outputs this error. Tried googling this error but cannot find any info on this.

**Comment by dsander** [comment]
Hi,

have you tried setting `"force_encoding": "utf-8"` in your Agent options? Sometimes webservers respond the wrong content encoding which then confuses the Agent.

**Comment by lilytumblr** [comment]
Thank you. Will try your method too if it happens again. I solved it not long after by changing to a different ip of the huginn.
