### ISSUE TITLE
Post Agent don't work

### ISSUE THREAD

**Issue by fanweiya** [huginn/huginn#2446]
thanks

**Comment by dsander** [comment]
Try removing the `content_type` from your Agent configuration. When you set it manually your are overriding the default configuration:

> By default, non-GETs will be sent with form encoding (application/x-www-form-urlencoded).

> When content_type contains a MIME type, and payload is a string, its interpolated value will be sent as a string in the HTTP request’s body and the request’s Content-Type HTTP header will be set to content_type.

**Comment by fanweiya** [comment]
thank you @dsander , But After I deleted it, After I deleted it, there was still no JSON message returned.
[![QQ截图20190103204708.png](https://i.loli.net/2019/01/03/5c2e047a4c107.png)](https://i.loli.net/2019/01/03/5c2e047a4c107.png)

**Comment by dsander** [comment]
You have `emit_events` set to `false`, which means the Agent will not create any Events. When you change it to `true` you should see the response.
