### ISSUE TITLE
JSON::ParserError 784

### ISSUE THREAD

**Issue by didier1969** [huginn/huginn#2450]
This is probably easy, but I cannot get it to work...

I am fetching a JSON from an IOT. As a result, I get this:

`  {
    "power": 14.627669334411621,
    "relay": true,
    "temperature": 20.437118530273438
  }`

I am trying to pass only the "temperature" tag to a peak detector agent, by using a Json Parse Agent.

The Json Parse Agent has "{{temperature}}" under Data field and "data" under Data key field, but I am always getting this message in the logs:

`{
  "data": "{{temperature}}",
  "data_key": "data"
}`

`Could not parse JSON: JSON::ParserError '784: unexpected token at '20.37446403503418''`

Any help would be appreciated.

**Comment by dsander** [comment]
That JSON looks valid to me, can you post the full Event payload that is send to the JsonParseAgent from either the Events or the source Agents detail page?

**Comment by didier1969** [comment]
Thanks for your kind help. Here is some additional info:

![image](https://user-images.githubusercontent.com/2456309/50682657-de33c780-100f-11e9-84be-fe645d650f39.png)

![image](https://user-images.githubusercontent.com/2456309/50682530-70879b80-100f-11e9-9934-14a0897a84de.png)

![image](https://user-images.githubusercontent.com/2456309/50682594-a593ee00-100f-11e9-8a60-1e3c0f98e03e.png)

![image](https://user-images.githubusercontent.com/2456309/50682627-c65c4380-100f-11e9-8458-bb1672577fc3.png)

![image](https://user-images.githubusercontent.com/2456309/50682710-03283a80-1010-11e9-8e45-dffd369b45c2.png)

**Comment by dsander** [comment]
Ah! You don't need the JsonParseAgent. The JSON has already been parsed by the WebsiteAgent, you can access the temperature in the "Hystou hot" Agent via `{{temperature}}`.

**Comment by didier1969** [comment]
Excellent ! Many thanks !!!
