### ISSUE TITLE
can i get system status without login

### ISSUE THREAD

**Issue by feilongfl** [huginn/huginn#2468]
Is there a way to read the system state (such as the number of job queues or the number of failures job) without logging in?

![screenshot 2019-01-18 at 10 48 14](https://user-images.githubusercontent.com/10269596/51362473-c0d22380-1b0e-11e9-889a-368759f634b3.png)

**Comment by dsander** [comment]
Not at the moment, but you can use [that scenario](https://huginnio.herokuapp.com/scenarios/19) to acquire a cookie and then use a WebsiteAgent to make a request to `/worker_status?since_id=1737361`

**Comment by feilongfl** [comment]
@dsander thanks for your reply.i will try this method.
