### ISSUE TITLE
Question: Possible to multiply incoming event?

### ISSUE THREAD

**Issue by trepmal** [huginn/huginn#2469]
This is probably easiest to explain with my scenario:

I'm sending automated SMS messages, driven by RSS, to a handful of friends.

I have an RSS Agent which checks a feed, then that message is passed to multiple Twilio Agents. This works fine, but is a minor nuisance to add more recipients.

I could use Shell Command Agent and create a standalone script that loops through the phone numbers and fires off Twilio requests. But I'm wondering if there's a more elegant way.

I'm thinking of something like RSS Agent -> Event Multiplier (multiplies RSS event by some factor, in my case a list of recipients) -> Twilio Agent.

This doesn't seem to be quite the same as #262 or #287

**Comment by dsander** [comment]
An alternative to the ShellCommandAgent would be the JavascriptAgent, but apart from those I don't think we have another option.

Your suggested Agent would be configured with an array of strings/object and re-emit the received event for every entry in it?

**Comment by trepmal** [comment]
> Your suggested Agent would be configured with an array of strings/object and re-emit the received event for every entry in it?

I've only had one coffee so far this morning, but that sounds like what I was imagining.

I'll check out the JavaScript Agent, I don't think I've looked at that one before.

**Comment by trepmal** [comment]
Just to follow up for anyone else stumbling across this issue, I was able to accomplish my goal using the following in with the JavaScript Agent:

```
var phones = [
  '+15555550001',
  '+15555550002,
  '+15555550003',
];

Agent.receive = function() {
  var events = this.incomingEvents();
  for(var i = 0; i < events.length; i++) {
    for(var x = 0; x < phones.length; x++) {
      this.createEvent({
        'message': events[i].payload.description,
        'toNumber' : phones[x]
      });
    }
  }
}
```
