### ISSUE TITLE
DB name should be escaped during migration

### ISSUE THREAD

**Issue by ehrlichja** [huginn/huginn#2480]
When running the db migration, a dash in the database name causes a syntax error:

``` -- execute("ALTER DATABASE leda-db CHARACTER SET utf8 COLLATE utf8_unicode_ci")```
causes
```Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-db CHARACTER SET utf8 COLLATE utf8_unicode_ci' at line 1```

I can reproduce this in a mysql console. I can also see that running 

```ALTER DATABASE `leda-db` CHARACTER SET utf8 COLLATE utf8_unicode_ci"``` (escaping the database name) succeeds.

Mysql 5.7, and I am using the huginn/huginn-single-process docker image.

**Comment by dsander** [comment]
Thanks for reporting the issue, mysql never stops surprising me 😄

**Comment by anouarattn** [comment]
I had the same error when using **huginn-db** as a database name, I changed it to **huginn_db** and the error disappeared
