### ISSUE TITLE
Enable easy integration with APIs available via rapidapi[.]com

### ISSUE THREAD

**Issue by ch40s** [huginn/huginn#2483]
RapidAPI is the world’s largest API marketplace with over 500,000 developers and 8,000 APIs. Making integration between Huginn and RapidAPI easier would help Huginn scale much faster. Users would be able to easily add more agents and integrate with so many services on their Huginn instances without having to create new agents from scratch.

**Comment by dsander** [comment]
Can you please add the suggestion to the [Official Agent Suggestions Thread](https://github.com/huginn/huginn/issues/353)? I just pinned the issue to make it easier to discover.
