### ISSUE TITLE
Dynamically match regex to input value in TriggerAgent

### ISSUE THREAD

**Issue by a10kiloham** [huginn/huginn#2484]
Trying to build a TriggerAgent to do a text match - input text (call it SearchQuery) would be a variable containing Foo and I want to match against another text variable (call it SearchResult). This is for a decision tree so I've two TriggerAgents one using regex the other !regex with different paths to create an account or match an existing account. But I need the regex to match on returned search results - I only want to return whether or not there's a full word(s) match so it would match "Foo Company" but not on "Food Company". Could someone suggest a path to best handle? TriggerAgent works great now except I can't seem to use a Liquid variable inside the regex itself.
Cheers

**Comment by dsander** [comment]
You can use liquid in the configuration of the TriggerAgent, it will get interpolated with the incoming event:

```json
{
  "expected_receive_period_in_days": "2",
  "keep_event": "false",
  "rules": [
    {
      "type": "regex",
      "value": "foo\\d+{{match}}",
      "path": "test"
    }
  ],
  "message": "Looks like your pattern matched in '{{test}}'!"
}
```
This event will cause it to trigger:
```
{
  "test": "foo123bar",
  "match": "bar"
}
```

**Comment by a10kiloham** [comment]
Amazing, thank you! I hadn't tried that - I'd assumed the curly braces wouldn't work. I'll check in a PR to clarify in the wording on that agent too.
