### ISSUE TITLE
Pushover doesn't include the source event payload as message

### ISSUE THREAD

**Issue by ch40s** [huginn/huginn#2485]
Hi there,
the pushover agent doesn't include the source event payload in the message. What's the proper value for the "message" option to make that work? I don't want to have a static messages but the source agent's output or event payload instead. `{{ message }}` for some reason doesn't work.

**Comment by ch40s** [comment]
@cantino could you possibly assist on this?

**Comment by cantino** [comment]
For some reason my Pushover Agent looks like this, but I'm not entirely sure why.

```
{
  "token": "TOKEN",
  "user": "USER",
  "message": "{% capture _default_ %}{{message}}{{text}}{% endcapture %}{{ message | default: text | default: _default_ }}",
  "device": "{{ device }}",
  "title": "{% capture _default_ %}Huginn says{% endcapture %}{{ title | default: subject | default: _default_ }}",
  "url": "{{ url }}",
  "url_title": "{{ url_title }}",
  "timestamp": "{{ timestamp }}",
   ...
}
```

**Comment by ch40s** [comment]
Interesting! Mine worked only twice and sent only two notifications out. For whatever reason new events are getting ignored.

Mine looks like this:
```
{
  "token": "",
  "user": "",
  "message": "{{ message }}",
  "device": "{{ device }}",
  "title": "{{ title }}",
  "url": "{{ url }}",
  "url_title": "{{ url_title }}",
  "priority": "{{ priority }}",
  "timestamp": "{{ timestamp }}",
  "sound": "{{ sound }}",
  "retry": "{{ retry }}",
  "expire": "{{ expire }}",
  "html": "false",
  "expected_receive_period_in_days": "1"
}
```

**Comment by ch40s** [comment]
Using your entry works fine!
