### ISSUE TITLE
Cannot reference field in DataOutputAgent for RSS output

### ISSUE THREAD

**Issue by fmeehan** [huginn/huginn#2490]
Hi, 

I am trying to generate an rss feed from a CSV report, that changes every day. 

Up to sending the CSV to the DataOutputAgent, no problem. 

Here is an event that is fed to DataOutputAgent: 
```
{
  "1crm": {
    "Nom": "Marie-Andrée Prévost",
    "Account": null,
    "Assigned": "admin",
    "Office": null,
    "Email": null,
    "Date": null
  }
}
```
Here his the config of my DataOutputAgent 
```
{
  "secrets": [
    "mysecretkey",
    "hissecretkey",
    "yoursecretkey"
  ],
  "expected_receive_period_in_days": 2,
  "template": {
    "title": "1crm Activity Report",
    "description": "Latest Activities in 1crm",
    "item": {
      "Nom": "{{Nom}}",
      "Nom du compte": "{{Account}}",
      "Assigné à": "{{Assigned}}",
      "Téléphone": "{{Office}}",
      "Courriel": "{{Email}}",
      "Dernière activité": "{{Date}}"
    }
  },
  "ns_media": "false"
}
```
Here is the output on Chrome:

{"title":"1crm Activity Report","description":"Latest Activities in 1crm","pubDate":"2019-02-12T10:12:19.775-05:00","items":[{"Nom":"","Nom du compte":"","Assigné à":"","Téléphone":"","Courriel":"","Dernière activité":"","guid":{"contents":330,"isPermaLink":"false"},"pubDate":"Tue, 12 Feb 2019 08:36:06 -0500"}

Fields are empty :-( 

I am pretty sure it is a simple newbie problem with Liquid, can someone help me please? 

Thanks in advance, 

François

**Comment by dsander** [comment]
Hi!

You need to use the whole "path" to the variable of your Event, try using `{{1crm.Nom}}`.

**Comment by fmeehan** [comment]
Ha! 

Thanks a million Sir!
