### ISSUE TITLE
Support for adding multiple account credentials in .env?

### ISSUE THREAD

**Issue by lilytumblr** [huginn/huginn#2493]
Hi,
I am using huginn twitter publish agent to automate a lot stuff with many twitter accounts. Sometimes tweets fail and output "User is over daily status update limit." In .env, OAuth Configuration setting, is it possible to add multiple twitter app credentials so it can use a different app credentials when one app hits the limit?  How complicated is that? Is this achievable by adding/changing a few codes manually and if possible, how? Thank you.

**Comment by dsander** [comment]
Hi,

I am not 100% certain, but I think the Twitter limits are per user, not per application. You should be able to authenticate multiple twitter users using the same application and work around the limits that way.

**Comment by lilytumblr** [comment]
Hi,
Yes. I have added multiple twitter accounts with same application and when the limit hits, it causes all twitter accounts to stop posting at that time period. The error messages I mentioned are the same and are for all twitter accounts. The limit is lifted automatically after some time. But still I wish there is another solution such like allowing multiple twitter app credentials to ease this problem. Can huginn achieve this?

**Comment by dsander** [comment]
Uh, that is annoying. You can try adding this to [`config/initializers/devise.rb`](https://github.com/huginn/huginn/blob/master/config/initializers/devise.rb#L241) if Huginn starts with that change and the second twitter services shows up in the services page the callback url should be `http://<your-huginn-domain.com>/auth/twitter2/callback`

```ruby
  if defined?(OmniAuth::Strategies::Twitter) &&
     (key = ENV["TWITTER_OAUTH_KEY2"]).present? &&
     (secret = ENV["TWITTER_OAUTH_SECRET2"]).present?
    config.omniauth :twitter2, key, secret, authorize_params: {force_login: 'true', use_authorize: 'true'}, strategy_class: OmniAuth::Strategies::Twitter
  end
```

**Comment by lilytumblr** [comment]
Hi,
After changing the code in devise.rb and adding TWITTER_OAUTH_KEY2 ,TWITTER_OAUTH_SECRET2 to .env file, filling the 2 credentials, exporting changes and restarting huginn, this error occured "Not found. Authentication passthru“ ,when i tried to visit http://someurl/auth/twitter2/, What could be wrong?
At twitter side, i set the callback url: http://someurl/auth/twitter2/callback
In my huginn instance, http://someurl/services  it does show a hyperlink  http://someurl/auth/twitter2 (no twitter button image)

**Comment by dsander** [comment]
Looks like it needs a more changes, replace [this line]() with:
```
 when *(Devise.omniauth_providers + [:twitter2])
```

I hope that is everything 😄

**Comment by lilytumblr** [comment]
Thank you.😄
But this line is not pointing to anywhere..

**Comment by dsander** [comment]
Woups, sorry I updated my comment 😊

**Comment by lilytumblr** [comment]
Still the same error...Maybe need more changes? 😥

**Comment by lilytumblr** [comment]
I tried to find some logs:
Started GET "/auth/twitter2" 
 Processing by OmniauthCallbacksController#passthru as HTML
 Rendering text template
 Rendered text template(0.0ms)
 Completed 404 Not Found in 1ms (Views: 0.5ms | ActiveRecord: 0.0ms)
Hope this will provide more info.

**Comment by dsander** [comment]
That was annoying to debug, I got it working by changing the first snippet to this:

```ruby
  if defined?(OmniAuth::Strategies::Twitter) &&
     (key = ENV["TWITTER_OAUTH_KEY2"]).present? &&
     (secret = ENV["TWITTER_OAUTH_SECRET2"]).present?
    config.omniauth :twitter2, key, secret, authorize_params: {force_login: 'true', use_authorize: 'true'}, request_path: '/auth/twitter2', callback_path: '/auth/twitter2/callback', strategy_class: OmniAuth::Strategies::Twitter
  end
```

Additionally you need to use different Twitter users for the two applications because our code uses the authentication provider name to create Huginn services. Logging into both apps using the same Twitter account will override the previous service.

**Comment by lilytumblr** [comment]
Thank you so much! I am able to authenticate with a second app successfully this time.
But encountered "Could not authenticate you" error when publishing tweets from the second app.(I already deleted twitter account authorization of the first app beforehand from somerurl/Services) 
After this error, I tried to delete the first set of credentials(TWITTER_OAUTH_KEY=something,TWITTER_OAUTH_SECRET=something)from .env and restart huginn, then I find all the twitter publish agents were deactivated, with red words "Missing Gems". But I guess this shouldn't happen to twitter agents authorized with that second app. Maybe the second set of credentials (TWITTER_OAUTH_KEY2=something,TWITTER_OAUTH_SECRET2=something) are not called when publishing tweets(still using the first set of credentials)?
Could you have a further check if you can publish tweets with that second app?  😄❤

**Comment by dsander** [comment]
Sorry, I wasn't aware that the Twitter API requires the [consumer key and secrect (what we call `TWITTER_OAUTH_KEY` and `TWITTER_OAUTH_SECRET`)](https://github.com/huginn/huginn/blob/master/app/concerns/twitter_concern.rb#L22-L28) to make calls. Many APIs that use the OAuth flow only require a token that is issued after authenticating. In theory you could modify those lines to use `:twitter2` instead of `:twitter` but then only the second application would be used.
I don't see an easy way for Huginn to support multiple applications.
If you _really_ want it you could copy the `twitter_concern.rb` to `twitter_concern2.rb` and rename `TwitterConcern` to `TwitterConcern2`. Then create duplicates of all the `twitter_*_agent.rb` agents in a similar factionm, replace ` include TwitterConcern` with ` include TwitterConcern2` and fianlly have one `TwitterConcern` use `:twitter` and the other use `:twitter2`.

At this point I think it might be easier to have a second Huginn instance forwarding the Twitter Events via a `WebhookAgent`.

**Comment by lilytumblr** [comment]
Hi,
Here is what i did: 
copy `twitter_concern.rb`, rename it to `twitter_concern2.rb`, open it, change `TwitterConcern` to `TwitterConcern2`,change provider name `twitter` to `twitter2`,change `TWITTER_OAUTH_KEY` and `TWITTER_OAUTH_SECRET` to `TWITTER_OAUTH_KEY2` and `TWITTER_OAUTH_SECRET2`

In another folder, copy `twitter_publish_agent.rb`, rename it to `twitter_publish_agent2.rb`, open it, change `include TwitterConcern` to `include TwitterConcern2`
export and restart huginn
Using a second twitter app to publish tweet is a success. But this time the first app outputs "Could not authenticate you", also when opening any twitter agent,there is no way to toggle twitter accounts, no drop down list,just empty. Creating new agent goes wrong, its output "We're sorry, but something went wrong."
But I am not sure if what i did in the above procedures are totally right, or have I missed anything.  Thank you again for the generous help!:)

**Comment by dsander** [comment]
> change `TWITTER_OAUTH_KEY` and `TWITTER_OAUTH_SECRET` to `TWITTER_OAUTH_KEY2` and `TWITTER_OAUTH_SECRET2`

If you want to use both accounts you need two sets of those credentials, the original one for the first application and the second for the second.

```
# Those will be used by the "original" Huginn Twitter agents
TWITTER_OAUTH_KEY=
TWITTER_OAUTH_SECRET=
# Those by the copies you created and included `TwitterConcern2`
TWITTER_OAUTH_KEY2=
TWITTER_OAUTH_SECRET2=
```


> We're sorry, but something went wrong.

Can you provide the exception logged to [the production log file](https://github.com/huginn/huginn/blob/master/doc/manual/installation.md#rails-application-log-homehuginnhuginnlogproductionlog)?

**Comment by lilytumblr** [comment]
Hi,
The error msg from the log file is:
Started GET "/agents/new" 
Processing by AgentsController#new as HTML
Rendering agents/new.html.erb within layouts/application
Rendered agents/_form.html.erb (20.1ms)
Rendered agents/new.html.erb within layouts/application (21.4ms)
Completed 500 Internal Server Error in 26ms (ActiveRecord: 0.4ms)
 FATAL -- :ActionView::Template::Error (uninitialized constant Agents::TwitterPublishAgent2

And yes , I set those 2 sets of credentials in .env file too.

**Comment by dsander** [comment]
Do you have `twitter_publish_agent2.rb` as a copy of `twitter_publish_agent.rb` in `app/models/agents` with [those two lines](https://github.com/huginn/huginn/blob/master/app/models/agents/twitter_publish_agent.rb#L2-L3) modified to:
```ruby
  class TwitterPublishAgent2 < Agent
    include TwitterConcern2
```
?

**Comment by lilytumblr** [comment]
After doing that,
I am able to create new agents, and I noticed a new agent Twitter Publish Agent2 but when configuring Service, there's no drop down list to pick any twitter account (and still no drop down list after I authorized one twitter account to the second app in huginnappurl/services)

**Comment by dsander** [comment]
At least we are past the exceptions 😄 I found another line that needs to be altered in the `twitter_concern2.rb` file: https://github.com/huginn/huginn/blob/master/app/concerns/twitter_concern.rb#L8. Change that to
```ruby
    valid_oauth_providers :twitter2
```

**Comment by lilytumblr** [comment]
😄, Yes I have already done that. I also changed the ones at line 10,23,27 and 51.  The only problem is that when creating Twitter Publish Agent2, there is no way to toggle or add any twitter account.  therefore there's no way to finish creating it. The workaround i used is making a copy of the original `twitter_concern.rb` as `twitter_concern2.rb`, and only changing the first line to `TwitterConcern2`, restart huginn, and then create Twitter Publish Agent2, after that changing the rest code on `twitter_concern2.rb` and restart in order to make it work with a second app.  Just some remaining glitches to fix but I am not able to find where to modify else myself😄

**Comment by dsander** [comment]
Sorry for the late reply. I think the problem is the way we are creating the omniauth services in the database. We store them based on the provider name, not the name we gave them, i.e. services for your second twitter application are also stored with the name `twitter` and not `twitter2`. 

It might work if you change `valid_oauth_providers :twitter2` in `twitter_concern2.rb` back to `:twitter`. I am assuming that the dropdown will then show all twitter accounts from both application.s

**Comment by lilytumblr** [comment]
It all works now! Thank you so so much for the help!😄😄😄❤❤❤
