### ISSUE TITLE
Is there any way to update credential with Liquid Output Agent using HTML page?

### ISSUE THREAD

**Issue by aaassseee** [huginn/huginn#2494]
Hi, I am currently using Liquid Output Agent to generate a HTML page for users to edit information. Can I use JavaScript within Liquid Output Agent content to change the Huginn credential?

**Comment by dsander** [comment]
Not as easy as it is in the `JavaScriptAgent`, if the users are logged into Huginn it should be possible to send an ajax request to the credentials update endpoint.

**Comment by aaassseee** [comment]
How if the user didn't login in?

**Comment by dsander** [comment]
Maybe send a ajax request to a WebhookAgent?

**Comment by aaassseee** [comment]
thanks!
