### ISSUE TITLE
Can't send email from Docker container

### ISSUE THREAD

**Issue by uisge-beatha** [huginn/huginn#2495]
Hello, 

I'm unable to send emails from the latest docker container of huginn/huginn (pulled last night). I'm receiving the error: "535-5.7.8 Username and Password not accepted" which I believe to be erroneous.  My email host provides detailed access logs and it shows no failed SMTP attempts. Attempts to validate the username and password outside of huginn work as expected and appear in the SMTP access logs. 

Here are the environmental variables I passed to the container:

SMTP_USER_NAME=first.last%domain
SMTP_PASSWORD=somepassword
SMTP_SERVER=mail.runbox.com
SMTP_PORT=465
SMTP_AUTHENTICATION=login
SMTP_ENABLE_STARTTLS_AUTO=true
SEND_EMAIL_IN_DEVELOPMENT=true
EMAIL_FROM_ADDRESS=email@domain

I've tried fidgeting with the port and authentication settings per issue #676 with no luck (the same settings work in an email client).  

Any thoughts on what I could be doing wrong?

**Comment by dsander** [comment]
Hi,

the configuration looks valid to me, what sounds odd is that your provider does not show any login requests. Can you try a different provider? Here is my configuration that works with sendgrind:

```
SMTP_USER_NAME=username
SMTP_PASSWORD=password
SMTP_SERVER=smtp.sendgrid.net
SMTP_PORT=587
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=true
````

**Comment by uisge-beatha** [comment]
Hi dsander, 

Thanks. Per your suggestion, I configured another, this time an Apple iCloud account. I haven't found a setting to view failed attempts in iCloud, but it once again failed with settings that work outside the container. I've already tried that configuration with my Runbox account. I can ping both of the smtp servers from bash sessions in the container. 

Regards

-Brad

**Comment by dsander** [comment]
Hmm, that is odd, can you share how you are starting your container?

**Comment by uisge-beatha** [comment]
I'm starting it via the Docker service on Synology DSM (fully patched). It's a busy box based OS if memory serves. Going to try and run the container via docker on my Mac after work.

**Comment by uisge-beatha** [comment]
So, it seems that having /etc/localtime mounted in ro mode was the root cause. I removed that and added the TZ environmental variable. That resolved the issue. Thanks for your help!
