### ISSUE TITLE
How to turn a relative hyperlink into an absolute hyperlink with WebsiteAgent/ EventFormattingAgent?

### ISSUE THREAD

**Issue by LeonLuchs** [huginn/huginn#2496]
I tried a lot to solve this problem but didn't find a solution. How can I transform a relative hyperlink into an absolute hyperlink? I'd like Huggin to email me the website information and then simply click on the link to get to the website. In principle, it works. I get the email and can read the titles but I can't click due to the relative link. Thanks for help!

I did the following:

WebsiteAgent
```
{
  "expected_update_period_in_days": "2",
  "url": "https://www.reddit.com/r/programming/",
  "type": "html",
  "mode": "all",
  "extract": {
    "headline": {
      "css": "#t3_au6i4u .kCqBrs",
      "value": ".//text()"
    },
    "link": {
      "css": "#t3_au6i4u .SQnoC3ObvgnGjWt90zD9Z",
      "value": "@href"
    }
  }
}
```

EventFormattingAgent
```
{
  "instructions": {
    "message": "<b>{{headline}}</b><br>{{link}}"
  },
  "matchers": [],
  "mode": "clean"
}
```

**Comment by johnleeming** [comment]
I have a similar situation where I use an event formatting agent of the following form:

```
{
  "instructions": {
    "body": "{{ body | replace: '<a href=\"', '<a href=\"https://xxx.yyy/zzz/'}}"
  },
  "mode": "clean"
}
```
where https://xxx.yyy/zzz/ is the stem of the relative URL.  This only works where teh relative urls are all from a known source.

**Comment by LeonLuchs** [comment]
Thank you for answering! But how can I put this into practice? I put your EventFormattingAgent-Form between the WebsiteAgent and the EmailDigestAgent but it doesn't find the hyperlink reference in the events stream to replace. It gives me empty values. What am I missing?

**Comment by johnleeming** [comment]
post an example output of your website agent?

Have you replaced "body" in my eventformatting agent by whatever field the url is in you event?

John Leeming

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by dsander** [comment]
We have the `to_uri` filter which does exactly that:

```json
{
  "expected_update_period_in_days": "2",
  "url": "https://www.reddit.com/r/programming/",
  "type": "html",
  "mode": "all",
  "extract": {
    "headline": {
      "css": "#t3_au6i4u .kCqBrs",
      "value": ".//text()"
    },
    "link": {
      "css": "#t3_au6i4u .SQnoC3ObvgnGjWt90zD9Z",
      "value": "@href"
    }
  },
  "template": {
    "link": "{{ link | to_uri: _response_.url }}"
  }
}
```

**Comment by LeonLuchs** [comment]
Thank you both very much! I didn't recognize the "to_uri" filter in the accompanying text in connection with url's. Nonetheless it works perfectly!
