### ISSUE TITLE
After install the pages loads but i cant sign in

### ISSUE THREAD

**Issue by whiznic** [huginn/huginn#2501]
I have installed huginn on a Debian 8 vps (2gb ram) as per the instructions on README file  and proceded to access it via a browser but i cant log into Huginn

[huginn_access.log](https://github.com/huginn/huginn/files/2926271/huginn_access.log)
[huginn_error.log](https://github.com/huginn/huginn/files/2926275/huginn_error.log

**Comment by dsander** [comment]
Did you do the steps mentioned in the [Install Init Script](https://github.com/huginn/huginn/blob/master/doc/manual/installation.md#install-init-script) step? The error log shows that the unicorn application server is not running.

If you still have problems please post the [other log files mentioned here](https://github.com/huginn/huginn/blob/master/doc/manual/installation.md#unicorn-log-homehuginnhuginnlogunicornlog)

**Comment by erebor** [comment]
@whiznic Could this issue be closed?

**Comment by whiznic** [comment]
yes close

**Comment by whiznic** [comment]
yes please close
