### ISSUE TITLE
Where's the huginn's local config file?

### ISSUE THREAD

**Issue by ron159** [huginn/huginn#2503]
I'm using huginn via the latest *docker image*.
After I use *Ctrl+c* stop the service and reuse the command to start huginn, the whole config has been **reset**,even the user and password?
is there any way to find the old config file? or what is the correct way to restart the service so that all the agents can be reserved
**Thanks!**

**Comment by dsander** [comment]
I am assuming you are the `huginn/huginn` image, check the [usage](https://github.com/huginn/huginn/tree/master/docker/multi-process#usage) section on how to link the Huginn container do a mysql or postgresql database.

**Comment by ron159** [comment]
> I am assuming you are the `huginn/huginn` image, check the [usage](https://github.com/huginn/huginn/tree/master/docker/multi-process#usage) section on how to link the Huginn container do a mysql or postgresql database.

Got it!Thanks for your help~😘
