### ISSUE TITLE
How to do a calculation like num1 / (num1 + num2) with format agent

### ISSUE THREAD

**Issue by redjumper** [huginn/huginn#2504]
How to do a calculation like num1 / (num1 + num2) with format agent, but in result logic the sum is always 0.  Thanks.
{
  "instructions": {
    "sum": "{{num1 plus num2}}",
    "result": "{% if num1 == 0 and num2 == 0 %}{{num1}} {% else %}{{num1 | times: 100.0 | divided_by: sum}} {% endif %}"
  },
  "mode": "merge"
}

**Comment by dsander** [comment]
The value of instructions are not available in other fields. Liquid's scope is limited to one field. 
I think you need to [capture](https://shopify.github.io/liquid/tags/variable/) the sum of the two numbers before your condition `{% capture sum %}{{num1 | plus: num2}}{% endcapture %}`. `sum` should then be available to be used as the divisor.

**Comment by redjumper** [comment]
Work like a charm, thanks.
