### ISSUE TITLE
Line Breaks in Telegram Message

### ISSUE THREAD

**Issue by hmnd** [huginn/huginn#2506]
I'm trying to figure out how to insert a line break in a Telegram text message. `\n` keeps getting escaped as `\\n`. Any suggestions?

**Comment by brianpetro** [comment]
Try `{% line_break %}`

https://github.com/huginn/huginn/wiki/Formatting-Events-using-Liquid#tags-added-by-huginn

**Comment by hmnd** [comment]
That worked! Thanks for the quick response!
