### ISSUE TITLE
How to format digest

### ISSUE THREAD

**Issue by icolab** [huginn/huginn#2517]
Hi, 

I did configure a digest from a dataoutput agent (RSS). It does work great. However, I would like to improve the content send by the digest. 
I try to use some liquid code:
```
{{events.title}}
{{events.url}}
{{events.description}}
```
Nontheless, the email I do received is not set up like expected, I have all the content of the output agent. 

Could you help me? 
Sincerely

**Comment by dsander** [comment]
Sorry for the massive delay I have been traveling last week and thought I would get work done, but didn't 😞 

Are  you using a `DigestAgent`? To work with the stored event you need to iterate over the events array 
```
{% for event in events %}
  {{event.title}}
  {{event.url}
{% endfor %}
```

**Comment by icolab** [comment]
Dear @dsander thanks for your answer, it's okay I wasn't in an hurry thanks a lot for your answer. 

I still have a lot of information like id, title, etc. but maybe (certainly) it's because I pushed the content to a rss agent and then I used Microsoft Flow to send e-mail. I'm going to try to set-up the smtp directly in Huginn in order to see if the result is better. 

Have a nice day
Sincerely

**Comment by icolab** [comment]
I succeed to send by email however, the content of the mail is still full of authors, categories, id and so one. 
I did specify on liquid that I would like only to have event.title et event.link without success

Sincerely

**Comment by dsander** [comment]
You can modify the email contents by setting the `body` option in you `EmailAgent`, if that value is not set the Agent will include the whole Event in the email.

**Comment by icolab** [comment]
Thanks, maybe I don't understand well how this work because it doesn't work. 

Here is what I did:
I have a RSS agent -> go to a trigger -> then a deduplication agent and after a digest agent configure with this configuration:
```
{
  "message": "{% for event in events %}\r\n  <event>\r\n    <title>{{ event.title }}<\/title>\r\n    <description>{{ event.description }}<\/description>\r\n    <pubDate>{{ post.date | date:\"%a, %d %b %Y %H:%M:%S %z\" }}<\/pubDate\r\n  <\/item>\r\n{% endfor %}",
  "expected_receive_period_in_days": "365",
  "retained_events": "0"
}
```
And the content go to an email digest agent:
```
{
  "subject": "You have some notifications!",
  "headline": "Your notifications:",
  "expected_receive_period_in_days": "365",
  "recipients": "xxxx@xxxxx",
  "body": "title", "description"
}
```

**Comment by dsander** [comment]
Are you sure you need a `DigestAgent` infront of a `EmailDigestAgent`? Normally generating a digest once should be enough.

```
  "body": "{% for event in events %}{{event.title}} {{event.url}}{% endfor %}"
````

should work for the `EmailDigestAgent`. For a `EmailAgent` you can skip the `for` loop and use just `{{event.title}} {{event.url}}`

**Comment by icolab** [comment]
Thanks for your answer. I'm going to try to see the result! 
Sincerely

**Comment by icolab** [comment]
Dear Dsander, it's strange I try both approach (with the loop and without) in the body however the e-mail is still full of content like that:

> 
> Le Bizlab, cet accélérateur de start-ups qui propulse Airbus dans le futur
> authors: ["MARINA ANGEL "]
> categories: []
> content: Le Global Summit du BizLab d'Airbus est le point d'orgue annuel du programme international d'accélération du groupe. 33 startups et intrapreneurs accompagnés par les équipes du Bizlab de Toulouse, Hambourg, Bangalore et Madrid ont été sélectionnées pour cette quatrième édition organisée à Blagnac. Pour [...] Lire l'article
> date_published: 2019-04-29T12:40:00+02:00
> description: Le Global Summit du BizLab d'Airbus est le point d'orgue annuel du programme international d'accélération du groupe. 33 startups et intrapreneurs accompagnés par les équipes du Bizlab de Toulouse, Hambourg, Bangalore et Madrid ont été sélectionnées pour cette quatrième édition organisée à Blagnac. Pour [...] Lire l'article
> enclosure: {"url"=>"https://www.usinenouvelle.com/mediatheque/0/4/4/000763440_image_256x170.jpg", "type"=>"image/jpg", "length"=>"0"}
> id: https://www.usinenouvelle.com/article/le-bizlab-cet-accelerateur-de-start-ups-qui-propulse-airbus-dans-le-futur.N836590
> image: https://www.usinenouvelle.com/mediatheque/0/4/4/000763440_image_256x170.jpg
> last_updated: 2019-04-29T12:40:00+02:00
> links: []
> url:
> urls: []
> /// Airbus établit un record d'endurance de 16 heures avec l'ACJ319neo
> authors: [""]
> categories: ["2019", "Airbus", "article buzz", "Avgeek", "Aviation d'affaires", "Constructeur", "Europe", "France", "Industrie", "Voyages d'Affaires", "✈︎", "ACJ", "ACJ319", "ACJ319neo", "airbus", "Allemagne", "CFM International", "K5 Aviation"]
> content: Le premier avion d'affaires du constructeur européen ACJ319neo a effectué avec succès le vendredi 26 avril un vol d'essai de 16 heures et 10 minutes, établissant un nouveau record du plus long vol de la famille A320 effectué par un équipage d'Airbus. Cette performance remarquable a été réalisée le lendemain du premier vol de l'avion...Lire la suite /// Airbus établit un record d'endurance de 16 heures avec l'ACJ319neo
> date_published: 2019-04-29T11:30:00+00:00
> description: Le premier avion d'affaires du constructeur européen ACJ319neo a effectué avec succès le vendredi 26 avril un vol d'essai de 16 heures et 10 minutes, établissant un nouveau record du plus long vol de la famille A320 effectué par un équipage d'Airbus. Cette performance remarquable a été réalisée le lendemain du premier vol de l'avion...Lire la suite /// Airbus établit un record d'endurance de 16 heures avec l'ACJ319neo
> enclosure:
> id: https://actu-aero.fr/?p=39006
> image:
> last_updated: 2019-04-29T11:30:00+00:00
> links: [{"href"=>"https://actu-aero.fr/2019/04/29/airbus-etablit-un-record-dendurance-de-16-heures-avec-lacj319neo/"}]
> url: https://actu-aero.fr/2019/04/29/airbus-etablit-un-record-dendurance-de-16-heures-avec-lacj319neo/
> urls: ["https://actu-aero.fr/2019/04/29/airbus-etablit-un-record-dendurance-de-16-heures-avec-lacj319neo/"]
> 

my digest email agent received the content from a de-duplication agent now.
Here is the agent:
```
{
  "subject": "Aircraft",
  "headline": "xxxx",
  "expected_receive_period_in_days": "365",
  "recipients": "xxx@xxxx",
  "body": "{{event.title}} {{event.url}}"
}
```

**Comment by iecompattest** [comment]
Check Check<https://www.msn.com/en-in/news/photos/the-20-richest-criminals-of-all-time/ss-AAufAue?ocid=spartanntp>
________________________________

**Comment by dsander** [comment]
I thought the `EmailDigestAgent` would accept the same parameters as the `EmailAgent`, but it doesn't:

> If the Events’ payloads contain a message, that will be highlighted, otherwise everything in their payloads will be shown.

It looks like the EmailDigestAgent will always include the full Event contents.

I think you need to chain the Agents like this `DeduplicationAgent` -> `DigestAgent` -> `EmailAgent`.

In the `DigestAgent` you should be able to use the loop to generate the `message`. The `EmailAgent`s `body` should then just be `{{message}}`.

**Comment by icolab** [comment]
Like this it does fonction! Thanks a lot for your help 

Have a nice day
