### ISSUE TITLE
Shell agent running on web_huginn instead of delayed_job(signle-process docker)

### ISSUE THREAD

**Issue by anouarattn** [huginn/huginn#2522]
Hi

it is normal that the Shell command agent run on web_huginn  container instead of delayed_job container ?

I'm using this command to check container id 
`cat /proc/self/cgroup | grep -o  -e "docker-.*.scope" | head -n 1 | sed "s/docker-\(.*\).scope/\\1/"
`

and it give me the id of web_huginn.

I use shell command to sleep events for long period using 'at' command and because I have lots of events I need that they run in delayed_job

Thanks for help

**Comment by dsander** [comment]
Hi,

the Agent should only run in the web container if you dry run it from the web interface. "Normal" Agent runs triggered by Events or a schedule should run in the delayed job container (that is assuming you are using the single-process images).

**Comment by anouarattn** [comment]
you are right, 

thanks
