### ISSUE TITLE
Website Agent on_change replace existing events on a key value property

### ISSUE THREAD

**Issue by Leosirth** [huginn/huginn#2528]
Hi,

I have a simple website agent that extract data from a page and notify me for changes, all is working fine but if a change is found how can I remove/replace the precedent event?

For example I have an event with 2 property:

{{name}} and {{version}}

let's say that yesterday the website agent create the event like

(name=Something version=1)

and today

(name=Something version=2)

a new event is emitted and it's OK, but I would like to remove the previous one (here my key is the name) or substitute the "version" property and re-emit this instead of having a new one.
How can I achieve this?

I'm assuming that the website agent with the "on_change" looks for changes in relation to previously emitted events, if that's not the case than I can simply add an expiration to my events.
Right now I have no expiration set in order to have the events always available to look for changes by the Website agent.

Thanks and regards,

**Comment by dsander** [comment]
Hi,



> but I would like to remove the previous one

That is not how Huginn works, you can imagine Events as a stream of data based on  with the receiving Agents do their actions. Modifying old Events is not supported.



> I'm assuming that the website agent with the "on_change" looks for changes in relation to previously emitted events

Kind of, the Agent is storing the previously extracted data in it "memory" and creates a new Event if the current extracted values differs from the one in the memory.

Can you share what you want to do with the generated Event?

**Comment by Leosirth** [comment]
Hi dsander,

thanks for the feedback.

I just want to get rid of old events once a new one is created.
To better explain I have the following webagent to scrape a website for change:
```
{
  "expected_update_period_in_days": "30",
  "url": "https://www.qnap.com/it-it/app_center/?II=235",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "appName": {
      "xpath": "//td[@class=\"top_td\"]/div[@class=\"title_place\"]/a",
      "value": "string(.)"
    },
    "type": {
      "xpath": "//td[@class=\"top_td\"]/div[@class=\"intro_place\"][1]/a",
      "value": "string(.)"
    },
    "category": {
      "xpath": "//td[@class=\"top_td\"]/div[@class=\"intro_place\"][2]/a",
      "value": "string(.)"
    },
    "version": {
      "xpath": "//td[@class=\"top_td\"]/div[@class=\"intro_place\"][3]/a",
      "value": "string(.)"
    }
  }
}
```
The emitted events are sent to a post agent in order to send me a notification when a new app version is found.

I have set the "Keep events: Forever"  for the website agent in order to always have an event available for each application to look for changes (I don't know how frequently an app could be updated).

In this scenario every time that a new app version is found a new event is triggered and propagated to the post agent, but the "old" version event will exist forever.

For example taking only the first application on the website, today I have the following:
```
{
  "appName": "Acronis True Image",
  "type": "consigliato",
  "category": "Backup/Sinc.",
  "version": "1.0.1"
}
```
If tomorrow a new version of the same application is released I will get the following new event:
```
{
  "appName": "Acronis True Image",
  "type": "consigliato",
  "category": "Backup/Sinc.",
  "version": "1.0.2"
}
```
At this point I would like to remove the previous one since no more useful and that otherwise will remain forever.

Thanks and regards,

**Comment by dsander** [comment]
> Kind of, the Agent is storing the previously extracted data in it "memory" and creates a new Event if the current extracted values differs from the one in the memory.

I checked the WebsiteAgent code and you are right, it needs the Events to determine if something changed.

The Agent also updates the previous Events expiry date, so you should be able to set a a short `keep events` interval. As long as it's longer than the `schedule` of the Agent it should keep the Events that match the extracted values.

**Comment by Leosirth** [comment]
Thank you dsander,

I will test it and update you.

Best regards,
