### ISSUE TITLE
Please update Liquid to version 4.02 and support the new filter "where"

### ISSUE THREAD

**Issue by tortoo** [huginn/huginn#2535]
I found Liquid had been updated to [version 4.02](https://github.com/Shopify/liquid/commit/8013df8ca2e25b72260d945f0d6bfb1484a7d04c) and added an new filter `where`. It's very functional and long-awaited. Please update and support it.😸

**Comment by dsander** [comment]
Sounds good to me, we are already using version `4.0.0` so bumping the version to `4.0.2` should not cause any issue. Do you mind sending a PR?

**Comment by tortoo** [comment]
@dsander First time to send a PR...Just modified the version and don't know what else should I do.😹
