### ISSUE TITLE
Unescape quotes in Post Agent

### ISSUE THREAD

**Issue by ygdar** [huginn/huginn#2542]
I need to send post request to a site which requires md5 hash for request payload string. But when huginn pass on payload from javascript agent to post agent, it's escaped quotes in json string
{"media":[{"type"
to this
{\\\"media\\\":[{\\\"type\\\"...
![Screenshot_1](https://user-images.githubusercontent.com/51164358/58562711-74bc8b80-8232-11e9-8d4f-704e1775937a.png)

I'm tried to encode string through encodeURIComponent and decode by url_decode, but it's also didn't work for me

How can i remove these backslashes, preferably without any custom filters?

**Comment by nigz** [comment]
Did you find a way to do it?
