### ISSUE TITLE
More check frequency

### ISSUE THREAD

**Issue by lourencofsilva-cs50** [huginn/huginn#2556]
Hey There!

Is there anyway that we can make huginn agents work by checking per every 5 seconds for example, instead of the limit of every minute?

Thanks!

**Comment by dsander** [comment]
Hi,

you can do that by using a `SchedulerAgent` to run your Agents. It offers much finer control over the check interval.

**Comment by lourencofsilva-cs50** [comment]
Thanks! That worked
