### ISSUE TITLE
DataOutputAgent RSS, how to switch page?

### ISSUE THREAD

**Issue by orange888** [huginn/huginn#2557]
Hi,
If I have 100 events/items in the DataOutputAgent (RSS), how to switch page?

For example, adding **?paged=2** to the url:
`https://xyz.com/users/1/web_requests/4/secret.json?paged=2`

Thanks.

**Comment by orange888** [comment]
> hit the wrong button

**Comment by dsander** [comment]
Hi,

the Agent does not support that. If your consumer calls the page to infrequent you can increase the `events_to_show`.

**Comment by orange888** [comment]
Thanks.
