### ISSUE TITLE
Liquid filters to grab url 'html tag'

### ISSUE THREAD

**Issue by rokhimin** [huginn/huginn#2559]
i use event formatting agent
example: `"description": "<img src=\"http://www.it-times.de/resources/dam/asset/5371/ittimes_news_detail.jpg\" /><br /> SUNNYVALE (IT-Times) - Das <br/>`
.
How to take url img `http://www.it-times.de/resources/dam/asset/5371/ittimes_news_detail.jpg`  ??

i searched filters command https://help.shopify.com/en/themes/liquid/filters but nothing matches .

i try `regex_replace` with https://stackoverflow.com/questions/6038061/regular-expression-to-find-urls-within-a-string . still can't work

**Comment by rokhimin** [comment]
```
 "instructions": {
    "description": "{{ description | replace: '<img src=\"', ''| regex_replace: '(?<=.jpg).+(?=\)', '' }}"
  }
```

maybe

**Comment by dsander** [comment]
You could also pass the Event to a a `WebsiteAgent`, configure `data_from_event` and extract the attribute using xpath or css selectors.
