### ISSUE TITLE
How to make as_object run in forloop?

### ISSUE THREAD

**Issue by tortoo** [huginn/huginn#2565]
I noticed that `` is the last filter in a Liquid expression [here](https://github.com/huginn/huginn/wiki/Formatting-Events-using-Liquid#filters-added-by-huginn). So I tested a lot and found that the filter after `` has no effect including one `` filter after the other one.

For example, in Digest Agent:

`"message": "{{ events[0] |  }}{{ events[1] |   }}"`

It only outputs the first event with index 0.

Maybe it's the reason the filter `as_object` can only output the first one in forloop. Then is there any way to make `as_object`  run in forloop?

**Comment by tortoo** [comment]
Theoretically this seems not to work. I've given up this way.

**Comment by dsander** [comment]
Hi,

I don't fully understand what you are trying to achieve, `as_object` is used when one wants to return the whole object as is. If you want to get all events `{{ events | as_object}}` should work.

**Comment by tortoo** [comment]
@dsander What I want is to update some value of the key with new event in Digest Agent and output that with a new object instead of string. Later I found that I probably need to add new key in the event. So object with json format is not realistic and I'm going to use string and Regular Expression.

**Comment by dsander** [comment]
Alright.
