### ISSUE TITLE
Is it possible to set a http_proxy in website agent?

### ISSUE THREAD

**Issue by LeonLuchs** [huginn/huginn#2566]
Is there a way to make setting up a proxy easier? For example instead of re-exporting the .env just to put a http_proxy to the website-agent (similar to user_agent)? If yes, how can I check this. Thanks.

**Comment by dsander** [comment]
From the code it looks like setting the `proxy` option should work.

**Comment by LeonLuchs** [comment]
Thank you! Seems to work.
