### ISSUE TITLE
The change you wanted was rejected

### ISSUE THREAD

**Issue by TheEagle13** [huginn/huginn#2569]
After a recent update, I can no longer login with chrome... I get the following error:
![image](https://user-images.githubusercontent.com/32144818/62062330-6ec13780-b1ee-11e9-9552-400f4b973ef7.png)

I can however login with firefox.

Chrome version: 75.0.3770.100 
Firefox Version: 68.0.1

**Comment by dsander** [comment]
If it works with one browser and not with the other I would suspect that one of the extensions installed is causing this. Can you try it in an incognito windows in chrome and/or disable all your extensions?

**Comment by TheEagle13** [comment]
Just tried in incognito with no extensions... same result. Pulling up the console shows the following error:
`Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)`

**Comment by dsander** [comment]
Are you using two reverse proxies? I just remembered I have the same issue with a different rails application that is proxied twice and I never got around fixing it.

**Comment by TheEagle13** [comment]
If there is a reverse proxy built into the docker image, I guess I am. But I didn't have any issues a month ago when I last logged in. Any idea how to resolve?

**Comment by dsander** [comment]
No, the docker images don't come with a reverse proxy. So are seeing this problem when Huginn in docker directly?

When I start the container with `docker run -it --rm -p 3000:3000 huginn/huginn` I have no issues logging using Chrome.

**Comment by TheEagle13** [comment]
It appears if I go directly to the the port it does allow me to login. However this is not a feasible for me on a regular basis with how my networks are setup, so I need to get this working again through the proxy like it was. Is there something I need to check to make sure the proxy is passing something that huginnn needs or not passing something it doesn't want?

**Comment by dsander** [comment]
When was the last time you updated Huginn? If id had been some time setting those headers in your proxy configuration might help: https://github.com/rails/rails/issues/22965#issuecomment-172929004

**Comment by TheEagle13** [comment]
I usually update Huginn every month (Or at least check for an update every month). 

That issue you referenced seems to not apply to my issue. Furthermore, in thinking more on this, it seems it cannot be an issue with the proxy, because it works just fine in other browsers. I'm thinking it has to deal with some recent update with the Chrome code, but I'm not sure what, or why it isn't playing nice with Huginn.

**Comment by dsander** [comment]
I can really pinpoint which update changed the behavior, but trust me it's the proxy configuration. You said the login works when bypassing the proxy and accessing the Huginn docker container directly and I saw the exact same behavior on my other Rails application: Login worked on Firefox but gave the "The change you wanted was rejected" error on Chrome. 

For me the fix was to pass the `X-Forwarded-Proto` header from the first proxy to the Rails application server in the configuration of the second proxy, if you are just using one proxy the configuration in the issue should work.

**Comment by TheEagle13** [comment]
OK, I did, I'm wrong.
However it does appear that if you are using HA proxy, you have to add the config to the back-end server, not the front-end, to work.

Thank you for taking the time to help a stubborn old guy like me!

**Comment by zblesk** [comment]
Thank you, I had the same issue. I do update regularly, but only after the last update (6 days ago) I encountered this exact issue. I am running a Docker image behind a nginx reverse proxy, which also terminates SSL. 
In case anyone else is looking for this, I added these headers (based on a post linked above) and it worked.

```
        location / {
                proxy_pass http://127.0.0.1:31337;
                proxy_set_header  Host $host;
                proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header  X-Forwarded-Proto $scheme;
                proxy_set_header  X-Forwarded-Port $server_port;
                proxy_set_header  X-Forwarded-Host $host;
        }
```

**Comment by michaelhull** [comment]
For HAProxy add the following to your Backend configuration:
```
  option forwardfor
  reqadd X-Forwarded-Proto:\ https
```

**Comment by yegle** [comment]
> For info, this problem also arises when you use the Cloudflare proxy in addition to a reverse proxy. (So it counts as a double proxy)

Hi, can you clarify why double proxy is an issue here and if you know a fix? Thank you!

**Comment by resurge** [comment]
> > For info, this problem also arises when you use the Cloudflare proxy in addition to a reverse proxy. (So it counts as a double proxy)
> 
> Hi, can you clarify why double proxy is an issue here and if you know a fix? Thank you!

I'm sorry, I don't remember anything from this issue any more.
I just checked my cloudflare config and my traefik config but can't see anything special that I did there.
Cloudflare *is* proxying the subdomain and traefik has the same config as my other services.
I can seem to access my huginn service through the browser.

Sorry I can't be more of help.
I don't actively use huginn that much any more.

**Comment by irfancharania** [comment]
I just switched to using Cloudflare and ran into this issue also. 

Here's what solved it for me in case anyone else runs into this:

1. Huginn .env FORCE_SSL = true
2. Cloudflare subdomain SSL set to Full
3. Force https in the location

```
 location / {
    proxy_read_timeout      300;
    proxy_connect_timeout   300;
    proxy_redirect          off;

    proxy_set_header    Host                $http_host;
    proxy_set_header    X-Real-IP           $remote_addr;
    proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
    proxy_set_header    X-Forwarded-Proto   https;
    proxy_set_header    X-Forwarded-Port    443;
    proxy_set_header    X-Forwarded-Host    $host;
    proxy_set_header    X-Frame-Options     SAMEORIGIN;

    proxy_pass http://huginn;
  }
```
