### ISSUE TITLE
Re-emit all?

### ISSUE THREAD

**Issue by elsurudo** [huginn/huginn#2570]
My use-case is that I have changed a downstream agent that filters these events, so I would like to re-run the filtering after the change (this will generate a different set of events for a further agent that the original set).

I don't see an option to re-emit all events from an agent, only one-at-a-time. It seems like useful functionality. If this is not currently possible, would you take a PR that added such functionality?

**Comment by elsurudo** [comment]
Related: https://github.com/huginn/huginn/issues/1344

Ideally, we should re-emit in batches somehow, so as not to overload the system.

**Comment by virtadpt** [comment]
I definitely have that occasional use case.
