### ISSUE TITLE
Telegram Agent set to 'split' for 'long_message' does not work for media without captions

### ISSUE THREAD

**Issue by chrigi** [huginn/huginn#2571]
When you set the Telegram Agent to 'truncate' long messages you can pass him a payload with only a e.g. a 'photo' field and **no** 'caption' but then you set the agent to 'split' long captions it will error out with the following message when you don't pass a 'caption' field in the event:
``` 
undefined method `scan' for nil:NilClass
/app/app/models/agents/telegram_agent.rb:137:in `send_telegram_messages'
```

This is because of a [missing existance check](https://github.com/huginn/huginn/blob/master/app/models/agents/telegram_agent.rb#L137) when handling the caption. It might also be good to add such a [check to 'text' type](https://github.com/huginn/huginn/blob/master/app/models/agents/telegram_agent.rb#L133) messages.

**Comment by erebor** [comment]
Can I get a 👍 or 👎 on this little PR?  If it needs changing, lemme know.
