### ISSUE TITLE
Parsing output of API

### ISSUE THREAD

**Issue by o---** [huginn/huginn#2576]
Can anybody help parsing the output of the following API? 

```
{
  "post_url": "https://be.wizzair.com/9.15.0/Api/search/search",
  "expected_receive_period_in_days": "1",
  "content_type": "json",
  "method": "post",
  "payload": {
    "isFlightChange": "false",
    "isSeniorOrStudent": "false",
    "flightList": [
      {
        "departureStation": "TIA",
        "arrivalStation": "DTM",
        "departureDate": "2019-09-28"
      },
      {
        "departureStation": "DTM",
        "arrivalStation": "TIA",
        "departureDate": "2019-10-01"
      }
    ],
    "dayInterval": 1,
    "adultCount": 1,
    "childCount": 0,
    "infantCount": 0
  },
  "headers": {
    "Content-Type": "application/json; charset=UTF-8",
    "Accept-Encoding": "gzip, deflate"
  },
  "emit_events": "true",
  "no_merge": "false",
  "output_mode": "clean"
}
```

What I am getting back is an quite complex with "\" escaped JSON 
```
{
  "body": "{\"outboundFlights\":[{\"departureStation\":\"TIA\",\"arrivalStation\":\"DTM ....
```
and so far I was unable to parse any variable out of it neither using **Trigger Agent** nor **Event Formatting Agent** 
Thanks

**Comment by johnleeming** [comment]
I used a javascript agent to parse a complex json returned by the pocket api
```
Agent.receive = function(){
	var events = this.incomingEvents();
	for(var i=0; i < events.length; i++){
		var event = events[i];
		var body = JSON.parse(event['payload']['body']);
		for(var item in body.list){
      
			  this.createEvent({ 'url':body.list[item]['resolved_url'], 'tag':'bad'});
		    this.log(body.list[item]['resolved_url'])
		    
		  
		}
	}
};
```

**Comment by o---** [comment]
Thank you @johnleeming, that's an interesting approach. I will give it a try. 

I have been able to make some progress passing the JSON from source to Trigger Agent:
`Post Agent -> Event Formatting Agent -> JSON Parse Agent -> Trigger Agent` 
where I have now the somewhat cleaned up body of the initial response. Now I am trying to figure out, how to use JSONXpath to traverse. So far no luck.

**Comment by dsander** [comment]
The response looks like normal JSON, i guess the response from the server does not include the correct content type which results in Huginn not parsing the JSON. I think you should be able to parse the body in a `JSONParseAgent`. How does the resulting event look?

**Comment by o---** [comment]
I guess there is several "ways to Rome". I succeeded with the idea of @johnleeming and used the Javascript agent to pull out the values I needed out of the JSON Response. I tried also other ways including JSONParseAgent, but with no luck. The resulting event is just Jabber Agent to sent a message.

**Comment by o---** [comment]
Managed to complete using Javascript agent. Thanks to all who tried to help. Much appreciated.

**Comment by wuyuansheng1982** [comment]
I have 2 Huginn tasks set up, the first to login to obtain the access token, the second to parse the output and set the credential key for use by other tasks.

The first job works fine, the parsing task works fine if I select dry run but nothing happens if I run the task. Any idea?
