### ISSUE TITLE
docker ssl not working

### ISSUE THREAD

**Issue by dreamflasher** [huginn/huginn#2578]
Running `sudo docker run -it -p 3131:3000 huginn/huginn` yields `SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG `

Can I specify SSL certificates for docker huginn somehow? I also tried reverse proxy, but that also resulted in errors.

**Comment by dsander** [comment]
You have to use a reverse proxy that handles the SSL termination. Which proxy with what configuration did you try?

**Comment by dreamflasher** [comment]
Thank you very much for your fast response. I use apache2 with the following config:

```
<VirtualHost *:443>
      ServerName mydomain.com
      ProxyPreserveHost On
      SSLEngine On

      Include /etc/letsencrypt/options-ssl-apache.conf
      SSLCertificateFile /etc/letsencrypt/live/domain/fullchain.pem
      SSLCertificateKeyFile /etc/letsencrypt/live/domain/privkey.pem

      ProxyPass / http://0.0.0.0:3131/
      ProxyPassReverse / http://0.0.0.0:3131/
</VirtualHost>

```

**Comment by dsander** [comment]
I don't know apache very well, but the configuration looks good to me, which error are you getting when trying to access the site?

**Comment by dreamflasher** [comment]
Currently I get `The page isn’t redirecting properly` and on server side `foreman stdout | 09:02:49 web.1  | 172.17.0.1 - - [10/Aug/2019:02:02:49 PDT] "GET / HTTP/1.1" 301 0`

**Comment by dreamflasher** [comment]
Ah, when I add `force_ssl=false` to the environment variables it works! Thank you for your help!

**Comment by dsander** [comment]
Ah! Nice I think you can also set those headers to tell the Rails application that it is proxies via SSL:

```
RequestHeader set X-FORWARDED-PROTOCOL https
RequestHeader set X-Forwarded-Ssl on
```

**Comment by dreamflasher** [comment]
How do I do that with docker?

**Comment by dsander** [comment]
Put them inside the `VirtualHost` block in your apache configuration.

**Comment by dreamflasher** [comment]
Oh that's perfect! Before it was redirecting to the http (and then failing), so I had to manually change it back to https, now it works even better than before!
