### ISSUE TITLE
JSONParseAgent Not Making Sense

### ISSUE THREAD

**Issue by Xinil** [huginn/huginn#2587]
Workflow I'm attempting: 
`POST authorize > POST accesstoken (with data from authorize) > POST sensor data (with data from accesstoken.)`

I have a PostAgent that posts to an API and the API returns application/json. The PostAgent options:

```
{
  "post_url": "https://api.sensorpush.com/api/v1/oauth/authorize",
  "expected_receive_period_in_days": "1",
  "content_type": "json",
  "method": "post",
  "payload": {
    "email": "??",
    "password": "??"
  },
  "emit_events": "true",
  "no_merge": "true",
  "output_mode": "clean"
}
```

The POST payload response is application/json:
```
{
    "authorization": "long-string-of-characters",
    "apikey": "more-characters"
}
```

The only capabilities I have to parse this information is to use {{ body }} in the `Data` field, which has unparsed JSON:  `{"body":"{\"authorization\":\"eyJraWQiOiJ1cy1lYXN0LTExIiwidHlwIjoiSldTIiwiYWxnIjoiUlM1MTIi`

That's not what I want, I only want `body.authorization`, or just `{{authorization}}` to pass on to my next agent (which needs it for another POST), but it complains about `[00:00:00] ERROR -- : Could not parse JSON: JSON::ParserError 'A JSON text must at least contain two octets!'`

Additional example of what Dry Run shows as the output from the source agent:
<img width="882" alt="Screenshot 2019-08-19 12 18 01" src="https://user-images.githubusercontent.com/1168011/63292959-bc741180-c27b-11e9-8f9e-e32cb81d3f38.png">

----

**Edit Update:** 
So it seems the 'body' issue is due to me using `emit_events:true` in the Post Agent. If I remove emit_events:true, my receiver agents no longer fire and I have no ability to inspect the logs.

I understand the problem to my original issue, but the way around it eludes me with the tools at my disposal. Is there not a clean way to do this in Huginn? Is there an example that details the magic? Much appreciated.

**Comment by dsander** [comment]
I would assume that a `JSONParseAgent` should be able to parse the data in body, it's cut off in the screenshot, but I would assume that it contains the full JSON. Can you post a complete Event that is emitted by the PostAgent?

**Comment by Xinil** [comment]
@dsander 
`{
    "body": "{\"authorization\":\"eyJraWQiOiJ1cyadfwidHlwIjoiSldTIiwiYMTIifQ..-x3oTO----wyd3ugLrqMFU--dNO-\",\"apikey\":\"us-east-1:5\"}",
    "status": 200,
    "headers": {
      "Content-Type": "application/json",
      "Content-Length": "923",
      "Connection": "keep-alive",
      "Date": "Thu, 22 Aug 2019 05:00:34 GMT",
    }
  }`

This is the event output emitted from the Post Agent (Authorize.) The JSON is escaped inside the body key, which I believe is preventing the JSON from parsing correctly? 

I appreciate the help!

**Comment by dsander** [comment]
Yes, the double quotes inside the `body` key are escaped, but that makes sense to keep the "outer" JSON valid. I was able to paste the whole event into the raw Dry-Run modal and send it  to a a JSONParseAgent configured with `data: {{body}}`.

**Comment by Xinil** [comment]
@dsander 
I understand that {{ body }} is parsed, but I want the key 'authorization' within the body text. Body by itself does not give me what I want. I've tried {{ body.authorization }} (as the shopify documentation states) but that fails with `[00:00:00] ERROR -- : Could not parse JSON: JSON::ParserError 'A JSON text must at least contain two octets!'` 

Again, I'm trying to get the actual data returned to me from my JSON API ('authorization' key.)

**Comment by dsander** [comment]
Yes, that is correct. The `JSONParseAgent` doesn't know anything about the JSON string, it can only parse it as a whole. If you want to access the `authorization` key of the parsed data you have to do it in an Agent downstream.

Feel free to reopen the issue of you have further questions.
