### ISSUE TITLE
phantomjscloud agent supports multiple urls?

### ISSUE THREAD

**Issue by lilytumblr** [huginn/huginn#2589]
In most situations website agents can do the job well and in many situations i only need to put ((url)) in the url setting to receive events. But if i need to set the phatomjscloud agent as the starting agent, and I need to put on multiple urls ,eg, something/page1, something/page2,something/page3,  But i cannot make it work.  Does it support multiple urls, if so what's the format. if not, how to achieve this.

**Comment by dsander** [comment]
Hi,

the `PhantomJSCloudAgent` only supports one url. You can either use multiple Agents or send the url in an Event to the Agent.

**Comment by lilytumblr** [comment]
Hi,
It would be simpler to use only one agent. But which agent should be used to send the urls. Can you give me an example. Thank you. It may sound like a silly question haa

**Comment by dsander** [comment]
Actually that is a pretty good question, the old good solution I can think of is a JavascriptAgent:

```
Agent.check = function() {
  let sites = [
    "http://google.com",
    "http://google.ca"
  ];
  sites.forEach(function (url) {
    this.createEvent({ 'url': url });
  }.bind(this))
};
```

**Comment by lilytumblr** [comment]
Thank you so much! it works.😄
