### ISSUE TITLE
Filter containing and not containing at the same time

### ISSUE THREAD

**Issue by Pcsl** [huginn/huginn#2591]
I assume and I am a completely clueless about filtering rules and that this question is probably out of scope of your rules section but your help would be greatly appreciated.

What I want to do is to match every post that contains the word "bus", "train" or "flight" as long as it doesn't include the word Greyhound but I have no idea how to make this possible in just one rule because I tried to use two rules but all post not containing "Greyhound".

My current Trigger Agent is as follows:

```
{
  "expected_receive_period_in_days": "2",
  "keep_event": "true",
  "rules": [
    {
      "type": "regex",
      "value": "bus|train|flight",
      "path": "content"
    }
  ],
  "message": "Looks like your pattern matched in '{{value}}'!"
}
```

**Comment by virtadpt** [comment]
Remove the "message" key from this agent.  "keep_event" will forward any matching events as-is.

Put another Trigger Agent after this one, type !regex, value "greyhound", with the path "$.content".

Generally speaking, try to break up tasks like this as much as possible.  Agents (in terms of system resources) are cheap, so use as many as you need.  Check the "Propagate immediately" box as necessary to get better response time (but don't use it all the time or you'll bog down the scheduler).

**Comment by dsander** [comment]
> Generally speaking, try to break up tasks like this as much as possible. Agents (in terms of system resources) are cheap, so use as many as you need.

That is very true.

In this particular case you could also add another rule to the `TriggerAgent` with `!regex` and value set to `greyhound`.

**Comment by Pcsl** [comment]
I never thought about using more than one agent to use different filters but it's indeed a clever idea.
Thank you both for your help!
