### ISSUE TITLE
Running Huginn via Docker on Chromebook with Crostini

### ISSUE THREAD

**Issue by davesgonechina** [huginn/huginn#2594]
It gives the following error:

`docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "setup user: invalid argument": unknown.`

My first guess is that this is because of the port forwarding in ChromeOS Crostini and that changes to the .env would resolve the issue, but not tried yet.

I tried Docker versions 18.06.01 and 18.09.01/02/03 as well as the latest below:
>Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:22:03 2019
 OS/Arch:           linux/amd64
 Experimental:      false
>Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:20:35 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc-chromeos:
  Version:          1.0.0-rc5+dev
  GitCommit:        a0b7d6dc09b58d2f44dd61c304a66d9249e56c8f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

Crostini:
`Linux penguin 4.19.34-04457-g5b63d4390e96 #1 SMP PREEMPT Mon May 13 14:30:19 PDT 2019 x86_64 GNU/Linux`

I also tried this `runc` fix but didn't help: https://www.reddit.com/r/Crostini/comments/9jabhq/docker_now_working/

**Comment by dsander** [comment]
How are you starting the container and what are the contents of your `.env` file?

**Comment by davesgonechina** [comment]
@dsander just using `docker run -it -p 3000:3000 huginn/huginn` and whatever .env is prebuilt within. I considered passing in my own .env but hadn't yet figured out what parameters would need to change.

**Comment by dsander** [comment]
Hmm that is odd, do other docker image work? The error message reads like it's something inside docker and not directly related to the huginn container/image.

**Comment by davesgonechina** [comment]
Yup, I tried the out-of-the-box Wordpress docker image and localhost:8080 worked fine.

**Comment by dsander** [comment]
Can you try starting the container with a different user?

Maybe `docker run --user `id -u` -it -p 3000:3000 huginn/huginn` or `docker run --user 1005 -it -p 3000:3000 huginn/huginn` works.

**Comment by davesgonechina** [comment]
1005 works, thank you!

**Comment by dsander** [comment]
Great!
