### ISSUE TITLE
Host key verification failed.

### ISSUE THREAD

**Issue by malagebidi** [huginn/huginn#2597]
`[
  {
    "command": "/bin/sh /tmp/r6300v2.sh",
    "path": "/",
    "exit_status": 255,
    "errors": "Host key verification failed.",
    "output": ""
  }
]`

why I'm always get this error by Shell Command Agent.

**Comment by dsander** [comment]
That sounds like your shell script is trying to make an ssh connection with host key checking enabled and the host key isn't known to the system already.
