### ISSUE TITLE
Is it possible to run huginn on a different VM than nginx?

### ISSUE THREAD

**Issue by adhishchugh** [huginn/huginn#2600]
If yes, can someone help me with the nginx configuration? 
I'm currently getting a 502 bad gateway error when I try to use a basic nginx config with a proxy pass. 
I'm not sure how to set the upstream to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket if that file is on a different VM. Same for root and some of the other properties.

**Comment by dsander** [comment]
Hi,

that will not work with the default configuration because NGINX is also serving static files. You need an NGINX server on the Huginn VM as well. The second server could then have `huginvm:80` as the upstream.

**Comment by adhishchugh** [comment]
Ah that makes sense. Thank you!
