### ISSUE TITLE
Some questions and suggestions about WebsiteAgent and DeDuplicationAgent

### ISSUE THREAD

**Issue by wuhgit** [huginn/huginn#2614]
I use huginn to generate RSS. and have many source websites, each website needs to use some separate WebsiteAgents to get the content, because last WebsiteAgent of each website have almost the same pattern, like get the article content then format it for output. every website have different way to format, I think it can work by calling different Credentials in the same WebsiteAgent, which not only save the resources and simplify the process also, but I found that the Liquid Templating of WebsiteAgent does not support Credentials. Is there any preparation for supporting this in the future?

Also for DeDuplicationAgent, the current DeDuplicationAgent has only one property. If I need to set multiple decisions, such as the same title and same content but URLs are different, the same URL but the title has some differences like the author modified it at some point but the article content is still the same. ,etc., I need to use multiple DeDuplicationAgents to filter. any possible to add multiple properties to this agent and then use AND or OR to make a decision?

**Comment by dsander** [comment]
> but I found that the Liquid Templating of WebsiteAgent does not support Credentials

That should work, we have the [`credential`](https://github.com/huginn/huginn/wiki/Formatting-Events-using-Liquid#tags-added-by-huginn) tag that you should be able to access credentials.



>  I need to use multiple DeDuplicationAgents to filter. any possible to add multiple properties to this agent and then use AND or OR to make a decision?

I think the easiest solution for that would be to put a `EventFormattingAgent` infront of the `DeDuplicationAgent` that combines the two fields you want the deduplication to be based on into a new field.

**Comment by wuhgit** [comment]
I am sorry that I did not describe the question clearly.My English is not well. I will describe this question in detail again.

Because each website has different ways to format the content, I want to store these methods in the corresponding Credentials. For example, website A uses Credentials named format_website_a , as follows:


```
Credentials Name : format_website_a
Mode: Text
Credential value ： {{content |split:'<div class="test">'|first|regex_replace..........(long content about regex and normal replace).........,""}}
```


when I call this Credentials in the webagent's Templating,like:


```
......
 "extract": {
    "content": {
      "path": "data.content",
      "value": "."
    }
......
template: {
"content": "{% credential format_website_a %}"
}
......
```

 the final output is the value of this Credentials not the content format with this template as my wish.

So I said the Liquid Templating of WebsiteAgent does not support Credentials

**Comment by dsander** [comment]
Understood, I don't think that this is something we can support. It would be pretty easy to get in an infinite loop when calling the same `credential` again in the contents of the credential. I think in general interpolating "twice" (i.e. running the interpolation based on the result of the previous interpolation) could also be a security risk because the first interpolation can contain data from anywhere.

**Comment by wuhgit** [comment]
you‘re right , I did not consider the situation that will fall into a loop
Thank you for your explanation.
