### ISSUE TITLE
DataOutputAgent escaping < to &tl;

### ISSUE THREAD

**Issue by Han-Orz** [huginn/huginn#2615]
Below is the JSON code for my DataOutputAgent
`{
  "secrets": [
    "mzitu"
  ],
  "expected_receive_period_in_days": "1",
  "template": {
    "title": "测试",
    "description": "……",
    "item": {
      "title": "{{title}}",
      "description": "{{img}}",
      "link": "{{url}}"
    },
    "link": "https://zcool.com.cn"
  }
}`

and
`{
  "url": "https://www.zcool.com.cn/work/ZNDAxMTI3NTY=.html",
  "title": "Figurama 《东京喰种 》雾岛董香VS月山习 1/6 雕像",
  "img": "<img src=\"https://img.zcool.cn/community/0158ab5daed3a0a801209e1f27e3da.jpg@1280w_1l_2o_100sh.jpg\" alt=\"Figurama 《东京喰种 》雾岛董香VS月山习 1/6 雕像\" width=\"700\" height=\"1245\">"
}`

then, in output .XML, i get that
`<description>&tl;scr img="https://img.zcool.cn/community/0158ab5daed3a0a801209e1f27e3da.jpg@1280w_1l_2o_100sh.jpg" alt="Figurama 《东京喰种 》雾岛董香VS月山习 1/6 雕像" width="700" height="1245"&gt;</description>`

so, it doesn't work in RSS reader——like reeder4. I don't know how to do.

**Comment by dsander** [comment]
I think that is intended to prevent XSS, @knu might know more about it.

You could use a `LiquidOutputAgent` and generate the RSS XML manually.

**Comment by knu** [comment]
`&tl;` instead of `&lt;`?  That's weird and something I've never seen.

**Comment by knu** [comment]
I have no idea how `<img src="https://img.z…` could possibly be encoded to `&tl;scr img="https://img.z`.  Is that the exact string copy-and-pasted from your browser, not hand-written?  In the latter case, there might be an invisible RTL control characters hidden somewhere.

**Comment by Han-Orz** [comment]
……
I decided to use LiquidoutputAgent, which should be more in line with my requirements.
