### ISSUE TITLE
Twitter.com

### ISSUE THREAD

**Issue by MGWVc** [huginn/huginn#2617]
Hello Security and Safety My account was rest ricted and then stopped during the follow-up and did not violate the laws of Twitter and did not breach the privacy and security Help me restore and control the account and thank you for your cooperation with me and find appropriate solutions @Jack should just keep me posted teach you Really out of order that @Twitter Support can suspend your account without even putting the reason on. @BryceTache is a good guy & if Twitter are serious about doing their bit to defend democracy then these admin errors need Twitter-Certainly url Safety to have a secure twitter environment. and environment.and sorted out sharpish freedom of expression if you need control check keep reading confirm of suspect Twitter Trust the helps you well and data tion Ruglinks The following audio Elementa tion of the Twitter Thanks support team continued to work ing uses fear or rules be information support make my account in order to send the security report #MGWVc is missing from the confirmation de com

**Comment by dsander** [comment]
I don't see how this is related to Huginn.
