### ISSUE TITLE
Website Agent encode fetch error with GBK web page

### ISSUE THREAD

**Issue by shawn8888** [huginn/huginn#2625]
I am a newbie of Huginn, and this is my first attempt of writing an agent and it failed. The web page I want to fetch is this:
https://info.51.ca/news/digest/

The source code shows the charset as GBK:
`content="text/html; charset=gbk"`

My Agent option is like this:
```
{
  "expected_update_period_in_days": "2",
  "url": "https://info.51.ca/news/digest/",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "url": {
      "xpath": "/html/body/div/section//div/h3/a",
      "value": "@href"
    },
    "title": {
      "xpath": "/html/body/div/section//div/h3/a",
      "value": "normalize-space(.)"
    },
    "content": {
      "xpath": "/html/body/div/section//div/h3/a",
      "value": "normalize-space(.)"
    }
  }
}
```

After a dry run, it gave me an error:
```
[00:00:00] INFO -- : Dry Run started
[00:00:00] INFO -- : Fetching https://info.51.ca/news/digest/
[00:00:00] ERROR -- : Error when fetching url: "\x84" on GB2312
/app/app/concerns/web_request_concern.rb:52:in `encode!'
/app/app/concerns/web_request_concern.rb:52:in `block in call'
```

I have tried adding a line in the option:
`"force_encoding": "GBK",`
And it didn’t work. 
Please help. I don’t want to give up yet.

**Comment by virtadpt** [comment]
Try setting "force_encoding" to "utf8" or "utf16".

**Comment by shawn8888** [comment]
> 
> 
> Try setting "force_encoding" to "utf8" or "utf16".

Error for UTF-16:
` "force_encoding": "UTF-16",`

```
[00:00:00] INFO -- : Dry Run started
[00:00:00] INFO -- : Fetching https://info.51.ca/news/digest/
[00:00:00] ERROR -- : Error when fetching url: "<!" on UTF-16
/app/app/concerns/web_request_concern.rb:52:in `encode!'
/app/app/concerns/web_request_concern.rb:52:in `block in call'
```

Also tried UTF-8, not the same error, but still not working.

Does website agent work with GBK at all? I read there is another thread about the same issue, but closed as "bug fixed". How come I still cannot get it working with GBK encoding?

**Comment by shawn8888** [comment]
So, no support for GBK at all? UTF8 or ISO-8859-1 only?

**Comment by dsander** [comment]
I can't really test the website because for me it's behind the cloudflare browser check. The first error you postest looks like the website is infact encoded in `utf-8`. Can you post the error you get when force encoding to `utf-8`?

**Comment by shawn8888** [comment]
I don't know what you mean about "behind the cloudflare browser check". The attachment is the error log when forced to UTF8.
UTF8 is totally different from GBK. If the webpage clearly declared as GBK like this:
` <meta http-equiv="Content-Type" content="text/html; charset=gbk">`
the website agent should be able to handle it correctly just like what a browser should do. "force_encoding" options shouldn't be used in most case scenario. 

[UTF8Error.txt](https://github.com/huginn/huginn/files/3894644/UTF8Error.txt)

**Comment by dsander** [comment]
Testing to download the website via curl and then running iconv to convert the characters seems to work. So there might be a bug in Huginn, what is the exception you get when you force the encoding to `gbk`?

**Comment by shawn8888** [comment]
Thank you  dsander for checking the error for me! I just saw your reply.
Here is the error if I set:
`  "force_encoding": "GBK",`
I hope it helps. I really hope this bug can be fixed.

[GBKError.txt](https://github.com/huginn/huginn/files/3914739/GBKError.txt)

**Comment by dsander** [comment]
@shawn8888 Can you try to use `GB18030` as the encoding?

**Comment by shawn8888** [comment]
> 
> 
> @shawn8888 Can you try to use `GB18030` as the encoding?

OMG! It works! Now I can write website agent to build RSS for GBK sites!
However, I still think it's a bug. Is it possible to fix so you don't have to force the encoding for GBK sites?

Thanks a lot, dsander!!!

**Comment by dsander** [comment]
That is great! The bug is actually in the site, it reports to be GBK encoded but is actually using GB18030 😄 I used a tool that tries to guess the encoding from a file, maybe we can integrate that with Huginn.

**Comment by shawn8888** [comment]
If the site is wrong with the encoding, how come all the browsers has no problem with it? I tried it with IE, Firefox, chrome, all fine. It's also a very popular website and no one seems have trouble with it.

**Comment by dsander** [comment]
As far as I know browser do guess the encoding, Huginn isn't so smart and if we or the website tell it to use the wrong encoding it yells at us 😄

**Comment by shawn8888** [comment]
I am closing this issue. But I do hope that Huginn can be smarter in the future!
