### ISSUE TITLE
Email Agent not using passed subject data

### ISSUE THREAD

**Issue by Taomyn** [huginn/huginn#2639]
I have numerous agents, some are RSS sgents other are Website agents, and they all set up parameters called "subject" and "headline" for use by the Email agent. However the subject does not seem to get used.

An example of one of my RSS agents is:

```
{
  "expected_update_period_in_days": "60",
  "clean": "true",
  "url": "https://feeds.feedburner.com/nirsoft/voiG",
  "events_order": [
    [
      "\"{{updated}}\", \"time\""
    ]
  ],
  "subject": "NirSoft Utility updated",
  "headline": "https://feeds.feedburner.com/nirsoft/voiG"
}
```

And the Email agent is:

```
{
  "subject": "Website Monitor Change Alert {{subject}}",
  "headline": "Your notification: {{headline}}",
  "expected_receive_period_in_days": "21"
}
```

The "Your notification" works fine and appears in the body of the generated emails, but the subject comes out as just "Website Monitor Change Alert" without the rest.

**Comment by dsander** [comment]
Hi!

The RssAgent does not mix in any options you specify into the Events it generates. You can check that by looking at the Events the Agent produced. To merge data into the Events you can use and `EventFormattingAgent` between the RSS and email Agents. When it's `mode` is set to `merge` you can inject your headline and subject in the `instructions`.

**Comment by Taomyn** [comment]
So I would need to add an extra agent for each RSS agent in order to do this? That's disappointing.

**Comment by dsander** [comment]
Yes this is how almost all Agents work.

**Comment by Taomyn** [comment]
Sorry to come back to this after so long. So this is what needs to be done for each of my RSS agents:

RssAgent_1 --> EventFormattingAgent_1 --> EmailAgent
RssAgent_2 --> EventFormattingAgent_2 --> EmailAgent
RssAgent_3 --> EventFormattingAgent_3 --> EmailAgent
etc?

**Comment by dsander** [comment]
Yes, if you want to use the same subject for every email that is emitted for the same RssAgent you could also put it in the EmailAgent configuration and skip the liquid interpolation in the `subject`.

**Comment by Taomyn** [comment]
Great, thanks for the confirmation. I went through all my agents and added the intermediate step to add the subject, took a while, but they're all working. Will close this issue.
