### ISSUE TITLE
Show diff between previous and current event

### ISSUE THREAD

**Issue by mkngrm** [huginn/huginn#2653]
Sorry in advance if this is something simple to do, but I've been trying to figure out a way to highlight the specific values that change in a website.  

I'm using a website agent to scrape a store webpage, storing the items (and all attributes related to it; price, quantity, stock status, etc.) in an array, and sending out an alert if Huginn notices a new/modified/removed item.  The problem is that in order to determine what changed, I need to visit the website and try to remember what previously existed on that store page, which is not always possible or accurate.  

Is there a way to do something like a diff between the set of values from the previous event and the values from the new event to spit out each individual item that changed?

**Comment by dsander** [comment]
I don't think we have anything like this at the moment. It should be possible to write the diffing logic in JavaScript using the `JavaScriptAgent`. In general I think some sort of `DiffAgent` would be a nice addition.

**Comment by mkngrm** [comment]
Thanks, @dsander.

If I were to try to write something, would I only be able to access those old values through the DB?

**Comment by dsander** [comment]
When writing an Agent in Ruby, yes, with the JavaScriptAgent not directly. We have the concept of Agent "memory" though. With that you can set the memory to anything you like when receiving the first Event. Then later retrieve the previous Event from memory and diff it with the current Event.

**Comment by mkngrm** [comment]
Thanks again.  I'll give it a shot and see what I can come up with.
