### ISSUE TITLE
Best practice for aging off events

### ISSUE THREAD

**Issue by BlueHatbRit** [huginn/huginn#2668]
I've been running huginn for a few months now after finding it on Hacker News (HN) and absolutely love it! It solves so many problems for me. I had a couple questions about the best practice of event storage and aging that I couldn't find the answer to.

1. I have an agent scanning the HN front page every 2-4 hours and emitting an event for new articles it's not seen before. I'm then applying some regex filters on these events to trigger various alerts / digest emails. Over the last 5 days it's generated around 440 events, I imagine this will continue at a fairly steady rate. The events are very small, just the title and link to the main article. I'm wondering at what point it's going to slow down the publishing of messages (when it attempts to de-dupe) and whether storage is going to be an issue. I'm only running at about 50GB disk space, so I'm currently aging off at 30 days, but I'm wondering if this is too relaxed. Is there any guidance on roughly how much space events take up or what a good age-off strategy might be? I'd rather not age them off too quickly in case I want to come back and apply an agent over some historical data.

2. If I edit an agent to change it's max event age ("Keep Events For") field, will that remove all existing events which meet that criteria? If so, when does that happen, is it on the next event, or some sort of scheduled time in the background?

I'm basically looking to maintain a fairly cheap, but reliable and well cared for setup that'll last me without having to do too much in the way of maintenance. Any advice would be much appreciated!

**Comment by virtadpt** [comment]
1. I'm not sure what event aging strategy would work well for you.  That said, for things that change that fast I tend to set the upper limit at seven days, and configured Huginn to expire old events every four hours in the .env file.

2. It will do so the next time the event expiring maintenance mole runs, dependent upon the value of EVENT_EXPIRATION_CHECK in the .env file.

**Comment by dsander** [comment]
>  1. Is there any guidance on roughly how much space events take up or what a good age-off strategy might be? I'd rather not age them off too quickly in case I want to come back and apply an agent over some historical data.

I don't know exact numbers, every Event is stored in a database table row, for postgres the size required would be the size of the JSON representation of the Event payload + a bit of overhead for the additional fields.

This is the size of my Huginn postgresql database on disk:

```
sudo du -sh postgresql-data/
822M	postgresql-data/
```

This is for 138638 Events. So I would say you don't need to worry about expiring Events too early with the 50GB of storage you have 😄 




> 2\. If so, when does that happen, is it on the next event, or some sort of scheduled time in the background?

Good question, I had too look that up in the code. When you change the Event expiration of an Agent, the date will be updated for all Events of the Agent when it's saved. The actual cleanup then happens every 6 hours or what whatever value `EVENT_EXPIRATION_CHECK` is set.

**Comment by BlueHatbRit** [comment]
It sounds like I can comfortably deal with age off times later on if you're on 138638 events at 822M, I'm no where close to that. I knew postgres was efficient at json but didn't realise it was that good.

> When you change the Event expiration of an Agent, the date will be updated for all Events of the Agent when it's saved. The actual cleanup then happens every 6 hours or what whatever value EVENT_EXPIRATION_CHECK is set.

That's great, every 6 hours is plenty if I do start getting some disk space alerts.

Fantastic, thanks so much for your time and advice! I'll go ahead and close this issue now 😄
