### ISSUE TITLE
Unable to enable new jq Agent

### ISSUE THREAD

**Issue by marcelbrueckner** [huginn/huginn#2672]
A new agent for processing JSON through `jq` have been added with #2665. I've tried to enable it but didn't have any luck so far.

I'm running the latest [`huginn/huginn`](https://hub.docker.com/r/huginn/huginn) Docker image on a Synology. According to the [example environment](https://github.com/huginn/huginn/blob/07a4d7c30bf8ee01d13a92a58b22f0efc34333b4/.env.example#L221-L226) I've set environment variable `USE_JQ=jq` but the agent is still disabled (showing **This agent is not enabled on this server** in agent description).

```bash
default@huginn:~$ jq --version
jq version 1.3
default@huginn:~$ cat /app/.env | grep USE_JQ
USE_JQ="jq"
```

How do I enable the jq agent?

**Comment by knu** [comment]
I figured out.  The jq command included in the huginn/huginn image is too old (1.3) to be detected by JqAgent.

I think #2656 will fix this automatically, but in the meantime I'll file a seperate PR to update Dockerfile's.

**Comment by dsander** [comment]
@marcelbrueckner Can you do me a favor and test if https://github.com/huginn/huginn/pull/2656 fixes the issue for you? I just rebased the branch to include the latest changes from `master`. If it does we know that we can revert the change @knu made when we merge the docker image base distribution update.

**Comment by marcelbrueckner** [comment]
I've swapped out the Docker image with your `huginnbuilder/huginn:pr-2656`. The jq agent is now enabled (showing **jq version 1.5-1-a5b5cbe is installed**).

Simple jq expressions are working fine. I'm having issues with variables and jq's SQL-style operator IN(source; s). It's throwing `jq: error: IN/2 is not defined at <top-level>, line 1`. (Nearly) The same works on [jqplay.org](https://jqplay.org/s/qGVW2dUlUJ) (they use jq 1.6):
```json
{
  "filter": "select( IN(.attribute; $disallowed_values) | not )",
  "variables": {
    "disallowed_values": [
      "value1",
      "value2",
      "value3",
      "value4"
    ]
  }
}
```

This variant works:
```json
{
  "filter": "select(.attribute != $v1 and .attribute != $v2 and .attribute != $v3 and .attribute != $v4)",
  "variables": {
    "v1": "value1",
    "v2": "value2",
    "v3": "value3",
    "v4": "value4"
  }
}
```

But that's probably an human error :D I will further investigate.

Thanks. This issue is solved for me.

**Comment by dsander** [comment]
Thanks for testing that!

**Comment by knu** [comment]
Great.

As for the matter with `in`, I guess `select(.attribute | in($disallowed_values) | not)` is the way to go.

**Comment by marcelbrueckner** [comment]
I've tried your suggestion and while this still doesn't work it outputs another error that led me to the solution (from [StackOverflow](https://stackoverflow.com/questions/43259563/how-to-check-if-element-exists-in-array-with-jq/5995009#43269105), of course :))

```bash
.attribute as $attr | select( $disallowed_values | index( $attr ) | not)
```

The SQL-like built-ins `IN/1` resp. `IN/2` aren't available in jq 1.5 but has been added in jq 1.6. Easy to spot when comparing e.g. the manuals [1.5](https://stedolan.github.io/jq/manual/v1.5/) vs. [1.6](https://stedolan.github.io/jq/manual/v1.6/).

Thanks again.

**Comment by a10kiloham** [comment]
Is there a good reason to still use Ubuntu 14.04 in the Docker image? That's end of lifed by now.

**Comment by knu** [comment]
#2603 is in the works.
