### ISSUE TITLE
Telegram Agent "No valid key found in event"

### ISSUE THREAD

**Issue by ColeB97** [huginn/huginn#2674]
I have a Twitter Stream Agent, a Peak Detector Agent, and a Event Formatting Agent. I'm wanting to setup a Telegram Agent so that it'll send alerts to a Telegram channel when the Peak Detector is hit. I have my bot created, Auth Token set, and Chat Channel selected. However, if I do a Dry Run I get the following error, "**_ERROR -- : No valid key found in event {"message"=>"Activity on [tweet] has peaked to 33.0 - https://twitter.com/search?q=[tweet]", "created_at"=>"2020-01-15 14:55:03 -0800"}_**".

This is how my EventFormattingAgent is setup:
`{`
`  "instructions": {`
`"message": "Activity on {{grouped_by}} has peaked to {{peak}} - https://twitter.com/search?q={{grouped_by | uri_escape}}",`
`"created_at": "{{created_at}}"`
`},`
`  "mode": "clean"`
`}`

**Comment by ColeB97** [comment]
I've decided to use Discord API as I have more experience with that already.

**Comment by Muurtegel** [comment]
I ran into the same issue. Seems like the Telegram Agent expects a _text_ key in the event. In the example above there's a "message" key, but no "text" key.

https://core.telegram.org/bots/api#sendmessage
