### ISSUE TITLE
Need help with Website Agent on one site

### ISSUE THREAD

**Issue by ColeB97** [huginn/huginn#2676]
First off, love that someone recommended this little gem of a tool to me. I do a lot of research and have to monitor events taking place in literally all corners of the earth, 24/7. This is helping automate a lot of my monitoring tasks, and I already have well over 100 agents running on my server. Absolutely love it!
Today I've been creating RSS feeds for all the sites I read, I got most of them down but one is giving me some problems. The site is small and it looks like they don't use the greatest of all Class management. This is the site in question, https://c4ads.org/reports. I'm specifically trying to watch that Reports page.

Using `"css": ".sqs-block-content p strong"` it also is picking up a lot of useless text such as "FEATURED REPORTS" and "GNSS attacks are emerging as a viable, disruptive strategic threat.". This is because this site literally has no classes for different content. Is there anyway to filter this down even further? Similar issues happen if I try to retrieve the description text. I tried a couple RSS Maker sites to maybe get some ideas if I was missing something, but those were messing up too.

Overall the website is just poorly coded obviously, but would there be anyway to navigate this?

**Comment by dsander** [comment]
Hi!

Glad to hear that you find Huginn useful! 

http://selectorgadget.com/ is very useful to get CSS selectors matching elements without having to dig through the source. You basically activate the plugin, click on the elements you want and shift+click on the false positives, I had to remove `featured reports` and then manually add one of the report headers again and it came up with this: `.span-6 strong , .span-6+ .sqs-block-html strong`. That is definitely one of the crazier CSS selectors I have seen, but maybe it works and hopefully continues to work.

**Comment by ColeB97** [comment]
@dsander Awesome, thanks. Didn't know I could shift click to deselect elements, so that'll help on other sites too for sure.
