### ISSUE TITLE
Sentiment Agent Discussion/Help

### ISSUE THREAD

**Issue by ColeB97** [huginn/huginn#2678]
This is going to be more of a discussion and requiring a bit of guidance. I'm for one, not a Physiology Major or anything like that, so this model is new to me. I'm trying my best to understand it, without getting a physiology degree here. I've searched around, seen tons of Scholarly Articles and pages going over Valence-Arousal and Dominance, but I'm lost when it comes to how it works in Huginn.

So I'm trying to understand how it works in Huginn, and specifically what scale is used. Online, I'm seeing a lot of graphs with four quadrants, however quadrants have negative numbers, (Ex: https://i.imgur.com/X9U6xp4.png). From my readings so far, I have yet to get a negative number. I have ~20,000 readings from a semi-sensitive/volatile topic. I'm only focusing on Valence and Arousal, not Dominance.
Arousal my low is 2.5, and the high is 8.2, with a mean of 5.5.
Valence my low is 1.4, and the high is 8.7, with a mean of 5.4.

So how can I interpret this data? If I look online, as I said, most models I've seen work with negative numbers too, which Huginn doesn't seem to use. So what's the scale Huginn uses? Is it 1-10, or a 0-10. Is 5 the "neutral" zone? Can someone, maybe the developers, explain the scale used here? Or are there any articles/references someone could link me to that uses the same scale Huginn uses so I can get a better idea?

**Comment by dsander** [comment]
I have never used the Agent myself, the Agent description  states it is returning values between 1 and 9.
