### ISSUE TITLE
Is last_property value global? 

### ISSUE THREAD

**Issue by o---** [huginn/huginn#2679]
I am using the `Change Detector Agent` to detect a change of a value on a website. The last value is stored in the `last_property` memory variable. Now I have several copies of this Agent including all its predecessors. Yet it seems, that the `last_property` value is not specific to its own chain of agents, but both agents have the same value in memory. Due to this, the Change detection is not working as expected.

**Comment by dsander** [comment]
It is possible that the `last_property` value was copied over when you duplicated the Agent. You should have a button to clear the Agent memory in the Agent detail page. In general `last_property` isn't global, but per Agent.

**Comment by o---** [comment]
Thank you for the confirmation. That makes sense!
