### ISSUE TITLE
SMTP does not work for Email Agents. But works for sign up and password reset

### ISSUE THREAD

**Issue by Flyffies** [huginn/huginn#2686]
Hi, 

I had a problem where Huginn could send mails for sign up and password resets, but not when the mail came from an Email Agent. 

I got the following error message
> getaddrinfo: Name or service not known: /usr/lib/ruby/2.5.0/net/smtp.rb

I figured out ruby smtp does not use the resolver of the system correctly. I am running my Mailserver and Huginn in docker an they share a network. So I put the internal name in the SMTP server address. That worked for the sign up and reset, but not for the Agents. When I put my external address in the SMTP server address everything works.

So my gues is, that ruby does not use the local resolver correctly.

**Comment by dsander** [comment]
Hi,

I think someone else reported a similar problem recently, but I still can't make any sense of it. Both the reset password and the email agent mailer use the same configuration. Are you certain both the application server and the delayed job background processor are using the same configuration?

**Comment by Flyffies** [comment]
Hi!

Yes, they both share the same .env file in docker-compose.

**Comment by dsander** [comment]
Sorry for the late response, can you share your docker(-compose) configuration you are using to start the containers including the `.env` (with the passwords obfuscated)?

**Comment by Flyffies** [comment]
Here you go: https://0bin.net/paste/aePkqQk5+c7N10RC#b-svvibG8nlWEtQya9OYFP0FIWt1leDsQ4Hx22SF82Y

**Comment by dsander** [comment]
I have no issues sending emails with that configuration. Do you have some sort of firewall configuration for outgoing connections? The only difference between the `web` and `threaded` service I see is that the `threaded` service isn't connected to any of the networks the `web` service uses.

**Comment by Flyffies** [comment]
Yea, it wasn't and it was probably that. Its working after adding the same networks to threaded.
Thanks!

**Comment by agalewsky-pnn** [comment]
i am having the exact same problem. emails are fine from reset password - but nothing from email agent with.  what is even more interesting is there is nothing on the log at all - its like the email agent is not even executing!

-Andy
