### ISSUE TITLE
How to limit the number of events in rss output?

### ISSUE THREAD

**Issue by uniartisan** [huginn/huginn#2688]
I set up a Website Agent in order to get rss, but how to ensure that there are only limited events in my RSS output?
For example, I only want to guarantee the last two hundred  events in chronological order.
I don't want the rss file to grow infinitely.

in issue #2245 ,i find a solution, but i dont know how to resolve my question.
this is my output.
https://files.uniartisan.com/xjtu/news.xml

![image](https://user-images.githubusercontent.com/31544054/75088946-a75f9e80-558e-11ea-8781-6506e4ba6530.png)
```
{
  "expected_update_period_in_days": "2",
  "url": "http://news.xjtu.edu.cn/zhxw.htm",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "url": {
      "xpath": "/html/body/div[4]/div[1]/div/a/@href",
      "value": "concat('http://news.xjtu.edu.cn/',.)"
    },
    "title": {
      "xpath": "/html/body/div[4]/div[1]/div/a",
      "value": "normalize-space(.)"
    },
    "time": {
      "xpath": "/html/body/div/div/div/cite",
      "value": "normalize-space(.)"
    }
  }
}
```
```
{
  "expected_update_period_in_days": "2",
  "url_from_event": "{{url}}",
  "type": "html",
  "mode": "merge",
  "extract": {
    "quanwen": {
      "xpath": "/html/body/div[4]/div[1]/form/div/div/div",
      "value": "."
    }
  }
}
```
```
{
  "secrets": [
    "news"
  ],
  "expected_receive_period_in_days": 2,
  "template": {
    "title": "交大新闻",
    "description": "This is a feed of recent XJTU NEWS, generated by LiZhiyuan",
    "item": {
      "title": "{{title}}",
      "description": "{{quanwen|regex_replace:'src=\"../../','src=\"http://news.xjtu.edu.cn/'}}",
      "link": "{{url}}",
      "pubDate": "{{time}} "
    },
    "link": "http://news.xjtu.edu.cn/"
  },
  "ns_media": "true"
}
```

**Comment by dsander** [comment]
The Agent has a configuration option for that: `events_to_show` which defaults to 40, so your feed should only contain 40 entries at all times.

**Comment by uniartisan** [comment]
> The Agent has a configuration option for that: `events_to_show` which defaults to 40, so your feed should only contain 40 entries at all times.

Thank you and I will close it soon!!!!
