### ISSUE TITLE
Telegram Agent Photo-Key

### ISSUE THREAD

**Issue by itsNik** [huginn/huginn#2689]
Hello,

I have a little bit of trouble with the right formatting for the Telegram Agent.
I have the following example event which im trying to send with the Telegram Agent:
`{"text":"Some-Headline","photo":"https://i.imgur.com/randompic.jpg"}`

But when I try to run the Telegram Agent with the event above I get the following error:
[https://pastebin.com/fKqskHau](https://pastebin.com/fKqskHau)

The Text-Key always gets submitted but all others don't and I don't know what I am doing wrong.
Or is there any other way to format and send Telegram messages?

**Comment by dsander** [comment]
Try adding a `caption` to the Event you are sending to the Agent.
