### ISSUE TITLE
Manually trigger agents' memory purging

### ISSUE THREAD

**Issue by virtadpt** [huginn/huginn#2697]
How difficult would it be to make it possible to manually trigger the DELETE queries that rotate out agents' oldest stored events?  I would like to 

Perhaps a `rake` task, if not an API rail or a new feature for the /agents screen?  Select some subset of agents and run their memory rotation task?

c.f. #2692

**Comment by dsander** [comment]
You can set `EVENT_EXPIRATION_CHECK` to a really high number like `10000d` which would effectively disable the schedule.

This command should run the cleanup:
```
sudo -u huginn -H bundle exec rails runner "Event.cleanup_expired!" RAILS_ENV=production
```

**Comment by virtadpt** [comment]
Hmmm... I'll have to look into doing that, thank you.  Might help with the problem I'm seeing over here.  And when I update today (the CVEs just recognized and published to Gemfile.lock) I'll look at running the cleanup manually.  If it's not too bad I'll add it to regular maintenance.

Thank you for your help!

**Comment by virtadpt** [comment]
I've added it to my regular maintenance cycle and it seems to be helping.  Thanks!
