### ISSUE TITLE
SMTP email doesn't work in Docker container - 535-5.7.8 Username and Password not accepted

### ISSUE THREAD

**Issue by Tieno** [huginn/huginn#2699]
I'm running the docker image huginn/huginn on Synology diskstation. I've tried all combinaties I could find on the internet but, I always get the error
"535-5.7.8 Username and Password not accepted. Learn more at"

I have no idea how to debug this further. Anybody have any ideas?

**Comment by dsander** [comment]
How did you configure the docker containers and what is your email provider?

**Comment by Tieno** [comment]
Hi,
thanks for the reply. 
I pulled in the image huginn/huginn.

I've tried all the stuff I could find here (different ports, authentication plain vs login, etc)
These are the current env variables.
![image](https://user-images.githubusercontent.com/977414/75723783-3ed69700-5cdd-11ea-8f53-cdd192e289fe.png)

**Comment by dsander** [comment]
Did you enable access for less secure apps for your GMail account? https://www.google.com/settings/security/lesssecureapps

**Comment by Tieno** [comment]
> Did you enable access for less secure apps for your GMail account? https://www.google.com/settings/security/lesssecureapps

No. I use two factor auth, so I use an app password. I verified the settings via an independent email test.

**Comment by dsander** [comment]
Did you try the setting? To my understanding an app password effectively bypasses the 2FA which should count as a "less secure app".

**Comment by Tieno** [comment]
I tried the setting, but it's not available for 2-factor
![image](https://user-images.githubusercontent.com/977414/75796815-7c3a3380-5d74-11ea-8b88-1a3bde6f3209.png)

**Comment by dsander** [comment]
Does setting `SMTP_DOMAIN=gmail.com` help?

**Comment by Tieno** [comment]
I deleted the entire container and started from scratch. it seems that changed a few stuff and my env variables are "read". Now I got some new error when I tries to send an email

Exception during receive. end of file reached: /usr/lib/ruby/2.5.0/net/protocol.rb:189:in `rbuf_fill' /usr/lib/ruby/2.5.0/net/protocol.rb:157:in `readuntil' /usr/lib/ruby/2.5.0/net/protocol.rb:167:...
--

**Comment by dsander** [comment]
https://github.com/huginn/huginn/issues/2592 https://github.com/huginn/huginn/issues/1894 https://github.com/huginn/huginn/issues/1604

These issues look similar, they seem to have had success with using `SMTP_PORT=587`

**Comment by Tieno** [comment]
after spending hours of debugging, checking time, ssl, veryfing I could make an smtp connection inside the container and so forth..., I finally got around to printing environment variables inside the docker container and noticed that I misspelled "SMTP_USER_NAME" as "SMPT_USER_NAME"

god damn it

**Comment by dsander** [comment]
Oh no, typos are always the most annoying errors 😿 Do the Agents now work as expected?

**Comment by Tieno** [comment]
Yeah! I couldn't get the gmail to work with the app passwords, but I have an email account from my isp which I don't use and does work. 
I'm really enjoying it, I love the simple UI and the power of the liquid syntax, it's clutterfree.

**Comment by dsander** [comment]
That is great! Feel free to reopen the issue if you have additional questions.

**Comment by mmalind** [comment]
@Tieno 

I am having similar issues with Synolgoy/docker/huginn. Can you advise on a few things. Huginn is running well, agents work but i cannot manage to get emails to send with any provider. I have tried sendgrid, gmail and a couple of others.

Have you made any specific settings to your docker install?
Is your Synology connected with a domain name?
Could you provide a full example (redacted when needed) of your environment settings for Huginn?

I would really love to get this working but i am at my wits end.

Best regards

**Comment by Tieno** [comment]
Hi,

I exported the docker settings for the container and redacted it, it should give you an idea.

[huginn-huginn1_exported_redacted.zip](https://github.com/huginn/huginn/files/5140252/huginn-huginn1_exported_redacted.zip)

**Comment by mmalind** [comment]
@Tieno 

Wow, thank you so much, i really appreciate the help! Ill get back to you in the progress. 

Thank you again!

**Comment by razzmatazh** [comment]
Hello,

Have a related question here... I'm running Huginn on Synology, and trying to get email to work but am a little bit confused about .env file and its whereabouts. Should it be called .env to begin with? And where should I locate it? (A bit of a noob here)

Will appreciate any help! Thanks.

**Comment by Logiar** [comment]
So found out the .env file is respected over environment variables. I had my docker container up before i decided to set up SMTP settings, had endless issues using the environment variables on the container. Getting this error and not understanding what was going on. So I got a shell and tried editing the .env with sed. After a restart i got an end of file error when sending, tried changing the EMAIL_FROM_ADDRESS and restarted one more time and email works. So seems after the .env file is generated changing the environment variables does nothing, guessing the file is generated on container creation from the comments above.

**Comment by virtadpt** [comment]
This seems like a thing that should be added to the wiki.  Would you mind?

**Comment by nemosmithasf** [comment]
For those whose email spontaneously stopped working, for me it was because[Google disable "less secure" access on May 30 2022](https://support.google.com/accounts/answer/6010255?hl=en)

The solution is to (1) use an *app specific password* and then (2) reset the container because of what @Logiar noted
