### ISSUE TITLE
Escaping backslash to replace it in HTML downloaded with curl

### ISSUE THREAD

**Issue by konwin** [huginn/huginn#2703]
Hi, I'm really no coder and tried to figure this out by myself, but somehow I can't get past the last step. Maybe I have not understood the regex scheme completely but really did not find an easy understandable how-to for regex which could help me with my problem...
I want to observ an html file which lays on a website secured with digest authentication. First I tried to fetch it with the website agent, until I found out that only basic authentication is supported by huginn. I fiddled a little bit around and could fetch the html file via a Shell Command Agent with:
```
{
  "path": "/",
  "command": "curl --digest -u user:pass \"https://www.my.target/\"",
  "unbundle": false,
  "suppress_on_failure": false,
  "suppress_on_empty_output": false,
  "expected_update_period_in_days": 1
}
```
Now the HTML is full of `\n` `\t` and `\` so I tried to regex_replace them with the Event Formatting Agent with:
```
{
  "instructions": {
    "message": "Server status",
    "Status": "{{output | regex_replace: '\\n', ' '| regex_replace: '\\t', ' '| regex_replace: '\\', ''}}"
  },
  "matchers": [],
  "mode": "clean"
}
```
The first and second regex_replace are doing exactely what they should and the html is almost clean, I just can not get rid of the `\` rigth before all `"`. The escaping of `\` somehow does not work the same way as with `\n` and `\t`. I tried already `regex_replace: '\\', ''` and many other combinations but every time I got the `\` to be replaced the `"` also disappeared, what made the html unusable for the Website Agent with which I wanted to inspect the html in the next step. I even tried `regex_replace: '\\\"', '\"'` or `regex_replace: '\\\x22', '\x22'to` replace `\"` with `"`, but nothing worked :( Is there a way how to use regex on `\`?

**Comment by konwin** [comment]
I am still trying to solve this by myself, but somehow I got the feeling that huginn behaves strang regarding the escaping of special characters.
I tried to validate my tests via [rubular.com](https://rubular.com/). My test string is:
```
<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\n   \"http://www.w3.org/TR/html4/loose.dtd\">\n
<HTML>\n
<HEAD>\n\t
<title>MyWebSite<\/title>\n\t
<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n\t
<meta name=\"robots\" content=\"noindex,nofollow\">\n\t
<meta http-equiv=\"language\" content=\"de\">\n\t
<link rel=\"stylesheet\" type=\"text/css\" href=\"site.css?v=11572\">\n\t
<link href=\"favicon.ico\" rel=\"icon\" type=\"image/x-icon\">\n\t
<script type=\"text/javascript\" src=\"jquery.js?v=11572\"><\/script>\n\t
```
As said before the `\n` and `\t` are found without any problems with `regex_replace: '\\n', ''| regex_replace: '\\t', ''` which can be easily validated via rubular with `\\n` and `\\t`.
For the backslashes I found `\\(?=\x22)` to be working via rubular but huginn gives me an error saying
> [00:00:00] ERROR -- : Exception during dry-run. unmatched close parenthesis: /\(?=x22)/: /app/app/concerns/liquid_interpolatable.rb:235:in `initialize'

when trying to use `regex_replace: '\\(?=\x22)', ''`

**Comment by dsander** [comment]
Hi, 

you can use basic authentication with the `WebsiteAgent`, provide the login credential as part of the URL:

```
{
  "expected_update_period_in_days": "2",
  "url": "https://guest:guest@jigsaw.w3.org/HTTP/Basic/",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "html": {
      "css": "body",
      "value": "."
    }
  }
}
```

**Comment by konwin** [comment]
Yes, basic authentication works, but my website uses digest authentication, which I did not managed to fetch via `WebsiteAgent`. That is why I am using the workaround via `curl`!

**Comment by konwin** [comment]
Ok, so with `regex_replace: '(\")'` I could find the `\"` characters, but I found no way to add a `"` instead ...
But I managed to solve my problem in another way. I read some hints on the command `unescaped` so my first `ShellCommandAgent` is now pulling the html via curl (because of the digest authentication):
```
{
  "path": "/",
  "command": "curl --digest -u user:pass 'https://www.my.target/'",
  "unbundle": false,
  "suppress_on_failure": false,
  "suppress_on_empty_output": false,
  "expected_update_period_in_days": 1
}
```
and the second `WebsiteAgent` gets the html with the first agent set to be the `Source` the right way with the added `unescape` command!
```
{
  "expected_update_period_in_days": "2",
  "data_from_event": "{{ output | unescape }}",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "url": {
      "css": "#comic img",
      "value": "@src"
    }
  }
}
```
maybe this will help somebody!

**Comment by dsander** [comment]
Glad you figured it out! I have not heard of "digest authentication" before. If it's based on HTTP headers, it should be supported by using the `headers` option.
