### ISSUE TITLE
new to huginn / problem with rss feeds

### ISSUE THREAD

**Issue by lessrand** [huginn/huginn#2719]
Hello, I am trying to do the following with huginn,

* collect a feed with Rss Agent, seems to work
* filter for title with Trigger agent, seems to work, but says Working:NO ??
* display it with DatOutputStream, contains no items, says Working: NO ??

Its very hard to debug, as you cannot see whats happening, or at least I do not know how to see this.

pleae help

kind regards

Randolph 

Detais on configuration are below.

 Type: Rss Agent
Schedule: Every 10m
Last checked: 1m ago
Keep events: 30 days
Last event created: ~1h ago
Events created: 500
Event receivers: Real Estate DealTrigger
Working: Yes
Options:
```
{
  "expected_update_period_in_days": "1",
  "clean": "false",
  "url": "http://www.deal-magazin.com/news/latest.rss"
}
```
 Type: Trigger Agent

Keep events: Forever

Last event created: never

Last received event: never

Events created: 0

Event sources: Real Estate Collector 1

Propagate immediately: Yes

Event receivers: Real Estate Transaction Stream

Working: No

Options:
```
{
  "expected_receive_period_in_days": "2",
  "keep_event": "true",
  "include_feed_info": "true",
  "rules": [
    {
      "type": "regex",
      "value": ".*Corona.*",
      "path": "title"
    }
  ],
  "message": "Corona Message: '{{title}}'!"
}
```

ype: Data Output Agent

Last received event: never

Event sources: Real Estate DealTrigger

Propagate immediately: Yes

Working: No

Options:
```
{
  "secrets": [
    "123re123re123"
  ],
  "expected_receive_period_in_days": 2,
  "template": {
    "title": "Real Estate Transactions",
    "description": "This is a feed of real estate transactions, generated by Huginn",
    "item": {
      "title": "{{title}}",
      "description": "{{description}}",
      "link": "{{url}}"
    }
  },
  "ns_media": "true"
}
```

**Comment by dsander** [comment]
Hi,

it sounds like the issue you are having is that the `TriggerAgent` never matches on an Event ans thus never forwards them. The best way to debug the Agent is to use the `Dry Run` button and feed it an actual event from your RSS source. I can't see any configuration error, if you have a event that contains `Corona` in it's `title` the Agent should trigger and forward the Event.

**Comment by lessrand** [comment]
Yes never triggered appently.
