### ISSUE TITLE
ID filtering agent

### ISSUE THREAD

**Issue by deathbybandaid** [huginn/huginn#2725]
This is something that I think would be easy to implement, but I'm not a ruby coder.

The RSS agent actually has the basis of this idea already. `remembered_id_count`

Essentially, I want to have an agent that keeps a database list of IDs with an assigned "namespace".

It would look something like this:

````
{
  "namespace": "indeed_reviews_companyname",
  "id_label": "label_of_incoming_id",
}
````

If the id_label is in the namespace database list, then it does not produce an event.
It also should have logic to prevent empty values to pass.

**Comment by dsander** [comment]
I think you should be able to use a `DeDuplicationAgent` for that. Set `lookback` big enough and use `{{namespace}}_{{id_label}}` as the `property`.
