### ISSUE TITLE
error when creating the database with ruby 2.7.0 and bundler 2

### ISSUE THREAD

**Issue by DanielRuf** [huginn/huginn#2727]
When I run `bundle exec rake db:create` I get the following using Ruby 2.7.0:

```
rake aborted!
TypeError: no implicit conversion of String into Integer
/Users/danielruf/projects/huginn/config/boot.rb:7:in `require'
/Users/danielruf/projects/huginn/config/boot.rb:7:in `<top (required)>'
/Users/danielruf/projects/huginn/config/application.rb:1:in `require_relative'
/Users/danielruf/projects/huginn/config/application.rb:1:in `<top (required)>'
/Users/danielruf/projects/huginn/Rakefile:5:in `require_relative'
/Users/danielruf/projects/huginn/Rakefile:5:in `<top (required)>'
/Users/danielruf/.rbenv/versions/2.7.0/bin/bundle:23:in `load'
/Users/danielruf/.rbenv/versions/2.7.0/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```

**Comment by dsander** [comment]
Hi,

we don't officially support ruby 2.7 yet, bundler 2 could work but I am not using it because it gave me so many problems after it's release. Bundler 1 with ruby 2.6.x should work.

**Comment by DanielRuf** [comment]
> Bundler 1 with ruby 2.6.x should work.

There is no mention of this in the readme or similar. Or at least I found no relevant information.

**Comment by DanielRuf** [comment]
Only the lockfile mentions this - but no further information about the support for the Ruby versions.

https://github.com/huginn/huginn/blob/master/Gemfile.lock

**Comment by dsander** [comment]
Pull requests improving the documentation are always very welcome! The best indicator for the supported ruby versions is our [`.travis-ci.yml`](https://github.com/huginn/huginn/blob/master/.travis.yml) configuration, basically the ruby versions we test against are supported. Like I said above, I am not sure about bundler 2, I'd need to give it another try if it now works properly.

**Comment by DanielRuf** [comment]
Ok, it finally works with Ruby 2.6 and bundler 1.
I'll keep the issue open to remind me that I want to provide a PR for better docs.

**Comment by cvalcke958** [comment]
not knowing ruby....got similar problems likely from Gemfile.lock? 
Built ruby2.6 per guide, downgraded to butler 1. 
When trying to initialize database (rake command), i get:
_Could not find ace-rails-ap-2.0.1 in any of the sources_
seems there's a disconnect between my installed Gems and Huginn needs?

**Comment by dsander** [comment]
@cvalcke958 Did you run [this step](https://github.com/huginn/huginn/blob/master/doc/manual/installation.md#install-gems)?

**Comment by cvalcke958** [comment]
followed all steps. including bundle install. Maybe this helps...

- in /home/huginn, typing rake --version, gives: _rake, version 12.3.3_

- in /home/huginn/huginn, same cmd gives:

> /usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/rubygems_integration.rb:200:
>  warning: constant Gem::ConfigMap is deprecated
> Traceback (most recent call last):
> 4: from /usr/local/bin/ruby_executable_hooks:24:in `<main>'
> 3: from /usr/local/bin/ruby_executable_hooks:24:in `eval'
> 2: from /usr/local/bin/rake:23:in `<main>'
> 1: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems.rb:294:in `activate_bin_path'
> /usr/local/lib/ruby/site_ruby/2.6.0/rubygems.rb:275:in `find_spec_for_exe': can't find gem 
> rake (>= 0.a) with executable rake (Gem::GemNotFoundException

**Comment by dsander** [comment]
@cvalcke958 I just went through the manual installation guide on a fresh Ubuntu 18.04 and only had to make one modification. Per default it installed `bundler 2` I had to uninstall that and install `bundler 1` after that the installation of gems worked without issues.

```
sudo gem uninstall -ax bundler
sudo gem install bundler:"~> 1"
```

**Comment by infominer33** [comment]
Installing ruby 2.6.6 on Ubuntu 18 LAMP image from Digital Ocean. 

I had trouble with dbm until I added `--with-dbm-include=/usr/include' :

`./configure --disable-install-rdoc  --with-dbm-include=/usr/include`

as per [How do I tell Ruby where my libraries are?](https://www.ruby-lang.org/en/documentation/faq/3/)

not sure if anyone else has encountered this...  also wondering as I'm working on the docs a bit, as I go.
