### ISSUE TITLE
Dark Sky End of Life: 2021

### ISSUE THREAD

**Issue by ghost** [huginn/huginn#2732]
For those who've missed it, [Dark Sky will be going End of Life at "the end of 2021."](https://blog.darksky.net/dark-sky-has-a-new-home/) I'm not sure what global alternatives there are, but Americans can take advantage of [weather.gov's API](https://www.weather.gov/documentation/services-web-api) fairly easy.

The default weather agent will need to be replaced with something else before the end of 2021.

**Comment by xnaas** [comment]
I suppose https://github.com/public-apis/public-apis#weather would be a good resource to review.

**Comment by virtadpt** [comment]
I've been using the NWS' API for a while.  Have some sample agent code for it handy.

**Comment by e-alfred** [comment]
Openweathermap works pretty well.

**Comment by seigel** [comment]
weatherbit seems to have a free tier...I am looking to see if I can wrangle an "fix" together..

**Comment by cantino** [comment]
@virtadpt, do you want to contribute an improvement to the WeatherAgent?

**Comment by snus-kin** [comment]
FYI you can no longer sign up for a darksky API key

**Comment by erebor** [comment]
Anybody had a chance to look at my PR for switching the WeatherAgent to Openweather?  I'm not sure the correct way to get on somebody's radar for this other than pushing up code.

**Comment by xthursdayx** [comment]
Hi folks, just wondering what the state of this issue (and associated PR) are? Has any progress been made to update the weather API options?

**Comment by xnaas** [comment]
Apple has determined that they will manage DarkSky under a new name (and you'll have to pay the Apple Developer fee of $100/yr): [WeatherKit](https://developer.apple.com/weatherkit/)

**Comment by virtadpt** [comment]
[Pirate Weather](https://pirateweather.net/) has an APi designed to be a drop-in replacement for the Darksky API.  API keys are free.  Maybe this would be a useful stopgap?

**Comment by cantino** [comment]
Have you tried it @virtadpt? That's an elegant solution.

**Comment by virtadpt** [comment]
@cantino I haven't yet.  I've been using the NWS API for a while and haven't migrated over yet.

**Comment by IBakeCookies** [comment]
Any progress here?

**Comment by alexcochran** [comment]
Howdy! I went ahead and adapted the [forecast-ruby](https://github.com/darkskyapp/forecast-ruby) gem to create [pirate-weather-forecast-ruby](https://github.com/alexcochran/pirate-weather-forecast-ruby). As the name suggests, pirate-weather-forecast-ruby uses the Pirate Weather API as a replacement for Dark Sky's API.

Tests and everything else are currently working, so now I'm just trying to get a Huginn wired up to use the [new gem](https://rubygems.org/gems/pirate_weather_forecast_ruby). I'll also make some efforts to clean up my code on the adapter once I have time.

**Comment by alexcochran** [comment]
I think I'm getting close. I can get the tests to pass, but the Coveralls action in the GitHub workflow is failing w/ `Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}`:

![image](https://github.com/huginn/huginn/assets/22733754/fc48ae34-96a7-48c9-a10a-956922ebdf6d)

@cantino @knu I admit I'm pretty inexperienced w/ Coveralls + Rails. Am I missing something here?

**Comment by cantino** [comment]
Hey @alexcochran, that doesn't look like something you broke. You might be able to skip the coveralls step and see if everything else works.

**Comment by alexcochran** [comment]
Thanks @cantino. I commented out Coveralls from the GitHub CI config and [everything seems to work](https://github.com/alexcochran/huginn/actions/runs/6214888208):

![image](https://github.com/huginn/huginn/assets/22733754/d7dff908-7820-43f5-8b48-59a5760be36b)


Should I go ahead and make a PR?

**Comment by cantino** [comment]
Sure!
