### ISSUE TITLE
can not show agent event flow in develop environment

### ISSUE THREAD

**Issue by DanielRuf** [huginn/huginn#2736]
All I get is `The diagram can't be displayed because it has too many nodes. Max allowed is 80.`. How can this be changed or viewed?

There are only the sample agents plus one RSS feed agent.

**Comment by dsander** [comment]
Installing `graphviz` and uncommenting the `USE_GRAPHVIZ_DOT` configuration in the `.env` file should do it. I am a bit surprised that the fallback method doesn't work though. You only created and seeded the database?

**Comment by DanielRuf** [comment]
Exactly. I followed the steps from the readme for local development on my MacBook with macOS 10.14.

**Comment by DanielRuf** [comment]
I did a restart now. Now it has shown me a 502 error and after a few more reloads I can finally see it. I changed nothing in the configuration.

**Comment by dsander** [comment]
Hmm not sure what is up with that. When `graphviz` is not installed we are [falling back to the Google charts API](https://github.com/huginn/huginn/blob/9d3b5ec326a1792ddd4482bd64f23022cfef92c9/app/helpers/dot_helper.rb#L11-L28), maybe they changed their responses or are overloaded at the moment.

**Comment by DanielRuf** [comment]
Probably was just a temporary problem. I would say we can close this for now.
