### ISSUE TITLE
Docker started but not working, mysql related..?

### ISSUE THREAD

**Issue by windlok1010** [huginn/huginn#2739]
I am using huginn on unraid with docker. Everything was working perfectly until the latest update (2 days ago). 

the log said:

```
mysqld stdout | 2020-04-07T07:49:43.218425Z mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
2020-04-07 15:49:44,130 INFO success: mysqld entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
mysqld stdout | 2020-04-07T07:49:44.128933Z mysqld_safe mysqld from pid file /app/tmp/pids/mysqld.pid ended
2020-04-07 15:49:44,134 INFO exited: mysqld (exit status 0; expected)
2020-04-07 15:49:45,137 INFO spawned: 'mysqld' with pid 20981
mysqld stderr | UMASK must be a 3-digit mode with an additional leading 0 to indicate octal.
The first digit will be corrected to 6, the others may be 0, 2, 4, or 6.
mysqld stdout | UMASK corrected from 002 to 0640 ...
mysqld stdout | 2020-04-07T07:49:45.421040Z mysqld_safe Logging to syslog.
mysqld stdout | 2020-04-07T07:49:45.425268Z mysqld_safe Logging to '/var/log/mysql/error.log'.
```

May I know what the problem is? Thanks.

**Comment by dsander** [comment]
> mysqld stderr | UMASK must be a 3-digit mode with an additional leading 0 to indicate octal.

That looks a bit off to me, but  it looks like the server still started, so what is the error you are getting?

**Comment by windlok1010** [comment]
Sorry for the late reply. This issue can be closed. I have a working huginn after removing everything in the persistent volume and start from scratch.

The problem I was having is that the container was running in docker but the webpage is not accessible.

Thanks :)
