### ISSUE TITLE
Can't locate the server executable (mysqld)

### ISSUE THREAD

**Issue by contributorpw** [huginn/huginn#2745]
OK. I'm newbie.

The next command

```shell
$>  docker run -it -p 3000:3000 -v /raid/huginn/mysql-data:/var/lib/mysql huginn/huginn
```

returns

```sh
2020-04-12 18:49:08,236 INFO spawned: 'bootstrap' with pid 370
2020-04-12 18:49:08,248 INFO success: bootstrap entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2020-04-12 18:49:08,254 INFO exited: bootstrap (exit status 1; not expected)
2020-04-12 18:49:09,262 INFO success: stdout entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
bootstrap stdout | DATABASE_HOST=localhost
bootstrap stdout | 2020-04-12 18:49:08 [WARNING] mysql_install_db is deprecated. Please consider switching to mysqld --initialize
bootstrap stderr | 2020-04-12 18:49:08 [ERROR]   Can't locate the server executable (mysqld).
```

I know about
* Rules https://github.com/huginn/huginn/tree/master/docker/multi-process
* #2472
* #2644

Additionals

```
$> docker -v
Docker version 19.03.8, build afacb8b7f0

$> docker images -a
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
huginn/huginn       latest              fe74dfe838ba        3 days ago          1.1GB

$> sudo ls -ln /raid/huginn
total 4
drwxrwxrwx 2 1001 1001 4096 Apr 12 21:30 mysql-data
```

It seems I don't know a secret of `chmod`/`chown`/"empty volume" for mysqld.
Any advice?

**Comment by contributorpw** [comment]
There is a workaround for me now (it doesn't close the issue)

1. Create a volume with an older docker tag `$> docker run blah-blah huginn/huginn:123456_TAG_UID`. You're still have to be a cmod-hacker.
2. Stop the container
3. Re-connect/re-run with the latest version  `$> docker run blah-blah huginn/huginn`
4. Remove the older image force

The next tags work fine:
* huginn/huginn:5ab1bd28d98bed3783091361d7cce82afba4da05
  * Ubuntu 16
  * Ubuntu 18
  * COS latest

**Comment by dsander** [comment]
Sorry about that, I did test upgrading from a previous version, but did not expect the newer mysql version not being able to create a database on new volumes. 

Using a named volume works for some reason:

```
docker run -it -p 3000:3000 --rm -v mysql-data:/var/lib/mysql huginn/huginn
```

If you are starting fresh I'd recommend looking into the `single-process` [image](https://github.com/huginn/huginn/tree/master/docker/single-process), it decouples the database from the Huginn container which is generally better practice.

We did not intend to break it but might use it as an opportunity to remove support for new installations of the build in mysql server because it's such an annoyance to maintain.

**Comment by contributorpw** [comment]
@dsander Thanks for your reply!

Unfortunately It's not work yet.

I intend to strengthen my knowledge in Docker and come back to help this issue.

Also I tried run prevoice tag and it falls too. I have to use the tag (image) of eight months ago for a successful launch. I didn't test any between them yet.

Thanks for the single-p advice. I'm just interested in multi-export from an automatic Huginn MySQL/Maria base to mine.

The great app & the cool support!

**Comment by universeroc** [comment]
I've the same problem

**Comment by dboptbd** [comment]
I had the same problem. The fix in the second commented worked for me, but is not a long-term solution for future users.

**Comment by rc1** [comment]
#2745 seems related

**Comment by dsander** [comment]
Can you please check if the image `huginnbuilder/huginn:pr-2768` from #2768 fixes the issue?

**Comment by mihird85** [comment]
`huginnbuilder/huginn:pr-2768` fixes the issue. The following parameters were used to launch the container. 

```
docker run --rm -it -p -d 3000:3000 -v /Users/mdass/huginn/mysql-data:/var/lib/mysql huginnbuilder/huginn:pr-2768
```

See the output below .. mysqld was spawned with pid 402

```
2020-05-01 19:34:28,667 INFO spawned: 'bootstrap' with pid 371
2020-05-01 19:34:28,680 INFO success: bootstrap entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2020-05-01 19:34:29,706 INFO success: stdout entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
bootstrap stdout | DATABASE_HOST=localhost
bootstrap stdout | Starting mysql server...
2020-05-01 19:34:35,706 INFO spawned: 'mysqld' with pid 402
mysqld stdout | 2020-05-01T19:34:35.974602Z mysqld_safe Logging to syslog.
mysqld stdout | 2020-05-01T19:34:35.986624Z mysqld_safe Logging to '/var/log/mysql/error.log'.
mysqld stdout | 2020-05-01T19:34:36.044412Z mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
```

**Comment by dsander** [comment]
Thanks for testing!

This should be fixed in the latest `huginn/huginn` image. Feel free to reopen the issue if you are still having issues.
