### ISSUE TITLE
Huginn becoming very slow when events are in the millions

### ISSUE THREAD

**Issue by axsuul** [huginn/huginn#2749]
I have 7,452,634 events at the moment with only 138 agents. The home page now takes about 10-15 seconds to load and it's impossible for me to import a scenario from JSON since it 500s due to taking too long.

Is there suggested maintenance I can do to get things back to running smoothly again?

I'm using the Docker image `3011370f4bae9d28425f004bfd8e484a24e40406`

Appreciate any help, thanks!

**Comment by dsander** [comment]
Reducing the amount of Events by setting `Keep events` to a lower value would probably help. If every operation is slow you server might be hitting a limit. Editing an Agent configuration or importing a Scenario should not be dependent on the amount of Events in the database. Can you try if increasing the available memory helps?

**Comment by virtadpt** [comment]
Holy crap, how fast are your agents firing?  Every minute?

You can run the agent expiration and purge manually.  I don't remember off the top of my head how to do it but I've got it written down.  After work I can get to it.

**Comment by axsuul** [comment]
@dsander @virtadpt Appreciate your guys' help! It appears it was due to a low diskspace issue 🤦

For reference, I ran a few SQL queries to purge a lot of the events that were unnecessary to keep, set a lot of the `Keep events` to lower values, and then ran this to reset the event counters for the agents

```ruby
Agent.find_each do |agent|
  Agent.reset_counters(agent.id, :events)
end
```

Then I did a `VACUUM FULL` on postgres to reclaim diskspace and voila, everything is back to being fast 🙌
