### ISSUE TITLE
Unite the events generated by two différents Agents

### ISSUE THREAD

**Issue by Hachann** [huginn/huginn#2752]
Hello,

I succesfully created two WebSite Agents : 

1. the first Agent generates one event containing _variable1_ and _variable2_ extracted from a webpage, and uses `mode : on_change` and `Event Receiver : WebsiteAgent2`. So when these 2 variables change, and only if they change, then WebsiteAgent2 is launched.

2. This second Agent watches a number on another website, so let's call it _variable3_.

My goal is to create a sentence where I can find these three variables together, and then sending this phrase via Telegram whenever a new sentence is generated. 

I also succeeded using the Telegram Agent, but where I can't succeed so far is the grouping of variables 1, 2 and 3.

I tried making a Event Formatting Agent, with it's event sources being the first and second Website Agents, my options look like this : 

```
{
  "instructions": {
    "text": "blabla {{variable1}} bla {{variable2}} blabla {{variable3}} bla."
  },
  "matchers": [

  ],
  "mode": "clean"
}
```

But this way, this Agent gives me 2 events : the first event is the text with variables 1 and 2 and empty space instead of variable 3, and the second event is inverse miror of the latter... Where I only a want 1 event.

Do you have some ideas that might help ?

Thank you !!

**Comment by virtadpt** [comment]
You could have one Website Agent feed into the other, and the other could merge them.  I did it like this (I haven't done the writeup yet):

Website Agent #1 - get OAuth token
```
{
  "post_url": "https://my.wallabag.example.com/oauth/v2/token",
  "expected_receive_period_in_days": "365",
  "content_type": "form",
  "method": "post",
  "payload": {
    "grant_type": "password",
    "client_id": "{% credential wallabag_client_id %}",
    "client_secret": "{% credential wallabag_client_secret %}",
    "username": "{% credential wallabag_username %}",
    "password": "{% credential wallabag_password %}"
  },
  "emit_events": "true",
  "no_merge": "true",
  "output_mode": "merge"
}
```

Website Agent #2 - merge OAuth token with URL
```
{
  "expected_update_period_in_days": "365",
  "data_from_event": "{{ body | unescape }}",
  "type": "json",
  "mode": "merge",
  "extract": {
    "access_token": {
      "path": "$.access_token"
    }
  },
  "output_mode": "merge",
  "template": {
    "url": "{{ message }}"
  }
}
```

It took me a couple of days to get that right.

The other thing you could do is set the Website Agents on a schedule and feed their outputs into an Event Formatting Agent, which would merge them into a single event on a schedule.

**Comment by Hachann** [comment]
Is it possible to store variable1 and variable2 (from first Website Agent) in the Website Agent number 2, so that we pass all three variables in an Event Formatting Agent ?

**Comment by virtadpt** [comment]
Yup - that's what does it.  The `"template": {}` block in the second Website Agent lets you reformat and/or rename one or more of the fields passed into that agent if you want.
