### ISSUE TITLE
Is there a way to scrape JS rendered pages (eg. React)?

### ISSUE THREAD

**Issue by nemosmithasf** [huginn/huginn#2759]
I might be missing something, but I don't think there's any way to configure "web agent" to load javascript before scraping?

Can somebody suggest a way around this? I assume it must be built into Huginn given how comment this scenario is.

**Comment by agaelebe** [comment]
You can use PhantomJS Cloud or fulldom server.
Check the wiki:
https://github.com/huginn/huginn/wiki/Browser-Emulation-Using-PhantomJs-Cloud
https://github.com/huginn/huginn/wiki/Browser-Emulation-using-fulldom-server

**Comment by nemosmithasf** [comment]
Thanks!
