### ISSUE TITLE
WeatherAgent: DarkSky API support ending in 2021

### ISSUE THREAD

**Issue by tantalum** [huginn/huginn#2763]
https://blog.darksky.net./dark-sky-has-a-new-home/

DarkSky will be shutting down it's API in 2021. As a user I want to be able to continue to use the weather agent even after the DarkSky API shuts down.

- [ ]  Select and implement a new weather data provider.
- [ ] Add warning that the DarkSky weather provider is depreciated and will not function after 2021.
- [ ] Remove the DarkSky weather provider when the API is shut down

**Comment by virtadpt** [comment]
cf #2732.

**Comment by tantalum** [comment]
Closed as duplicate of #2732
