### ISSUE TITLE
foreman - crash in `/app/lib/huginn_scheduler.rb`

### ISSUE THREAD

**Issue by oltdaniel** [huginn/huginn#2767]
### My setup

I run huginn in the official docker container `huginn/huginn` with postgres connected, SMTP settings set and working, unsafe agents disabled. I have a Webhook Agent connected to an EMail agent.

### Issue

`foreman stdout | 10:27:11 jobs.1 | /app/lib/huginn_scheduler.rb:141:in '+': no implicit conversion of nil into String (TypeError)`
...
`2020-05-01 10:27:11,804 INFO exited: foreman (exit status 0; expected)`

Full log [`here`](https://pastebin.com/raw/BuwD4JMT).

### Result

No jobs will be executed. Incomming events e.g. Webhook calls will be still processed.

### Solutions

I tried re-creating the docker containers by deleting all volumes and data and let them boot and re-install. Same issue as before. **No solution found yet.**

**Comment by dsander** [comment]
Hi!

How did you configure the container? I think the error is related to the `TIMEZONE` environment variable.

**Comment by oltdaniel** [comment]
Hi! Currently it looks like I fixed it. I had `TIMEZONE` set and the scheduler couldn't find the wrong timezone I set. My mistake, but looks like there is no default timezone.
