### ISSUE TITLE
de_duplication_agent might need locking?

### ISSUE THREAD

**Issue by ndrwrbgs** [huginn/huginn#2770]
I tried adding more workers, and started getting inconsistent results out of the deduplication agent. Is it correct to assume that it might need locking for this scenario?

**Comment by dsander** [comment]
Yes, you are right a couple of Agents would need locking to function properly when they are run in multiple processes and on a high interval. The main problem with this is that the background processing tool we are using doesn't have support for job uniqueness.

**Comment by ndrwrbgs** [comment]
Thanks! I won't leave this open on the backlog since officially concurrency isn't supported.
