### ISSUE TITLE
Website agent - specify which field needs to be unique

### ISSUE THREAD

**Issue by GameBurrow** [huginn/huginn#2771]
I have a website agent set up with following code:

```json
{
  "expected_update_period_in_days": "30",
  "url_from_event": "https://www.lotus-simulator.de/forum/index.php?thread/778-neuigkeiten-rund-um-lotus/&pageNo={{latest_page}}",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "url": {
      "css": ".messageHeaderMetaData a",
      "value": "@href"
    },
    "title": {
      "css": ".contentTitle",
      "value": "./node()",
      "repeat": "true"
    },
    "content": {
      "css": ".messageText",
      "value": "./node()"
    },
    "date": {
      "css": ".messageHeaderMetaData time",
      "value": "@datetime"
    },
    "id": {
      "css": ".message",
      "value": "@data-post-id"
    }
  }
}
```

How can I tell it do consider it as a new item if id is different. `on_change` looks at all fields and I have a issue that posts that have youtube videos in the change with every check because the html changes a bit. Can be seen here: 
![image](https://user-images.githubusercontent.com/4341091/80963029-dc059700-8e16-11ea-871d-bded1357ce58.png)

Or can I somehow tell that don't monitor changes in `content` (because I need to pass content on to next agent)

**Comment by dsander** [comment]
You can do that by passing the Events to a `ChangeDetectorAgent` which is more configurable. The `WebsiteAgent` always checks if the whole Event it emits changed.

**Comment by GameBurrow** [comment]
Thanks, 

sorry to ask, but could you provide an example how I can configure this. The example provided with the agent doesn't really help at all (+ I a complete rookie with this liquid templating) and doesn't last_property mean it only is able to check one event behind? What would happen if the rss feed picks up item1 >item2 > item 3 > item1 (again)? Because that's the issue I have, it picks the same item up again every time it scans the website because the video iframe changes.

**Comment by dsander** [comment]
> What would happen if the rss feed picks up item1 >item2 > item 3 > item1 (again)?

In that case the `ChangeDetectorAgent` would emit the Event again, it is useful when you want to watch for changes of one property (like the price of an item for example).

For your use case the `DeDuplicationAgent` might be better you can configure it's `property` using liquid to something like this `{{url}}{{title}}{{date}}` if you only want to de-duplicate Events based on those three properties.

**Comment by GameBurrow** [comment]
That worked @dsander . Thanks.
