### ISSUE TITLE
ShellCommandAgent is escaping output

### ISSUE THREAD

**Issue by Hrafnthor** [huginn/huginn#2777]
Hi,

I have a ShellCommandAgent that performs actions on the shell that returns back a JSON payload. However the output from the agent is being escaped, which is causing me some problems further on where I am attempting to create a Liquid template to manipulate the output JSON but failing due to unexpected quotes in the string.

The output from the agent is as follows (cut down for brevity):

```
{
  "command": "<command>",
  "path": "<path>",
  "exit_status": 0,
  "errors": "<errors>",
  "output": "{\"symbol\":\"...\",\"name\":\"....\",.....}"
}
```

Am I perhaps overlooking some options for turning the escaping off for the ShellCommandAgent?

**Comment by virtadpt** [comment]
I do not think it's possible to turn off escaping.  I've no idea where this misfeature is coming from.  That said, other agents are able to parse the "output":{} objects normally.  I've got one like that and it seems to be working just fine right now.

**Comment by Hrafnthor** [comment]
Thx for the quick reply @virtadpt. It would seem that the problem was mine after all, and not related to the escaped JSON output. I did get an error indicating that a " was to blame, but turns out I was using Liquid wrong (still trying to grasp how to use it).
