### ISSUE TITLE
add string to event value

### ISSUE THREAD

**Issue by mmm286** [huginn/huginn#2779]
Hi,
With website agent I extract all events.
Now with email agent I would like to add text in one event (add "http://xxxxx.xxx.x" to event slug) like these:

{
  "subject": "NOTIFICATION",
  "headline": "Your notification:",
  "expected_receive_period_in_days": "2",
  "recipients": "XXXXXX@gmail.com",
  "body": "{{event.title}}{{event.price}}{{http://xxxx.xxx.x}}{{event.slug}}"
}

But not works, how could I do that?
Thanks!

**Comment by deurk** [comment]
use concat ?
```
"body": "concat({{event.title}}{{event.price}}, http://xxxx.xxx.x'', {{event.slug}})"

**Comment by mmm286** [comment]
> use concat ?
> 
> ```
> "body": "concat({{event.title}}{{event.price}}, http://xxxx.xxx.x'', {{event.slug}})"
> ```

Not works :-(

**Comment by deurk** [comment]
Then chain an Event Formatting Agent with your Website Agent with the following configuration:

```
{
  "instructions": {
    "body": "{{event.title}}{{event.price}} http://xxxx.xxx.x{{event.slug}})"
  },
  "mode": "merge"
}
```

**Comment by dsander** [comment]
```
 "body": "{{event.title}}{{event.price}} http://xxxx.xxx.x{{event.slug}}"
```
Should work as well, it might also be worth to have a look at the `template` option of the `WebsiteAgent` and use it with the `to_uri: _response_.url` filter (search for `template` in the description of the `WebsiteAgent` for an example)

**Comment by mmm286** [comment]
Done..
I have to do an Event Formatting Agent with preprend command:
  "Total": "{{event.title}}{{event.price}}{{ slug | prepend: 'https://ur/try/' }}"
