### ISSUE TITLE
help me to extract info with website agent

### ISSUE THREAD

**Issue by mmm286** [huginn/huginn#2784]
Hi,
I set up website agent to extract main price of url. I use "SelectorGadget" to extract css field, but no way. Someone could help me please?
My code:

{
  "expected_update_period_in_days": "2",
  "url": "https://www.ludonauta.es/buscar/cerca-y-lejos",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "url": {
      "css": "#a btn_default",
      "value": "@price"
    }
  }
}

Many thanks!

**Comment by dsander** [comment]
```json
{
  "expected_update_period_in_days": "2",
  "url": "https://www.ludonauta.es/buscar/cerca-y-lejos",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "url": {
      "css": ".product-price.btn-primary",
      "value": "normalize-space(.)"
    }
  }
}
```

This works for the "primary" price. I'd suggest reading about CSS selectors, checking out the developer tools of your browser to understand the HTML structure and reading the Agent description `@price` tries to extract the value of the `price` attribute of the selected HTML tag.
