### ISSUE TITLE
Trouble in debugging EmailAgent problem

### ISSUE THREAD

**Issue by simos** [huginn/huginn#2785]
I have a self-hosted installation of _huginn_ and I am trying to use _EmailAgent_ to send email notifications.

I have tried a few SMTP services while trying to figure out how to set them up.
I could not get email notifications to work. 
After using `tcpdump`, I noticed that _huginn_ insists on using the very first SMTP server I had configured. I have removed (`grep -r xxx`) all references to that very first SMTP server in `.env`, and also verified it is not found in the database. I also emptied the _cache_ folders in _huginn_.

Still, `tcpdump` shows attempts to connect to the old SMTP server. 
When I edit my Email agent, it still shows the old email address at the side of the edit page,

> You can provide a from address for the email, or leave it blank to default to the value of EMAIL_FROM_ADDRESS (me@THAT.OLD.DOMAIN.COM).

Where is that email _me@THAT.OLD.DOMAIN.COM_ stored in _huginn_?
Is there a way to get any debugging details from the attempt to send an email?

**Comment by dsander** [comment]
Hi!

Did you use the [manual installation](https://github.com/huginn/huginn/blob/master/doc/manual/installation.md) guide? If that is the case need to [re-export](https://github.com/huginn/huginn/blob/master/doc/manual/installation.md#install-init-script) the services with `sudo bundle exec rake production:export` after changing the configuration in `.env`

**Comment by simos** [comment]
Thanks! 
I omitted to perform the `production:export` step. I notice in the documentation that it is mentioned specifically for such issues.
