### ISSUE TITLE
[00:00:00] ERROR -- : No valid key found in event with Telegram Agent

### ISSUE THREAD

**Issue by mmm286** [huginn/huginn#2790]
Hi,
I don't know why gives me these error:
"[00:00:00] ERROR -- : No valid key found in event {"name"=>"desddf:sdfsdf", "url"=>"73342,00€"}"

In telegram agent
My code:

{
  "auth_token": "xxxxxxxxxxxxxxxxxxxxxxx",
  "chat_id": "yyyyyyyyyyyyyyyyy",
  "caption": "name",
  "disable_notification": "",
  "disable_web_page_preview": "",
  "long_message": "split",
  "parse_mode": "html"
}

Any help? Thanks

**Comment by mmm286** [comment]
Solved! The event must be text. With text message arrives ok!. Thanks

**Comment by andresmazzo** [comment]
Lucky I found this issue! :raised_hands: 
I fixed implementing `Event Formatting Agent` to manipulate data from source event.

**Comment by TradeCrafter** [comment]
i want to receive like a printscreen of the tweet on telegram, can i do that?
