### ISSUE TITLE
Unable to use built-in jq functions in filters

### ISSUE THREAD

**Issue by Hrafnthor** [huginn/huginn#2791]
Hi,

I've constructed a jq filter that works perfectly when used outside of Huginn. However due to it using strftime which requires a string input such as `strftime("%Y-%m-%d")` this breaks the JSON structure when trying to configure a jq agent.

I have attempted to escape the quotes but that breaks the filter. Anyone found a way to use these built in functions in a jq agent within Huginn?

**Comment by Hrafnthor** [comment]
Was able to figure this out.

**Comment by virtadpt** [comment]
How did you do it?  Can you post an example of what you did?
