### ISSUE TITLE
how to install docker image from different branch

### ISSUE THREAD

**Issue by mmm286** [huginn/huginn#2792]
Hi,
I would like to install docker image for different branch. Case #2563
Someone could help how could I install?
Normally for original branch I do:
 sudo docker run -it -p 3000:3000 huginn/huginn

I would like to execute : https://github.com/sfischer13/huginn/tree/docker-armhf
Thanks!

**Comment by dsander** [comment]
You have to check out the fork locally and [build it yourself](https://github.com/huginn/huginn/blob/master/docker/multi-process/README.md#building-on-your-own).
