### ISSUE TITLE
How to use Liquid in JavaScript Agent?

### ISSUE THREAD

**Issue by tortoo** [huginn/huginn#2800]
Following is the event of Manual Event Agent as source of JavaScript Agent:

`{ "count": "abc" }`

❶
```
Agent.receive = function() {
	var events = this.incomingEvents();
    for (var i = 0; i < events.length; i++){
	var a = '{{ 'now' | date : '%Y' }}'
	var e = '{{ 'events[i].payload.count' | append : 'xyz' | remove : 'bc' }}'; 
	this.log(a);
    }
};
```
Output: 
`2020`  
Liquid took effect in JavaScript Agent and `now` was recognized as variable.

❷
```
Agent.receive = function() {
	var events = this.incomingEvents();
    for (var i = 0; i < events.length; i++){
	var a = '{{ 'now' | date : '%Y' }}'
	var e = '{{ 'events[i].payload.count' | append : 'xyz' | remove : 'count' }}'; 
	this.log(e);
    }
};
```
Output: 
`events[i].payload.xyz`  
Here `events[i].payload.count` was recognized as string instead of variable. But Liquid was effect.

❸
```
Agent.receive = function() {
	var events = this.incomingEvents();
    for (var i = 0; i < events.length; i++){
	var a = '{{ 'now' | date : '%Y' }}'
	var e = {{ 'events[i].payload.count' }}; 
	this.log(e);
    }
};
```
Output:
`abc`
Here `events[i].payload.count` was recognized as variable. 

❹
```
Agent.receive = function() {
	var events = this.incomingEvents();
    for (var i = 0; i < events.length; i++){
	var a = '{{ 'now' | date : '%Y' }}'
	var e = {{ 'events[i].payload.count' | append : 'xyz' | remove : 'bc' }}; 
	this.log(e);
    }
};
```
Output nothing. `events[i].payload.count` was variable but Liquid wasn't effect.

My question is how to use Liquid in JavaScript Agent especially make the last one above output `axyz`.

**Comment by dsander** [comment]
You can't really (and shouldn't need to). Think of Liquid as a preprocessor for the JavaScript source code that will be evaluated by JavaScript. You can use liquid to generate the code, but nothing more. In practice I don't see any need to use Liquid as you have all the Events input available in JavaScript.

**Comment by tortoo** [comment]
I just want to use Liquid to handle string and nothing more. More complicated things need JavaScript such as using `Memory`. JavaScript is a little heavy to me and I'm not sure I can learn enough to master everything in JavaScript. For strings Liquid is simple and intuitive and I like Liquid very much!😹
I want to know whether JavaScript has all the filter functions in Liquid and totally replace them.
Such as the filter `{% regex_replace a in %}{{  b }}{% with %}c{% endregex_replace %}` and how to achieve that in JavaScript? Here a and b are variables.

**Comment by tortoo** [comment]
I think I got the solutions! `events[i].payload.count.replace(/bc/, "xyz")` is a good way and more simple! `"xyz"` can also be an variable. JavaScript is so strong and I love it!😻
