### ISSUE TITLE
Is there a way to get minimum and maximum of the history of events?

### ISSUE THREAD

**Issue by Xaelias** [huginn/huginn#2808]
Hi,
I tried to go through the list of agents and google search this but couldn't find anything relevant.
So apologies in advance if this has already been asked/answered.

Is there a way to extract the minimum/maximum of the events off another agent?
The use case for me is something logging prices of something. I'd like to be able to log the min/max over time when new events come in.
I can't figure out an easy way to do this.

Thanks

**Comment by dsander** [comment]
Hi!

If you have one Agent per Item you could use a `TriggerAgent` to compare the price with the maximum, then send the new price to a `CommanderAgent` that reconfigures the `TriggerAgent` with the new maximum price, the same Event that is handled by the `Commander` can also be send somewhere to send a notification.

If one Agent handles multiple item, I think it would be easier to do with a `JavaScriptAgent`.

**Comment by Xaelias** [comment]
I'm configuring one agent per item right now (it makes looking back at the history of even for a specific item easier, and also allows for different timers very easily).
Thanks I'll take a look and see if I can make this combination work.

**Comment by Xaelias** [comment]
@dsander So I see the commander agent has support for conditional actions. I assume there is no way to have variable targets?
The obvious goal would be to re-configure whatever is sending an event in the first place for instance, while a second hardcoded action could be to trigger a slack notification for instance.

**Comment by dsander** [comment]
> I assume there is no way to have variable targets?

That is correct.



> The obvious goal would be to re-configure whatever is sending an event in the first place for instance, while a second hardcoded action could be to trigger a slack notification for instance.

I think that should work for the notification, it could be handled by an Agent receiving Events from multiple `TriggerAgent`s as long as the shape of the Event payload is similar.

**Comment by Xaelias** [comment]
I ended up using the javascript agent, and basically use the memory of the agent as a database of min/max/... indexed based on the URL of the thing I'm scraping.
That way, I can have the one web agent scraping all the urls, and then the JS agent is doing the bookkeeping, the maths, and decides whether or not to trigger an alert.

Thanks for giving me pointers in all this :-)
