### ISSUE TITLE
CyberChef agent

### ISSUE THREAD

**Issue by winchester5050** [huginn/huginn#2820]
It would be massively cool to have an Agent that can tap into CyberChef's possibilities: https://gchq.github.io/CyberChef/
That would open a whole new level of automation possibilities.
The address of the CyberChef should be customizable as many people self-host it.
I came to this idea when I was trying to extract a url from a complex string in a Huginn Website agent. This is really painful using Regex (I still have not managed to do it due to the complexity of the regexp needed), but with CyberChef it is a breeze.

**Comment by dsander** [comment]
That looks like a very neat project. Thanks for posting it in the agent suggestion issue!
