### ISSUE TITLE
Extract url from page element function (onclick) using Website Agent

### ISSUE THREAD

**Issue by winchester5050** [huginn/huginn#2821]
I'm scrapping a web using the Website agent to extract a url from a specific "a" html element. The "a" element has the property onclick that contains the url, but it also contains the call to a function.

This is the html code for the element I'm scrapping:
`<a onclick="viewVacancyDetails('3945','https://some.website.com/wd/plsql/wd_portal.show_job?p_web_site_id=3325&p_web_page_id=419915')" class="">One vacancy</a>`

 This is the example of what I get in Huginn:
`"url": "viewVacancyDetails('3945','https://some.website.com/wd/plsql/wd_portal.show_job?p_web_site_id=3325&p_web_page_id=419915')",`

So far so good. Now, I'm trying to extract just the URL in the same "url" parameter. This is what I'm trying to get:
`https://some.website.com/wd/plsql/wd_portal.show_job?p_web_site_id=3325&p_web_page_id=419915`

I tried with Regexp but due to the complexity of the url formats I cannot get it done. Any idea how can I extract the url?

**Comment by dsander** [comment]
`viewVacancyDetails\('\d+','(.+?)'\)` should do it, I believe quotes inside the URL should be urlencoded, so I don't think you need to worry about them.

**Comment by winchester5050** [comment]
That one didn't work, but this one did: 
`  "matchers": [
{
   "path": "{{url}}",
   "regexp": "https.+?(?=')",
   "to":"url_clean"
}
],`
