### ISSUE TITLE
can't modify frozen String: ""

### ISSUE THREAD

**Issue by AntonMyr** [huginn/huginn#2822]
I got this issue when I used the local setup guide on Ubuntu 18.04. Everything was freshly installed.

This is what the error looks like:
![image](https://user-images.githubusercontent.com/16903933/85298983-02ee5a00-b4a5-11ea-9a8b-f461aee1e11c.png)

The temporary solution is to upgrade the `foreman` and the `kramdown` gems. This article shows how you can upgrade gems: https://sourabhbajaj.com/mac-setup/Ruby/RubyGems.html. When you upgrade your gems you also have to write the correct version number in Gemfile.

I don't know if this is the recommended thing to do but it has worked so far for me.

**Comment by dsander** [comment]
That is a very odd exception. What ruby version are you running and to which gem versions did you upgrade?

**Comment by AntonMyr** [comment]
Oh yea I forgot to add the versions. 

I'm running ruby 2.7.1.

I upgraded foreman from version 0.63.0 to 0.87.1 and kramdown from 1.3.3 to 2.2.1.

**Comment by dsander** [comment]
Sorry we don't support ruby 2.7 yet, can you try it with ruby 2.6?

**Comment by AntonMyr** [comment]
Yes I will try that as well!

I'll get back with the results.

**Comment by AntonMyr** [comment]
I tried it with Ruby version 2.6.6 and that worked as well!

**Comment by dsander** [comment]
Closing since we don't have support for ruby 2.7 yet.
