### ISSUE TITLE
How to backup, restore or use volume when using docker?

### ISSUE THREAD

**Issue by thepenguinthatwants** [huginn/huginn#2833]
Hi I could easily launch huginn using dockerhub examples. But the problem is that this doesnt seem to be persistent.
Is there any official examples on this part?

```
docker run --name huginn_postgres -e POSTGRES_PASSWORD=mysecretpassword -e POSTGRES_USER=huginn -d postgres
docker run --rm --name huginn --link huginn_postgres:postgres -p 3000:3000 -e HUGINN_DATABASE_USERNAME=huginn -e HUGINN_DATABASE_PASSWORD=mysecretpassword -e HUGINN_DATABASE_ADAPTER=postgresql huginn/huginn

```

**Comment by dsander** [comment]
You need to configure the database container to store it's data either in a docker volume or mount a local directory. See https://hub.docker.com/_/postgres for reference.
