### ISSUE TITLE
search bar missing on mobile device?

### ISSUE THREAD

**Issue by lilytumblr** [huginn/huginn#2834]
Hi, 
I use search a lot but it is not showing on mobile device. Default safari isn't showing, tried installing Firefox but no avail too. Any idea on how to fix it? No problem when i access it through desktop browsers. My device is ipad..

**Comment by dsander** [comment]
I don't think anyone ever optimized the UI for mobile browsers.

**Comment by lilytumblr** [comment]
By removing visible-lg in _navigation.html.erb actually makes it show in small screen again 😄

**Comment by dsander** [comment]
That's a good catch! Do you mind sending a pull request with the change?
