### ISSUE TITLE
no sendmail present in default huginn image?

### ISSUE THREAD

**Issue by akhe45** [huginn/huginn#2837]
I setup SMTP and it seems to be correct. However when setting up an agent and trying to run a dry run after choosing a recipient, email never gets delivered. in the logs i see:

web.1  | sh: 1: /usr/sbin/sendmail: not found

sendmail is not present in the image and i can't install it as default user does not have sudo rights.
Doesn't the standard image provide sendmail?

SMTP_DELIVERY_METHOD="sendmail"

Any suggestions?

**Comment by akhe45** [comment]
In short there is no sendmail to the base image and the delivery method is set to sendmail

**Comment by dsander** [comment]
`sendmail` will only work when a local smtp server is running which will never be the case in the docker image. Use the default `smtp` delivery option and configure the external smtp server.
