### ISSUE TITLE
Website Agent for Amazon item with multiple options

### ISSUE THREAD

**Issue by winchester5050** [huginn/huginn#2841]
I'm trying to extract the price of an Amazon item that has multiple choices. I've search previous examples for Amazon agents but none takes into account this extra complexity. This is my agent:
```
{
  "expected_update_period_in_days": "90",
  "url": "https://www.amazon.sg/Seagate-ST10000VNZ004-VN0004-IronWolf-Multicolour/dp/B07H241VK4/ref=sr_1_1?dchild=1&keywords=ironwolf%2B10tb&qid=1594694101&refinements=p_n_feature_eighteen_browse-bin%3A6450383051&rnid=6449848051&s=electronics&sr=1-1&th=1",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "body_text": {
      "xpath": "//*[@id=\"priceblock_ourprice\"]",
      "value": "string(.)"
    }
  }
}
```

And the feedback from the dry run I get:

> [00:00:00] INFO -- : Dry Run started
[00:00:00] INFO -- : Fetching https://www.amazon.sg/Seagate-ST10000VNZ004-VN0004-IronWolf-Multicolour/dp/B07H241VK4/ref=sr_1_1?dchild=1&keywords=ironwolf%2B10tb&qid=1594694101&refinements=p_n_feature_eighteen_browse-bin%3A6450383051&rnid=6449848051&s=electronics&sr=1-1&th=1
[00:00:02] INFO -- : Extracting html at //*[@id="priceblock_ourprice"]
[00:00:02] INFO -- : Values extracted: []
[00:00:02] INFO -- : Dry Run finished

I've tried getting the whole html and manually search for that id but there is probably some protection in the page that prevents it from loading the price itself in the tag. Any idea how to fix this?

**Comment by dsander** [comment]
Hmm not sure, I can't find the selector in the HTML even if I load it in a browser, it is possible that the site is using JavaScript to generate the content. Huginn itself is not able to scrape pages build via Javascript, but you can use [fulldom-server](https://github.com/strugee/fulldom-server) or https://phantomjscloud.com/ to do extraction based on the final page that has been generated by the JavaScript.

**Comment by winchester5050** [comment]
It seems more difficult than expected. I tried with PhantomJS but the price is not rendered. I will check fulldom-server. Thank you for the response.

**Comment by virtadpt** [comment]
Hmmm... thinking about this a little bit, I have a question: Do you mean an Amazon item for sale that has multiple price points, e.g., "Here's the $20us version, here's the $30us version, here's the $50us deluxe version," on pages that are of the form "Click on the variant you're interested in?"

The reason I'm asking is, I may have done something similar in the past and worked around it with the use of RSS Bridge (https://github.com/rss-bridge/rss-bridge).

**Comment by winchester5050** [comment]
Replying to your question, yes, if you check that specific article, a hard drive, it has different models: 2TB, 10TB, 14TB, etc.
What is strange is that the url already "selects" the 10TB one, so it carries the selected one, but the price is not rendered properly by Huginn nor by PhantomJS.
Can you elaborate on how you did it with rss-bridge? Sounds like an interesting idea to explore.

**Comment by procyh** [comment]
Added a header and mine is working now. You can give it a try

`  "headers": {
    "user-agent": "Mozilla/5.0"
  }`

**Comment by winchester5050** [comment]
That worked! thank you so much!
