### ISSUE TITLE
Rails 6 Zeitwerk Mode for Dependencies Autoloading breaks external Agents

### ISSUE THREAD

**Issue by alessio-signorini** [huginn/huginn#2845]
External agents which rely on `huginn_agent` are [loaded during initialization](https://github.com/huginn/huginn/blob/master/config/initializers/requires.rb#L2) and [injected in `Agent::TYPES`](https://github.com/huginn/huginn_agent/blob/master/lib/huginn_agent.rb#L31).

Rails 6 implements a [new dependencies autoloading system called Zeitwerk Mode](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html).

Unfortunately this change breaks `huginn_agent` paradigm because `Agent::TYPES` will be rebuild from scratch after initialization and only contain default agents.

It also generates a lengthy warning when running tests
```
DEPRECATION WARNING: Initialization autoloaded the constants AssignableTypes,
MarkdownClassAttributes, JsonSerializedField, RdbmsFunctions, WorkingHelpers,
LiquidInterpolatable, HasGuid, LiquidDroppable, DryRunnable, SortableEvents,
OwnedByValidator, Agent, and FormConfigurable.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload AssignableTypes, for example,
the expected changes won't be reflected in that stale Module object.

These autoloaded constants have been unloaded.

Please, check the "Autoloading and Reloading Constants" guide for solutions.
 (called from <top (required)> at /home/alessio/huginn/config/environment.rb:5)
```

**Comment by alessio-signorini** [comment]
Current workaround is to [opt-out of Zeitwerk Mode](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#opting-out) adding
```ruby
config.autoloader = :classic
```
to `config/application.rb` but a more permanent fix needs to be implemented.

**Comment by dsander** [comment]
Hmm this is odd I am using a bunch of Agent gems in production and don't seem to have any issues with it. In which environments are you seeing the issue?

**Comment by alessio-signorini** [comment]
I too have a production system that kept/keeps chugging along and drove me nuts when suddenly I could no longer develop locally external gems!

I just looked at your commits and on [May 26th you did force](https://github.com/huginn/huginn/commit/2efdf4cdcb0ecfbfba3da5c258ef6ffd1bcf4758#diff-b1fe55db50c712fef0673345e5b9c0d9R15) `config.autoloader` to `classic`.

**Comment by dsander** [comment]
Urg, that is annoying I thought I still had Agent gems active in my development environment. I guess the auto-reloader changed in some way that it breaks.I think we should still try to support the new autoloader because I am assuming Rails will get rid of the old one at some point, but I don't know when I have the time to work on it.

**Comment by alessio-signorini** [comment]
@dsander - now that `huginn_agent` is part of the master codebase, we could improve/expand the [definition of `TYPES`](https://github.com/huginn/huginn/blob/master/app/concerns/assignable_types.rb#L21) to include Agent gems and easily/cleanly solve this. I can take a stab at it if it sounds good to you.

**Comment by dsander** [comment]
Sure, that would be great!

**Comment by alessio-signorini** [comment]
Patch is ready and quite simple (example below). As soon the change in `huginn_agent` is merged (will make things cleaner) I'll open a PR for this.

```ruby
    def types
      all_agents.map(&:constantize)
    end

    def all_agents
      const_get(:TYPES) + HuginnAgent.additional_agents
    end

    def valid_type?(type)
      all_agents.include?(type)
    end
```

**Comment by dsander** [comment]
That's great! Can you open a PR to Huginn as well? You can switch the branch of `huginn_agent` in the `Gemfile` similar to [this](https://github.com/huginn/huginn/blob/master/Gemfile#L65)
