### ISSUE TITLE
Preventing Internal MySQL From Starting Up in Docker Container is Not Working

### ISSUE THREAD

**Issue by jimmybrancaccio** [huginn/huginn#2849]
Greetings,

I'm using the Docker container for my Huginn instance, however I can't seem to get it to _not_ start the MySQL service. I am using MariaDB in another container which is working fine (I see the Huginn database populated with stuff). In my `docker-compose.yml` file I have:

```yaml
links:
    - mariadb
```

However I can see it has started the MySQL service:

```
default      378  0.0  0.0   4624  1692 ?        S    11:49   0:00 /bin/sh /usr/bin/mysqld_safe --init-file=/app/tmp/mysql_init.sql
default      742  0.1  0.2 1440632 198376 ?      Sl   11:49   0:00  \_ /usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib/mysql/plugin --init-file=/app/tmp/mysql_init.sql --log-error=/var/log/mysql/error.log --pid-file=/app/tmp/pids/mysqld.pid --socket=/app/tmp/sockets/mysqld.sock --port=3306 --log-syslog=1 --log-syslog-facility=daemon --log-syslog-tag=
```

How do I get it to not do this?

Thanks!

P.S. I did try asking in Gitter several times but that seems to be a dead channel.

**Comment by dsander** [comment]
Hmm the code looks like [this logic](https://github.com/huginn/huginn/blob/7ca39eb9dda5bb5862a7163228147fd5c97b3358/docker/scripts/setup_env#L22-L34) should not set the `START_MYSQL` variable in your setup which is then [checked later](https://github.com/huginn/huginn/blob/13d0ca344ae72515795645db058e7c329fd3de5d/docker/multi-process/scripts/bootstrap.sh#L7) to determine if the server should be started. Can you try to set `START_MYSQL=false` in the environment you set for your docker containers?

**Comment by jimmybrancaccio** [comment]
@dsander That seems to have done the trick. No more MySQL 😝 Thanks!
