### ISSUE TITLE
LiquidOutputAgent: How to pass last 5 minutes events to the template

### ISSUE THREAD

**Issue by procyh** [huginn/huginn#2851]
Hi, I tried many times.... just don't know how to use this "Last X events" mode and the "5 minutes" filter. 

Can you please help? Thanks!

When I tried this, I was not able to save this agent and got this error: Event limit must be an integer that is less than 1001.
![1](https://user-images.githubusercontent.com/58379915/88742447-41181280-d110-11ea-8a5e-f9cb1a117951.png)

I can select "manual input" > input "5 minutes" > save, but it doesn't provide any output.
![3](https://user-images.githubusercontent.com/58379915/88742558-88060800-d110-11ea-8da3-3c0c79709097.png)
![2](https://user-images.githubusercontent.com/58379915/88742452-437a6c80-d110-11ea-879e-9ff1b4898876.png)

It only works when I input an integer number...
`  "mode": "Last X events",
  "event_limit": "10"`

**Comment by dsander** [comment]
That looks like a bug in the validation to me, no idea how and if that ever worked 😄

**Comment by procyh** [comment]
oh, that is a bug. I see. Glad that I found a bug in this great system. : )

**Comment by procyh** [comment]
It is working. Thanks for fixing the bug! 👍
