### ISSUE TITLE
RSS changed now problem with formatting

### ISSUE THREAD

**Issue by JtheBAB** [huginn/huginn#2852]
Dear all

I fetch pubmed with the RSS Option. Now it looks like they change the authors output from:

`"authors": [
    " Schuler BR, Daundasekara SS, Hernandez DC, Dumenci L, Clark M, Fisher JO, Miller AL"
  ],`

to 

`"authors": [
    "Melanie B Horev",
    "Yishaia Zabary",
    "Revital Zarka",
    "Simona Sorrentino",
    "Ohad Medalia",
    "Assaf Zaritsky",
    "Benjamin Geiger"
  ],`

which causes me problems with my post agent

`"payload": {
    "text": "[{{title}}]({{url}}) - by {{authors}} :tada:"
  },`

The problem is that now it comes like 

`Melanie B Horev,Yishaia Zabary,Revital Zarka,Simona Sorrentino,Ohad Medalia,Assaf Zaritsky,Benjamin Geiger`

instead of

`Melanie B Horev, Yishaia Zabary, Revital Zarka, Simona Sorrentino, Ohad Medalia, Assaf Zaritsky, Benjamin Geiger`

Is there any possibility within huginn to get the nice formated authors?

Thanks

**Comment by dsander** [comment]
Hi!

Does `{{authors | join: ', '}}` work?

**Comment by JtheBAB** [comment]
@dsander you are a hero. Working perfectly :)

Thank you very much.
