### ISSUE TITLE
Admin access required to view that page

### ISSUE THREAD

**Issue by jwigert** [huginn/huginn#2856]
Every few days, I end up with a lot of pending jobs, but no jobs are being processed. I'm not able to navigate to /jobs, so I can't see which jobs are pending and why. I get the following error message when trying to navigate to /jobs:
"Admin access required to view that page"
I'm running on heroku, and there is only one huginn user set up. This user has the role "owner", and my understanding is that this user should have admin access.
I'd be grateful for any guidance on how to analyze the issue.

**Comment by dsander** [comment]
Hmm that is odd, did you create the user when running `bin/setup_heroku`? That user should be an admin. The easiest way to make your user an admin is to start a rails console via `heroku run rails  c` and run `User.first.update(admin: true)` in the console. After that your user should be an admin.

**Comment by jwigert** [comment]
I set it up about 3 months ago, so I'm afraid I don't remember exactly how I created the user. The solution you provided solved the issue. Thanks!
