### ISSUE TITLE
Proxy Web Request

### ISSUE THREAD

**Issue by Brets0150** [huginn/huginn#2859]
Hello,
I am looking to use a socks proxy for web agent requests. I could not find anything in the wiki or .env file about doing this.

Is there a setting somewhere for this?

**Comment by virtadpt** [comment]
I don't know.  I managed to do something similar with a public proxy gateway, if you're doing what I think you are.

**Comment by Brets0150** [comment]
I am trying to force the huginn web agent to use TOR, so I can scan DW sites for change. I just need to proxy the request to localhost:9050. 

I tried adding 'HTTP_PROXY: "localhost:9050" ' to the .env file but no luck.

**Comment by dsander** [comment]
@Brets0150 You can specify the proxy in the `proxy` options key when configuring your website or post Agents.

**Comment by virtadpt** [comment]
@Brets0150 Yup, that's what I'm doing.  I pull sites by prepending the Tor hostname to `onion.pet`.

**Comment by Brets0150** [comment]
Hello,
Thanks for all the advice. I ended up using the "onion.pet" option since this produced fewer issues.

**Comment by gingerbeardman** [comment]
> @Brets0150 Yup, that's what I'm doing. I pull sites by prepending the Tor hostname to `onion.pet`.

@virtadpt can you please explain this further?

**Comment by gingerbeardman** [comment]
Ah, so this only works for Onion sites, right? Not generally for any URL?

Sorry, I'm not really familiar with onion/tor/etc.

**Comment by virtadpt** [comment]
I don't know.  I only use the method for onionsites.  I can't reach onion.pet from where I'm at right now so I'll have to check later.  They might be having problems right now.
