### ISSUE TITLE
Issues with UTF-8 Character Sets

### ISSUE THREAD

**Issue by Silvenga** [huginn/huginn#286]
I'm having issues with saving any text with UTF-8 characters. The issue appears whenever Huginn attempts to save output to the MySQL database.

One of the exceptions thrown:
`ActiveRecord::StatementInvalid: Mysql2::Error: Incorrect string value: '\xE2\x98\x85 Ca...'`

This causes Huginn to loop indefinitely.  In order to fix the issue I converted my database to use the UTF-8 character sets. 

```
SHOW VARIABLES LIKE 'character\_set\_%';
+--------------------------+--------+
| Variable_name            | Value  |
+--------------------------+--------+
| character_set_client     | utf8   |
| character_set_connection | utf8   |
| character_set_database   | utf8   |
| character_set_filesystem | binary |
| character_set_results    | utf8   |
| character_set_server     | utf8   |
| character_set_system     | utf8   |
+--------------------------+--------+
```

This however creates issues with the Website Agent. Huginn saves the UTF-8 characters as `?`. This prevents any type of matching from being accurate.

**Comment by jonaslejon** [comment]
From my fresh install of Ubuntu 14.04.2 LTS and most recent Huginn:

MySQL Server version: 5.5.43-0ubuntu0.14.04.1 (Ubuntu)

05:14:05 jobs.1 | Exception Mysql2::Error: Incorrect string value: '\xF0\x9F\x8E\x89\xE2\x9C...' for column 'last_error' at row 1: UPDATE `delayed_jobs` SET `last_error` = 'Mysql2::Error: Incorrect string value: \'\\xF0\\x9F\\x8E\\x89\\xE2\\x9C...\' for column \'message\' at row 1: INSERT INTO `agent_logs` (`level`, `message`, `agent_id`, `created_at`, `updated_at`) VALUES (4, \'Exception during check. Mysql2::Error: Incorrect string value: \\\'\\\\xF0\\\\x9F\\\\x8E\\\\x89\\\\xE2\\\\x9C...\\\' for column \\\'payload\\\' at row 1: INSERT INTO `events` (`user_id`, `payload`, `agent_id`, `created_at`, `updated_at`) VALUES.. cut..

Seems to be related to Emojis in the twitter stream.

```
mysql> SHOW VARIABLES LIKE 'character\_set\_%';
+--------------------------+---------+
| Variable_name            | Value   |
+--------------------------+---------+
| character_set_client     | utf8    |
| character_set_connection | utf8    |
| character_set_database   | utf8    |
| character_set_filesystem | binary  |
| character_set_results    | utf8    |
| character_set_server     | utf8mb4 |
| character_set_system     | utf8    |
+--------------------------+---------+

mysql> SHOW CREATE TABLE events\G
*************************** 1. row ***************************
       Table: events
Create Table: CREATE TABLE `events` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL,
  `agent_id` int(11) DEFAULT NULL,
  `lat` decimal(15,10) DEFAULT NULL,
  `lng` decimal(15,10) DEFAULT NULL,
  `payload` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `expires_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_events_on_user_id_and_created_at` (`user_id`,`created_at`),
  KEY `index_events_on_agent_id_and_created_at` (`agent_id`,`created_at`),
  KEY `index_events_on_expires_at` (`expires_at`)
) ENGINE=InnoDB AUTO_INCREMENT=7783 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
1 row in set (0.00 sec)

**Comment by cantino** [comment]
Hey @jonaslejon.  Do you have `DATABASE_ENCODING=utf8mb4` in your `.env` file?

**Comment by jonaslejon** [comment]
@cantino No. It was the default DATABASE_ENCODING=utf8

Worked when I changed it to DATABASE_ENCODING=utf8mb4, thanks!

**Comment by cantino** [comment]
@knu, should I make `DATABASE_ENCODING=utf8mb4` the default in `.env.example`?

**Comment by virtadpt** [comment]
@cantino Yes, please!

**Comment by dsander** [comment]
@cantino If you do so, please add a warning for postgresql users, since that encoding probably is not supported.

**Comment by virtadpt** [comment]
This seems to suggest that it does: http://www.postgresql.org/message-id/201503061055293002598@pconline.com.cn

Official Postgres docs do not say anywhere that it does:

http://www.postgresql.org/docs/9.3/static/multibyte.html

http://www.postgresql.org/docs/9.0/static/multibyte.html

**Comment by cantino** [comment]
You're correct, though, that having `DATABASE_ENCODING=utf8mb4` is invalid when I try to make a postgres database.  Darn, I guess we shouldn't change the default.
