### ISSUE TITLE
Add port to Http Status Agent

### ISSUE THREAD

**Issue by Petemir** [huginn/huginn#2865]
Hello,

Is there any reason why it isn't possible to use a port in the HTTP Status Agent? Some web services answer in ports other than 80/443, so it could be useful to just add ":port" to the URL.

Thanks!

**Comment by dsander** [comment]
Hi!

Did you try to use `http::/some.server.com:1234` as the URL? I just glanced at the code and I would assume that this works.

**Comment by Petemir** [comment]
Hi @dsander , thanks for the answer. Sorry, but is it possible that you have a typo? (::/ instead of ://)

Nevertheless,  if I try (i.e., a dry-run) https://URL/ or http://URL, I get a 403 HTTP status code [0], which is OK because I have nothing running in that domain:port (443/80, default). If I try https://URL:8384 or http://URL:8384, I get an empty event.

Thanks!

[0]


[
  {
    "url": "http://URL",
    "response_received": true,
    "elapsed_time": 1.0654824599998847,
    "final_url": "https://URL/",
    "redirected": true,
    "status": "403"
  }
]



[1]
[00:00:00] INFO -- : Dry Run started
[00:00:05] INFO -- : Dry Run finished

**Comment by dsander** [comment]
Hmm I just tried it with `http://www.asnt.org:8080/Test.html` that that seems to work:

```
[
  {
    "url": "http://www.asnt.org:8080/Test.html",
    "response_received": true,
    "elapsed_time": 0.392034343094565,
    "final_url": "http://www.asnt.org:8080/Test.html",
    "redirected": false,
    "status": "200"
  }
]
```

**Comment by Petemir** [comment]
OK, it is clearly something wrong with my setup, apparently invalid certificate problems (`ERROR: cannot verify domain.com's certificate` from curl) will generate this. Sorry.
