### ISSUE TITLE
Twitter agents suddenly not pulling tweets using list searching

### ISSUE THREAD

**Issue by TheChrisK** [huginn/huginn#2869]
Hey team,

Not sure where to start. I have two Huginn installs running on two Ubuntu VMs (one in Rackspace and one in VMWare locally) with several Twitter agents that are posting to Discord webhooks. About 24 hours ago, they just stopped pulling new items. There are no errors in the logs. The agent seems to run fine but nothing is generated. API keys are correct and I just updated to the latest release. The Rackspace instance is quite large with around 200 agents configured.

I haven't really had to touch anything on either deployment for months so I know nothing has changed on my end.

What can I provide to help troubleshoot this?

**Update: I am able to successfully pull tweets from a single account (from:username). List searching seems to have stopped functioning. (i.e. list:username/listname).**

**Comment by TheChrisK** [comment]
It's been 12 days. Is Huginn still supported here?

**Comment by TheChrisK** [comment]
I'm not sure what changed or even what happened but the agents I have set up for list searching suddenly started pulling again. It's been 24 hours since this started and they seem to be stable. Hopefully it is a temporary issue that has since been resolved. Perhaps Twitter API?

**Comment by virtadpt** [comment]
Could be.  None of me have heard anything about it, but birbsite isn't the greatest about status reports that don't involve complete system failures.

**Comment by dsander** [comment]
Sorry I don't know, we didn't change anything and I don't use twitter lists. Let's hope it was just a glitch in the twitter API.

**Comment by TheChrisK** [comment]
> Sorry I don't know, we didn't change anything and I don't use twitter lists. Let's hope it was just a glitch in the twitter API.

Yeah most likely. Still working fine today. Thanks for the response.
