### ISSUE TITLE
有偿，100元求助：利用huginn获取子网页“新闻”里的内容，制作rss。手机18028750764 联系人：郑生 

### ISSUE THREAD

**Issue by iyzh635428** [huginn/huginn#2873]
我想利用huginn制作rss，获取关于小米集团的新闻，但由于“新闻”是这个页面下的子网页，我无法像获取静态网页那样，顺利获取里面的内容。有没有高手可以点拨一下？如果我成功解决问题，我会支付100元给首位点拨我的人，谢谢！如果希望通过淘宝平台交易也行。
利用huginn制作rss获取静态网页内容我已经滚瓜烂熟了，这些细节无需指点。请提供一下关键的，这个“新闻”选项卡下的内容有点不一样，好像是动态的，无法按常规方法获取。
网址：https://www.laohu8.com/stock/01810 
![202009152](https://user-images.githubusercontent.com/51829028/92306386-4eeb6e00-efc1-11ea-8a51-e1e956ab2cb9.jpg)
![2020091511](https://user-images.githubusercontent.com/51829028/92306389-53178b80-efc1-11ea-8c65-cf174a39ea6e.jpg)

**Comment by 10362227** [comment]
有json https://www.laohu8.com/proxy/news/news/list?symbols=01810&pageCount=1
