### ISSUE TITLE
Omniauth/rack can not find a valid mapping for path with new omniauth gem

### ISSUE THREAD

**Issue by cristovao-alves-apilio** [huginn/huginn#2892]
Hi There,

I've spent a couple of days trying to wrap my head around how to solve this issue and I got stuck. I got some inspiration from other gems ([37signals](https://github.com/tallgreentree/omniauth-37signals), [dropbox](https://github.com/stve/omniauth-dropbox), [lifx/](https://github.com/hfwang/omniauth-lifx/), etc) but I'm not being able to understand the differences or why mine does not work and others do.
So I'm able to get the service:
![service](https://user-images.githubusercontent.com/56302459/96971859-03ac0100-1516-11eb-8478-6eaabd69f13a.png)
But after authenticating I get an error:
`RuntimeError at /auth/tuya/callback: Could not find a valid mapping for path "/auth/tuya/callback"`

Here is the log:
![log](https://user-images.githubusercontent.com/56302459/96971222-1eca4100-1515-11eb-910c-88f25af63ec4.png)

**Strategy**:
```
module OmniAuth
  module Strategies
    class Tuya < OmniAuth::Strategies::OAuth2
      option :client_options, {
        :site => 'https://openapi.tuyaeu.com',
        :authorize_url => '/login/open/tuya/login/v1/index.html',
      }

      uid {
        user_uuid
      }

      def user_uuid
        all_devices
        @user_uuid
      end

      def all_devices
        return @all_devices if @all_devices
        @all_devices = {}
        uri = URI("https://api.tuya.com/v1/devices/all")
        req = Net::HTTP::Get.new(uri)
        req["Authorization"] = "Bearer #{access_token.token}"
        Net::HTTP.start(uri.host, uri.port, :use_ssl => true) do |http|
          res = http.request(req)
          @user_uuid = res["uid"]
          @all_devices = JSON.parse(res.body)
        end
        return @all_devices
      end
    end
  end
end
```

**gemspec**:
```
# coding: utf-8
lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'omniauth/tuya/version'

Gem::Specification.new do |spec|
  spec.name          = "omniauth-tuya"
  spec.version       = Omniauth::Tuya::VERSION
  spec.authors       = ["Example name"]
  spec.email         = ["mail@example.com"]

  spec.summary       = %q{The Tuya startegy for OmniAuth}
  spec.description   = %q{The Tuya strategy for OmniAuth 1.x}
  spec.homepage      = "https://example.com"
  spec.license       = "MIT"

  spec.files         = `git ls-files -z`.split("\x0").reject { |f| f.match(%r{^(test|spec|features)/}) }
  spec.bindir        = "exe"
  spec.executables   = spec.files.grep(%r{^exe/}) { |f| File.basename(f) }
  spec.require_paths = ["lib"]

  spec.add_dependency 'omniauth', '~> 1.0'
  spec.add_dependency 'omniauth-oauth2', '~> 1.1'

  spec.add_development_dependency "bundler", "~> 1.11"
  spec.add_development_dependency "rake", "~> 10.0"
end
```

Agent using this omniauth gem:
```
require "huginn_tuya_agents/version"
require "huginn_agent"
require "omniauth-tuya"
require "devise"

module HuginnTuyaAgents
  I18n.load_path << "#{File.dirname(__FILE__)}/locales/devise.en.yml"

  begin
    Devise.setup do |config|
      if defined?(OmniAuth::Strategies::Tuya) &&
          (key = ENV["TUYA_CLIENT_ID"]).present? &&
          (secret = ENV["TUYA_CLIENT_SECRET"]).present?
        config.omniauth :tuya, key, secret
      end
    end
  end
end

HuginnAgent.load 'huginn_tuya_agents/clients/tuya_client'
HuginnAgent.load 'huginn_tuya_agents/concerns/tuya_agentable'
HuginnAgent.load 'huginn_tuya_agents/service_option'
HuginnAgent.register 'huginn_tuya_agents/tuya_pulse_lights_agent'
HuginnAgent.register 'huginn_tuya_agents/tuya_toggle_lights_agent'
```

Preview of workflow:
![screencast_00000](https://user-images.githubusercontent.com/56302459/96973049-aa44d180-1517-11eb-880f-aa667400e366.gif)

Is there an approach I haven't considered that will allow me to achieve this? Or I'm missing something?

**Comment by dsander** [comment]
Sorry for the late reply, I am not sure if it's possible to use an Agent gem with a omniauth provider. It is possible that there is some sort of "race condition" between the gems registering themselves against/with omniauth/devise. Were you able to test the omniauth strategy with a "plain" rails application (without the complication of a Huginn agent gem)?

**Comment by cristovao-alves-apilio** [comment]
@dsander Thank you for the reply!
I ended giving up on this, at least for now.
I was able to test it in a standalone app, and it did work. Likewise, I agree with you, it may be a "race condition".

If I get back to this again and make it work I will post something here.
