### ISSUE TITLE
The "Deploy to Heroku" button got some troubles

### ISSUE THREAD

**Issue by shyrz** [huginn/huginn#2893]
![image](https://user-images.githubusercontent.com/5728981/97173945-4eef3980-17cc-11eb-9a9b-2c098cfef95b.png)

**Comment by joelvh** [comment]
@shyrz just worked for me. Maybe it's a browser issue for you? I get redirected here: https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2Fhuginn%2Fhuginn&template=https%3A%2F%2Fgithub.com%2Fhuginn%2Fhuginn

**Comment by dsander** [comment]
> @shyrz just worked for me. Maybe it's a browser issue for you? I get redirected here: https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2Fhuginn%2Fhuginn&template=https%3A%2F%2Fgithub.com%2Fhuginn%2Fhuginn

Agreed, the button works for me as well, check your browser (extensions).
