### ISSUE TITLE
Tumblr Agent

### ISSUE THREAD

**Issue by 0xdevalias** [huginn/huginn#290]
Quick note to remind myself that I want to create a Tumblr agent.

Basic Idea:
- Events From Tumblr
  - Monitor a users posts
  - Monitor specific hashtag posts for a user
  - Monitor 'stream' hashtags/searches
  - General notification/stats type stuff (new follower, reblogged, liked, etc)
  - Ability to differentiate between actual post and reblog?
  - Filter to certain post types?
  - Etc?
- Events To Tumblr
  - Create new post (of different types)
  - Follow user?
  - Etc?

Ref:
- http://www.tumblr.com/docs/en/api/v2

**Question:** With something as 'complex' as this, should it all be in one agent (that has different 'modes'), or should it be split into multiple semi-related agents (like Twitter currently is) If multiple agents, is there a nice way to 'group' related agents together? Perhaps we could have related agents in 'subpackages' that come as a bundle (even if they are technically in separate source files)?

As always, open to ideas/suggestions/comments/criticism.

**Comment by edent** [comment]
There is an official Ruby Gem, if that's any help https://github.com/tumblr/tumblr_client
