### ISSUE TITLE
can't login if behind Cloudflare https mode 

### ISSUE THREAD

**Issue by saiqulhaq** [huginn/huginn#2902]
I use docker version https://hub.docker.com/r/huginn/huginn behind Cloudflare

when I login using http, it works
but if using https, it says `The change you wanted was rejected`

![image](https://user-images.githubusercontent.com/1275215/99377788-38cf2780-28f9-11eb-98ab-7b225489759e.png)

**Comment by mfontani** [comment]
Ensure your web server (the one in front of the docker isntance) sets X-Forwarded-Proto to https if the request comes via https.

**Comment by dsander** [comment]
I believe the solution suggested by @mfclarke should solve the problem. Feel free to reopen the issue if you still have problems.
