### ISSUE TITLE
Another WebAgent question, monitoring a specific part of a page 

### ISSUE THREAD

**Issue by JTT-JustTheTip** [huginn/huginn#2916]
Hi, 

So like many people right now I am attempting to monitor stock numbers / see when a particularly sought after item is back on sale. 

I thought it would be a good idea to monitor the page which has them all listed on the store ill be getting said item from, but the issue is the banner ads cause it to alert me to a change 1/5 times it checks, which is becoming annoying, so I though I could use the xpath reference for the "In Stock" filter option which has the number of in stock lines to monitor for the change I am after. The issue is every time I do a dry run it shows nothing in the values extracted field which to me seems like it cant see anything and therefore wont detect a change. 

To get the XPath I have been using chromes inspect element function and copying the full XPath. the template is shown below

```
{
  "expected_update_period_in_days": "1",
  "url": "https://www.scan.co.uk/shop/computer-hardware/gpu-nvidia/geforce-rtx-3060-ti-graphics-cards#filter=1",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "url": {
      "xpath": "/html/body/div[2]/div[3]/div[3]/div/div[1]/div/div[2]/div[1]/div/ul/li[1]",
      "value": "normalize-space(.)"
    }
  }
}
```

Here is the dry run output 

```
[00:00:00] INFO -- : Dry Run started
[00:00:00] INFO -- : Fetching https://www.scan.co.uk/shop/computer-hardware/gpu-nvidia/geforce-rtx-3060-ti-graphics-cards#filter=1
[00:00:00] INFO -- : Extracting html at /html/body/div[2]/div[3]/div[3]/div/div[1]/div/div[2]/div[1]/div/ul/li[1]
[00:00:00] INFO -- : Values extracted: []
[00:00:00] INFO -- : Dry Run finished
```

What exactly is it that I am missing or am I doing this correctly?

And before anyone asks, no I am not using this to scalp them or be malicious, I missed the launch of this card and my brother and I would quite one for our PC's as his is affecting his work now as well. 

Thanks

**Comment by JTT-JustTheTip** [comment]
Found alternate solution

**Comment by virtadpt** [comment]
What was your solution?

**Comment by JTT-JustTheTip** [comment]
I found API site which just gave me a JSON output and I watched that output for changes instead. Was a much simpler way of doing it.

I never found a solution to my original problem as such.
