### ISSUE TITLE
After I use reverse proxy, I can't log in via domain

### ISSUE THREAD

**Issue by starsareintherose** [huginn/huginn#2954]
After I use reverse proxy, I can't log in. I let my_IP:3000 reserve proxy huginn.my_domain and then I found that I can log in via the IP:port but when I use the huginn.my_domain to log in, the word "The change you wanted was rejected. Maybe you tried to change something you didn't have access to." is present and I can't login.
What's the problem? And how I can solve it?

**Comment by Neutrino3316** [comment]
You may refer to these comments

https://github.com/huginn/huginn/issues/2357#issuecomment-442313281
https://github.com/huginn/huginn/issues/2569#issuecomment-547844248

**Comment by JC5** [comment]
If you have this line in your reverse proxy config, REMOVE it:

```
add_header Referrer-Policy no-referrer;
```

Correct value:

```
#add_header Referrer-Policy no-referrer;
```
