### ISSUE TITLE
Wait between events

### ISSUE THREAD

**Issue by hunhejj** [huginn/huginn#2955]
I have an agent that generates multiple events. It is the source for a Website Agent. Currently all events are performed immediately by the website agent resulting in many requests within a short time. 

Is it possible with any of the agents to throttle the events, i.e. define a delay time _between_ events? I still want to keep all of them, but don't want to overload the target pages.

**Comment by virtadpt** [comment]
You could either use a Scheduler Agent to schedule the Website Agent in a more polite manner, or you could use a Delay Agent to buffer events that your Website Agent emits.

**Comment by hunhejj** [comment]
I checked them both, but as I understood they are both doing a different thing. I don't see how I could delay the time _between_ each event if a group of events is emitted from the previous event. Could you please show me an example @virtadpt ?

**Comment by virtadpt** [comment]
```
    {
      "type": "Agents::DelayAgent",
      "name": "Cataclysm - Grab the sensor reading from mom's when she wakes up",
      "disabled": false,
      "guid": "a0e4c0edb1a50cc294fb59b90bbc30d8",
      "options": {
        "expected_receive_period_in_days": "7",
        "max_events": "1",
        "keep": "newest",
        "max_emitted_events": "1"
      },
      "schedule": "5am",
      "keep_events_for": 86400,
      "propagate_immediately": false
    }
```

"Run at 0500 hours.  Emit at most one event.  That event is always the newest one received.  The size of the buffer is one event - all others are silently dropped."

**Comment by hunhejj** [comment]
My use case is somewhat different:
1. Website Agent "A" extracts multiple (different) urls from a single site and emits them as separate events
2. Website Agent "B" receives these urls and is supposed to parse them.

However currently it parses _all_ events emitted from "A" at once (more or less). Thus effectively overloading the target url. 

Instead I would like to achieve the following:
1. Website Agent "A" emits 12 events at once
2. Some middleware adds a delay between all these events, e.g. the events are propagated one by one with 6 seconds between them, no event is dropped though
3. --> Website Agent "B" never receives events more often than 6 seconds

**Comment by Unending** [comment]
This is exactly what the delay agents does.

- Set `max_events` to a high number (higher than ever could be buffered at once) so that no events are ever dropped.
- Set `max_emitted_events` to the number of events you want to emit at the same time.
- Set the delayed agent schedule to the frequency that you want the events to be emitted.

e.g.: website agent A → delay agent → website agent B: delay agent schedule = Every 15m, `max_emitted_events` = 1.
Website agent A will create an event for each URL scraped, the delay agent will hold these and emit 1 event every 15 minutes to website agent B, which will scrape them in turn (immediately or when event propagation runs each minute).

The shortest possible time to schedule something is 1 minute.

**Comment by kurzschlussstrom** [comment]
Thanks @Unending, that's perfectly what I wanted! Until now I couldn't understand how the delay agent could do what I want it to do.

Any chance that I can have smaller schedules than 1 minute?

**Comment by hunhejj** [comment]
Thanks @Unending, that's perfectly what I wanted! Until now I couldn't understand how the delay agent could do what I want it to do.

Any chance that I can have smaller schedules than 1 minute?

**Comment by Unending** [comment]
@hunhejj Guess you could use the scheduler agent for that.

**Comment by XRakudaiKaiX** [comment]
> @hunhejj Guess you could use the scheduler agent for that.

Can you share an example sir?

**Comment by Unending** [comment]
@virtadpt Depends on your cron flavor.

According to the help text of the Schuleder Agent you can go as low as 15 seconds.

> You can optionally specify seconds before the minute field.
> 
> * `*/30 * * * * *`: every 30 seconds
>
> Only multiples of fifteen are allowed as values for the seconds field, i.e. `*/15`, `*/30`, `15,45` etc.

I haven't tried it though.

**Comment by carmatana** [comment]
HI,

I have had a bad time trying to use DelayAgent.

My case:

(1) I have a list of stock symbols a CSV file (symbols.csv)
(2) I read the file  with File Agent and CSV Agent **and for each row**, I send the the symbol to a Website agent that extracts, among other things, the last stock price available. So, I have 10 stocks the Website agent runs ten times.
(3) This info is written in another CSV file, line by line, for each symbol (data.csv). Assuming again 10 stocks, this agent generates 10 events.

when the above finishes, I have all the stocks and their prices that I need in the data.csv file.

-----

(4) Then I read the data.csv file and send the whole file (in this case not line by line) to a Formatting agent. So, regardless of the number of stocks I want this agent to generate a single event for all the info.
(5) and then to a Pushover agent
(6) and finally, I erase the data.csv file  to start fresh then next time.

All the events, have Schedule = Never, except 2. That is triggered by a Scheduler Agent at certain times.
 

------

My problem:

Between (3) and (4) I put a DelayAgent with the following parameters:


  "max_events": "1",     ====> I do not want to accumulate events in (3), just want to keep only 1 to trigger step number 4), that it is scheduled to run only when receiving events (Schedule = Never)

  "keep": "newest",

  "max_emitted_events": "1"   ======> again, I only need to keep one event to trigger next Receiver agent (4)

  "emit_interval": "60". ===== > I guess this is the time the Writing CSV agent in (3) takes to write all the data and the time I was hoping the next agent (4) would be triggered.


-----

This does not work. (4) is never triggered.

I tried other parameters with no success.

-----

Am I understanding correctly the Delay Agent ?
