### ISSUE TITLE
cannot create regular file '/app/.env': Permission denied

### ISSUE THREAD

**Issue by bobokun** [huginn/huginn#2958]
The latest image of the docker container is giving me this error and I'm unable to start the container.
Using the docker previous docker container works fine. `docker pull huginn/huginn:2ab169a8d03dcc425796093e3d358ea9caf30734`

### Logs:
```
Generating random APP_SECRET_TOKEN.
1+0 records in
1+0 records out
36 bytes copied, 2.4043e-05 s, 1.5 MB/s
cp: cannot create regular file '/app/.env': Permission denied
```

### Docker Create:
`docker create --name='huginn' --net='proxynet' -e TZ="America/New_York" -e HOST_OS="Unraid" -p '3050:3000/tcp' -v '/mnt/user/appdata/Huggin':'/var/lib/mysql':'rw' 'huginn/huginn'`

**Comment by Mire39** [comment]
Jo no he enviat un alesto ninguno de estos archivos ni estorninos
anteriores ni los próximos los demandado yo-ni hackeado todas las cuentas
d'internet

El dj., 4 de març 2021, 16:27, bobokun ***@***.***> va
escriure:
