### ISSUE TITLE
How can I change port via docker install

### ISSUE THREAD

**Issue by starsareintherose** [huginn/huginn#2961]
My command
```
docker pull huginn/huginn
docker run -itd --name huginn -p 4321:4321 huginn/huginn
```
But I visit it and found 502 return.

**Comment by Leosirth** [comment]
If I remember correctly Huginn listen on port 3000 by default so your command should be:

`docker run -itd --name huginn -p 4321:3000 huginn/huginn`

Regards,

**Comment by starsareintherose** [comment]
> If I remember correctly Huginn listen on port 3000 by default so your command should be:
> 
> `docker run -itd --name huginn -p 4321:3000 huginn/huginn`
> 
> Regards,

Thanks, but it doesn't work, because some essential service is using the port 3000, could I change the default port?

**Comment by starsareintherose** [comment]
thanks.
