### ISSUE TITLE
Feature Request: Enable MarkdownV2 for Telegram Agent

### ISSUE THREAD

**Issue by hatchcanon** [huginn/huginn#2967]
I'm unable to pick MarkdownV2. The current options are markdown and html. Putting MarkdownV2 manually doesn't work either.

https://core.telegram.org/bots/api#formatting-options

**Comment by Unending** [comment]
This appears to be hardcoded in the agent.

I'm unfamiliar with the usage of telegram agent, do you just pass the raw HTML or markdown code to the agent? If so this should be an easy fix.

**Comment by hatchcanon** [comment]
Yeah you just pass the code to the agent. It should be an easy fix to allow a manual option in there

**Comment by Unending** [comment]
Can you try with the telegram_markdownv2 branch at [Unending/huginn](https://github.com/Unending/huginn/tree/telegram_markdownv2)? You can also just replace [this file](https://github.com/Unending/huginn/blob/telegram_markdownv2/app/models/agents/telegram_agent.rb).

If there are no issues I'll submit a PR.

**Comment by hatchcanon** [comment]
Just tested a dry run. It works great!
