### ISSUE TITLE
Can anyone help me check this website? thanks! 京东网页爬取失败求助

### ISSUE THREAD

**Issue by se7cn** [huginn/huginn#2981]
In Website Agent
url it's  
- https://item.m.jd.com/product/10026247046302.html

But unable to get the content of the webpage. It looks like it has been redirected to
"Https://wqs11.jd.com/data/coss/recoverydata/45/fe2c4ab59833605dc85b41b408b70e3d.shtml"

This is my setup:
Cookie is set, from my browser
user_agent set to "Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Mobile Safari/537.36 Edg/89.0.774.75"

Can someone help me how to fix it? thanks!

that‘s my settings

> {
>   "expected_update_period_in_days": "2",
>   "url": "https://item.m.jd.com/product/10026247046302.html",
>   "type": "html",
>   "mode": "all",
>   "extract": {
>     "title": {
>       "xpath": "//title",
>       "value": "."
>     }
>   },
>   "headers": {
>     "cookie": "###############"
>   },
>   "user_agent": "Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Mobile Safari/537.36 Edg/89.0.774.75"
> }

**Comment by 10362227** [comment]
正常
![Uploading QQ截图20210415230009.jpg…]()

**Comment by se7cn** [comment]
多谢，我觉得我ip可能block了，奇怪的是，只有这一个类型的页面无法访问， 其他都正常
