### ISSUE TITLE
Trigger Agent Regexp match 

### ISSUE THREAD

**Issue by amino-8** [huginn/huginn#2984]
Hello,
I'm just getting started with huginn and am really impressed with what can be done.
One issue I'm having is understanding how I can get a matched term out of the trigger agent. I have an agent successfully collecting twitter events from a user that I am passing through to a trigger agent. I want the trigger agent to check if there are any words in the tweet that start with a $ (for the purposes of determining if this user is tweeting about a stock).
I have the matching working correctly with the following:
```
{
  "expected_receive_period_in_days": "2",
  "keep_event": "true",
  "rules": [
    {
      "type": "regex",
      "value": "\\B\\$\\w+",
      "path": "full_text"
    }
  ],
  "message": "<MATCHED TERM>"

}
```
Where I can't figure out what to do, is I want to return the matched word starting with $ (shown in the message: block.
Can someone help me understand what I need to do?

**Comment by Unending** [comment]
Don't think you can do that with the Trigger Agent, but the Event Formatting Agent has a `matchers` option which could be used.
