### ISSUE TITLE
Detect if value is the same after X time

### ISSUE THREAD

**Issue by thedeany** [huginn/huginn#2993]
I'm not sure how to go about this and have looked at Scheduler, Delay, Trigger, and a handful of Reddit posts, but I'm not able to put things together in my head well enough to figure out what I need to do.

Currently I have a WebsiteAgent retrieving a value from my AdGuard Home instance to determine whether protection is enabled or not. (Sometimes I disable protection if I'm testing something to ensure it's not AdGuard causing problems.) That part is working and I get the correct value from AdGuard.

Now I'd like to set something up in Huginn where it would notify me if protection has been disabled for X amount of time, to ensure I don't forget to turn it back on 😄 

I could set up a Delay or something to fire X time after a `protection_enabled: false` value is given, but it should _also_ check if the value is _still false_ before it actually notifies. Otherwise, I'll turn protection off, the delay will start, I'll turn protection back on a few minutes later, and then at X time I'd get a false positive.

Can anyone enlighten me how I might be able to accomplish something like this?

**Comment by degan6** [comment]
Hey thedeany,

You need state! Basically you need something that will know the last time your ad blocker was enabled then every time your website agent runs, will find the difference in time between when it was on and now.
This is similar to the built in gap detector.

You can do this with the Javascript agent.


This will get you started. This agent will create an event everytime you website agent scrapes the status the time has elapsed. 

`Agent.receive = function() {
  #how long do you want to wait after you've disabled ads?
  var gapTimeMinutes = 10
  var events = this.incomingEvents();
  for(var i = 0; i < events.length; i++) {
    if (events[i].payload['protection_enabled'] == 'true')  {
      this.log('Recorded time last ad block enabled')
      this.memory('ad_blocker_seen_last_enabled', Math.round((new Date()).getTime() / 1000))
    } else {
      lastEnabled = this.memory('ad_blocker_seen_last_enabled')
      diffInMinutes =  ((Math.round((new Date()).getTime() / 1000) - lastEnabled ) / 60 )
      if (diffInMinutes >= gapTimeMinutes){
        this.createEvent({ 'message': 'add blocker has been off for ten minutes!', 'event_was': events[i].payload });    
      }
    }
    
  }
}
`

**Comment by thedeany** [comment]
@degan6 wow, I never got a notification about your comment! What you provided makes sense, I'm just not familiar with the JS agent much (though I am well-versed in JS itself; the agent just hadn't made much sense to me without a concrete example.) I was able to get it working though! The way I have it configured now will alert me every five minutes after the ten-minute threshold is reached of the protection being disabled.

Thanks a bunch!
