### ISSUE TITLE
Problem with Trigger Agent's "field>value" rule

### ISSUE THREAD

**Issue by alexrengel** [huginn/huginn#3001]
Hey all,
I have a Website agent that passes the event field "price" to the trigger agent below:

```
{
  "expected_receive_period_in_days": "5",
  "keep_event": "false",
  "rules": [
    {
      "type": "field<value",
      "value": "500",
      "path": "{{ price | replace:'$','' | ceil | times:1 }}"
    }
  ],
  "message": {
    "title": "Availability {{price}}",
    "message": "Check out: https://[url]",
    "priority": "0"
  }
}
```
Price is a string, e.g. "$949.99," and the rule is true when the price is below 500. However, {{ price | replace:'$','' | ceil | times:1 }} does not return a number, so the "field<value" does not evaluate correctly. Is there any way of making the rule work?

Thank you in advance!

**Comment by Unending** [comment]
> The `path` value is a dotted path through a hash in JSONPaths syntax.

It doesn't support Liquid templating, you'll have to pass it through an `Event Formatting Agent` first.

**Comment by alexrengel** [comment]
Bummer. I was trying to avoid creating yet another agent. Thank you for the quick and helpful reply!

**Comment by virtadpt** [comment]
> Bummer. I was trying to avoid creating yet another agent. Thank you for the quick and helpful reply!

Agents are cheap.  Make as many as you need.  Don't try to be overly clever with them (ask me how I know...)
