### ISSUE TITLE
Help: How to pass source url from Website Agent to Event Formatting Agent 

### ISSUE THREAD

**Issue by info-path** [huginn/huginn#3005]
Guys, I'm stuck and I don't know how to pass source url from _Website Agent_ to _Event Formatting Agent_. Is there any way to pass this parameter? I have dozens of website agents on a single Event Formatting Agent and passing a tracked url saves me a lot of work.

The `{{url}}` in _Event Formatting Agent_ is empty :(

**Event Formatting Agent**
```

{
  "instructions": {
    "text": "Price is {{price}} (this.is.a.source.url: {{url}} )"
  },
  "matchers": [

  ],
  "mode": "clean"
}
```

**Website Agent**
```
{
  "expected_update_period_in_days": "2",
  "url": "https://this.is.a.source.url/..../",
  "type": "text",
  "mode": "on_change",
  "extract": {
    "price": {
      "regexp": "... some regexp ...",
      "index": "..."
    }
  }
}
```

**Comment by Unending** [comment]
Add the template option and use Liquid formatting to add the url:
```
{
  "expected_update_period_in_days": "2",
  "url": "https://this.is.a.source.url/..../",
  "type": "text",
  "mode": "on_change",
  "extract": {
    "price": {
      "regexp": "... some regexp ...",
      "index": "..."
    }
  },
  "template": {
    "url": "{{ _url_ }}"
  }
}
```

For more explanation/options see the help text on the right when editing the website agent (_General options_ and _Liquid templating_).

**Comment by info-path** [comment]
That is exactly what I was looking for! Thanks a lot!
