### ISSUE TITLE
POST Agent doesn't support data-raw argument from cURL

### ISSUE THREAD

**Issue by Windyo** [huginn/huginn#3010]
Maybe I didn't search properly but I've been over all the documentation I could find.

I short I'm trying to convert a cURL command to a Huginn POST agent.
`curl "https://my.test.url" -X POST -H "Content-Type: application/x-www-form-urlencoded;charset=UTF-8" -H "Sec-Fetch-Dest: empty" -H "Sec-Fetch-Mode: cors" -H "Sec-Fetch-Site: same-origin" --data-raw "message="%"7B"%"22actions"morestuffgoeshere"`

I can't find a way to simulate data-raw in Huginn.

**Comment by Unending** [comment]
If you set `content_type` to "text/plain" and make `payload` a string it just puts that string into the request body.

But your example command isn't valid so I can't be sure that's what you want.

**Comment by Windyo** [comment]
Hmmm, tried that, it didn't return what I expect.

What I send out is `curl "https://help.salesforce.com/s/sfsites/aura?r=4&aura.ApexAction.execute=1" -X POST -H "Content-Type: application/x-www-form-urlencoded;charset=UTF-8" -H "Origin: https://help.salesforce.com" -H "Sec-Fetch-Dest: empty" -H "Sec-Fetch-Mode: cors" -H "Sec-Fetch-Site: same-origin" --data-raw "message="%"7B"%"22actions"%"22"%"3A"%"5B"%"7B"%"22id"%"22"%"3A"%"22115"%"3Ba"%"22"%"2C"%"22descriptor"%"22"%"3A"%"22aura"%"3A"%"2F"%"2FApexActionController"%"2FACTION"%"24execute"%"22"%"2C"%"22callingDescriptor"%"22"%"3A"%"22UNKNOWN"%"22"%"2C"%"22params"%"22"%"3A"%"7B"%"22namespace"%"22"%"3A"%"22"%"22"%"2C"%"22classname"%"22"%"3A"%"22Help_ArticleDataController"%"22"%"2C"%"22method"%"22"%"3A"%"22getData"%"22"%"2C"%"22params"%"22"%"3A"%"7B"%"22articleParameters"%"22"%"3A"%"7B"%"22urlName"%"22"%"3A"%"22release-notes.salesforce_release_notes.htm"%"22"%"2C"%"22language"%"22"%"3A"%"22en_US"%"22"%"2C"%"22release"%"22"%"3A"%"22232.17.0"%"22"%"2C"%"22requestedArticleType"%"22"%"3A"%"22HelpDocs"%"22"%"2C"%"22requestedArticleTypeNumber"%"22"%"3A"%"225"%"22"%"7D"%"7D"%"2C"%"22cacheable"%"22"%"3Afalse"%"2C"%"22isContinuation"%"22"%"3Afalse"%"7D"%"7D"%"5D"%"7D&aura.context="%"7B"%"22mode"%"22"%"3A"%"22PROD"%"22"%"2C"%"22fwuid"%"22"%"3A"%"22YeF9IbuOAuhiq8yQ65xJFA"%"22"%"2C"%"22app"%"22"%"3A"%"22siteforce"%"3AcommunityApp"%"22"%"2C"%"22loaded"%"22"%"3A"%"7B"%"22APPLICATION"%"40markup"%"3A"%"2F"%"2Fsiteforce"%"3AcommunityApp"%"22"%"3A"%"22DYdB31LOonS00uVlJ2dWlg"%"22"%"7D"%"2C"%"22dn"%"22"%"3A"%"5B"%"5D"%"2C"%"22globals"%"22"%"3A"%"7B"%"7D"%"2C"%"22uad"%"22"%"3Afalse"%"7D&aura.pageURI="%"2Fs"%"2FarticleView"%"3Flanguage"%"3Den_US"%"26type"%"3D5"%"26release"%"3D232"%"26id"%"3Drelease-notes.salesforce_release_notes.htm&aura.token=undefined"`

and I expect an HTML response.

In huginn, what I configured the POST agent as is 

```{
  "post_url": "https://help.salesforce.com/s/sfsites/aura?r=4&aura.ApexAction.execute=1",
  "expected_receive_period_in_days": "1",
  "content_type": "text/plain",
  "method": "post",
  "payload": "message={\"actions\":[{\"id\":\"115;a\",\"descriptor\":\"aura://ApexActionController/ACTION$execute\",\"callingDescriptor\":\"UNKNOWN\",\"params\":{\"namespace\":\"\",\"classname\":\"Help_ArticleDataController\",\"method\":\"getData\",\"params\":{\"articleParameters\":{\"urlName\":\"release-notes.salesforce_release_notes.htm\",\"language\":\"en_US\",\"release\":\"232.17.0\",\"requestedArticleType\":\"HelpDocs\",\"requestedArticleTypeNumber\":\"5\"}},\"cacheable\":false,\"isContinuation\":false}}]}&aura.context={\"mode\":\"PROD\",\"fwuid\":\"YeF9IbuOAuhiq8yQ65xJFA\",\"app\":\"siteforce:communityApp\",\"loaded\":{\"APPLICATION@markup://siteforce:communityApp\":\"DYdB31LOonS00uVlJ2dWlg\"},\"dn\":[],\"globals\":{},\"uad\":false}&aura.pageURI=/s/articleView?language=en_US&type=5&release=232&id=release-notes.salesforce_release_notes.htm&aura.token=undefined",
  "headers": {
    "Origin": "https://help.salesforce.com",
    "Sec-Fetch-Dest": "empty",
    "Sec-Fetch-Mode": "cors",
    "Sec-Fetch-Site": "same-origin"
  },
  "emit_events": "true",
  "no_merge": "true",
  "output_mode": "clean"
}```

but the response I get is `{\"event\":{\"descriptor\":\"markup://aura:invalidSession\",\"attributes\":{\"values\":{}},\"eventDef\":{\"descriptor\":\"markup://aura:invalidSession\",\"t\":\"APPLICATION\",\"xs\":\"I\",\"a\":{\"newToken\":[\"newToken\",\"aura://String\",\"I\",false]}}},\"exceptionEvent\":true}` which is the receiving website's way of telling me the "message" part isn't being interpreted correctly.

**Comment by Unending** [comment]
You can just send this regularly:

```
{
  "post_url": "https://help.salesforce.com/s/sfsites/aura?r=4&aura.ApexAction.execute=1",
  "expected_receive_period_in_days": "1",
  "content_type": "form",
  "method": "post",
  "payload": {
    "aura.context": "{\"mode\":\"PROD\",\"fwuid\":\"YeF9IbuOAuhiq8yQ65xJFA\",\"app\":\"siteforce:communityApp\",\"loaded\":{\"APPLICATION@markup://siteforce:communityApp\":\"DYdB31LOonS00uVlJ2dWlg\"},\"dn\":[],\"globals\":{},\"uad\":false}",
    "aura.pageURI": "/s/articleView?language=en_US&type=5&release=232&id=release-notes.salesforce_release_notes.htm",
    "aura.token": "undefined",
    "message": "{\"actions\":[{\"id\":\"115;a\",\"descriptor\":\"aura://ApexActionController/ACTION$execute\",\"callingDescriptor\":\"UNKNOWN\",\"params\":{\"namespace\":\"\",\"classname\":\"Help_ArticleDataController\",\"method\":\"getData\",\"params\":{\"articleParameters\":{\"urlName\":\"release-notes.salesforce_release_notes.htm\",\"language\":\"en_US\",\"release\":\"232.17.0\",\"requestedArticleType\":\"HelpDocs\",\"requestedArticleTypeNumber\":\"5\"}},\"cacheable\":false,\"isContinuation\":false}}]}"
  },
  "headers": {
    "Origin": "https://help.salesforce.com",
    "Sec-Fetch-Dest": "empty",
    "Sec-Fetch-Mode": "cors",
    "Sec-Fetch-Site": "same-origin"
  },
  "emit_events": "true",
  "no_merge": "true",
  "output_mode": "clean"
}
```

**Comment by Windyo** [comment]
oh damn, I adn't thought of that. thanks
