### ISSUE TITLE
Architecture and Design readings.

### ISSUE THREAD

**Issue by SinghCoder** [huginn/huginn#3011]
Hey @cantino, thank you so much for this wonderful project of yours.
I wanted to ask if there is some kind of existing documentation regarding how architecture is designed, how agents are scaled, who is responsible for handling transfer of data from one agent to another, is there some message broker pattern, REST API calls, or some RPCs.
I am not sure if this is the right place to ask this question since I am new here, so feel free to close this if this ain't the right place.

**Comment by cantino** [comment]
Hey @SinghCoder, glad you like Huginn! All documentation is in [the wiki](https://github.com/huginn/huginn/wiki). There isn't a ton of technical documentation about the internals, though. It's mostly a normal Rails application beyond the Agents-in-a-gem pattern.

**Comment by SinghCoder** [comment]
Ah okay, thanks for responding. 
Yeah I need to learn some basic Ruby and see the code.
Thanks again..
