### ISSUE TITLE
Docker database environment variables handled oddly

### ISSUE THREAD

**Issue by RedFantom** [huginn/huginn#3014]
This is my first time setting up Huginn and I'm not a docker wizard, but I'm pretty sure I've stumbled into a bug.

**What happens?**
When using an `.env` file with the following contents:
```env
DATABASE_NAME=huginn
DATABASE_USERNAME=huginn
DATABASE_PASSWORD=REDACTED
DATABASE_HOST=localhost
DATABASE_PORT=3306

START_MYSQL=false
DO_NOT_CREATE_DATABASE=true
```
in combination with the docker argument `--net=host` to allow Huginn to connect to the MySQL server running on the localhost, Huginn attempts and fails to connect to `/tmp/mysql.sock`:
```
Mysql2::Error::ConnectionError: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
```

**What do I expect to happen?**
I expect that using `localhost` there makes Huginn connect to the MySQL server running on localhost instead.

**What fixes the issue?**
The issue does not occur when running with the `DATABASE_HOST=127.0.0.1` set instead.

Is this something I've missed in the documentation somewhere? I would expect `localhost` and `127.0.0.1` to be functionally equivalent, but they are not. It would appear to me that setting the `DATABASE_HOST` to `localhost` instead makes Huginn attempt to connect to the internal database server, which was ([forcefully](https://github.com/huginn/huginn/issues/2849), which took me a long while to find) disabled.

If this is intended behaviour, could perhaps the documentation be updated to include both the `START_MYSQL` and `DATABASE_HOST` environment variable peculiarities?

**Comment by Unending** [comment]
This isn't really a huginn issue.

When you try to connect to a MySQL database with `localhost` it will try to connect using a unix socket. Which is why it complains it can't find `/tmp/mysql.sock`.
If that's what you want you'll have to expose the hosts folder to the container. `-v location-on-host:/tmp/mysql.sock`.

If you want to connect using a TCP/IP connection you'll have to use the hosts internal ip (`127.0.0.1`)) or `host.docker.internal`.

**Comment by RedFantom** [comment]
@Unending Thanks for pointing that out to me. Apparently some, though not all, MySQL clients attempt connecting through a socket when `localhost` is given, but only on Linux. I did not know that this is generic behaviour. I'll make sure to type `127.0.0.1` where MySQL is involved from now on... 😅 

Thank you!
