### ISSUE TITLE
Need for migrating from Travis CI

### ISSUE THREAD

**Issue by knu** [huginn/huginn#3026]
We need to migrate from Travis CI since https://travis-ci.org/ shut down on June 15th, 2021.  Any help is granted!

@dsander Do you have any plan to fix the current workflows that are broken?  I think I can migrate the CI part to GitHub Actions, but the secrets needed for pushing docker images are out of my reach.

**Comment by dsander** [comment]
Sorry I will probably not have time to help much in the coming week, I will try and review some PR related to GitHub actions. We now have `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` GitHub Action secrets which should have permission to push the docker images. @knu If you have a Docker Hub account I can add you to the organization there.

**Comment by knu** [comment]
@dsander OK, my Docker Hub account is https://hub.docker.com/u/akinori.  I'll check if the Actions secrets you set works, thanks.

**Comment by knu** [comment]
I'm working on this. https://github.com/huginn/huginn/runs/4551913731

**Comment by knu** [comment]
Done!

**Comment by dsander** [comment]
Nice! I changed [This setting](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-required-approval-for-workflows-from-public-forks) to ` Require approval for all outside collaborators` just to be sure. The `pull_request` action always confuses and scares me and I was worried people could simply change the action to push a new docker image based on their code. Feel free to change it back if it is safe.

**Comment by knu** [comment]
@dsander Thank you!  As I understand it, a `pull_request` event submitted from a forked repository is triggered and the workflow is run without access to the "secrets" variables, so it should be safe. (unlike `pull_request_target`)

**Comment by dsander** [comment]
Ah! You are right `pull_request_target` was the dangerous one, sorry for the confusion! I changed the setting back to the previous value
