### ISSUE TITLE
Filter event based on date

### ISSUE THREAD

**Issue by Enissay** [huginn/huginn#3029]
Hi,

I am new to Huginn, and would need support to make a filter based on date. 

The scenario is as follows:
1. extract events from RSS => OK
2. send via email any new events => OK

Sadly, the RSS feed contains like the last 50 events from the last 2-3 months, and sometimes some of the events gets deleted, which means that some even older events will trigger the Agent (since the feed always contains 50).

I would like a way to filter events and activate the trigger only when the event is created over the last X days for instance. 
I managed to extract that and is of format `2021-09-16T20:52:44+00:00` but I have no idea how to do the filtering if someone could orient me.

**Comment by Enissay** [comment]
Hi Unending,

I have seen this syntax but didn't dare to dive into it as it seemed complex (Liquid).

Now that I did, I have some questions if you don't mind guiding me knowing that my events are of type:
```Json
{
  "url": "...",
  "title": "...",
  "description": "...",
  "PublishedOn": "2021-09-16T20:52:44+00:00",
  "UpdatedOn": "2021-09-16T20:52:44+00:00"
}
```
1. I believe field from `field>value` represents my date, but how cam it parse and compare properly the  `PublishedOn` date ? Shouldn't I indicate the date format so It is reads it correctly ?
2. I simply want the events validating the condition to be passed over to the EmailAgent as they are. All formatting is done there already during RSS parsing... Is there any config needed to do that ?
`RssParser --> Trigger/Filter --> EmailAgent`
3. Finally, when I try a dry-run with your example, I am getting an error I don't quite understand if you can please advise:

![image](https://user-images.githubusercontent.com/794673/140199461-b4c071a4-71a3-4700-a9bc-89b76cb8094e.png)

**Comment by Unending** [comment]
- Convert your date to UNIX time `{{ PublishedOn | date: '%s' }}`, you can do this with an `Even Formatting Agent`. Liquid should interpret the date formatting automatically. You're just comparing two integers now.
- `keep_events: true` does this
- You have to provide it with an example event (the green part "event to send"). If you click any of the last 5 events you blurred out it will auto fill it with that one. You can modify it for testing.

**Comment by Enissay** [comment]
Thank you very much for the guidance Unending, I am starting to see clear but still do not understand a couple things:

Now I have this flow: `RSS_Parser (keep 2 days) --> Rss_Formatter (keep 1hr)  --> Rss_Trigger (keep 1hr) --> Email_Sender`
I did check the casting to timestamps works fine, BUT I noticed also that the Trigger is never activated. I can see 4 recent events from the Parser, but trigger is not activated... I wonder what I am missing now ?

![image](https://user-images.githubusercontent.com/794673/141016092-0e18789a-c175-4970-8268-5435a0ba8632.png)
