### ISSUE TITLE
How to get data from Event Formatting Agent upstream after a Website Agent?

### ISSUE THREAD

**Issue by oneilldt** [huginn/huginn#3036]
Hi, 
I am using Huginn for a week now. I am not a programmer and the learning curve is quite steep, but i find my way making things work. (Love it so far!)

I am running a website agent (agent 1) that scrapes alle the relative url's from the overview page, after that i have a Event Formatting Agent (agent 2) that  adds the domain to the relative URL so i can scrape the detail pages (Agent 3). This goes without an issue, however i am missing the url that i made in agent 2. I can't seem to take it upstream after i use the second Website Agent (agent 3)

On the detail page itself i cannot find the URL of the page. And if i try to add {{text}} in the website agent (agent 3) it says it can't because it only looks for html. 

How can i add the {{text}} variable from the the event formatting agent (agent 2) upstream after the second website agent (agent 3)? Or is it possible to grab the url from the detail pages even though it is not available in the html?

![diagram huginn issue](https://user-images.githubusercontent.com/55442639/141977362-4909c2ed-2e0c-4222-9b00-e2246f79ab03.png)

```
{
  "expected_update_period_in_days": "2",
  "url": "https://www.marktplaats.nl/l/huis-en-inrichting/banken-bankstellen/#q:banken|searchInTitleAndDescription:true",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "link": {
      "css": ".mp-Listing-coverLink",
      "value": "@href"
    }
  }
}

{
  "instructions": {
    "text": "https://marktplaats.nl{{link}}",
  },
  "message": {},
  "matchers": [],
  "mode": "clean"
}

{
  "expected_update_period_in_days": "2",
  "url": "{{text}}",
  "type": "html",
  "mode": "all",
  "extract": {
    "id": {
      "css": ".Report-itemIdText",
      "value": ".//text()"
    },
    "title": {
      "css": ".Listing-title",
      "value": ".//text()"
    },
    "description": {
      "css": ".Description-description",
      "value": ".//text()"
    }
  }
}
```

**Comment by Unending** [comment]
> If you want to retain original contents of events and only add new keys, then set `mode` to `merge`, otherwise set it to `clean`.

You could also just skip the Event Formatting Agent and set `url` to `https://marktplaats.nl{{link}}` directly.

**Comment by oneilldt** [comment]
Thanks for your reply!
I managed to fix it with the merge setting and deleting the event formatting agent.
