### ISSUE TITLE
EventFormattingAgent seems to have inconsistent regex problems

### ISSUE THREAD

**Issue by culorsung** [huginn/huginn#3039]
Hello
I'm working on a formatting agent, and found I can't use the matchers as I would expect to be able to. I have two matchers, one works, the other does not:

working (string example: `location": " Brainerd, MN, US):`
```
       "path": "{{location}}",
      "regexp": "^(\\s+)(?<location>.*)",
      "to": "loc1"
```

not working (string example: `#1234 Site Administrator, Network Solutions - `):
```
      "path": "{{title}}",
      "regexp": "^(?<id>%5CW%5Cd*)%5Cs(?<title>.*)%5CW%5CW%5CW(?<location>.*)",
      "to": "jobtitle"
```

The working example allows me to use {{loc1.location}}, and matches the string like I'd expect. The non-working example produces no output despite the regex matching. I've tried double-slashes in the non-working example as well (although this is not noted in the examples, it does appear to be required), and get the same result. I assume I'm doing something wrong, but I'm not sure if it's my shitty regex or some nuance in how I'm organizing things or what.

**Comment by Unending** [comment]
Why type the backslashes as ASCII hex code? Your example works fine if I use `^(?<id>\W\d*)\s(?<title>.*)\W\W\W(?<location>.*)`. (That's `"regexp": "^(?<id>\\W\\d*)\\s(?<title>.*)\\W\\W\\W(?<location>.*)"`

You only need to double backslash if you're in the JSON raw mode, I does that automatically if you type it in the regular mode.
