### ISSUE TITLE
Url used in website agent to be used in Telegram text

### ISSUE THREAD

**Issue by Koliera** [huginn/huginn#3042]
Hi, I currently have the following flow for checking if a book goes in stock - WebsiteAgent -> Event Formatting Agent -> Telegram Agent
I have it sending me the Title and the price once it changes, but the issue is getting the url to be sent. For some reason it just doesn't grab the url mentioned in the WebsiteAgent.
Here's an example of the setup:
**WebsiteAgent**
{
  "expected_update_period_in_days": "2",
  "url": "https://www.booksetc.co.uk/books/view/-9781421597713",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "price": {
      "css": "#item_info > table > tbody > tr > td.price",
      "value": "normalize-space(.)"
    },
    "title": {
      "css": "#item_info > div:nth-child(1) > div.details > h1",
      "value": "normalize-space(.)"
    }
  }
}

**Event Formatting Agent**
{
  "instructions": {
    "agent": "{{agent.type}}",
    "text": " TITLE - {{title}} Price - {{price}} URL - {{url}}"
  },
  "matchers": [],
  "mode": "clean"
}

As mentioned, the title and Price is getting sent out correct, but the url is empty. As I understood it should get the url from the field mentioned in the WebsiteAgent.
Any help appreciated!

**Comment by Unending** [comment]
You're not actually sending the url in your event, only `{{ title }}` and `{{ price }}`.

You can add the url field using the template option, either manually define it again or dynamically call it using Liquid templating with `{{ _url_ }}` or `{{ _response_.url }}` if needed. More info about this can be found in the help text on the right when editing the agent.

So like this:
```
{
  "expected_update_period_in_days": "2",
  "url": "https://www.booksetc.co.uk/books/view/-9781421597713",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "price": {
      "css": "#item_info > table > tbody > tr > td.price",
      "value": "normalize-space(.)"
    },
    "title": {
      "css": "#item_info > div:nth-child(1) > div.details > h1",
      "value": "normalize-space(.)"
    }
  },
  "template": {
    "url": "{{ _url_ }}"
  }
}
```

**Comment by Koliera** [comment]
Excellent, thanks!
