### ISSUE TITLE
Docker image broken

### ISSUE THREAD

**Issue by roylez** [huginn/huginn#3057]
I guess some of recent commit breaks docker.

> foreman stderr | ERROR:  invalid value for parameter "client_encoding": "utf8mb4"
> foreman stderr | Couldn't create 'huginn' database. Please check your configuration.
> rake aborted!
> PG::Error: ERROR:  invalid value for parameter "client_encoding": "utf8mb4"

If I revert to `huginn/huginn:2dff33d350aabbcd012bd8b2d72487c96493c819`, everything is working fine again.

I use postgres for data. Below is my env for reference. I guess the problem could be introduced by https://github.com/huginn/huginn/commit/5d6528358009cdda29e219c2f951cd713f99fb0e .

**Comment by dsander** [comment]
FYIW `8b66caf9232c` works on my docker setup with postgres, my database related environment settings:

```
DATABASE_ADAPTER=postgresql
DATABASE_ENCODING=utf8
DATABASE_RECONNECT=true
DATABASE_NAME=huginn
DATABASE_POOL=30
DATABASE_USERNAME=huginn
DATABASE_PASSWORD=myhuginnpassword
```

**Comment by knu** [comment]
@roylez What are your environment settings?  Do you happen to have (`HUGINN_`) `DATABASE_ENCODING=utf8mb4` defined somewhere, like with `docker -e`, in your local Dockerfile, `.env`, or `heroku config:set` if you are on Heroku?

The `utf8mb4` value only exists in the `[[ -n "${MYSQL_PORT_3306_TCP_ADDR}" || ("${DATABASE_ADAPTER}" == "mysql2" && -n "${DATABASE_HOST}") ]]` branch, so I'm curious where it came from.

**Comment by roylez** [comment]
I do not have this environment variable at all and I have no idea why it comes up.

```
DATABASE_URL=postgres://postgres:passwd@db:5432/huginn
HOSTNAME=7986002ae0da
ENABLE_INSECURE_AGENTS=true
DIAGRAM_DEFAULT_LAYOUT=dot
DO_NOT_SEED=1
DATABASE_PORT=5432
HOME=/app
PROCFILE_PATH=Procfile
OUTDATED_DOCKER_IMAGE_NAMESPACE=false
TIMEZONE=xxx
TERM=xterm
INVITATION_CODE=xxx
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
USE_GRAPHVIZ_DOT=dot
ALLOW_JSONPATH_EVAL=true
FORCE_SSL=false
RAILS_ENV=production
APP_SECRET_TOKEN=xxx
EVENT_EXPIRATION_CHECK=1h
RAILS_SERVE_STATIC_FILES=true
PWD=/app
TZ=xxx
DATABASE_ADAPTER=postgresql
DATABASE_HOST=db
```

**Comment by knu** [comment]
I've made a change in the default branch that explicitly sets DATABASE_ENCODING to utf8.  Please give it a try when the build is pushed.

**Comment by roylez** [comment]
It runs fine now. Thanks.
