### ISSUE TITLE
Reference to agent name in WebsiteAgent json?

### ISSUE THREAD

**Issue by gingerbeardman** [huginn/huginn#3082]
Where and how would I use `agent.name` in my WebsiteAgent json?

**Comment by daviddavo** [comment]
I'm trying to get the agent name too, I tried both with `agent.name` and `event.agent.name`. In a Digest Agent and Liquid Output agent that receive events from an RssAgent, but it didn't work, it seems that these agents can't access the info from those events within a for loop, like this:

```
{{% for event in events %}}
  Agent Name: {{event.agent.name}}
  
{{% endfor %}
```

Nevertheless, I managed to access the agent name with the EventFormatter. You can create a new field and use `{{agent | as_object }}` to pass the agent to the following Agents.

**Comment by gingerbeardman** [comment]
Thanks for that!

My workaround, which depends on the website, was to add my own URL parameter and then grab it back out of the resulting page. Hacky, but I have been using it since February. I'll transition to your approach.
