### ISSUE TITLE
Deploy to Heroku failing: There was an error parsing `Gemfile`: tried to create Proc object without a block

### ISSUE THREAD

**Issue by rhankins** [huginn/huginn#3094]
Trying to use the Deploy to Heroku button here:
https://elements.heroku.com/buttons/huginn/huginn

Getting an error parsing the Gemfile. Log attached.

Any help would be much appreciated as I am not (yet) a Ruby developer.

[build.log.txt](https://github.com/huginn/huginn/files/8157846/build.log.txt)

**Comment by rhankins** [comment]
Trying to use the Deploy to Heroku button here:
https://elements.heroku.com/buttons/huginn/huginn

Getting an error parsing the Gemfile.  Log attached.

Any help would be much appreciated as I am not (yet) a Ruby developer.
[build.log.txt](https://github.com/huginn/huginn/files/8157837/build.log.txt)

**Comment by bleakstew** [comment]
FWIW, I received the same error when trying to update my Heroku installation just now.

**Comment by wantosure** [comment]
@knu @zoomequipd plz merge pr to resovle the problem plz!

**Comment by wantosure** [comment]
@knu @zoomequipd plz check and merge

**Comment by zoomequipd** [comment]
i don' have merge access to this repo, idk why i'm being tagged

**Comment by sillygwailo** [comment]
I encountered the same thing. #3097 has been merged, and now I'm able to push to Heroku.

**Comment by wantosure** [comment]
@JaHIY @knu Thank you for the bug! It is resovled. I push to heroku successfully
