### ISSUE TITLE
Deploy to Heroku fail

### ISSUE THREAD

**Issue by wantosure** [huginn/huginn#3100]
-----> Building on the Heroku-18 stack-----> Using buildpack: https://github.com/heroku/heroku-buildpack-multi.git-----> Multipack app detected=====> Downloading Buildpack: https://github.com/cantino/heroku-selectable-procfile.git=====> Detected Framework: Selectable Procfile-----> Using deployment/heroku/Procfile.heroku as Procfile=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-ruby.git=====> Detected Framework: Ruby-----> Installing bundler 2.2.33-----> Removing BUNDLED WITH version in the Gemfile.lock-----> Compiling Ruby/Rails ! !     There was an error parsing your Gemfile, we cannot continue !      !     [!] There was an error parsing `Gemfile`: tried to create Proc object without a block. Bundler cannot continue. !      !     #  from /tmp/build_f7c9cc38/Gemfile:26 !     #  ------------------------------------------- !     #      # to include them, so we scope them to an unsupported platform. !     >      platform :ruby_18, &proc !     #    end !     #  ------------------------------------------- ! !     Push rejected, failed to compile Multipack app. !     Push failed

**Comment by wflanagan** [comment]
Note this isn't a Heroku issue. I came to look for a solution to this for my local dev environment on a freshly downloaded Huginn.

**Comment by wantosure** [comment]
> 
I think my problem is same to this one?
https://github.com/huginn/huginn/issues/3094

if the problem is same, the problem is resolved,but is waiting to merge pr

**Comment by sillygwailo** [comment]
I encountered the same thing. #3097 has been merged, and now I'm able to push to Heroku.

**Comment by wantosure** [comment]
> 

I am able to  Thanks for the coder
