### ISSUE TITLE
Move huginn installation to another computer 

### ISSUE THREAD

**Issue by anashashmi** [huginn/huginn#3101]
I have a huginn instance running on a docker vm with mysql in the same container. I'd like to export my huginn setup to another vm. How can I do this?

**Comment by bit-man** [comment]
I did it the mysqldump way using the next steps :
- enable ssh port and install ssh server at source and destination docker database instances
- Do `mysqldump` at source database instance to a `.sql` file
- copy `.sql` file between both databases instances using ssh
- restore using `mysql` at target database instance
- restart both containers (Huginn and DB)

For a detalied explanation take a look at [Move huginn dockerized instance to Raspberry Pi 4](https://www.bit-man.guru/posts/huginn-dockerized-to-raspi4/) (my post)
