### ISSUE TITLE
Unable to create Twitter service

### ISSUE THREAD

**Issue by R0cketM0nster** [huginn/huginn#3102]
I have just installed Huginn on Debian Stretch, install was from source using the following instructions - https://github.com/huginn/huginn/blob/master/doc/manual/installation.md

Twitter keys were added to .env file and the Huginn server is up and working, however when i click the "Authenticate with Twitter" button on the services tab, i enter my Twitter credentials, confirm MFA, then get the message that I am being redirected back to the application, the screen refreshes and I am back at the Services tab, nothing listed under "provider" and when i try to create a twitter stream agent, there are no services in the dropdown box.

The authentication and communication with Huginn seems to be working based on the log in the production.log:

```
I, [2022-03-23T18:30:02.856272 #30857]  INFO -- : 2022-03-23T18:30:02+1300: [Worker(host:****** pid:30857)] 5 jobs processed at 32.6122 j/s, 0 failed
I, [2022-03-23T18:30:09.740510 #30899]  INFO -- : [267d67c4-309a-45a6-a5a9-8c6c81d74d61] Started GET "/auth/twitter/callback?oauth_token=************&oauth_verifier=****************" for 127.0.0.1 at 2022-03-23 18:30:09 +1300
I, [2022-03-23T18:30:09.741086 #30899]  INFO -- : [267d67c4-309a-45a6-a5a9-8c6c81d74d61] (twitter) Callback phase initiated.
I, [2022-03-23T18:30:11.190779 #30899]  INFO -- : [267d67c4-309a-45a6-a5a9-8c6c81d74d61] Processing by OmniauthCallbacksController#twitter as HTML
I, [2022-03-23T18:30:11.190949 #30899]  INFO -- : [267d67c4-309a-45a6-a5a9-8c6c81d74d61]   Parameters: {"oauth_token"=>"****************", "oauth_verifier"=>"*************"}
I, [2022-03-23T18:30:11.201425 #30899]  INFO -- : [267d67c4-309a-45a6-a5a9-8c6c81d74d61] Redirected to https://*************.com/services
I, [2022-03-23T18:30:11.201726 #30899]  INFO -- : [267d67c4-309a-45a6-a5a9-8c6c81d74d61] Completed 302 Found in 11ms (ActiveRecord: 1.7ms | Allocations: 2192)
I, [2022-03-23T18:30:11.439621 #30898]  INFO -- : [6de0347a-729c-446b-9b1e-71739aa7a6d4] Started GET "/services" for 127.0.0.1 at 2022-03-23 18:30:11 +1300
I, [2022-03-23T18:30:11.440922 #30898]  INFO -- : [6de0347a-729c-446b-9b1e-71739aa7a6d4] Processing by ServicesController#index as HTML
I, [2022-03-23T18:30:11.449767 #30898]  INFO -- : [6de0347a-729c-446b-9b1e-71739aa7a6d4]   Rendering services/index.html.erb within layouts/application
I, [2022-03-23T18:30:11.452593 #30898]  INFO -- : [6de0347a-729c-446b-9b1e-71739aa7a6d4]   Rendered services/index.html.erb within layouts/application (Duration: 2.6ms | Allocations: 705)
I, [2022-03-23T18:30:11.455337 #30898]  INFO -- : [6de0347a-729c-446b-9b1e-71739aa7a6d4]   Rendered layouts/_navigation.html.erb (Duration: 1.8ms | Allocations: 751)
I, [2022-03-23T18:30:11.455748 #30898]  INFO -- : [6de0347a-729c-446b-9b1e-71739aa7a6d4]   Rendered layouts/_messages.html.erb (Duration: 0.1ms | Allocations: 18)
I, [2022-03-23T18:30:11.456162 #30898]  INFO -- : [6de0347a-729c-446b-9b1e-71739aa7a6d4]   Rendered application/_upgrade_warning.html.erb (Duration: 0.1ms | Allocations: 5)
I, [2022-03-23T18:30:11.459814 #30898]  INFO -- : [6de0347a-729c-446b-9b1e-71739aa7a6d4] Completed 200 OK in 19ms (Views: 9.3ms | ActiveRecord: 2.4ms | Allocations: 4702)


```
If someone can please point out something I might be missing that would be really appreciated.

**Comment by mdf-ido** [comment]
Same here

**Comment by mdf-ido** [comment]
Getting the same result as well in a microk8s pod using docker.io/huginn/huginn-single-process.

**Comment by JimWas** [comment]
Same issues has been ongoing for me. Heroku with SSL, self-hosted, Gcloud.

**Comment by jangliss** [comment]
After fighting with #3037 and a few redeployments of the docker container, I'm now seeing this issue too.  After a bit of research, it looks like the callback phase never executes properly.  This results in huginn/omniauth-twitter not making the second request to twitter to get the actual authentication token required. ([See here](https://developer.twitter.com/en/docs/authentication/guides/log-in-with-twitter), step 2 works, step 3 doesn't get executed).

I'm not sure if this is limited to the docker builds, or it applies to stuff outside of docker as well.

**Comment by nitlott** [comment]
im stuck on this, is there any workaround? i auth with twitter, i see the green redirect message, and then im back to autenticate with twitter button :/

**Comment by nitlott** [comment]
after some googling, it seams like twitter has changed something. if you have created the twitter app years ago it works (even works to reset keys), but if you use a newly created app in twitter it dosent work, i guess something with callback payload is different. lack the dev skills to figure it out tho

**Comment by jangliss** [comment]
> after some googling, it seams like twitter has changed something. if you have created the twitter app years ago it works (even works to reset keys), but if you use a newly created app in twitter it dosent work, i guess something with callback payload is different. lack the dev skills to figure it out tho

This is the assumption I've come to as well. I've had somebody that uses huginn and twitter test successfully using their keys, which were created a few years a go, new clean install works no problem, put my keys in and it doesn't. It'd be nice if huginn was moved over to omniauth-twitter2, which'd use the newer auth methods. That said, I did see somebody post a blog post on using twurl https://weblog.antranigv.am/posts/2022/03/tweeting-with-huginn-and-twurl/ but in the docker image, that becomes a little harder to implement.

I've been trying to setup a skeleton of just the auth portion for twitter to see if I can see what might be different to submit a request for the change. Ruby isn't my forte, so I've been bashing my head a bit.

**Comment by jangliss** [comment]
I decided to do some playing around and spun up a very basic ruby on rails environment, and think I've figured out the potential cause.  Twitter has several "access levels" based on your needs and what they'll grant you to (see [here](https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve)).  If you go to your twitter dashboard and look at your project, you may see it says "Essential" next to it.  Based on that, and the allowed access levels, you no longer have access to OAuth 1.0a, which is what `omniauth-twitter` uses to authenticate, nor a number of the standard v1.1 API endpoints (note it says "limited access - only media endpoints").  The failure is actually upstream in the omniauth-twitter gem itself.

I suspect earlier apps/projects were grandfathered into the "Elevated".

I'll do some more tinkering and see if I can build something against omniauth-twitter2.

**Comment by nitlott** [comment]
interresting, hoping for good results :D

like you said here "I suspect earlier apps/projects were grandfathered into the "Elevated"."
i believe the same thing, something differs between old and new apps, even if you have elavated acces on a new app it dont work.

**Comment by nitlott** [comment]
I should add, the search agent work fine, but stream does not. So the auth is correct. Must be something specific with stream in api. If that helps:)

**Comment by royaldunlin** [comment]
The Twitter functionality was the reason I installed Huginn. It's unfortunate that it doesn't work. Hope there's a fix soon.

**Comment by nitlott** [comment]
> The Twitter functionality was the reason I installed Huginn. It's unfortunate that it doesn't work. Hope there's a fix soon.

It does work with twitter search for example. Its just the live stream that dont work

**Comment by Slikkster** [comment]
It doesn't work for me. I'm unable to successfully authenticate with twitter. When I click on the "Authenticate with Twitter" button, I just get redirected to a page with red text saying "We're sorry, but something went wrong." which is utterly useless.

**Comment by nitlott** [comment]
> It doesn't work for me. I'm unable to successfully authenticate with twitter. When I click on the "Authenticate with Twitter" button, I just get redirected to a page with red text saying "We're sorry, but something went wrong." which is utterly useless.

Then you use wrong keys, should use consumer keys

**Comment by Slikkster** [comment]
I saw the tip about using consumer keys already, and I verified that's what I'm using. I even tried regenerating them just now, to no avail. I've also tried applying for elevated access, which I received. It did not help.

**Comment by nitlott** [comment]
> I saw the tip about using consumer keys already, and I verified that's what I'm using. I even tried regenerating them just now, to no avail. I've also tried applying for elevated access to the Twitter API, which I received. It did not help. I'm using Docker if that makes any difference.

try reset keys? works everytime for me even remade the app many times. or your callbackurl is wrong somehow?
it works without elevated even i think.

also run docker, with hugin.env file with inputs from above

**Comment by Slikkster** [comment]
I did reset the keys, I mentioned that above. I don't think the callback url is the issue, I'm not even getting that far in the auth process. What callback url should I be using? I'm going off what it says in the wiki.

When did you create your developer account/app? I just made my account and app a couple of days ago.

**Comment by nitlott** [comment]
i did my dev account few weeks ago.
you should use http://adress**you**use**to**reach**huginn**:3000/auth/twitter/callback as url, add multiple if you use many diff adresses/ips

**Comment by Slikkster** [comment]
Well I don't know then, that's exactly what I've done, and it doesn't work. I can't find any logs that say exactly what is wrong either, so I'm stuck.

**Comment by nitlott** [comment]
> Well I don't know then, that's exactly what I've done, and it doesn't work. I can't find any logs that say exactly what is wrong either, so I'm stuck.

restart docker withouth -d flag and look in terminal what happens when you press the auth button

**Comment by nitlott** [comment]
show me your huginn.env file (not the actual keys tho)

**Comment by Slikkster** [comment]
This is the only thing twitter related I see in the terminal, and it happens shortly after startup:
```
huginn_app  | foreman stdout | 11:04:10 web.1  | 172.20.0.3 - - [15/Oct/2022:11:04:10 PDT] "GET /auth/twitter HTTP/1.1" 500 643
huginn_app  | 11:04:10 web.1  | - -> /auth/twitter
```
There is no specific output when I click the auth button.

I'm not using a .env file, I simply have the environment variables defined in my docker-compose.yml file. I'm not using any quotes.
```
- HUGINN_TWITTER_OAUTH_KEY=xxxxxxxxxxxxxxx
- HUGINN_TWITTER_OAUTH_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
I've tried with and without the HUGINN_ prefix (which is what the wiki says to use), both seem to work (the auth button appears under services), but the result is the same either way. I've even tried using the various other keys and secrets the twitter app gives me; the auth button won't even appear with the v2 keys (which I expected not to work anyways).

**Comment by Slikkster** [comment]
I finally got it working. For some reason, I had to create a new, standalone app in my Twitter dev portal, and configure it exactly the same as before. For whatever reason, it does not work with the initial app/project the dev portal has you create when you first sign up.

**Comment by jangliss** [comment]
So you managed to get yours to authenticate? And it appears now as a service under the Services tab? I've tried the consumer keys, the access tokens, etc.  Redirects to Twitter auth page just fine, twitter sends back to Huginn, and never actually creates the entry.  Deleted and recreated the project and app in the twitter dashboard so many times I've lost count.

**Comment by Slikkster** [comment]
Yes, I was able to click the authenticate button, get redirected to Twitter, login, and then get redirected back to Huginn, and the new service was listed. I just set up a twitter search agent using the newly added service.

What I did was create a new app in my twitter dev portal and did not add it to a project (so it shows in the left menu under "Standalone Apps"). I then followed the instructions here https://andreas.scherbaum.la/blog/archives/1061-Enable-Huginn-Twitter-integration.html and was able to successfully authenticate.

**Comment by jangliss** [comment]
So that seems to be the difference, I don't have an option anywhere in the Twitter Dev portal to create a stand-alone app, it has to be in a project, which forces it to v2. Unless there's another dashboard I'm missing out, I'm hitting this one https://developer.twitter.com/en/portal/dashboard.

If I click on the link from the setting up OAuth docs, it takes me to one page, very briefly see a red error about not being able to retrieve apps, and then immediately redirects to /en/portal/dashboard.

**Comment by Slikkster** [comment]
I have applied for elevated API access (free, just submit the application), so you may need to do that first before you can create a standalone app.

**Comment by normen** [comment]
I can confirm that you need to 
- Create a dev account
- Apply for elevated access
- Create a "Standalone App" (OAuth 1.0a)
- Enter the API Key and Secret (*not* ClientID and Secret)

..for this to work properly

**Comment by nitlott** [comment]
Stream agent dont work on new dev accounts for some wierd reason, other twitter agents work tho

**Comment by Max-le** [comment]
Apply for elevated access worked for me.
