### ISSUE TITLE
Following extensions are not compiled: dbm

### ISSUE THREAD

**Issue by StrangeRanger** [huginn/huginn#3105]
When attempting to install ruby and after executing ``make -j`nproc` ``, I'm presented with the following text: 

```
*** Following extensions are not compiled:
dbm:
	Could not be configured. It will not be installed.
	Check ext/dbm/mkmf.log for more details.
*** Fix the problems, then remove these directories and try again if you want.
```

I'm unsure how to go about fixing this issue. How do I fix it?

**Comment by yiqixueba56** [comment]
I also encountered the same problem as above. I don't know how to solve it. The following is the log file mkmf.log.
![dbm安装报错](https://user-images.githubusercontent.com/102757709/164888692-17291126-b942-4e99-8ac4-ae63933541fa.png)
[mkmf.log](https://github.com/huginn/huginn/files/8546601/mkmf.log)

**Comment by ohingardail** [comment]
You might want to try installing old database compatibility headers first, then re-compile. 

`apt install libgdbm-compat-dev`

**Comment by milespossing** [comment]
> You might want to try installing old database compatibility headers first, then re-compile Ruby.
> 
> `apt install libgdbm-compat-dev`
> 
> If this works generally and not just for me, then this issue probably needs to be reconsidered as "[Instructions to install Ruby v2.6.9](https://github.com/huginn/huginn/blob/master/doc/manual/installation.md) as a Huginn pre-requisite on later versions of Ubuntu need to include instructions to install OS package ibgdbm-compat-dev first", or something similar.
> 
> It seems to work on Ubuntu v20 and v21; it might work on other versions as well (I haven't tested all versions). I found this potential workaround [here](https://unix.stackexchange.com/questions/66841/ubuntu-cant-find-ndbm-h), logged in 2013 and workaround logged in 2020.

Confirming on Ubuntu 18.04 I had the same issue and the above step mitigated it
