### ISSUE TITLE
When I run it in Docker, the 3000 ports inside the container automatically shut down every few hours

### ISSUE THREAD

**Issue by Darkluna999** [huginn/huginn#3108]
When I run it in Docker, the 3000 ports inside the container automatically shut down every few hours
![image](https://user-images.githubusercontent.com/53258301/161791959-c77c82f7-3c0b-4bc7-a4d8-72c419133400.png)
And that caused me to have to restart containers frequently

**Comment by Darkluna999** [comment]
fixed

**Comment by virtadpt** [comment]
For documentation purposes, how did you fix it?

**Comment by Darkluna999** [comment]
> For documentation purposes, how did you fix it?

I increased the virtual cache of the server to 2G and total 3G, and the operation became much more stable

**Comment by Darkluna999** [comment]
Nevertheless, I also wrote a script that monitors the container's internal ports and restarts the container in time, although it has not been triggered

**Comment by virtadpt** [comment]
Excellent - thank you.
