### ISSUE TITLE
Can’t updraft docker image without loosing data

### ISSUE THREAD

**Issue by martinorob** [huginn/huginn#3109]
Hi, 
is there a way to update docker image without loosing data?

This is my dover inspect output

`huginn# docker inspect cd1ff682bb57
[
    {
        "Id": "cd1ff682bb577cd02f8f8e8257438a27cdc916fb98b1f0198de93a6765e2facf",
        "Created": "2020-09-23T09:53:02.069814188Z",
        "Path": "/scripts/init",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 3070,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2022-04-10T14:24:06.020573123Z",
            "FinishedAt": "2022-04-10T14:23:08.691305776Z"
        },
        "Image": "sha256:c8c4c18beb16f738e58817529b0f976e0211fc6378af12d964ce009885f0b34c",
        "ResolvConfPath": "/var/snap/docker/common/var-lib-docker/containers/cd1ff682bb577cd02f8f8e8257438a27cdc916fb98b1f0198de93a6765e2facf/resolv.conf",
        "HostnamePath": "/var/snap/docker/common/var-lib-docker/containers/cd1ff682bb577cd02f8f8e8257438a27cdc916fb98b1f0198de93a6765e2facf/hostname",
        "HostsPath": "/var/snap/docker/common/var-lib-docker/containers/cd1ff682bb577cd02f8f8e8257438a27cdc916fb98b1f0198de93a6765e2facf/hosts",
        "LogPath": "/var/snap/docker/common/var-lib-docker/containers/cd1ff682bb577cd02f8f8e8257438a27cdc916fb98b1f0198de93a6765e2facf/cd1ff682bb577cd02f8f8e8257438a27cdc916fb98b1f0198de93a6765e2facf-json.log",
        "Name": "/focused_wiles",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "3000/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "3000"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "",
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/snap/docker/common/var-lib-docker/overlay2/46bdc761f99c15397591f192dd96bcb04b2958ec68aedbb19281d3a4638c038a-init/diff:/var/snap/docker/common/var-lib-docker/overlay2/e878f0ad14999f9122d4cf926f90cfc6e8094833eefbe06ffa6c039db1418abe/diff:/var/snap/docker/common/var-lib-docker/overlay2/62a4f938590a8df0fe588e461dcc3b9a6a96989a35e959a8e2bc4a0482ec908a/diff:/var/snap/docker/common/var-lib-docker/overlay2/0922db72d52c575636a0ce9f960dbc37071a35beb5f853f6a4d1bb86730e49ea/diff:/var/snap/docker/common/var-lib-docker/overlay2/2aa3f536c85850ff9f2abaa862824f9d467b0a8ccd4efcb03c8b33b4d6e8bfb3/diff:/var/snap/docker/common/var-lib-docker/overlay2/7264f6c5fbc79191df7b3456cca4ba4b56aefdc6ecdcdfe16f0031031b8d2555/diff:/var/snap/docker/common/var-lib-docker/overlay2/4c68c456a3a1f67185ce0f79d2d351d56f599a8f5012e32ae69eb4cd339d68ee/diff:/var/snap/docker/common/var-lib-docker/overlay2/d90a001325ef71ae13dc16785289352b349939b3afc8f85a952da26cce469f61/diff:/var/snap/docker/common/var-lib-docker/overlay2/13b62ae703049ac6f4caa2b3b6d2202cc0dc5244eec1f38ad7859b9a1583d18c/diff:/var/snap/docker/common/var-lib-docker/overlay2/83790cadbb89b81d0ce7f68c0a3420891100faef2db53ea5605e82f16633eb68/diff:/var/snap/docker/common/var-lib-docker/overlay2/197d60837c3b2119b4147afb3181a19e544c93d7f078049997e362146f1f41c4/diff:/var/snap/docker/common/var-lib-docker/overlay2/e3b18ecfe46874bf340dbe6a64fcfb4c305465a583559184ca5487b6343a8879/diff:/var/snap/docker/common/var-lib-docker/overlay2/a1c448e167f02ca7aa6cec62c6604f21a373ea869129f0efd1c56d3b1b692a54/diff:/var/snap/docker/common/var-lib-docker/overlay2/88162c880a1ab21b3e2768f5ffdc87f3fc56ae1182acc9c4779d605e1edd8b9e/diff:/var/snap/docker/common/var-lib-docker/overlay2/4d57db95a5e10ab84d7af14c845c8780ca57b2c69e7e022233c2cf08836ecfdc/diff:/var/snap/docker/common/var-lib-docker/overlay2/6980ce2ae01ad0a684bc0dc4b433756f14303ac5338abbcdbb95328980e09a0e/diff:/var/snap/docker/common/var-lib-docker/overlay2/db2d311f573e9d8c16703816b38bab7fd7dffe1cb8b8c8bc56c74c2fb8736367/diff:/var/snap/docker/common/var-lib-docker/overlay2/13c8c36a69724e2304587bd720ee40ee912dbd10785b33bcfa0ca6f1caf6b24a/diff",
                "MergedDir": "/var/snap/docker/common/var-lib-docker/overlay2/46bdc761f99c15397591f192dd96bcb04b2958ec68aedbb19281d3a4638c038a/merged",
                "UpperDir": "/var/snap/docker/common/var-lib-docker/overlay2/46bdc761f99c15397591f192dd96bcb04b2958ec68aedbb19281d3a4638c038a/diff",
                "WorkDir": "/var/snap/docker/common/var-lib-docker/overlay2/46bdc761f99c15397591f192dd96bcb04b2958ec68aedbb19281d3a4638c038a/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "c59448eac42c4aa1cf2ac9fb4245fea20d51b38c9142249d9fe45d09f3d13ee3",
                "Source": "/var/snap/docker/common/var-lib-docker/volumes/c59448eac42c4aa1cf2ac9fb4245fea20d51b38c9142249d9fe45d09f3d13ee3/_data",
                "Destination": "/var/lib/mysql",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "cd1ff682bb57",
            "Domainname": "",
            "User": "1001",
            "AttachStdin": true,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "3000/tcp": {}
            },
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": true,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "OUTDATED_DOCKER_IMAGE_NAMESPACE=false"
            ],
            "Cmd": [
                "/scripts/init"
            ],
            "Image": "huginn/huginn",
            "Volumes": {
                "/var/lib/mysql": {}
            },
            "WorkingDir": "/app",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "445b5448bb8b54fd6cb38cc2efbc4518be55da7860b63f0ebcbb57b8db002c51",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "3000/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "3000"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "3000"
                    }
                ]
            },
            "SandboxKey": "/run/snap.docker/netns/445b5448bb8b",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "90ada37526e135735b1de2cc0e288dccf9eb8d6360261b981495034fe3b31cc4",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.3",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:03",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "5c953a9c59c3a8bad8a31c6d6cba37a7298e2fbf07112bb1e414ddcc18fdc800",
                    "EndpointID": "90ada37526e135735b1de2cc0e288dccf9eb8d6360261b981495034fe3b31cc4",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.3",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:03",
                    "DriverOpts": null
                }
            }
        }
    }
]
huginn# `

**Comment by martinorob** [comment]
This are my docker-compose file 

```
locate docker-compose.yml 
/var/snap/docker/common/var-lib-docker/overlay2/363ecfa8cd120c7fc88a348176a8b9d936d7eaf9ff3df1968e45a3c4cbe68267/diff/app/docker/single-process/docker-compose.yml
/var/snap/docker/common/var-lib-docker/overlay2/7264f6c5fbc79191df7b3456cca4ba4b56aefdc6ecdcdfe16f0031031b8d2555/diff/app/docker/single-process/docker-compose.yml
```

```

cat /var/snap/docker/common/var-lib-docker/overlay2/363ecfa8cd120c7fc88a348176a8b9d936d7eaf9ff3df1968e45a3c4cbe68267/diff/app/docker/single-process/docker-compose.yml
version: '2'

services:
  mysqldata:
    image: mysql:5.7
    command: /bin/true

  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - ../mysql.env
    volumes_from:
      - mysqldata

  web:
    image: huginn/huginn-single-process
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ../mysql.env
      - ../secrets.env
    depends_on:
      - mysql

  threaded:
    image: huginn/huginn-single-process
    command: /scripts/init bin/threaded.rb
    restart: always
    env_file:
      - ../mysql.env
      - ../secrets.env
    depends_on:
      - mysql
      - web
huginn# 
```

**Comment by Petemir** [comment]
You should add a volume to your composer. 

e.g., to add to the MySQL service:
```
        volumes:
            - 'CHANGE_FOR_PATH_TO_YOUR_DIRECTORY/huginn-mysql-data:/var/lib/mysql'
```
That will preserve the MySQL database between upgrades. Change the appropriate variable to where you want to keep the data.
