### ISSUE TITLE
How to get JSON data from URL in JavaScript Agent?

### ISSUE THREAD

**Issue by tortoo** [huginn/huginn#3110]
I followed [this](https://stackoverflow.com/questions/12460378/how-to-get-json-from-url-in-javascripttried) and tried: 
```
Agent.receive = function() {
  $.getJSON('http://api.k780.com:88/?app=finance.rate&scur=USD&tcur=CNY&appkey=10003&sign=b59bc3ef6191eb9f747dd4e83c99f2a4', function(data){
    this.log("JSON Data: " + data);
  });
}
```
Dry run but got nothing.

**Comment by Vandinimodi1595** [comment]
Hey, @tortoo , Can you assign this issue to me?

**Comment by tortoo** [comment]
Sorry I couldn't do that because I'm not the collaborator of the repository and I'm not very familiar with GitHub operations.🙈 @Vandinimodi1595

**Comment by Snikeron** [comment]
@tortoo Am new to Huginn myself. If you were to use the Javascript agent you would probably need to use the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch), as I don't think jQuery is an included dependency in the JavaScript Agent.

I managed to successfully set up the Website Agent instead to fetch JSON data from a URL, extract the fields I want, and then send the data on to the JavaScript agent to do stuff I want.

An example of my Website Agent setup (not my miner -- just grabbed a random one lol):
```
{
  "expected_update_period_in_days": "2",
  "url": "https://api.ethermine.org/miner/ea3a6B08418FebAC9f9B54C6dF6Dc38C05aB78E6/dashboard",
  "type": "json",
  "mode": "on_change",
  "extract": {
    "workersActive": {
      "path": "data.statistics[-1].activeWorkers"
    },
    "workers": {
      "path": "data.workers"
    }
  },
  "template": {
    "miningType": "Ethermine"
  }
}
```

`extract` lets you setup keys with a `path` property that extracts json values you want, and `template` lets you add custom properties to be included in the created event.

See "Scraping JSON" in [the docs](https://huginnio.herokuapp.com/agents/search?q=website#WebsiteAgent)

**Comment by tortoo** [comment]
@Snikeron Thanks a lot for help and detailed explanation. Fetching JSON data with Website Agent is not difficult but more agents will lag and lead to inefficiency. 

I tested `fetch()` but got error `fetch is not defined`. Is it possible to get JSON data directly in JavaScript Agent by installing some dependency?
