### ISSUE TITLE
how can I repeat postagent with different number in payload

### ISSUE THREAD

**Issue by flyxj** [huginn/huginn#3111]
how can I repeat post with different number in the payload with one agent?

{
  "post_url": "http://xxx/search/category",
  "expected_receive_period_in_days": "1",
  "content_type": "json",
  "method": "post",
  "payload": {
    "pageSize": "100",
    **"pageNo": "1"**
  },
  "headers": {},
  "emit_events": "true",
  "no_merge": "false",
  "output_mode": "merge"
}

like here, change pageNo:1 to pageNo:2  and so on.

Thank you.

**Comment by gingerbeardman** [comment]
See: https://github.com/huginn/huginn/issues/873#issuecomment-302666130

Alternatively, for full programmatic control use a *Shell Command Agent* to do this from the command line/shell script.
