### ISSUE TITLE
Help parsing JSON

### ISSUE THREAD

**Issue by nobodyspecial** [huginn/huginn#3118]
I have some JSON I'd like to format using the Event Formatting Agent. I cannot figure out how to format anything in the "episodes" array. I think I'm missing something super simple.

`{
  "series": {
    "id": 1,
    "title": "Test Title",
    "path": "C:\\testpath",
    "tvdbId": 1234,
    "tvMazeId": 0,
    "type": "standard"
  },
  "episodes": [
    {
      "id": 123,
      "episodeNumber": 1,
      "seasonNumber": 1,
      "title": "Test title"
    }
  ],
  "eventType": "Test"
}`

**Comment by nobodyspecial** [comment]
figured it out

**Comment by virtadpt** [comment]
How did you fix it?  What did you see?

**Comment by nobodyspecial** [comment]
> How did you fix it? What did you see?

{{episodes[0].id}} or {{episodes[0].episodeNumber}} etc...
