### ISSUE TITLE
How can I write to huginn process logs from shell agent script

### ISSUE THREAD

**Issue by Nahums0** [huginn/huginn#3123]
I have a shell agent that calls a python script and I want to output logs from the python script to the huginn process logs
I see that the agent's log are outputted (Agent#12: Ran 'python3 some_script.py' under './parent_dir') 
Is there a way to do that?

**Comment by virtadpt** [comment]
Redirect stdout and maybe stderr into the process log of your choice.  `python3 /path/to/some_script.py >> /path/to/huginn/log/production.log`

**Comment by Nahums0** [comment]
Hey @virtadpt thanks for the quick response!
They way I managed to solve this was to redirect the script stdout to /proc/1/fd/1
Followed by this [answer](https://askubuntu.com/a/307887)

**Comment by virtadpt** [comment]
Excellent!  Glad to hear it.
