### ISSUE TITLE
Newbie mistakes trying to install huginn in a Raspberry Pi 3b+

### ISSUE THREAD

**Issue by vico93** [huginn/huginn#3129]
Hello!

I'm trying to install huginn in my Pi 3b+ manually (without docker).

The OS on my Pi is Raspberry Pi OS Lite (64 bit version). I'm already cloned huggin repo to a writable folder, installed MariaDB and Ruby using `sudo apt install ruby`, gem and bundle with `gem install rake bundle`, but trying to run `bundle` on the terminal after install doesn't work - I need to pull the whole path: `/usr/bin/bundle2.7 install` instead of `bundle install`.

Well, when trying to install the dependencies with bundle (like i said above) i ran with the following issues and errors:

```
Warning: the running version of Bundler (2.1.4) is older than the version that created the lockfile (2.3.10). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.3.10`.
Following files may not be writable, so sudo is needed:
  /usr/local/bin
  /var/lib/gems/2.7.0
  /var/lib/gems/2.7.0/build_info
  /var/lib/gems/2.7.0/cache
  /var/lib/gems/2.7.0/doc
  /var/lib/gems/2.7.0/extensions
  /var/lib/gems/2.7.0/gems
  /var/lib/gems/2.7.0/plugins
  /var/lib/gems/2.7.0/specifications
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for aarch64-linux, arm64-darwin, ruby, x86_64-darwin, x86_64-linux but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32`.
^Cpi@vico-pi:/misc/huginn $ /usr/bin/bundle2.7 install
Warning: the running version of Bundler (2.1.4) is older than the version that created the lockfile (2.3.10). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.3.10`.
Following files may not be writable, so sudo is needed:
  /usr/local/bin
  /var/lib/gems/2.7.0
  /var/lib/gems/2.7.0/build_info
  /var/lib/gems/2.7.0/cache
  /var/lib/gems/2.7.0/doc
  /var/lib/gems/2.7.0/extensions
  /var/lib/gems/2.7.0/gems
  /var/lib/gems/2.7.0/plugins
  /var/lib/gems/2.7.0/specifications
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for aarch64-linux, arm64-darwin, ruby, x86_64-darwin, x86_64-linux but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32`.
Fetching gem metadata from https://rubygems.org/.......
Fetching https://github.com/Hirurg103/capybara_select2.git
Fetching https://github.com/dsander/delayed_job_active_record.git
Fetching https://github.com/dsander/dropbox-api.git
Fetching https://github.com/dsander/erector.git
Fetching https://github.com/huginn/omniauth-dropbox-oauth2.git
Fetching https://github.com/albertsun/tumblr_client.git
Fetching https://github.com/sferik/twitter.git
Fetching https://github.com/cantino/twitter-stream.git
Fetching https://github.com/albertsun/weibo_2.git
Using rake 13.0.6
Fetching ace-rails-ap 2.0.1
Installing ace-rails-ap 2.0.1
Fetching concurrent-ruby 1.1.9
Installing concurrent-ruby 1.1.9
Fetching i18n 1.8.11
Installing i18n 1.8.11
Fetching minitest 5.15.0
Installing minitest 5.15.0
Fetching thread_safe 0.3.6
Installing thread_safe 0.3.6
Fetching tzinfo 1.2.9
Installing tzinfo 1.2.9
Fetching zeitwerk 2.5.3
Installing zeitwerk 2.5.3
Fetching activesupport 6.0.4.4
Installing activesupport 6.0.4.4
Fetching builder 3.2.4
Installing builder 3.2.4
Fetching erubi 1.10.0
Installing erubi 1.10.0
Fetching mini_portile2 2.6.1
Installing mini_portile2 2.6.1
Fetching racc 1.6.0
Installing racc 1.6.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /tmp/bundler20220522-1877-mavtupracc-1.6.0/gems/racc-1.6.0/ext/racc/cparse
/usr/bin/ruby2.7 -I /usr/lib/ruby/vendor_ruby -r ./siteconf20220522-1877-h8wjfl.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

You might have to install separate package for the ruby development
environment, ruby-dev or ruby-devel for example.

extconf failed, exit code 1

Gem files will remain installed in /tmp/bundler20220522-1877-mavtupracc-1.6.0/gems/racc-1.6.0 for inspection.
Results logged to /tmp/bundler20220522-1877-mavtupracc-1.6.0/extensions/aarch64-linux/2.7.0/racc-1.6.0/gem_make.out

An error occurred while installing racc (1.6.0), and Bundler cannot continue.
Make sure that `gem install racc -v '1.6.0' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  bootstrap-kaminari-views was resolved to 0.0.5, which depends on
    rails was resolved to 6.0.4.4, which depends on
      actioncable was resolved to 6.0.4.4, which depends on
        actionpack was resolved to 6.0.4.4, which depends on
          actionview was resolved to 6.0.4.4, which depends on
            rails-dom-testing was resolved to 2.0.3, which depends on
              nokogiri was resolved to 1.12.5, which depends on
                racc
```

What i did wrong?

**Comment by gaael** [comment]
It looks like your Ruby version is more recent than the one used to develop Huginn.
Depending on your OS and repositories, `$ apt install ruby` can install a version or another.
You can check your Ruby version with `$ ruby --version`

If you check again the [Huggin Readme](https://github.com/huginn/huginn), you will find the link to the **Installation guide** in the [Manual installation on any server section](https://github.com/huginn/huginn#manual-installation-on-any-server).
Then, in **Requirements**, you will find [the Ruby versions section](https://github.com/huginn/huginn/blob/master/doc/manual/requirements.md#ruby-versions) :

> Huginn requires Ruby (MRI) 2.2 or 2.3

If you need to install another version of Ruby, the instructions are available on the Official Ruby Website under Download Ruby. I'd recommand uninstalling and purging the `ruby` apt package first, and then installing the correct version with the method of your choice. I use rvm and find it efficient and easy to use, but that's only my opinion.

Installing ruby via rvm usually takes care of adding directories to the path and will hopefully solve the other problem you mentionned - having to use the full path to the bundle executable instead of just typing `$ bundle install`.
If it doesn't, you can search the internet for _bash add directory to path_ and you should find plenty of solutions/workarounds.

**Comment by vico93** [comment]
Thanks for the information. Unfortunately that's too much for me personally, so i think i will pass the advice.

**Comment by vico93** [comment]
Well, i decided to give another chance to try to install huginn. I installed rvm with the instructions available [in this website](http://rvm.io/), no how can i install the specific version of ruby (and also the other dependencies required for huginn) using this tool?

**Comment by gaael** [comment]
> how can i install the specific version of ruby

On the [official RVM website](https://rvm.io) that you used to install the Ruby Version Manager, you will find their documentation. I advise you to lookup the two following commands: 
* `rvm list known` to find out which versions can be installed using rvm
* `rvm install [VERSION NUMBER]` to install a specific Ruby version

> (and also the other dependencies required for huginn) using this tool?

Once your ruby version is correct, cloning the repo and running `bundle install` should take care of all gem dependencies without having you installing the gems manually.

**Comment by vico93** [comment]
And what is the specific version that huginn needs?

**Comment by gaael** [comment]
>If you check again the [Huggin Readme](https://github.com/huginn/huginn), you will find the link to the Installation guide in the [Manual installation on any server section](https://github.com/huginn/huginn#manual-installation-on-any-server).
Then, in Requirements, you will find [the Ruby versions section](https://github.com/huginn/huginn/blob/master/doc/manual/requirements.md#ruby-versions).

**Comment by virtadpt** [comment]
For what it's worth, I'm running Ruby 2.6.3p62 in production (installed with rvm) and it works quite nicely.
