### ISSUE TITLE
Newbie100%: Stuck at 'Install Gems' from [Installation from source]

### ISSUE THREAD

**Issue by gcplaw** [huginn/huginn#3132]
**sudo -u huginn -H bundle install --deployment --without development test**

The above code output suggests `--deployment` flag and `--without` flags are deprecated.  screenshot as below:
![2022-06-01_170309](https://user-images.githubusercontent.com/46683378/171371490-4dbc7213-e920-420f-869e-adb627676cef.png)

**Any sugeestions? big Thanks!** 

btw: i'm totally newbie, no knowledge of real coding, maybe some html, but no way like the guides from 'Installation from source'...

**Comment by frankdzh** [comment]
unsubscript

python1984 ***@***.***>于2022年6月1日 周三17:21写道：

**Comment by gcplaw** [comment]
i restart the server and its... now ok///
