### ISSUE TITLE
Help - Web agent and pushover configuration

### ISSUE THREAD

**Issue by spencerskinner99** [huginn/huginn#3133]
Hi,

This is a help/ feature suggestion thread.

Is it possible to have several web agents connected to a single pushover agent (and or slack agent too) such that when an event is produced by a web agent the url sent by the pushover agent is the url of that specific web agent. 

Currently the only way I see of doing this is to make a pushover agent for every web agent, this seems excessive. 

Many Thanks
Spencer

**Comment by Unending** [comment]
You can send arbitrary data in your web agent event using the `template` option. If you want to set the URL dynamically to the scraped page you can use `{{ _url_ }}` or `{{ _response_.url }}` depending on your use case.

**Comment by spencerskinner99** [comment]
Hi, I've given that a go but I am getting an error with my config which stops it saving. 

`When type is html or xml, all extractions must have a css or xpath attribute (bad extraction details for "template")`

My config is below, sorry about the phone screenshot.

![Screenshot_20220602-233935__01](https://user-images.githubusercontent.com/36821615/171750137-a8282c92-f06f-416c-8b91-9d459e43ef16.jpg)

**Comment by Unending** [comment]
The template isn't extracted and thus goes outside the `extract` option like this:
```
{
  "expected_update_period_in_days": "7",
  "url": "{{ url-e }}",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "title": {
      "css": "h1",
      "value": "string(.)"
    },
  "template": {
    "url": "{{ _url_ }}"
  }
}
```

**Comment by spencerskinner99** [comment]
Just managed to get that working, thank you very much!

Last quick question how would the url be embedded into a slack message 

```
{
  "webhook_url": "xxx",
  "channel": "#123",
  "username": "Huginn",
  "message": "Site change",
  "icon": "",
  "url": "{{_url_}}"
}
```
This is currently how I have it and its not worked

**Comment by spencerskinner99** [comment]
works a dream, thanks again!

**Comment by frankdzh** [comment]
unsubsribe

Unending ***@***.***>于2022年6月3日 周五20:03写道：
