### ISSUE TITLE
Newbie100%: 502 error and [YOUR_SERVER_FQDN]?

### ISSUE THREAD

**Issue by gcplaw** [huginn/huginn#3134]
**Background**
I set up Ubuntu 18.04.1 LTS on my cloud server and it gives me a public ip(lets say 2.2.2.2) and an intranet IP.

**My issue**
I dont have a doman name so I set my FDQN with my public ip.
When i access my public ip, it returns 502 bad gateway error with colored favicon of huggin.
I tried troubleshoot with 'sudo bundle exec rake production:check' and it returns **green ok everything is fine**.

**What should I do now? THANKS!**

**Comment by gcplaw** [comment]
When I click @, you four guys pop up... sorry to bother you guys like this but I really like to know how to solve the issue... apologize again for any inconveniences.....
@brynary @amoeba @necrodome @raucao

**Comment by gcplaw** [comment]
What I tried: ... too many bad returns... 
1. Troubleshooting - sudo bundle exec rake production:check
Return: [  OK  ] Everything is fine

2. Troubleshooting - Nginx error log /var/log/nginx/huginn_error.log
Return: connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed
BUT i did follow the guide to set the Procfile as below:
![image](https://user-images.githubusercontent.com/46683378/171854309-0fd54d31-e2cc-4e33-b135-80cf23daf8e8.png)

2. Troubleshooting - Unicorn log /home/huginn/huginn/log/unicorn.log
2.1 my unicorn.rb as below:
![image](https://user-images.githubusercontent.com/46683378/171854826-6ef351b4-4f1f-4afe-905e-08bf99b7436c.png)

2.2 Gem dependencies not all installed, wonder why as below
![image](https://user-images.githubusercontent.com/46683378/171855086-b04e6cd7-b765-455a-8c93-dfc6a8ecdb3e.png)

**Comment by virtadpt** [comment]
Nginx is trying to connect to the socket but can't.

`ls -alF /home/huginn/huginn/tmp/sockets/unicorn.socket`

What comes back?

**Comment by gcplaw** [comment]
> Nginx is trying to connect to the socket but can't.
> 
> `ls -alF /home/huginn/huginn/tmp/sockets/unicorn.socket`
> 
> What comes back?

`ls: cannot access '/home/huginn/huginn/tmp/sockets/unicorn.socket': No such file or directory`

@virtadpt no such file... and thank you for pick up my issue!

**Comment by virtadpt** [comment]
Yep, that's your problem.  No unicorn.socket, nothing for Nginx to connect to.  What happens when you try to start up the Unicorn server?

`rake production:export`
