### ISSUE TITLE
Huginn REST Endpoint Agent

### ISSUE THREAD

**Issue by Blizliam** [huginn/huginn#3135]
Please let me know if something like this already exists in the agent functionality and I am simply missing it.

I would love for the ability to create a REST API Endpoint Agent (or listener agent) that exposes an endpoint that creates events when POST, GET, or PUT requests are made. I feel like this would be very beneficial to the flexibility of Huginn.

The use case for myself would be a shell script that checks the status of docker containers and sends a curl POST/GET request to Huginn whenever a docker container fails to start or errors out. Currently I plan to use Grafana and have Huginn check Grafana for new data to solve my particular need, but I think this kind of thing would be a great addition to Huginn.

Just a thought! ;)

**Comment by virtadpt** [comment]
Take a look at the Webhook Agent.  That's what I use it for.

**Comment by Blizliam** [comment]
@virtadpt I'll give it a look. Thanks!
