### ISSUE TITLE
Is it possible to build multiple rules inside one scheduler agent?

### ISSUE THREAD

**Issue by alston19** [huginn/huginn#3138]
I'm trying to build a scheduler agent for announcing current price for centain stock every 15 minutes. The trading time is from 9:30-11:30 & 13:00-15:00. It's hard to write one rule to get what I want. Can I just write two rules inside one scheduler agent?
>>>now:
{
  "action": "run",
  "schedule": "0/30 9,10,11,13,14,15 * * 1-5"
}

>>>what I want:
{
  "action": "run",
  "schedule": ["0 10-11,13-15 * * 1-5", "30 9-11,13-14 * * 1-5"]
}

**Comment by ohingardail** [comment]
I don't think you can do that, but you can have more than one scheduler agent acting on the same agent, which would have exactly the same effect.

**Comment by virtadpt** [comment]
@ohingardail You cannot, and you can (respectively).  That's what I do.
