### ISSUE TITLE
Lost Huginn Web GUI Userid and Password

### ISSUE THREAD

**Issue by happening-primal** [huginn/huginn#3139]
I've lost both the userid and password to my huginn installation web interface.  It continues to run fine, but I can no longer access it.  Any suggestions on retrieving this info directly from the database?  I'm running in docker with a mariadb:10.3 backend (also in docker).

Any help much appreciated.

**Comment by virtadpt** [comment]
That's a really good question.  I went through the output of `bundle exec rake -AT` and didn't find anything (surprisingly).  Anybody else?

**Comment by Unending** [comment]
If you can still login to the database you can find this in the table `users`, but the passwords are obviously encrypted.

(You could also try `admin`/`password` if you never disabled the default account…)

There is a password reset feature build in which will send you a reset link via email, it also writes this to the logs so you can intercept it their if email doesn't work.

**Comment by happening-primal** [comment]
> If you can still login to the database you can find this in the table `users`, but the passwords are obviously encrypted.
> 
> (You could also try `admin`/`password` if you never disabled the default account…)
> 
> There is a password reset feature build in which will send you a reset link via email, it also writes this to the logs so you can intercept it there if email doesn't work.

Yes, this worked!  Thanks for your help. :)

**Comment by radry** [comment]
> If you can still login to the database you can find this in the table `users`, but the passwords are obviously encrypted.
> 
> (You could also try `admin`/`password` if you never disabled the default account…)
> 
> There is a password reset feature build in which will send you a reset link via email, it also writes this to the logs so you can intercept it there if email doesn't work.

I have the same problem. Email server isn't set up, so I need the log file. It runs inside docker. Which log file does it write it to?
