### ISSUE TITLE
 Typhoeus version bump request

### ISSUE THREAD

**Issue by yegle** [huginn/huginn#3140]
Hi,

I ran into this issue on certain websites:

https://github.com/curl/curl/issues/3750

Seeing typhoeus 1.3.1 is from 2018, can we bump it to 1.4.0?

Thanks!

**Comment by yegle** [comment]
Hmm actually Ruby 2.6 is EOL and maybe we should update to 2.7 instead?

**Comment by yegle** [comment]
Actually I just realized it's simply a wrapper around libcurl. I guess that means we need to update the base image to something like `ubuntu:22.04`?

**Comment by virtadpt** [comment]
Yes, please.
