### ISSUE TITLE
The Heroku-18 stack is deprecated

### ISSUE THREAD

**Issue by 362227** [huginn/huginn#3145]
"You have 1 personal app that is using the Heroku-18 stack, which is deprecated. From April 30th, 2023, Heroku-18 will be end-of-life and no longer receive security updates. From May 1st, 2023, builds will be disabled. Please upgrade your app to a newer Heroku stack"

**Comment by hdhoang** [comment]
in my experience, heroku-20 stack works fine, since gemfile uses a supported ruby2.7. i think you can try stack upgrade to 20
