### ISSUE TITLE
Message shows source name not

### ISSUE THREAD

**Issue by TsAbsinthe** [huginn/huginn#3155]
Hello all, 

I'm doing my first steps with Huginn and despair. 

I have an HTTP agent that monitors a specific IP address to see if it is still alive. 

This also works so far and I can trigger a trigger agent via HTTP agent, which in turn triggers the notification via pushover. 

Now I would like to get the name of the HTTP agent in the message of the trigger agent... 

But unfortunately this does not work and the output remains empty...

{
  "expected_receive_period_in_days": "2",
  "keep_event": "false",
  "rules": [
    {
      }, "type": "regex",
      }, "value": "false",
      "path": "response_received"
    }
  ],
  { "message": "IP: {{url}} offline. Name: {{sources}}"
}

Anybody have an idea???

**Comment by Unending** [comment]
`{{ sources }}` is not an included field from the HTTP status agent. Try the special object key `{{ agent.name }}` instead, it should give you the name of the upstream agent which created the event.

**Comment by TsAbsinthe** [comment]
Thank you. This solution works well.
