### ISSUE TITLE
Can't access web UI: Docker through Unraid

### ISSUE THREAD

**Issue by tmartinek** [huginn/huginn#3168]
I'm trying to access huginn web UI through my docker container on Unraid. When I try to access it, I get a "this site can't be reached" page. I've confirmed that I'm trying to connect via localhost:3005 - I changed the port just in case that was causing the issue, but it's the same error. It's Unraid build 6.11.0 if that's important. Any advice or recommendations would be greatly appreciated. I'm a beginner and probably in over my head, but I've tried all the google searches and usual troubleshooting I can think of. 

I pasted the logs below:

Using google-apis-core 0.4.1
Using google-apis-discovery_v1 0.7.0
Using google-apis-generator 0.4.0
Using google-api-client 0.53.0
Using google-cloud-env 1.5.0
Using google-cloud-errors 1.2.0
Using google-cloud-core 1.6.0
Using google-protobuf 3.21.5 (x86_64-linux)
Using googleapis-common-protos-types 1.3.0
Using grpc 1.42.0 (x86_64-linux)
Using googleapis-common-protos 1.3.12
Using rly 0.2.3
Using google-gax 1.8.2
Using google-cloud-translate 2.3.0
Using haversine 0.3.0
Using httparty 0.14.0
Using hipchat 1.2.0
Using mimemagic 0.4.3
Using httmultiparty 0.3.16
Using http-cookie 1.0.3
Using http-form_data 1.0.1
Using http 2.1.0
Using huginn_agent 0.6.1
Using hypdf 1.0.10
Using jquery-rails 4.2.2
Using json 2.6.1
Using jsonpath 1.1.0
Using kgio 2.11.4
Using kramdown 2.3.1
Using libv8-node 16.10.0.0 (x86_64-linux)
Using liquid 5.3.0
Using listen 3.0.8
Using systemu 2.6.4
Using macaddr 1.7.1
Using memoizable 0.4.2
Using mime-types-data 3.2021.1115
Using mime-types 3.4.1
Using mini_magick 4.11.0
Using mini_racer 0.6.2
Using mqtt 0.3.1
Using mysql2 0.5.3
Using naught 1.1.0
Using net-ftp-list 3.2.8
Using netrc 0.11.0
Using omniauth 1.9.1
Using omniauth-oauth2 1.7.2
Using omniauth-dropbox-oauth2 0.3.0 from https://github.com/huginn/omniauth-dropbox-oauth2.git
Using omniauth-oauth 1.1.0
Using omniauth-evernote 1.2.1
Using omniauth-google-oauth2 0.8.2
Using omniauth-tumblr 1.2
Using omniauth-twitter 1.3.0
Using raindrops 0.20.0
Using rb-kqueue 0.2.4
Using rest-client 2.0.2
Using rturk 2.12.1
Using uuid 2.3.7
Using ruby-growl 4.1
Using rufus-scheduler 3.8.1
Using sassc 2.3.0
Using tilt 2.0.10
Using sassc-rails 2.1.2
Using sass-rails 6.0.0
Using select2-rails 3.5.9.3
Using simple_oauth 0.3.1
Using slack-notifier 1.0.0
Using spectrum-rails 1.3.4
Using tumblr_client 0.8.5 from https://github.com/albertsun/tumblr_client.git (at e046fe6@e046fe6)
Using twilio-ruby 5.62.0
Using twitter 5.15.0 from https://github.com/sferik/twitter.git
Using twitter-stream 0.1.15 from https://github.com/cantino/twitter-stream.git (at huginn@a80822d)
Using typhoeus 1.3.1
Using uglifier 2.7.2
Using unicorn 6.1.0
Using weibo_2 0.1.7 from https://github.com/albertsun/weibo_2.git (at master@ac38d04)
Using xmpp4r 0.5.6
Bundle complete! 110 Gemfile dependencies, 204 gems now installed.
Gems in the groups 'test' and 'development' were not installed.
Bundled gems are installed into `./vendor/bundle`
2022-09-26 13:18:42,316 INFO Included extra file "/etc/supervisor/conf.d/bootstrap.conf" during parsing
2022-09-26 13:18:42,316 INFO Included extra file "/etc/supervisor/conf.d/foreman.conf" during parsing
2022-09-26 13:18:42,316 INFO Included extra file "/etc/supervisor/conf.d/mysqld.conf" during parsing
2022-09-26 13:18:42,322 INFO RPC interface 'supervisor' initialized
2022-09-26 13:18:42,322 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2022-09-26 13:18:42,322 INFO supervisord started with pid 1
2022-09-26 13:18:43,324 INFO spawned: 'stdout' with pid 574
2022-09-26 13:18:43,326 INFO spawned: 'bootstrap' with pid 575
2022-09-26 13:18:43,330 INFO success: bootstrap entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-09-26 13:18:43,340 INFO exited: bootstrap (exit status 1; not expected)
2022-09-26 13:18:44,342 INFO success: stdout entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by tmartinek** [comment]
Edit: I checked back the logs, and these were there. I'm fairly confident they shouldn't be there, but I'm not sure what's causing them. I checked the permissions of the share, and there isn't anything out of the ordinary. 

bootstrap stdout | DATABASE_HOST=localhost
bootstrap stderr | mv: cannot create regular file '/var/lib/mysql/auto.cnf': Permission denied
bootstrap stderr | mv: cannot create regular file '/var/lib/mysql/ca-key.pem': Permission denied
bootstrap stderr | mv: cannot create regular file '/var/lib/mysql/ca.pem': Permission denied
bootstrap stderr | mv: cannot create regular file '/var/lib/mysql/client-cert.pem': Permission denied
bootstrap stderr | mv: cannot create regular file '/var/lib/mysql/client-key.pem': Permission denied
bootstrap stderr | mv: cannot create regular file '/var/lib/mysql/ib_buffer_pool': Permission denied
bootstrap stderr | mv: cannot create regular file '/var/lib/mysql/ibdata1': Permission denied
bootstrap stderr | mv: cannot create regular file '/var/lib/mysql/ib_logfile0': Permission denied
bootstrap stderr | mv: cannot create regular file '/var/lib/mysql/ib_logfile1': Permission denied
bootstrap stderr | mv: cannot create directory '/var/lib/mysql/mysql': Permission denied
bootstrap stderr | mv: cannot create directory '/var/lib/mysql/performance_schema': Permission denied
bootstrap stderr | mv: cannot create regular file '/var/lib/mysql/private_key.pem': Permission denied
bootstrap stderr | mv: cannot create regular file '/var/lib/mysql/public_key.pem': Permission denied
bootstrap stderr | mv: cannot create regular file '/var/lib/mysql/server-cert.pem': Permission denied
bootstrap stderr | mv: cannot create regular file '/var/lib/mysql/server-key.pem': Permission denied
bootstrap stderr | mv: cannot create directory '/var/lib/mysql/sys': Permission denied
2022-09-26 15:13:01,209 INFO exited: bootstrap (exit status 1; not expected)

**Comment by Serph91P** [comment]
Have the same error, log attached:

> bootstrap stdout | DATABASE_HOST=localhost
> bootstrap stderr | 2022-10-25T09:33:52.093482Z 0 [Warning] Ignoring user change to 'default' because the user was set to '1001' earlier on the command line
> 
> 2022-10-25T09:33:52.093514Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
> 2022-10-25T09:33:52.094736Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
> 2022-10-25T09:33:52.094751Z 0 [ERROR] Aborting
> 
> 2022-10-25 02:34:44,997 WARN received SIGTERM indicating exit request
> 2022-10-25 02:34:44,997 INFO waiting for stdout to die
> 2022-10-25 02:34:48,000 INFO waiting for stdout to die
> 2022-10-25 02:34:48,000 INFO stopped: stdout (terminated by SIGTERM)
> You are replacing the current local value of without, which is currently "test:development"
> fatal: detected dubious ownership in repository at '/app'
> To add an exception for this directory, call:
> 
>         git config --global --add safe.directory /app
> fatal: detected dubious ownership in repository at '/app'
> To add an exception for this directory, call:
> 
>         git config --global --add safe.directory /app
> Using rake 13.0.6
> Using ace-rails-ap 2.0.1
> Using concurrent-ruby 1.1.10
> Using i18n 1.12.0
> Using minitest 5.16.3
> Using thread_safe 0.3.6
> Using tzinfo 1.2.10
> Using zeitwerk 2.6.0
> Using activesupport 6.0.5.1
> Using builder 3.2.4
> Using erubi 1.11.0
> Using racc 1.6.0
> Using nokogiri 1.13.8 (x86_64-linux)
> Using rails-dom-testing 2.0.3
> Using crass 1.0.6
> Using loofah 2.18.0
> Using rails-html-sanitizer 1.4.3
> Using actionview 6.0.5.1
> Using rack 2.2.4
> Using rack-test 2.0.2
> Using actionpack 6.0.5.1
> Using nio4r 2.5.8
> Using websocket-extensions 0.1.5
> Using websocket-driver 0.7.5
> Using actioncable 6.0.5.1
> Using globalid 1.0.0
> Using activejob 6.0.5.1
> Using activemodel 6.0.5.1
> Using activerecord 6.0.5.1
> Using marcel 1.0.2
> Using activestorage 6.0.5.1
> Using mini_mime 1.1.2
> Using mail 2.7.1
> Using actionmailbox 6.0.5.1
> Using actionmailer 6.0.5.1
> Using actiontext 6.0.5.1
> Using public_suffix 4.0.7
> Using addressable 2.8.0
> Using aws-eventstream 1.2.0
> Using aws-partitions 1.547.0
> Using aws-sigv4 1.4.0
> Using jmespath 1.6.1
> Using aws-sdk-core 3.125.2
> Using aws-sdk-kms 1.53.0
> Using aws-sdk-s3 1.111.1
> Using bcrypt 3.1.16
> Using msgpack 1.4.2
> Using bootsnap 1.9.3
> Using kaminari-core 1.2.2
> Using kaminari-actionview 1.2.2
> Using kaminari-activerecord 1.2.2
> Using kaminari 1.2.2
> Using bundler 2.3.10
> Using method_source 1.0.0
> Using thor 0.20.3
> Using railties 6.0.5.1
> Using sprockets 3.7.2
> Using sprockets-rails 3.4.2
> Using rails 6.0.5.1
> Using bootstrap-kaminari-views 0.0.5
> Using buftok 0.2.0
> Using coffee-script-source 1.12.2
> Using execjs 2.8.1
> Using coffee-script 2.4.1
> Using coffee-rails 5.0.0
> Using cookiejar 0.3.3
> Using daemons 1.1.9
> Using declarative 0.0.20
> Using delayed_job 4.1.9
> Using delayed_job_active_record 4.1.4 from https://github.com/dsander/delayed_job_active_record.git (at rails6-zeitwerk@ac2dfef)
> Using orm_adapter 0.5.0
> Using responders 3.0.1
> Using warden 1.2.9
> Using devise 4.8.1
> Using unf_ext 0.0.7.4
> Using unf 0.1.4
> Using domain_name 0.5.20170404
> Using dotenv 2.0.1 from source at `vendor/gems/dotenv-2.0.1`
> Using dotenv-rails 2.0.1 from source at `vendor/gems/dotenv-2.0.1`
> Using hashie 3.5.7
> Using multi_json 1.15.0
> Using multipart-post 2.1.1
> Using faraday 0.17.4
> Using jwt 2.3.0
> Using multi_xml 0.6.0
> Using oauth2 1.4.7
> Using dropbox-api 0.5.0 from https://github.com/dsander/dropbox-api.git (at 86cb7b5@86cb7b5)
> Using eventmachine 1.2.7
> Using em-socksify 0.3.2
> Using http_parser.rb 0.6.0
> Using em-http-request 1.1.7
> Using equalizer 0.0.11
> Using polyglot 0.3.5
> Using treetop 1.6.10
> Using erector 0.10.0 from https://github.com/dsander/erector.git (at rails6@821c2fa)
> Using et-orbi 1.2.6
> Using ffi 1.15.5
> Using ethon 0.12.0
> Using evernote-thrift 1.25.1
> Using oauth 0.5.8
> Using evernote_oauth 0.2.3
> Using faraday_middleware 0.12.2
> Using sax-machine 1.3.2
> Using feedjira 3.2.0
> Using rb-fsevent 0.11.0
> Using rb-inotify 0.10.1
> Using sass-listen 4.0.0
> Using sass 3.7.4
> Using font-awesome-sass 4.7.0
> Using forecast_io 2.0.1
> Using foreman 0.63.0
> Using raabro 1.4.0
> Using fugit 1.5.2
> Using gems 1.2.0
> Using geokit 1.13.1
> Using geokit-rails 2.3.2
> Using gmail_xoauth 0.4.2
> Using memoist 0.16.2
> Using os 1.1.4
> Using signet 0.16.0
> Using googleauth 0.17.1
> Using httpclient 2.8.3
> Using trailblazer-option 0.1.2
> Using uber 0.1.0
> Using representable 3.1.1
> Using retriable 3.1.2
> Using rexml 3.2.5
> Using webrick 1.7.0
> Using google-apis-core 0.4.1
> Using google-apis-discovery_v1 0.7.0
> Using google-apis-generator 0.4.0
> Using google-api-client 0.53.0
> Using google-cloud-env 1.5.0
> Using google-cloud-errors 1.2.0
> Using google-cloud-core 1.6.0
> Using google-protobuf 3.21.5 (x86_64-linux)
> Using googleapis-common-protos-types 1.3.0
> Using grpc 1.42.0 (x86_64-linux)
> Using googleapis-common-protos 1.3.12
> Using rly 0.2.3
> Using google-gax 1.8.2
> Using google-cloud-translate 2.3.0
> Using haversine 0.3.0
> Using httparty 0.14.0
> Using hipchat 1.2.0
> Using mimemagic 0.4.3
> Using httmultiparty 0.3.16
> Using http-cookie 1.0.3
> Using http-form_data 1.0.1
> Using http 2.1.0
> Using huginn_agent 0.6.1
> Using hypdf 1.0.10
> Using jquery-rails 4.2.2
> Using json 2.6.1
> Using jsonpath 1.1.0
> Using kgio 2.11.4
> Using kramdown 2.3.1
> Using libv8-node 16.10.0.0 (x86_64-linux)
> Using liquid 5.3.0
> Using listen 3.0.8
> Using systemu 2.6.4
> Using macaddr 1.7.1
> Using memoizable 0.4.2
> Using mime-types-data 3.2021.1115
> Using mime-types 3.4.1
> Using mini_magick 4.11.0
> Using mini_racer 0.6.2
> Using mqtt 0.3.1
> Using mysql2 0.5.3
> Using naught 1.1.0
> Using net-ftp-list 3.2.8
> Using netrc 0.11.0
> Using omniauth 1.9.1
> Using omniauth-oauth2 1.7.2
> Using omniauth-dropbox-oauth2 0.3.0 from https://github.com/huginn/omniauth-dropbox-oauth2.git
> Using omniauth-oauth 1.1.0
> Using omniauth-evernote 1.2.1
> Using omniauth-google-oauth2 0.8.2
> Using omniauth-tumblr 1.2
> Using omniauth-twitter 1.3.0
> Using raindrops 0.20.0
> Using rb-kqueue 0.2.4
> Using rest-client 2.0.2
> Using rturk 2.12.1
> Using uuid 2.3.7
> Using ruby-growl 4.1
> Using rufus-scheduler 3.8.1
> Using sassc 2.3.0
> Using tilt 2.0.10
> Using sassc-rails 2.1.2
> Using sass-rails 6.0.0
> Using select2-rails 3.5.9.3
> Using simple_oauth 0.3.1
> Using slack-notifier 1.0.0
> Using spectrum-rails 1.3.4
> Using tumblr_client 0.8.5 from https://github.com/albertsun/tumblr_client.git (at e046fe6@e046fe6)
> Using twilio-ruby 5.62.0
> Using twitter 5.15.0 from https://github.com/sferik/twitter.git
> Using twitter-stream 0.1.15 from https://github.com/cantino/twitter-stream.git (at huginn@a80822d)
> Using typhoeus 1.3.1
> Using uglifier 2.7.2
> Using unicorn 6.1.0
> Using weibo_2 0.1.7 from https://github.com/albertsun/weibo_2.git (at master@ac38d04)
> Using xmpp4r 0.5.6
> Bundle complete! 110 Gemfile dependencies, 204 gems now installed.
> Gems in the groups 'test' and 'development' were not installed.
> Bundled gems are installed into `./vendor/bundle`
> 2022-10-25 02:35:21,336 INFO Included extra file "/etc/supervisor/conf.d/bootstrap.conf" during parsing
> 2022-10-25 02:35:21,337 INFO Included extra file "/etc/supervisor/conf.d/foreman.conf" during parsing
> 2022-10-25 02:35:21,337 INFO Included extra file "/etc/supervisor/conf.d/mysqld.conf" during parsing
> 2022-10-25 02:35:21,343 INFO RPC interface 'supervisor' initialized
> 2022-10-25 02:35:21,343 CRIT Server 'unix_http_server' running without any HTTP authentication checking
> 2022-10-25 02:35:21,343 INFO supervisord started with pid 1
> 2022-10-25 02:35:22,345 INFO spawned: 'stdout' with pid 574
> 2022-10-25 02:35:22,346 INFO spawned: 'bootstrap' with pid 575
> 2022-10-25 02:35:22,351 INFO success: bootstrap entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
> 2022-10-25 02:35:22,359 INFO exited: bootstrap (exit status 1; not expected)
> 2022-10-25 02:35:23,361 INFO success: stdout entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by Kagami** [comment]
```bash
ssh root@unraid
cd /mnt/user/appdata/<path_to_huginn_mysql_volume>
chmod -R 777 <mysql_folder>
```

**Comment by tupcakes** [comment]
> ```shell
> ssh root@unraid
> cd /mnt/user/appdata/<path_to_huginn_mysql_volume>
> chmod -R 777 <mysql_folder>
> ```

I'm seeing the same error, but when spinning up a container using external mysql. I don't think it's related to folder permissions on the internal mysql folder.

**Comment by gslin** [comment]
I guess you're running the docker command with volume settings like `-v /somewhere/huginn-mysql:/var/lib/mysql`, just like the official guide from https://hub.docker.com/r/huginn/huginn/.

The root cause looks like mysqld is running with `default` user inside the container, and `default`'s uid is `1001`, and in you case `/somewhere/huginn-mysql` does not allow container's mysqld to write into this directory.

A not-so-clean workaround is `chown -R 1001:0 /somewhere/huginn-mysql` to allow `default` user in the container (whose uid is `1001`) can read/write the directory.  A better solution should be fixing in huginn Dockerfile or somewhere, just like https://github.com/huginn/huginn/issues/3147#issuecomment-1207375095 this fix.

**Comment by DLCIncluded** [comment]
Thank you, changing the owner works for to get it running on unRAID.  Was having the same issue
