### ISSUE TITLE
LiquidOutputAgent should be able to act as a source; templating engine does not eval strings as truthy/falsy

### ISSUE THREAD

**Issue by randomshinichi** [huginn/huginn#3169]
I wasted a lot of time trying to output a html page from a stream of events, or even multiple streams - and finally found it in the LiquidOutput Agent, only to find that I cannot pipe it into a Digest email from there! What gives? This is such an obvious usecase.

The Javascript agent was not so useful because it was only receiving one event at a time, and I couldn't get `this.memory()` working.

Also, https://shopify.github.io/liquid/basics/truthy-and-falsy/ says that non-empty strings are falsy.
```
{% for event in events %}
  {% if event.price != "" %} // here, just saying event.price wasn't enough! That's not correct - it should be enough.
    <li>{{event.price}} <a href="{{event.url}}">{{ event.title }}</a></li>
  {% endif %}
{% endfor %}
```

**Comment by Unending** [comment]
Why don't you use the `Event Formatting Agent` it should be able to do the exact same as the `Liquid Output Agent` except it outputs events instead of an output page.

> Also, https://shopify.github.io/liquid/basics/truthy-and-falsy/ says that non-empty strings are falsy.

The page literally says the oposite: 
> All values in Liquid are truthy except nil and false.

> [Strings](https://shopify.github.io/liquid/basics/types/#string), even when empty, are truthy.
