### ISSUE TITLE
Docker images no longer build (mini_racer can't find libv8-node)

### ISSUE THREAD

**Issue by iay** [huginn/huginn#3171]
I tried to build a Docker image from the current repository in order to have a baseline for testing fixes for another issue. This failed at the `bundle install` stage, with the `mini_racer` gem being unable to locate the precompiled library installed as part of `libv8-node`.

This turned out to be due to a change in rubygems platform handling introduced in rubygems 3.3.21; the last image build was made with `gem env` indicating 3.3.20, but the current version is 3.3.22.

I fixed this locally by changing `docker/scripts/prepare` from this:

```bash
gem update --system --no-document
```

to this:

```bash
# Specific version 3.3.20: 3.3.21 changes platform support, breaks our build
gem update --system 3.3.20 --no-document
```

This is obviously not a great long-term solution, but I suspect really fixing this requires one of the gems to be changed to address the new platform system and that's beyond my skills. For now, setting the rubygems version explicitly stabilises the build.

I can submit a PR for this if that would be helpful.

**Comment by SharkBeard** [comment]
I think I might be running into the same problem.

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /scripts/init: exec format error
```

**Comment by iay** [comment]
> I think I might be running into the same problem.
> 
> ```
> WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
> exec /scripts/init: exec format error
> ```

@SharkBeard: I think you have a different issue. The message you are seeing is _exactly_ the error I get if I try to `docker run --rm -it huginn/huginn` on  a Raspberry Pi or other ARM hardware without emulation support.

The `huginn/huginn` image is only built for the Intel architecture. There's at least one other issue discussing this (see #2648) and you might take a look there; at some point, someone put in the work to make that happen for them.

(I briefly tried building an ARM image myself, but ran into first the same issue as I mention here, but also what looks like a similar Ruby platform issue in `nokogiri`.)

To clarify, my issue is with `docker build` rather than `docker run`, and it's about the Ruby platform system distinguishing between different x86 variants (by operating system and C library) rather than a CPU architecture mismatch.

**Comment by SharkBeard** [comment]
> @SharkBeard: I think you have a different issue. The message you are seeing is _exactly_ the error I get if I try to `docker run --rm -it huginn/huginn` on a Raspberry Pi or other ARM hardware without emulation support.
> 
> The `huginn/huginn` image is only built for the Intel architecture. There's at least one other issue discussing this (see #2648) and you might take a look there; at some point, someone put in the work to make that happen for them.
> 
> (I briefly tried building an ARM image myself, but ran into first the same issue as I mention here, but also what looks like a similar Ruby platform issue in `nokogiri`.)
> 
> To clarify, my issue is with `docker build` rather than `docker run`, and it's about the Ruby platform system distinguishing between different x86 variants (by operating system and C library) rather than a CPU architecture mismatch.

Ah, thanks for the reply. I just read `linux/arm64/v8` and `libv8-node` and assumed the v8s were related.

Thanks for the help though! I just got a pi to experiment with and learn docker so I am a bit of a newbie. I'm guessing if that is the case a lot of ruby images will have trouble running in docker unless they built it with arm in mind.

**Comment by iay** [comment]
>I'm guessing if that is the case a lot of ruby images will have trouble running in docker unless they built it with arm in mind.

Yes, a lot of images (not just Ruby ones) are Intel-only and won't run in Docker on a Raspberry Pi unless you [enable emulation](https://hub.docker.com/r/tonistiigi/binfmt) (and then they will run slowly). Multi-architecture images are becoming much more common, though. For example, if you look at the [tags for the official Ruby image](https://hub.docker.com/_/ruby/tags) you can see that it's available for eight architectures including three ARM variants.

The Raspberry Pi is a great learning platform (if you can get hold of one, they are a bit scarce right now).

**Comment by iay** [comment]
Opened PR #3173.

**Comment by knu** [comment]
Good catch, thanks!  I investigated and concluded that the problem should be fixed in libv8-node:  https://github.com/rubyjs/libv8-node/pull/36
