### ISSUE TITLE
Need help with Discord Post Agent

### ISSUE THREAD

**Issue by geezfools** [huginn/huginn#3181]
Just installed huginn last night and got it working, but was overwhelmed. Sat down tonight and figured I'd get into one thing at a time. First, set up an Event Agent with an RSS feed. Only took me a few minutes, but I was able to get that going, seems like a pretty common thing inside huginn. Now, I want to use that info and push it to a discord server I run. And now I'm stumped...

Here is the data I'm getting from the RSS feed. It's a website selling vinyl records.

> {
>   "id": "https://www.newburycomics.com/products/7308238913716",
>   "url": "https://www.newburycomics.com/products/justin_townes_earle-the_good_life_exclusive_lp",
>   "urls": [
>     "https://www.newburycomics.com/products/justin_townes_earle-the_good_life_exclusive_lp"
>   ],
>   "links": [
>     {
>       "href": "https://www.newburycomics.com/products/justin_townes_earle-the_good_life_exclusive_lp",
>       "rel": "alternate",
>       "type": "text/html"
>     }
>   ],
>   "title": "The Good Life Exclusive LP",
>   "description": "\n      <table border=\"0\">\n  <tr>\n    <td width=\"200\"><img width=\"200\" src=\"https://cdn.shopify.com/s/files/1/0882/5118/products/Justin-Townes-Earle-The-Good-Life-Exclusive-Color-Vinyl-2610581.jpg?v=1667845097\"><\/td>\n    <td valign=\"bottom\">\n      <p>\n\n        <strong>Vendor: <\/strong>Justin Townes Earle<br>\n        <strong>Type: <\/strong>Vinyl<br>\n        <strong>Price: <\/strong>\n            27.99\n      <\/p>\n    <\/td>\n  <\/tr>\n  <tr>\n    <td colspan=\"2\"><p>A Newbury Comics exclusive color vinyl pressing.<\/p><p>A modern-day troubadour, Justin Townes Earle blends genres seamlessly, framing his songs in warm musical settings and creating tunes that could easily be mistaken for classics. Earle melds the qualities of a short story with the lyrical acuity of excellent songs, blowing a fresh breeze across the musical gardens and dive bars of Nashville.<\/p><\/td>\n  <\/tr>\n<\/table>\n\n    ",
>   "content": "\n      <table border=\"0\">\n  <tr>\n    <td width=\"200\"><img width=\"200\" src=\"https://cdn.shopify.com/s/files/1/0882/5118/products/Justin-Townes-Earle-The-Good-Life-Exclusive-Color-Vinyl-2610581.jpg?v=1667845097\"><\/td>\n    <td valign=\"bottom\">\n      <p>\n\n        <strong>Vendor: <\/strong>Justin Townes Earle<br>\n        <strong>Type: <\/strong>Vinyl<br>\n        <strong>Price: <\/strong>\n            27.99\n      <\/p>\n    <\/td>\n  <\/tr>\n  <tr>\n    <td colspan=\"2\"><p>A Newbury Comics exclusive color vinyl pressing.<\/p><p>A modern-day troubadour, Justin Townes Earle blends genres seamlessly, framing his songs in warm musical settings and creating tunes that could easily be mistaken for classics. Earle melds the qualities of a short story with the lyrical acuity of excellent songs, blowing a fresh breeze across the musical gardens and dive bars of Nashville.<\/p><\/td>\n  <\/tr>\n<\/table>\n\n    ",
>   "image": null,
>   "enclosure": null,
>   "authors": [
> 
>   ],
>   "categories": [
> 
>   ],
>   "date_published": "2022-11-08T11:00:04-05:00",
>   "last_updated": "2022-11-08T11:00:04-05:00"
> }

I've been trying a few different things for my post agent and with what I'm posting, it only posts a single dash. It is pushing through thankfully, but none of the data is making it through. Any help would be awesome!

> {
>   "post_url": "https://discord.com/api/webhooks/103973......",
>   "expected_receive_period_in_days": "1",
>   "content_type": "json",
>   "method": "post",
>   "payload": {
>     "content": "{{url}} - {{id}}",
>     "username": "{{author}}",
>     "url": "{{link}}"
>   },
>   "headers": {
>     "Content-Type": "application/json"
>   },
>   "emit_events": "true",
>   "no_merge": "false",
>   "output_mode": "clean"
> }

**Comment by geezfools** [comment]
So I was having issues with pushing it through as a "dry run". As a test, I found a popular reddit feed and added that in and kinda letting it do it's thing and it seems to be pushing through as expected.

**Comment by dreamerc** [comment]
Please check https://discord.com/developers/docs/resources/webhook#execute-webhook

The problem is :
`
"url": "{{link}}"
`
It's not in API.

**Comment by geezfools** [comment]
> 

I did end up removing that. Seems to be working more or less as desired. I'm still curious if I can pull anything else from the data I'm getting from the initial feed or if I'm limited to URLs, titles and maybe icons...

**Comment by geezfools** [comment]
Figured I should close this. It's working as hoped and I'm starting to dabble into other parts of Huginn for my needs with a discord server. Sharing my current options for the Post Agent for anyone else who might come along. I'm not sure if my new line use of \n is correct, but it's working. Whenever I edit the agent though, it adds an extra \ in front of it and I have to remember to delete that each time.

{
  "post_url": "https://discord.com/api/webhooks/104049...",
  "expected_receive_period_in_days": "1",
  "content_type": "json",
  "method": "post",
  "payload": {
    "content": "**{{title}}** \n{{url}}",
    "username": "Captain Huginn"
  },
  "headers": {
    "Content-Type": "application/json"
  },
  "emit_events": "false",
  "no_merge": "true",
  "output_mode": "clean"
}
