### ISSUE TITLE
Please explain to a beginner how to make a Email Agent work

### ISSUE THREAD

**Issue by VlaK0r** [huginn/huginn#3187]
I enter all the data in the appropriate fields. But the email is not sent to the specified address. Maybe something else needs to be configured?

**Comment by virtadpt** [comment]
How do you have outbound SMTP configured in your huginn/.env file?  Let's start there.

**Comment by VlaK0r** [comment]
> How do you have outbound SMTP configured in your huginn/.env file? Let's start there.

Can I have more details please?
I deployed hugin using docker on a VPS server.
How can I find and edit this file now?

**Comment by VlaK0r** [comment]
> How do you have outbound SMTP configured in your huginn/.env file? Let's start there.

So you don't know what to do next?

**Comment by virtadpt** [comment]
I have other stuff going on in addition to Huginn.  Please be nice.

Let's start by finding it: `find / -type f -name '.env' -print`

That command will print the full path to Huginn's .env file.

**Comment by VlaK0r** [comment]
What's next?

**Comment by virtadpt** [comment]
What is the full path to the file?

**Comment by VlaK0r** [comment]
/var/lib/docker/overlay2/2b1f6a860db6c3a1c8df6b63a208741aea3d8a36914df5b984d3597790c10bec/merged/tmp/.env
/var/lib/docker/overlay2/2b1f6a860db6c3a1c8df6b63a208741aea3d8a36914df5b984d3597790c10bec/merged/app/.env
/var/lib/docker/overlay2/2b1f6a860db6c3a1c8df6b63a208741aea3d8a36914df5b984d3597790c10bec/diff/app/.env
/var/lib/docker/overlay2/2b1f6a860db6c3a1c8df6b63a208741aea3d8a36914df5b984d3597790c10bec/diff/tmp/.env

**Comment by Cordelya** [comment]
In case the OP comes back, or if anyone else comes here looking for this answer:

I edited the relevant lines in my version of `/var/lib/docker/overlay2/[container-id]/merged/app/.env`

The environment variables you want to customize are:

- SMTP_DOMAIN (this is the domain or public IP of your machine)
- SMTP_USER_NAME (the Google account username that the app password is issued through)
- SMTP_PASSWORD (the app password you get from Google)
- EMAIL_FROM_ADDRESS (I set this to the same value as SMTP_USER_NAME)

I then did `docker restart [container-name]`
I tried running an email agent and it worked as it should

**Comment by VlaK0r** [comment]
> In case the OP comes back, or if anyone else comes here looking for this answer:
> 
> I edited the relevant lines in my version of `/var/lib/docker/overlay2/[container-id]/merged/app/.env`
> 
> The environment variables you want to customize are:
> 
> * SMTP_DOMAIN (this is the domain or public IP of your machine)
> * SMTP_USER_NAME (the Google account username that the app password is issued through)
> * SMTP_PASSWORD (the app password you get from Google)
> * EMAIL_FROM_ADDRESS (I set this to the same value as SMTP_USER_NAME)
> 
> I then did `docker restart [container-name]` I tried running an email agent and it worked as it should
