### ISSUE TITLE
RSS to Telegram

### ISSUE THREAD

**Issue by VlaK0r** [huginn/huginn#3188]
Please help the newbie.
I can't make a simple sequence.
It is necessary that with a new event in the RSS feed, a simple message was sent in a telegram, for example, "RSS new event"

**Comment by virtadpt** [comment]
Could you clarify a bit, please?

Are you asking, "for every new RSS feed event, a new Telegram message is sent?"

Are you asking how events are emitted by the RSS Agent, i.e., only new events are emitted?

**Comment by VlaK0r** [comment]
> Could you clarify a bit, please?
> 
> Are you asking, "for every new RSS feed event, a new Telegram message is sent?"
> 
> Are you asking how events are emitted by the RSS Agent, i.e., only new events are emitted?

**Comment by VlaK0r** [comment]
Thank you, I have already solved the question myself.

**Comment by virtadpt** [comment]
Could you please post your solution here so other people can use it if they need it?

**Comment by VlaK0r** [comment]
> Could you please post your solution here so other people can use it if they need it?

Please upload the script.
[Huginn rss - telegram.txt](https://github.com/huginn/huginn/files/10148188/Huginn.rss.-.telegram.txt)
