### ISSUE TITLE
ArgumentError at app/concerns/dry_runnable.rb:64:in `save'

### ISSUE THREAD

**Issue by Aodaruma** [huginn/huginn#3195]
I have deployed huginn with [oracle cloud's ampare a1 compute](https://www.oracle.com/jp/cloud/compute/arm/) and got to the part where I run the service, but when I try to create an agent, the web page says "We're sorry, but something went wrong." and an error occurs.

The following error was written in log/production.log (I hid authenticy_token)

```
I, [2022-12-26T02:06:27.771390 #1852]  INFO -- : [18c79aae-443c-4f3c-8e28-852ac74558b6] Processing by AgentsController#create as HTML
I, [2022-12-26T02:06:27.771461 #1852]  INFO -- : [18c79aae-443c-4f3c-8e28-852ac74558b6]   Parameters: {"authenticity_token"=>"", "return"=>"", "agent"=>{"type"=>"Agents::DelayAgent", "name"=>"", "schedule"=>"every_12h", "controller_ids"=>[""], "control_target_ids"=>[""], "keep_events_for"=>"0", "source_ids"=>[""], "propagate_immediately"=>"0", "receiver_ids"=>[""], "scenario_ids"=>[""], "options"=>{"expected_receive_period_in_days"=>"10", "max_events"=>"100", "keep"=>"newest", "max_emitted_events"=>""}}, "commit"=>"Save"}
I, [2022-12-26T02:06:27.776446 #1852]  INFO -- : [18c79aae-443c-4f3c-8e28-852ac74558b6] Completed 500 Internal Server Error in 5ms (ActiveRecord: 0.8ms | Allocations: 2397)
F, [2022-12-26T02:06:27.777048 #1852] FATAL -- : [18c79aae-443c-4f3c-8e28-852ac74558b6]   
[18c79aae-443c-4f3c-8e28-852ac74558b6] ArgumentError (wrong number of arguments (given 1, expected 0)):
[18c79aae-443c-4f3c-8e28-852ac74558b6]   
[18c79aae-443c-4f3c-8e28-852ac74558b6] app/concerns/dry_runnable.rb:64:in `save'
[18c79aae-443c-4f3c-8e28-852ac74558b6] app/controllers/agents_controller.rb:160:in `block in create'
[18c79aae-443c-4f3c-8e28-852ac74558b6] app/controllers/agents_controller.rb:159:in `create'
[18c79aae-443c-4f3c-8e28-852ac74558b6] config/initializers/silence_worker_status_logger.rb:3:in `call'
```

I don't know Ruby very well, so looking at `app/concerns/dry_runnable.rb:64`(... `return super unless dry_run?` ...) doesn't seem to indicate anything is wrong.
Please let me know if there is any other information needed. Thanks!

**Comment by simcop2387** [comment]
I'm seeing the same thing, it looks like that line needs to change a bit:

```ruby
...

    def save(options = {})
      return super() unless dry_run?
....
```

Without the () it looks like the options argument will get passed to whatever the parent class is via `super`, which doesn't take any arguments.  I suspect this is something with us using a newer version of ruby than huginn is tested on or something like that.

**Comment by Aodaruma** [comment]
I rewrote it that way and it works!
However, since other errors are occurring, such as dry_run, I will check if the version of ruby huginn using is running at the expected version.

**Comment by Aodaruma** [comment]
It appeared that 3.0.0 was installed using rbenv.
Also, I had rbenv to switch versions, but installing to 2.7.6 with rbenv was causing all sorts of errors, so I installed 2.7.6 directly to the system, and it worked!
