### ISSUE TITLE
website agent struggles - missing articles

### ISSUE THREAD

**Issue by geezfools** [huginn/huginn#3196]
Trying to monitor this site: https://eu.kingsroadmerch.com/shop/category/1033/vinyl

I'm using the code below and it is catching events, but since it's running every 10 minutes, it's only catching the top "article" or record. So if the site is adding like 15 records in one shot, it misses a bunch. My skills are limited and I'm honestly impressed I've got this far with huginn. So if I'm missing something obvious, take it easy on me, lol. 

Not sure if it matters, but this gets pushed to a post agent which is pushing to a discord webhook.

```
{
  "expected_update_period_in_days": "30",
  "url": "https://eu.kingsroadmerch.com/shop/category/1033/vinyl",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "title": {
      "xpath": "/html/body/section/div[2]/article/figure[1]/p[1]",
      "value": "./node()"
    },
    "description": {
      "xpath": "/html/body/section/div[2]/article/figure[1]/p[2]",
      "value": "./node()"
    },
    "link": {
      "value": "@href",
      "xpath": "/html/body/section/div[2]/article/figure[1]/a"
    }
  },
  "template": {
    "url": "https://eu.kingsroadmerch.com{{ link }}",
    "title": "{{ title }} - {{ description }}"
  }
}
```

**Comment by mightymt** [comment]
Looks like you're explicitly only fetching the first item. Just replace `figure[1]` with `figure` in all three xpath expressions and you should get all the results.

**Comment by geezfools** [comment]
> Looks like you're explicitly only fetching the first item. Just replace `figure[1]` with `figure` in all three xpath expressions and you should get all the results.

Thank you, I'll give that a shot and report back.

**Comment by geezfools** [comment]
> Looks like you're explicitly only fetching the first item. Just replace `figure[1]` with `figure` in all three xpath expressions and you should get all the results.

Thank you, seems to be fitting the bill. Any suggestions on finding the difference easier or is it checking a few tables and noticing the differences? I fixed two agents so far with your suggestion, I appreciate your help :)
