### ISSUE TITLE
RSS collector

### ISSUE THREAD

**Issue by tassoman** [huginn/huginn#3211]
Hello there, I'm trying to build an rss activitypub bot. Various `RSS Agent` should fetch new messages and trasform into events. Then another agent `API Client` should consume them asap or 1 at time (each minute) when there are more queued.

Until now, I wrote this agents. But, looks like the queue gets consumed instantly by `API Client`. Any hint how to make it less hungry/spammy?

### RSS Agent

- Type: Rss Agent
- Schedule: Every 5m
- Last checked: 4m ago
- Keep events: 7 days
- Last event created: 12m ago
- Events created: [41]
- Event receivers: [API Client]
- Working: Yes

```json
{
  "expected_update_period_in_days": "1",
  "clean": "true",
  "url": "https://rss.url/rss/mytopic",
  "include_feed_info": "true"
}
```

### API Client

- Type: Post Agent
- Schedule: Never
- Last checked: 9m ago
- Keep events: 30 days
- Last event created: 9m ago
- Last received event: 13m ago
- Events created: [57]
- Event sources: [RSS Agent 1] and [RSS Agent 2]
- Propagate immediately: Yes
- Event receivers: None
- Working: Yes

```json
{
  "post_url": "https://activitypub.destination/api/v1/statuses",
  "expected_receive_period_in_days": "1",
  "method": "post",
  "payload": {
    "expires_in": "2600000",
    "status": "{{title}} {{content}} {{url}}"
  },
  "headers": {
  },
  "emit_events": "true",
  "no_merge": "true",
  "output_mode": "clean",
  "basic_auth": [
    "user",
    "pass"
  ]
}
```

**Comment by virtadpt** [comment]
So... it looks like you're crossposting new RSS feed entries to your Fedi account?  I do pretty much the same thing with my blog.

For starters, you have to have `"content_type": "form",` in your agent configuration.  Relying on the default doesn't work.  `"no_merge": false," also needs to be set.  Basic authentication is for HTTP basic auth and not for authenticating to the instance.  You'll want to use bearer token authentication instead: `"Authorization": "Bearer {% credential your_access_token %}"`

**Comment by tassoman** [comment]
Thank you for answering!
Well, yes. I made a Soapbox/Rebased (pleroma) newsbot. Oauth2 accepts also basic auth (under TLS it's ok).
I moved the password inside the credential area, also. POST it's ok. 

I'm unaware how to avoid spamposting many events in a one-shot. My goal is to consume the event queue once, hourly.

I tried setting `schedule = 1 hour` but the agent tries to post empty payload. It should run only when the queue length is greater than 0 :thinking:

**Comment by Unending** [comment]
Agent schedules and event propagation are two different things. By default, iirc, pending events are processed every minute.

Try the Delay Agent, it will only run on a set schedule and emit a predefined number of events at a time.

**Comment by tassoman** [comment]
I added this agent, between the other two. Expecting will have a queue of 72 items (hours), pushing out the older.

### RSS Queue

- Type: Delay Agent
- Schedule: Every 1h
- Last checked: never
- Keep events: 7 days
- Last event created: never
- Last received event: never
- Events created: [0]
- Event sources: [RSS 1] and [RSS 2]
- Propagate immediately: No
- Event receivers: [API Client]
- Working: [No]

```json
{
  "expected_receive_period_in_days": "1",
  "max_events": "72",
  "keep": "newest",
  "max_emitted_events": "1"
}
```

**Comment by tassoman** [comment]
I forced running the job _Rss1_, by selecting _Run now_.  There was a new item into RSS feed. Why didn't discovered itself?
The Rss1 job now it's **queued**, looks like stuck. Wasn't passed to 2nd Agent _Rss Queue_
I tried to find `propagate immediately` parameter but I didn't found it. I bet it's propagated instantly (type: Rss Agent).
I waited for 1 hour but message isn't queued at all. (type: Delay Agent) Didn't received.
Any idea how do I debug the Agents chain? :thinking:

**Comment by virtadpt** [comment]
> I'm unaware how to avoid spamposting many events in a one-shot. My goal is to consume the event queue once, hourly.

You could use a Delay Agent to prevent this.

**Comment by tassoman** [comment]
The problem here is `type:RssAgent` don't fires any event. It's still stuck into queued state:

![immagine](https://user-images.githubusercontent.com/92727/216831876-346223b2-9f9c-4ddb-bd3d-ffc87e7ec944.png)

I've tried following [Wiki's Rss+Email example](https://github.com/huginn/huginn/wiki/Flyertalk-RSS-to-Email-Scenario). But something it's sleeping :zzz:

**Comment by virtadpt** [comment]
Your Docker logs seem to have it all right there - schedule.rb was killed inside the container.  Troubleshoot that and, if it doesn't solve it all, it'll get you most of the way there.

**Comment by tassoman** [comment]
My database was messed up. So I erased it to restart again from scratch. Now working as expected, thanks!
