### ISSUE TITLE
Upgrade Ubuntu 18.04 to a newer LTS release

### ISSUE THREAD

**Issue by knu** [huginn/huginn#3239]
We've been testing Huginn with Ubuntu 20.04 in CI, Ubuntu 22.04 is already great for general use, 24.04 is drawing near, and 18.04 will reach its end of standard support soon.
https://wiki.ubuntu.com/Releases

**Comment by ohingardail** [comment]
This issue has already been raised in #3149 (in July 2022).

**Comment by knu** [comment]
We have migrated to Ubuntu 22.04 (jammy).

**Comment by virtadpt** [comment]
Did you do a distro upgrade, or a lift-and-shift into a new system?

What all went into it?  Did you run into any gotchas (like the MySQL/SSL problem that caught a lot of us)?  Workarounds?

**Comment by dsander** [comment]
I think this was only about the docker images. We have kind of nasty hack in place to keep compatibility with mysql versions of the `huginn/huginn` image https://github.com/huginn/huginn/pull/3216/commits/aaf6e357dec6ab9eca845f56eebb755bb4c9db27. When installed on the host directly I don't think anything but the ruby version and the binary/library dependencies we have matters.
