### ISSUE TITLE
Why postAgent ran without any event in

### ISSUE THREAD

**Issue by auningzzz** [huginn/huginn#3245]
I has a postAgent **Schedule 6am**, my configuration items are as follows:

```json
{
  "post_url": "xxxx",
  "expected_receive_period_in_days": "10",
  "content_type": "json",
  "method": "post",
  "payload": {
    "msgtype": "markdown",
    "markdown": {
      "content": "# {{ title }}{% line_break %}{{ content }}"
    }
  },
  "headers": {},
  "emit_events": "false",
  "no_merge": "false",
  "output_mode": "clean"
}
```

I set up a Sources for this postAgent, which does not have event emited every day, so sometimes the payload will be empty, but the agent will run.

what's wrong with my configuration?

**Comment by Unending** [comment]
Don't schedule the agent if you don't want it to run by itself on that schedule. The postagent will run when it receives the event from the source-agent.
