### ISSUE TITLE
Emit events at a random interval?

### ISSUE THREAD

**Issue by MysticalMusings** [huginn/huginn#3260]
Is it possible to emit events at a random interval to avoid having ip banned? 
I have tried Delay Agent but still got banned by the website. And it seems Javascript Agent can't do something like this:
```js
Agent.receive = function() {
  var events = this.incomingEvents();
  for(var i = 0; i < events.length; i++) {
    var delay = Math.random() * 5000;
    setTimeout(function(){
      this.createEvent(events[i].payload);
    }, delay);
  }
}
```
And got an error:
```
JavaScript error: ReferenceError: setTimeout is not defined
```

**Comment by gingerbeardman** [comment]
Is it definitely the quantity of events in a short space of time? Not the User Agent text or anything like that?

You might try enabling the Shell agent and using shell command `sleep` to do the pause.

**Comment by MysticalMusings** [comment]
> Is it definitely the quantity of events in a short space of time? Not the User Agent text or anything like that?
> 
> You might try enabling the Shell Agent and using shell command `sleep` to do the pause.

Thank you for your replying. 

Actually I wanna have an agent like a gateway or something like that, to decide when to emit **every** incoming event. 

But I find such fine-grained controlling may not be necessary. DelayAgent is good enough.
