### ISSUE TITLE
Issue with a WebsiteAgent

### ISSUE THREAD

**Issue by rc042** [huginn/huginn#3270]
Hi!

I use Huginn on Docker with `docker-compose` (latest version). It works fine however, I meet a strange issue.

I have the following website agent configured:

```
{
  "expected_update_period_in_days": "2",
  "url": "https://www.enforcementtracker.com/data.json",
  "type": "json",
  "mode": "on_change",
  "extract": {
    "description": {
      "path": ".data[*]"
    }
  }
}
```

Dry-run works fine in editing mode but does NOT work outside the edition of the script...

If I launch manually a `run` or a `dry-run`, it processes for a long time then I have a popup saying: `error:`.

I don't find anything useful in the Docker's logs:

```
web_1        | I, [2023-05-31T19:10:06.132145 #632]  INFO -- : [371b] Started POST "/agents/61/dry_runs" for AA.BB.CC.DD at 2023-05-31 19:10:06 +0200
web_1        | I, [2023-05-31T19:10:06.132764 #632]  INFO -- : [371b] Processing by Agents::DryRunsController#create as HTML
web_1        | I, [2023-05-31T19:10:06.132791 #632]  INFO -- : [371b]   Parameters: {"agent_id"=>"61"}
web_1        | AA.BB.CC.DD - - [31/May/2023:19:10:06 +0200] "GET /worker_status?since_id=26323 HTTP/1.1" 200 - 0.1320
[...]
web_1        | AA.BB.CC.DD - - [31/May/2023:19:11:05 +0200] "GET /worker_status?since_id=26323 HTTP/1.1" 200 - 0.0085
web_1        | I, [2023-05-31T19:11:06.135930 #637]  INFO -- : [9e58] Started GET "/50x.html" for AA.BB.CC.DD at 2023-05-31 19:11:06 +0200
web_1        | F, [2023-05-31T19:11:06.136859 #637] FATAL -- : [9e58]
web_1        | [9e58] ActionController::RoutingError (No route matches [GET] "/50x.html"):
web_1        | [9e58]
web_1        | [9e58] config/initializers/silence_worker_status_logger.rb:3:in `call'
web_1        | AA.BB.CC.DD - - [31/May/2023:19:11:06 +0200] "GET /404 HTTP/1.1" 404 728 0.0031
```

Maybe there is a limitation about the size of the file but I don't know where to configure it to try...

Any advise is apreciated!

Thanks,
R.

**Comment by Plausible0Bug** [comment]
Worked for me.

```
{
  "expected_update_period_in_days": "2",
  "url": "https://www.enforcementtracker.com/data.json",
  "type": "json",
  "mode": "on_change",
  "extract": {
    "description": {
      "path": "data[*]"
    }
  }
}
```
May be switch from `mode: on_change` to `mode: all` to avoid in memory dedup.

**Comment by rc042** [comment]
Hello @Plausible0Bug! You're right, it works if I change `mode: on_change` to `mode: all`, thanks a lot!

Did you have the same issue with `mode: on_change`?

Thank again!

**Comment by Plausible0Bug** [comment]
No.
But my machine has 3-digits number of cores with multi-terabytes memory, it is not some typical setup you see around.
Dedup is resource hungry, it is a known problem.

**Comment by rc042** [comment]
Thanks! My server is not so bad but far away from yours! I close the issue as it's a known issue. Thanks again

**Comment by rc042** [comment]
> Thanks! My server is not so bad but far away from yours! I close the issue as it's a known issue. Thanks again

Closed!
