### ISSUE TITLE
Get Image Using Website Agent

### ISSUE THREAD

**Issue by mcanady** [huginn/huginn#3275]
Hi--I'm trying to extract the first image URL for each item in this feed below using Website Agent.

RSS Feed:
https://www.prnewswire.com/rss/health-latest-news/health-latest-news-list.rss

 The image URL is in "item media:content" but I've tried ~20 different coding options and I can't figure it out. Posting an example of what I've tried doesn't seem like it would help as I feel I'm not even close to getting it. Yes, I've seen the Huginn agent examples pages and done google searches, tried Selector Gadget (doesn't work on XML?) and even tried to generate Xpath. 

If you're wondering why I'm not using an RSSAgent for this RSS feed, it's because I couldn't use RSSAgent due to the fact that I need to filter out non-English entries. I can't remember exactly why exactly, note that I also have limited coding skills.

HELP ME Huginn Wan Kenobi, e.g. @cantino ! Happy to donate to your efforts for this vital service, just tell me how!

Mary

**Comment by Plausible0Bug** [comment]
```
//item//*[name()="media:content"]/@url
```
I suggest you ask this question in a different community specialized in XPath query next time.

**Comment by mcanady** [comment]
Thanks, however I can't get this to work--I tried pasting it into both Huginn views, using "toggle view." I really don't know Xpath at all, so if someone can give more explicit instructions, I'd appreciate it.

**Comment by Plausible0Bug** [comment]
Pick a website agent, configure it as following:
```
{
  "expected_update_period_in_days": "2",
  "url": "https://www.prnewswire.com/rss/health-latest-news/health-latest-news-list.rss",
  "type": "html",
  "mode": "on_change",
  "extract": {
    "images": {
      "css": "//item//*[name()=\"media:content\"]",
      "value": "@url"
    }
  }
}
```
![test](https://github.com/huginn/huginn/assets/46285962/4e5c8c76-18bd-468d-93b2-4ceacbfab257)
![test2](https://github.com/huginn/huginn/assets/46285962/090219b3-962e-44d7-aefd-a4347f5d29e9)

Good luck.

**Comment by mcanady** [comment]
Thanks @Plausible0Bug ! I believe that this outputs every image on the page for all items, however. How do I change it so it only outputs one image per item?

**Comment by mcanady** [comment]
Hi @Plausible0Bug thank you so much!

When you run it, however, it gives an error that is something like "mismatch of number of items." I can send it if you'd like, let me know. I decided to instead run the feed through Inoreader, which exports the first image as an enclosure, which I can then work with.

Thanks again!

**Comment by Plausible0Bug** [comment]
You have other selectors capturing other elements and since the number of outputs is different across different selectors huginn cannot match them 1:1 .
For example of you try to capture title as well as images, given some items don't have image, the number of titles captured will be more than number of images captured.
The fix would be setting `array: true` for the selectors.

**Comment by mcanady** [comment]
Thanks @Plausible0Bug !
