### ISSUE TITLE
It's possible split string from credentials?

### ISSUE THREAD

**Issue by dimio** [huginn/huginn#3296]
Hello!
I need to to get one (random) value from credentials string (stored as `my_string`), like this: "a,b".
This liquid is work (I test it via _ManualEventAgent_):
```
{
  "message": "{% assign msg = 'a,b' %} {{ msg | split: ',' | size }}"
}
```
or
```
{
  "message": "{% assign msg = 'a,b' | split: ',' | size %} {{ msg }}"
}
```
returns a right result: `{"message":"2"}`
But that's doesn't work for credentials string:
```
{
  "message": "{% assign crd = credential my_string %}{{ crd | split: ',' | size }}"
}
```
or
```
{
  "message": "{% credential my_string | split: ',' | size %}"
}
```
this produce zero `{"message":"0"}`

Assignment not work for credentials?
```
{
  "message": "{% assign crd = credential gpt_authors %}{{ crd | as_object }}"
}
```
returns a `{"message":null}`

Any ideas - how can i get this? Maybe i need use a JS credentials?
Thnx for you help and sorry for my google translate.

**Comment by knu** [comment]
I think you can use the capture tag for that: https://shopify.github.io/liquid/tags/variable/#capture

```liquid
{% capture csv %}{% credential my_string %}{% endcapture -%}
{% assign values = csv | split: "," -%}
{{ values[0] }} and {{ values[1] -}}
```

This will give you `a and b`.

**Comment by dimio** [comment]
Thanks a lot for your help, it works!
