### ISSUE TITLE
New to Huginn help me with this. How to get Huginn to work with Reddit Search

### ISSUE THREAD

**Issue by weir1** [huginn/huginn#3304]
I am searching for new remote job in reddit with this URL
https://www.reddit.com/search/?q=remotejob&sort=new.json

but I am getting html file
normal sub reddit working fine
but not search term.
How to solve this?

**Comment by virtadpt** [comment]
Or, it looks like there was a typo in the URL you were using.  Try this: https://www.reddit.com/search.json?q=remotejob&sort=new

**Comment by weir1** [comment]
Wonderful, Thanks
