### ISSUE TITLE
How to make the LocalFileAgent working?

### ISSUE THREAD

**Issue by tortoo** [huginn/huginn#3322]
I've set  `ENABLE_INSECURE_AGENTS` to true in .env file. After restarting huginn the warning on LocalFileAgent's right side changed to **currently enabled**. But the working state is always **NO**! What else do I need to do?

```
Type: Local File Agent

Schedule: Every 1m

Last checked: <1m ago

Last received event: 1d ago

Events created: [0]

Event sources: [test1](URL1)

Propagate immediately: Yes

Event receivers: [test2](URL2)

Working: [No]

Options:

{
  "mode": "read",
  "watch": "true",
  "path": "/root/abc/test.txt",
  "append_radio": "false",
  "append": "false",
  "data": "{{ data }}"
}
```

**Comment by virtadpt** [comment]
When you say you restarted Huginn, what do you mean?  What, exactly, did you restart?

What's on the agent's Logs tab?

Did it emit any events?

**Comment by tortoo** [comment]
Sorry after I changed path to` ~/test.txt` it worked. It seems that the files can only be placed in the **app** directory of huginn. Thank u very much!
