### ISSUE TITLE
How to convert Unix timestamp 

### ISSUE THREAD

**Issue by coolbele** [huginn/huginn#3329]
I need to convert 1697946296756 of the original website to 2023-10-22 11:44:56,How to operate.

**Comment by Petemir** [comment]
You could use the [javascript agent](https://github.com/huginn/huginn/wiki/Agent-Types-&-Descriptions#javascript-agent) and use [some code from here](https://www.influxdata.com/blog/how-get-convert-format-javascript-date-timestamp/)

**Comment by Unending** [comment]
This is natively supported in [Liquid](https://github.com/huginn/huginn/wiki/Formatting-Events-using-Liquid): `{{ "1697946296" | date: "%Y-%m-%d %H:%M:%S" }}`
If you're using milliseconds, divide by 1000 first: `{{ "1697946296756" | divided_by: "1000" | date: "%Y-%m-%d %H:%M:%S" }}`

**Comment by coolbele** [comment]
> [Liquid](https://github.com/huginn/huginn/wiki/Formatting-Events-using-Liquid)本身支持这一点：`{{ "1697946296" | date: "%Y-%m-%d %H:%M:%S" }}` 如果您使用毫秒，请先除以 1000：`{{ "1697946296756" | divided_by: "1000" | date: "%Y-%m-%d %H:%M:%S" }}`

Thank you very much, it was useful

**Comment by jjeffers** [comment]
Closing as the question was answered.
