### ISSUE TITLE
Is Huginn dead project?

### ISSUE THREAD

**Issue by sandipp** [huginn/huginn#3332]
There's been no active development since June and unanswered open issues. Is this project dead? Not maintained? Are there any better alternatives for this?

**Comment by virtadpt** [comment]
No active development since July of 2023.  And the project is not dead.  We're all busy doing our day job type stuff, trying to learn Ruby (or at least I am), and are using Huginn as part of our everyday lives.  Is there anything in particular that you have in mind?

**Comment by Plausible0Bug** [comment]
The latest `ghcr.io/huginn/huginn` image was built 2 weeks ago so no.

**Comment by jjeffers** [comment]
Closing this issue as the question was answered.
