### ISSUE TITLE
Multiple RAW files with dcraw don't work

### ISSUE THREAD

**Issue by schabau** [huginn/huginn#3342]
Hello,

I've had good results with JPEG files using Hugin and wanted to try RAW files.
Since it is sufficient and you don't need any major software, I wanted to use dcraw. But I have a problem when I select several files at once as recommended.
The first file is processed and then the import stops. If I interpret it correctly, there is probably a problem with the white-balance reference where, I think, not all the data is passed to the next pass.
```
Prozessiere: C:\Program Files\Hugin\bin\dcraw.exe  -w -v -4 -T "D:\test\test\IMG_0005.CR2"
Loading Canon EOS 1300D image from D:\test\test\IMG_0005.CR2 ...
Scaling with darkness 2048, saturation 13584, and
multipliers 2.089844 1.000000 1.419922 1.000000
AHD interpolation...
Converting to sRGB colorspace...
Writing data to D:\test\test\IMG_0005.tiff ...
Aktualisiere EXIF-Daten der Datei D:\test\test\IMG_0005.tiff
    1 image files updated

Vorgang dauerte 3 s
Prozessiere: C:\Program Files\Hugin\bin\dcraw.exe -r 2.089844 1.000000  -v -4 -T "D:\test\test\IMG_0006.CR2"
Non-numeric argument to "-r"

Vorgang dauerte 0 s
```
From here nothing happens anymore. You can only cancel the import.
If you import one file at a time, as is not recommended, there are no problems.

Best regards
schabau

**Comment by virtadpt** [comment]
I don't think this is the software you're thinking of.

**Comment by jjeffers** [comment]
Perhaps this is the project @schabau has in mind? https://hugin.sourceforge.io/
