### ISSUE TITLE
Can the Post Agent emit event only when changed?

### ISSUE THREAD

**Issue by JayJayBinks** [huginn/huginn#3347]
I am performing a search on a server which is available via post method, but am only interested in a new event if the response has changed from the previous one.
I would like something like the Website Agent with on_change.
Can it be configured somehow?

**Comment by virtadpt** [comment]
That's a good question.  I'm not sure.  It might require the use of a DeDuplication Agent downstream.

**Comment by JayJayBinks** [comment]
Thanks for the answer!. So far i was just looking at the events tab because i had only events i am interested in.
I think now when there are also events i am not interested in,  i will use the Pushover Agent to just inform me about the imprtant events
