### ISSUE TITLE
DataOutput Agent ... Output feed lifetime / timeout?

### ISSUE THREAD

**Issue by radry** [huginn/huginn#3358]
I couldn't find any answer in previous issues (which is odd) or way to configure this.

After a while the feed of the dataoutput agent becomes emtpy (no items), although no new events were sent to it.

The dataoutput agent always updates its feed when it receives new events, which is correct. But something is causing the agent to "lose" all data after a certain time and the feed is empty (no items present) 

Why and how can this be disabled? I want the data to live until it is refreshed by new events and not have a timeout.

**Comment by radry** [comment]
Oh ok. Does the DataOutput Agent have a internal trigger/schedule where it looks up the upstream agent? How does it know these Events were deleted? Because itself it doesn't store any events.

**Comment by Unending** [comment]
No, this is handled by the event propagation mechanism, which is once a minute unless you enable "Propagate immediately".

Unlike other agents that actually generate output (events, api calls, file writes, …) the Data Output Agent funnily doesn't actually output anything, it generates the content on the fly.

"Keep Events" refers to the events an agent outputs not that it receives, if no events are generated there's nothing to keep.
