### ISSUE TITLE
Post Agent not working

### ISSUE THREAD

**Issue by GGn0** [huginn/huginn#3366]
Hi
First of all, love the project!

I have a problem using a post agent together with a self-hosted instance of browserless
Both hughinn and browserless run as docker containers on the same machine

The post requests towards browserless only fail if coming from huginn's post agent

Basically it seems that the post agent adds an `&launch={}` parameter at the end of the post string

I can show the difference between a successful request made from curl and the same request using the post agent

*curl post request*
~~~sh
curl -X POST http://LOCAL_BL_ADDRESS/content?token=MY_TOKEN \
 -H 'Content-Type: application/json' \
 -d '{
  "url": "https://www.google.com"
}'
~~~

*post agent code*
~~~json
{
  "post_url": "http://LOCAL_BL_ADDRESS/content?token=MY_TOKEN",
  "content_type": "json",
  "method": "put",
  "payload": {
    "url": "https://www.google.com"
  },
  "headers": {},
  "emit_events": "true",
  "parse_body": "false",
  "no_merge": "true",
  "output_mode": "clean"
}
~~~

These are the results in the browserless log:

![docker_log](https://github.com/huginn/huginn/assets/44038661/90b11a77-5e16-48bc-aaf0-3f1a544d8306)
`1` is the failed request with huginn
`2` is the successful request with curl

The expected result would be to have the post string without `&launch{}` at the end
Thanks

> [!NOTE]
> Both `LOCAL_BL_ADDRESS` and `MY_TOKEN` are written in clear in the code. I just redacted them

EDIT:
The picture reads `put` instead of `post` as method, the error is the same using `post`

**Comment by Galaxyor** [comment]
I just ran into this issue, and I was able to fix it by using the following workaround: https://github.com/huginn/huginn/issues/2248#issuecomment-376879963.

For reference, this is my postAgent code: 
```json
{
  "post_url": "http://LOCAL_BL_ADDRESS/content",
  "content_type": "application/json",
  "method": "post",
  "payload": "{\"url\":  \"https://www.google.com\"}",
  "headers": {},
  "emit_events":  "true",
  "parse_body": "false",
  "no_merge": "true",
  "output_mode": "clean",
}
```

**Comment by GGn0** [comment]
I tried with that solution, but I received this error in huginn

> [!CAUTION]
> 1 error prohibited this Agent from being saved:
> - if provided, payload must be a hash or an array

I just wrapped the payload string with [ ]
```json
{

    "payload": [
    "{\"url\": \"https://www.google.com\"}"
  ],

}
```

That said
The problem is still there
The post request is sent to http://LOCAL_BL_ADDRESS/content?token=MY_TOKEN<b>&launch={}</b> instead of http://LOCAL_BL_ADDRESS/content?token=MY_TOKEN

**Comment by Galaxyor** [comment]
I got the same error when I used `json` as a content type instead of `application/json`. Have you tried with the following content type ?
```json
{
    "content_type": "application/json",
}
```
In my case, this also fixes the problem with the post request.

**Comment by GGn0** [comment]
Wow I completely missed it, now it works!!

So for future reference, it is necessary to use ***both***
```json
{

    "content_type": "application/json"
    "payload":  "{\"url\": \"https://www.google.com\"}"

}
```
using `"content_type": "json"` doesn't allow to fill the payload with just a string and causes `&launch={}` to pop up

Thanks @Galaxyor!
