### ISSUE TITLE
Ability to remotely see or be notified when jobs are stacking up because of a blockage

### ISSUE THREAD

**Issue by gingerbeardman** [huginn/huginn#3368]
Pretty much once a month my Huginn install jams.

It would be great if there was a way to remotely detect this sort of backlog of jobs.

**Comment by Unending** [comment]
You could create a "heartbeat agent" which pings a monitoring service like [healthchecks.io](https://healthchecks.io) and have it notify you when it hasn't received anything for a set amount of time. This is what I did when I used to have issues whit the queue getting stuck years ago.

You could also try to monitor huginn itself, but the API is undocumented so that would be a lot more work.

**Comment by gingerbeardman** [comment]
Heartbeat sounds ideal

**Comment by gingerbeardman** [comment]
@Unending that worked a treat! thanks again.

here is my final recipe:

1. [healthchecks.io](https://healthchecks.io/) URL
1. huginn scenario with Website Agent set to request the above URL
1. [healthchecks.io](https://healthchecks.io/) Status Badge URL (JSON format)
1. [uptimerobot.com](uptimerobot.com) Keyword monitor to Status Badge URL (check for keyword "up", start incident when not found)

Tada!

**Comment by Unending** [comment]
Why not have healthchecks.io notify you itself? Or ping uptimerobot directly? Seems a roundabout way to do this, but hey, if it works it works.

I haven't used it in years but I used to selfhost healthcheck and used the post agent to send a request, healthchecks would send notifications via pushover.

In any case, happy to help.

**Comment by gingerbeardman** [comment]
healthchecks.io can send email (works) or SMS (I never received it).

...but I prefer all my server/service status notifications to come the same way (uptime robot)

This was the way that the healthcheck creator recommended, if there's a simpler way to hook it to uptimerobot do let me know.

**Comment by Unending** [comment]
Fair enough.

I haven't used uptimerobot but they seem to offer the same cron job / heartbeat monitoring functionality. Ping uptimerobot directly from huginn, skipping healthchecks.io entirely. Check [Our complete cron job guide for 2024](https://uptimerobot.com/blog/cron-job-guide/) (scroll down to "Step-by-step Cron job monitoring with UptimeRobot").

**Comment by gingerbeardman** [comment]
thanks, that's cool! I'll try it out.
