### ISSUE TITLE
diagrams not working

### ISSUE THREAD

**Issue by level20peon** [huginn/huginn#3373]
I just checked out a completely fresh copy of the current Huginn master and also installed/compiled everything (gems/assets) from scratch (using rvm to install ruby 3.2.2). Unfortunately, diagrams aren't currently rendering on this system:

![image](https://github.com/huginn/huginn/assets/14050847/5fd92c87-a80f-497b-886a-e095fc2e229e)

I am using unicorn, and the logs indicate that it actually rendered the diagram, so I am not sure where the 404 is coming from:

```
I, [2024-04-26T11:33:29.850370 #2232350]  INFO -- : [8094cff4-d94a-4464-8c13-bc33c276cc7c] Started GET "/scenarios/42/diagram" for x.x.x.x at 2024-04-26 11:33:29 +0200
I, [2024-04-26T11:33:29.851895 #2232350]  INFO -- : [8094cff4-d94a-4464-8c13-bc33c276cc7c] Processing by DiagramsController#show as HTML
I, [2024-04-26T11:33:29.852036 #2232350]  INFO -- : [8094cff4-d94a-4464-8c13-bc33c276cc7c]   Parameters: {"scenario_id"=>"42"}
I, [2024-04-26T11:33:30.283115 #2232350]  INFO -- : [8094cff4-d94a-4464-8c13-bc33c276cc7c]   Rendered diagrams/show.html.erb within layouts/application (Duration: 419.9ms | Allocations: 32237)
I, [2024-04-26T11:33:30.295020 #2232350]  INFO -- : [8094cff4-d94a-4464-8c13-bc33c276cc7c]   Rendered layout layouts/application.html.erb (Duration: 431.8ms | Allocations: 51930)
I, [2024-04-26T11:33:30.295243 #2232350]  INFO -- : [8094cff4-d94a-4464-8c13-bc33c276cc7c] Completed 200 OK in 443ms (Views: 424.4ms | ActiveRecord: 11.4ms | Allocations: 53240)
x.x.x.x - - [26/Apr/2024:11:33:30 +0200] "GET /scenarios/42/diagram HTTP/1.1" 200 - 0.4490
```

Any pointers?

PS: bare metal, debian bookworm, anything else?

**Comment by haileyambition** [comment]
that api is discontinued install graphviz locally and use that instead

**Comment by level20peon** [comment]
All I could find about graphviz in the Huginn repository was pointing to a .env setting called `USE_GRAPHVIZ_DOT`. However, there's no explanation about graphviz nor any installation requirement for graphviz in the Wiki.

So, could you elaborate on how to render the graphs based on your approach?

**Comment by virtadpt** [comment]
`sudo apt-get install graphviz` is what I used.

**Comment by kg333** [comment]
To elaborate on the full solution:
1. Install `graphviz` as @virtadpt describes
2. Find the path of `dot` from `graphviz` using `which dot`.  Mine was `/usr/bin/dot`.
3. Update the `.env` in your Huginn install to point at that path by uncommenting and changing this line: `USE_GRAPHVIZ_DOT=/usr/bin/dot`
4. Restart Huginn.

Propagation graph no longer returns a 404 and now correctly draws for me.

**Comment by level20peon** [comment]
> To elaborate on the full solution:

Perfect, thank you!
