### ISSUE TITLE
Add support for monospace font in PUSHOVER

### ISSUE THREAD

**Issue by carmatana** [huginn/huginn#3388]
Pushover can present messages in either html or monospace font

Seems that huginn only supports the html option

Please add support to have also the monospace font option

It is very useful when sending messages that have columns, they are visualized better, like stocks and their prices

According to the below reference, pushover should receive "monospace = 1" to activate this, I added this option to my pushover agent but seems that Huginn is not passing it to the Pushover API

Reference: https://pushover.net/api#html

Thank you very much for your attention !

**Comment by knu** [comment]
Good call, I was thinking of that.

**Comment by carmatana** [comment]
@knu 

thanks !
