### ISSUE TITLE
How does Sentiment Agent work, exactly?

### ISSUE THREAD

**Issue by virtadpt** [huginn/huginn#3412]
I'm scanning through the code for sentiment_agent.rb because I was trying to figure out what NLP gem was used to implement sentiment analysis, but it only seems to reference huginn/data/anew.csv.

Where did that come from, exactly?  Is there a column schema for it?  Column 0 is pretty easy to suss out (it's just a word) but the numerical values are opaque.

**Comment by Unending** [comment]
The good old days of doing thing by hand: [Affective Norms for English Words (ANEW):
Instruction Manual and Affective Ratings](https://pdodds.w3.uvm.edu/teaching/courses/2009-08UVM-300/docs/others/everything/bradley1999a.pdf)

**Comment by virtadpt** [comment]
I did not know about this!  Thank you so much!
