### ISSUE TITLE
Can WebsiteAgent's change detection ignore certain keys in json?

### ISSUE THREAD

**Issue by tempppabx1** [huginn/huginn#3436]
I'm using Website Agent to monitor changes in the json and create rough events for the new content, which are then sent to a downstream agent for next processing. In the normal case this works well

original json:
```json
[{
        "sub_time": 123,
        "sub_user": "xxx",
        "content_node": {
            "text": ".....",
            "video": {
                "play": 123123
            }
            ...
        }
    },
    {
        "sub_time": 456,
        "sub_user": "xxx",
        "content_node": {
            "text": ".....",
            ...
        }
    },
    ...]
```
events extracted:
`{ "sub_time": "123", "content":{ content_node... } }`
`{ "sub_time": "456", "content":{ content_node... } }`
However, in some content, there are nested values that change frequently. For example, in the following json, the value of "play" changes often, which causes WebsiteAgent to create a new event each time it changes. This results in duplicate events for the same content.
```json
"video": {
    "play": 123456
}
```
I’ve tried using special JSONPath filtering syntax or set hidden to `true`  filter out these changes, but it doesn’t seem to be effective.

Since I'm not very familiar with Agent, is there a better solution, thanks!

**Comment by virtadpt** [comment]
You might not want to use the Website Agent for change detection for this very reason.  Maybe run the events output through an Attribute Difference Agent or a Change Detector Agent and have it look for the different values.

**Comment by virtadpt** [comment]
The only thing you would have to pass to a Change Detector Agent would be a JSONpath to the value you're interested in.  It would look something like this:

```
{
    "property": "{{ $.*.*.video.play }}",
    "expected_update_period_in_days": 31
}
```

I had to fix up your sample event so that it looked like this so I could mess around with it.  I hope it's illustrative of the real thing:

```
[
    {
        "sub_time": 123,
        "sub_user": "xxx",
        "content_node": {
            "text": ".....",
            "video": {
                "play": 123123
            }
        }
    },
    {
        "sub_time": 456,
        "sub_user": "xxx",
        "content_node": {
            "text": ".....",
            "video": {
                "play": 234234
            }
        }
    }
]
```

JS Agent would definitely do it.
