### ISSUE TITLE
"Encryption not available on this event-machine"

### ISSUE THREAD

**Issue by craigmayhew** [huginn/huginn#386]
After setting up a twitter oauth agent, the huginn process terminated and now won't start.

It gives the error:

~/huginn$ foreman start
18:53:01 web.1  | started with pid 23945
18:53:01 jobs.1  | started with pid 23947
18:54:45 web.1  | [2014-06-20 18:54:45] INFO  WEBrick 1.3.1
18:54:45 web.1  | [2014-06-20 18:54:45] INFO  ruby 1.9.3 (2013-11-22) [x86_64-linux]
18:54:45 web.1  | [2014-06-20 18:54:45] INFO  WEBrick::HTTPServer#start: pid=23950 port=3000
18:54:47 jobs.1 | Found 1 agent(s).  Loading them now...
18:54:47 jobs.1 | terminate called after throwing an instance of 'std::runtime_error'
18:54:47 jobs.1 | what():  Encryption not available on this event-machine
18:54:48 jobs.1 | Aborted (core dumped)
18:54:48 jobs.1 | exited with code 134
18:54:48 system | sending SIGTERM to all processes
18:54:48 web.1  | terminated by SIGTERM

I've had a google but this isn't obvious to me, has anyone had a similar issue?

**Comment by jonaslejon** [comment]
I'm having the same problem. But getting the following error:

$ bundle exec foreman start
Could not find http-0.6.4 in any of the sources
Run `bundle install` to install missing gems.

**Comment by cantino** [comment]
What happens when you run `bundle install`?

**Comment by jonaslejon** [comment]
Thanks for replying @cantino 

$ sudo apt-get install libssl-dev

Solved the problem. I also needed to reinstall the gems

**Comment by cantino** [comment]
Glad to hear it's working!

**Comment by rjhornsby** [comment]
+1. Installing libssl-dev and reinstalling/rebuilding eventmachine gem worked perfectly to resolve same issue using TweetStream gem. Thanks @cantino @craigmayhew

**Comment by Kavi6** [comment]
i am a windows user..what have to be done to get fix this issue?

**Comment by cantino** [comment]
We recommend using VirtualBox with Linux if you're on Windows.

**Comment by cfmartinez83** [comment]
thank youu!! it works 
sudo gem install eventmachine
