### ISSUE TITLE
Secret (Consumer) Agent

### ISSUE THREAD

**Issue by harayz** [huginn/huginn#415]
Purpose: 
To monitor the price of goods & services.

Problem: 
Business owners sometimes colluded to jack up the prices by creating artificial shortage - usually seasonal during festivities ie: turkey price during thanksgiving (US). This is an illegal practice and this agent can help the consumer watch groups do their job. 

Positive:
Can also be used to watch websites like ebay, craigslist or amazon for specific items based on predefined keywords that are within a specified price range. This can improve the chances for finding an extremely peculiar items within reasonable price without spending much time looking for it.

**Comment by blackberryoctopus** [comment]
@snicker 
What query frequency do you use with your CL agent?
