### ISSUE TITLE
Question about extraction matching with website agent

### ISSUE THREAD

**Issue by bwaltz** [huginn/huginn#469]
I am reading from an rss feed that has has news stories in it and trying to map the contents to another wordpress site. Some news items have images attached and some do not. Is there a way with the website agent to match the image content when possible and not have an uneven number of matches?

I guess some sort of conditional would solve the problem, such as save the element text if found, if not, save ' ' or null.

**Comment by eugenesvk** [comment]
Thanks a bunch, @knu! Was very valuable for me to fix an error with my podcast importing by separating podcast title from podcast item titles!
Just a minor typo in your instructions - the closing parenthesis is missing in the **starts-with** function
