### ISSUE TITLE
Finally huginn runs on my Raspberry but with rufus-scheduler intercepted error 

### ISSUE THREAD

**Issue by othreed** [huginn/huginn#534]
Hi,
Huginn ( many_gems_are_optional) runs in Production and Development mode on Raspbian.
It is very slow .. but that is ok for me now.
The XKCD Source / Website Agent is working but the jobs.1 log show the same error in Production or development 
I found some information on the net about a similar error here 
https://www.bountysource.com/issues/1118774-probable-bug-in-bin-schedule-rb-with-rufus-scheduler-3-0-0
Is this related?

> 21:14:56 jobs.1 | { 31558272 rufus-scheduler intercepted an error:
> 21:14:56 jobs.1 |   31558272   job:
> 21:14:56 jobs.1 |   31558272     Rufus::Scheduler::EveryJob "1m" {}
> 21:14:56 jobs.1 |   31558272   error:
> 21:14:56 jobs.1 |   31558272     31558272
> 21:14:56 jobs.1 |   31558272     ActiveRecord::ConnectionTimeoutError
> 21:14:56 jobs.1 |   31558272     could not obtain a database connection within 5.000 seconds (waited 5.927 seconds)
> 21:14:56 jobs.1 |   31558272       /var/lib/gems/1.9.1/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:190:in `block in wait_poll'
> 21:14:56 jobs.1 |   31558272       /var/lib/gems/1.9.1/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in`loop'
> 21:14:56 jobs.1 |   31558272       /var/lib/gems/1.9.1/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in `wait_poll'
> 21:14:56 jobs.1 |   31558272       /var/lib/gems/1.9.1/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:136:in`block in poll'
> 21:14:56 jobs.1 |   31558272       /usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
> 21:14:56 jobs.1 |   31558272       /var/lib/gems/1.9.1/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:146:in`synchronize'
> 21:14:56 jobs.1 |   31558272       /var/lib/gems/1.9.1/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:134:in `poll'
> 21:14:56 jobs.1 |   31558272       /var/lib/gems/1.9.1/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:418:in`acquire_connection'
> 21:14:56 jobs.1 |   31558272       /var/lib/gems/1.9.1/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
> 21:14:56 jobs.1 |   31558272       /usr/lib/ruby/1.9.1/monitor.rb:211:in`mon_synchronize'
> 21:14:56 jobs.1 |   31558272       /var/lib/gems/1.9.1/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:350:in `checkout'
> 21:14:56 jobs.1 |   31558272       /var/lib/gems/1.9.1/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in`block in connection'
> 21:14:56 jobs.1 |   31558272       /usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
> 21:14:56 jobs.1 |   31558272       /var/lib/gems/1.9.1/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in`connection'
> 21:14:56 jobs.1 |   31558272       /var/lib/gems/1.9.1/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
> 21:14:56 jobs.1 |   31558272       /home/pi/huginn/lib/huginn_scheduler.rb:190:in`with_mutex'
> 21:14:56 jobs.1 |   31558272       /home/pi/huginn/lib/huginn_scheduler.rb:151:in `run_schedule'
> 21:14:56 jobs.1 |   31558272       /home/pi/huginn/lib/huginn_scheduler.rb:129:in`block (2 levels) in run!'
> 21:14:56 jobs.1 |   31558272       /var/lib/gems/1.9.1/gems/rufus-scheduler-3.0.8/lib/rufus/scheduler/jobs.rb:233:in `call'
> 21:14:56 jobs.1 |   31558272       /var/lib/gems/1.9.1/gems/rufus-scheduler-3.0.8/lib/rufus/scheduler/jobs.rb:233:in`do_call'
> 21:14:56 jobs.1 |   31558272       /var/lib/gems/1.9.1/gems/rufus-scheduler-3.0.8/lib/rufus/scheduler/jobs.rb:257:in `do_trigger'
> 21:14:56 jobs.1 |   31558272       /var/lib/gems/1.9.1/gems/rufus-scheduler-3.0.8/lib/rufus/scheduler/jobs.rb:299:in`block (3 levels) in start_work_thread'
> 21:14:56 jobs.1 |   31558272       /var/lib/gems/1.9.1/gems/rufus-scheduler-3.0.8/lib/rufus/scheduler/jobs.rb:298:in `call'
> 21:14:56 jobs.1 |   31558272       /var/lib/gems/1.9.1/gems/rufus-scheduler-3.0.8/lib/rufus/scheduler/jobs.rb:298:in`block (2 levels) in start_work_thread'
> 21:14:56 jobs.1 |   31558272       /var/lib/gems/1.9.1/gems/rufus-scheduler-3.0.8/lib/rufus/scheduler/jobs.rb:288:in `loop'
> 21:14:56 jobs.1 |   31558272       /var/lib/gems/1.9.1/gems/rufus-scheduler-3.0.8/lib/rufus/scheduler/jobs.rb:288:in`block in start_work_thread'
> 21:14:56 jobs.1 |   31558272   tz:
> 21:14:56 jobs.1 |   31558272     ENV['TZ']: 
> 21:14:56 jobs.1 |   31558272     Time.now: 2014-09-23 21:14:55 +0200
> 21:14:56 jobs.1 |   31558272   scheduler:
> 21:14:56 jobs.1 |   31558272     object_id: 32129544
> 21:14:56 jobs.1 |   31558272     opts:
> 21:14:56 jobs.1 |   31558272       {}
> 21:14:56 jobs.1 |   31558272       frequency: 0.3
> 21:14:56 jobs.1 |   31558272       lockfile: nil
> 21:14:56 jobs.1 |   31558272     uptime: 1636.016434907913 (27m16s17)
> 21:14:56 jobs.1 |   31558272     down?: false
> 21:14:56 jobs.1 |   31558272     threads: 8
> 21:14:56 jobs.1 |   31558272       thread: #Thread:0x3d46c28
> 21:14:56 jobs.1 |   31558272       thread_key: rufus_scheduler_32129544
> 21:14:56 jobs.1 |   31558272       work_threads: 7
> 21:14:56 jobs.1 |   31558272         active: 1
> 21:14:56 jobs.1 |   31558272         vacant: 6
> 21:14:56 jobs.1 |   31558272         max_work_threads: 28
> 21:14:56 jobs.1 |   31558272       mutexes: {}
> 21:14:56 jobs.1 |   31558272     jobs: 40
> 21:14:56 jobs.1 |   31558272       at_jobs: 0
> 21:14:56 jobs.1 |   31558272       in_jobs: 0
> 21:14:56 jobs.1 |   31558272       every_jobs: 15
> 21:14:56 jobs.1 |   31558272       interval_jobs: 0
> 21:14:56 jobs.1 |   31558272       cron_jobs: 25
> 21:14:56 jobs.1 |   31558272     running_jobs: 1
> 21:14:56 jobs.1 |   31558272     work_queue: 0
> 21:14:56 jobs.1 | } 31558272 .
> 21:15:01 jobs.1 | No agents found.  Will look again in a minute.

Thanks for any help : )

**Comment by mustang2015** [comment]
How did you get it working? I had a very hard time installing all the gems and such... always fail at socket not found

**Comment by othreed** [comment]
Hi,
i found these notes I took when I setup my Pi.

further down I have some settings for nginx etc.

I hope this might be useful

Since a year I did not really use the Pi anymore.

:)


*LoadModule passenger_module
/var/lib/gems/1.9.1/gems/passenger-4.0.50/buildout/apache2/mod_passenger.so*

*   <IfModule mod_passenger.c>*

*     PassengerRoot /var/lib/gems/1.9.1/gems/passenger-4.0.50*

*     PassengerDefaultRuby /usr/bin/ruby1.9.1*

*   </IfModule>*


* <VirtualHost *:80>*

*      ServerName www.yourhost.com <http://www.yourhost.com>*

*      # !!! Be sure to point DocumentRoot to 'public'!*

*      DocumentRoot /somewhere/public    *

*      <Directory /somewhere/public>*

*         # This relaxes Apache security settings.*

*         AllowOverride all*

*         # MultiViews must be turned off.*

*         Options -MultiViews*

*         # Uncomment this if you're on Apache >= 2.4:*

*         #Require all granted*

*      </Directory>*

*   </VirtualHost>*


____



sudo diskutil unmount /dev/disk2s1

sudo dd bs=1m if=raspi_20092014.img of=/dev/rdisk2


#backup

sudo dd if=/dev/rdisk2 of=huginn.img bs=1m


sudo diskutil unmount /dev/disk2s1


ssh into rpi

raspi-config


>password change

>expand sd

> memory split to 16


reboot


sudo vi /etc/dphys-swapfile

change SWAP from 100 to 512 MB

sudo dphys-swapfile setup

sudo dphys-swapfile swapon


reboot

sudo apt-get purge -y desktop-file-utils lxde-icon-theme gnome-themes*
x11-common libx11-.* xkb-data xdg-utils menu-xdg oracle-java.*
wolfram-engine squeak-vm sonic-pi pistore midori dillo penguinspuzzle
'raspberrypi-(artwork|doc)'  samba-common smbclient python-numpy
python-pygame python3-numpy liblapack3 libatlas3-base



 rm -rf Desktop/ python_games/ ocr_pi.png

  sudo rm -rf /usr/share/{icons,images}

  sudo apt-get --purge autoremove

  sudo apt-get update

  sudo apt-get upgrade

  sudo apt-get clean



ssh-keygen -t rsa -C pi@192.168.178.24

#copy id_rsa content and past into github>settings>ssh>keystone

vi id_rsa.pub


ssh -vT git@github.com

eval "$(ssh-agent -s)"

ssh-add ~/.ssh/id_rsa

ssh-add -l


sudo apt-get install -y gcc curl ruby ruby-dev rubygems ruby-shadow make
git libmysqlclient-dev build-essential libreadline6-dev git-core zlib1g
libssl-dev libxml2-dev libxslt-dev autoconf automake libtool bison
zlib1g-dev make git mysql-server rails nodejs nginx libffi-dev


# setup huginn_production Database

mysql -u root -p

CREATE DATABASE huginn_production;

quit


sudo cp /usr/share/doc/mysql-server-5.5/examples/my-small.cnf
/etc/mysql/my.cnf

sudo vi /etc/mysql/my.cnf

sudo service mysql restart


sudo gem install execjs rake bundle unicorn --no-ri --no-rdoc

# on your development machine in your huginn folder run


cap setup

bundle exec rake secret

pi@raspberrypi ~/app/shared/config $ vi .env

pi@raspberrypi ~/app/shared/config $ vi Procfile



cap deploy


mysqladmin -u root -p variables | grep socket

>> /var/run/mysqld/mysqld.sock



RAILS_ENV=production bundle exec rake db:seed


   38  git clone git://github.com/cantino/huginn.git

   39  sudo gem install rake bundle --no-ri --no-rdoc

   41  ls

   42  ls -la

   43  vi .gem/

   44  cd .gem/

   45  ls

   46  ls -la

   47  cd ..

   48  ls

   49  ls

   50  ls -la

51  ls

   52  echo "gem: --no-ri --no-rdoc" > ~/.gemrc

   53  ls

   54  cd huginn/

   55  ls

   56  cp .env.example .env

   57  rake secret

   58  bundle install

   59  ls

   60  sudo shutdown -h now

   61  sudo raspi-config

   62  logout

   63  lynx http://localhost:3000

     71  cd huginn/

   72  ls

   73  vi .env

   74  ls

   75  rake secret

   76  vi .env

   77  sudo apt-get install mysql-server

   78  ls

   79  sudo apt-get install lynx

   80  ls

   81  rake db:create

   82  rake db:migrate

   83  ls

   84  rake db:seed

   85  ls

   86  vi .env

   87  ls

   88  foreman start



sudo apt-get --purge remove apache2

sudo apt-get autoremove


apt-get --purge remove ^nginx

apt-get install nginx

-----


upstream huginn_app_server {

  server unix:/home/pi/app/shared/pids/unicorn.socket;


}


http {

  types_hash_max_size 2048;

  include    mime.types;


  upstream huginn_server {

    server unix:/home/huginn/shared/tmp/sockets/unicorn.sock;

  }


  server {

    listen 80;

    server_name 192.168.178.24;

    keepalive_timeout 5;

    root /home/pi/app/current/public;

    try_files $uri/index.html $uri.html $uri @app;

    error_page 500 502 503 504 /500.html;

    location = /500.html {

      root /home/pi/app/current/public;

    }

    location @app {

      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_set_header Host $http_host;

      proxy_redirect off;

      proxy_pass http://huginn_app_server;

    }

}







On Fri, Aug 21, 2015 at 11:54 PM, mustang2015 <notifications@github.com>
wrote:

> How did you get it working? I had a very hard time installing all the gems
> and such... always fail at socket not found
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cantino/huginn/issues/534#issuecomment-133574511>.
>



-- 
--------------------------------------------------------------
Mit freundlichen Grüßen aus Geestland,

Ole Heinzow, Octone e.K.
Ohldorpsweg 16
27607 Geestland
Deutschland

Telefon (mobile): +49(0)176 90729138
(erreichbar von Montag bis Samstag von 9 - 21 Uhr)
Web: www.octone.eu

Registergericht: Amtsgericht Tostedt
Handelsregister Registernummer: HRA 202888

Umsatzsteuer-Identifikationsnummer gemäß § 27a Umsatzsteuergesetz:
DE249614441
Inhaltlich Verantwortlicher gemäß § 55 Rundfunkstaatsvertrag: Ole Heinzow,
Ohldorpsweg 16, 27607 Geestland, Deutschland

Haftungshinweis: Trotz sorgfältiger inhaltlicher Kontrolle übernehmen wir
keine Haftung für die Inhalte externer Links. Für den Inhalt der verlinkten
Seiten sind ausschließlich deren Betreiber verantwortlich.
