### ISSUE TITLE
Trigger Agent 

### ISSUE THREAD

**Issue by signallhill** [huginn/huginn#586]
I have payload from feed agent that I am trying to filter with anyone of the value below in the title.
It appears only "value1" and "value4" is filtering, what am I doing wrong?

Also, is it possible to also filter another path "description" in the same agent?

{
  "expected_receive_period_in_days": "5",
  "keep_event": "true",
  "rules": [
    {
      "type": "regex",
      "value": "value1 | value2 | value3 | value4",
      "path": "title"
    }
  ]
}

**Comment by string-token** [comment]
> Also, is it possible to also filter another path "description" in the same agent?

I would be also interested whether I can have multiple paths in the same TriggerAgent! Otherwise, I would have to set up multiple agents and then deduplicate the created events again.

**Comment by cantino** [comment]
So if `path` were an array, would it mean "any of these must match" or "all of these must match"?

**Comment by string-token** [comment]
In this case, it would mean "any of these must match".

**Comment by cantino** [comment]
I think it would be reasonable to make it so if `path` is an array, all instances in the array will be run against all `values` and if any match, the rule matches.  Would you like to try and make this change?

**Comment by marycanady** [comment]
Do spaces work within string, for example can I use:

"value": "value1a value1b| value2 | value3 | value4",

**Comment by cantino** [comment]
@marycanady If you're using the regex type, yes, spaces would be allowed and would need to match actual spaces in the input.  "hello world|hello there" would match either "hello world how are you" or "hello there what's up?"
